### ISSUE TITLE
阻止相册打开

### ISSUE THREAD

**Issue by CaiMiao** [xfangfang/wiliwili#1]
可参考：
https://github.com/CaiMiao/borealis/blob/57df22525c9ff098b8c6420bb2bfb7e8a16cabc8/library/lib/platforms/switch/switch_font.cpp#L63

**Comment by xfangfang** [comment]
感谢提醒

**Comment by xfangfang** [comment]
最新版已经加入了判断，所以先关闭这个issue了，再次感谢
