### ISSUE TITLE
有办法套用Anime4K滤镜吗？

### ISSUE THREAD

**Issue by may349007** [xfangfang/wiliwili#101]
这滤镜追番满好用的，能加强清晰度，有没有可能实现呢？

**Comment by xfangfang** [comment]
@may349007 可以下载测试版试用，欢迎给出反馈

https://github.com/xfangfang/wiliwili/wiki#自定义着色器

**Comment by may349007** [comment]
刚试用了下，运行正常，就是shader的设置不会保存，每次重开都归零

**Comment by xfangfang** [comment]
@may349007 
是的，因为这个功能毕竟使用场景比较有限，如果默认开启可能会出现每次正常播放都需要手动关闭的情况，所以我并没有保存这个配置

**Comment by may349007** [comment]
不需要默认开启啊，能记录上一次使用的设置就行了，如果用不到的人上一次使用就是关闭的，那下次开播放器时仍是关闭啊，并不需要每次都手动关吧。

**Comment by xfangfang** [comment]
我是按照我自己的使用场景来做的。

我在看老番的时候会开启这个功能，但是下一次使用wiliwili的时候大概率并不会继续看老番而是随机刷一刷其他视频，这种情况下就需要我手动去关闭。

一个更好的处理方式是针对每个番剧或视频单独保存记录，但是这样需要写一些代码来保存这些状态，对我来说这只是偶尔用一下的功能，所以我感觉目前的状态对我来说刚刚好

**Comment by may349007** [comment]
确实能单独保存最好，有空再做就行了

**Comment by xfangfang** [comment]
@may349007 经过一段时间测试加载 shader 已经比较稳定啦，先关闭这个issue了
