### ISSUE TITLE
请问有什么办法可以把libglfw作为静态库调用

### ISSUE THREAD

**Issue by kero990** [xfangfang/wiliwili#102]
是这样，我现在使用的是统信UOS ，arm64架构，但这系统基于debian10，系统库中libglfw的版本是3.2，无法满足使用需要。这导致我无法通过apt自动安装依赖，而必须手动安装glfw3.3。我想问有没有可能把glfw作为静态库单独放在程序执行目录，而不使用系统的共享库。这个需要改动编译参数？改动cmake文件？还是需要改动源代码？
如果只需要改动参数或者cmake，我想尝试一下。

**Comment by xfangfang** [comment]
@kero990 

静态库的作用是链接到程序里，陪同程序一起分发的是动态库。

最新的代码，无论是yoga分支还是dev分支都不需要依赖外部的glfw，默认使用的是一个我修改过的glfw。

详情可以看对应分支的说明即可。

**Comment by kero990** [comment]
啊，

> @kero990
> 
> 静态库的作用是链接到程序里，陪同程序一起分发的是动态库。
> 
> 最新的代码，无论是yoga分支还是dev分支都不需要依赖外部的glfw，默认使用的是一个我修改过的glfw。
> 
> 详情可以看对应分支的说明即可。

啊，那是我想当然了，我编译过旧版本。现在的报错是这样

> CMake Error at library/borealis/library/CMakeLists.txt:7 (add_subdirectory):
>   The source directory                                                                                                
>                                                                                                                       
>     /root/wiliwili/library/borealis/library/lib/extern/glfw                                                           
>                                                                                                                       
>   does not contain a CMakeLists.txt file. 

我一看到glfw就想当然的想到上次glfw的问题了。那现在这是啥情况？

oh，好吧，这是我子模块的子模块没拉取到。。。。。
国内用github是真的神烦，尤其是终端

**Comment by kero990** [comment]
现在又爆出

> CMake Error at library/CMakeLists.txt:30 (add_library):
>   Cannot find source file:                                                                                            
>                                                                                                                       
>     /root/wiliwili/library/QR-Code-generator/cpp/QrCode.cpp                                                           
>                                                                                                                       
>   Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h                                          
>   .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc                                           
>                                                                                                                       
>                                                                                                                       
> CMake Error at library/CMakeLists.txt:30 (add_library):QrCode.cpp  
>   No SOURCES given to target: qrcode

看了一下，发现QR-Code-generator现在的master分支已经没有QrCode.cpp  ，而使用代理抓取的git没法获取非分支项的提交记录，再说一遍，国内用github好烦，我真的是

**Comment by xfangfang** [comment]
我建议你重开一个目录，按照readme说明clone项目。

不要自己手动去子模块里拉取，git的子模块是有特殊的拉取方式的

**Comment by kero990** [comment]
> 我建议你重开一个目录，按照readme说明clone项目。
> 
> 不要自己手动去子模块里拉取，git的子模块是有特殊的拉取方式的

我也想，但不开梯子访问github就不可能clone成功。而这台arm64机器是配发的，哪敢在这个上面开梯子
我上次都是被迫用国外vps克隆了打包转回来的。只是同样速度感人

**Comment by xfangfang** [comment]
你可以本地局域网其他机器开代理，然后在uos命令行里临时配置http代理

**Comment by xfangfang** [comment]
考虑到问题已经解决了，我先暂时关闭啦～

有任何问题都可以继续在下面问我，编译好之后也欢迎分享在下面供大家使用。

目前项目是支持flatpak的aarch64安装包的，如果希望未来持续获得其他安装包，可以完善自动构建安装包的脚本，制作其他安装包（deb, appimage等等均可），github action虽然只免费提供了x86的linux主机，但是可以通过docker的方式来编译arm程序。
