### ISSUE TITLE
Arch Linux上无法运行

### ISSUE THREAD

**Issue by Wind134** [xfangfang/wiliwili#103]
难道是因为窗口协议的原因？我用的是Wayland！
终端运行报错日志：
```
11:05:29.843[INFO] wiliwili 
11:05:29.843[INFO] Set app locale: zh-Hans
11:05:29.850[INFO] Using platform GLFW
11:05:29.850[ERROR] Cannot load locale en-US: directory /usr/local/share/wiliwili/resources/i18n/en-US doesn't exist
11:05:29.850[ERROR] Cannot load locale zh-Hans: directory /usr/local/share/wiliwili/resources/i18n/zh-Hans doesn't exist
11:05:29.906[INFO] glfw: GL Vendor: Intel
11:05:29.906[INFO] glfw: GL Renderer: Mesa Intel(R) Xe Graphics (TGL GT2)
11:05:29.906[INFO] glfw: GL Version: 4.6 (Core Profile) Mesa 23.0.0
11:05:29.906[INFO] glfw: GLFW Version: 3.4.0
11:05:29.920[WARNING] Cannot find custom gamepad db, (Searched at: /home/ping/.config/wiliwili/gamecontrollerdb.txt)
11:05:29.921[WARNING] Cannot find custom font, (Searched at: /home/ping/.config/wiliwili/font.ttf)
11:05:29.921[INFO] Using internal font: /usr/local/share/wiliwili/resources/font/switch_font.ttf
11:05:29.921[WARNING] "regular" font couldn't be located (searched at "/usr/local/share/wiliwili/resources/font/switch_font.ttf")
11:05:29.921[WARNING] Cannot find keymap icon, (Searched at: /usr/local/share/wiliwili/resources/font/keymap_xbox.ttf)
11:05:29.921[WARNING] Icons may not be displayed, for more information please refer to: https://github.com/xfangfang/wiliwili/discussions/38
11:05:29.921[WARNING] "material" font couldn't be located (searched at "/usr/local/share/wiliwili/resources/material/MaterialIcons-Regular.ttf")
11:05:29.921[ERROR] switch: could not load Material icons font from resources
11:05:29.921[INFO] createWindow done
11:05:29.921[ERROR] Fatal error: Unable to load XML file "/usr/local/share/wiliwili/resources/xml/activity/main.xml": error 3
terminate called after throwing an instance of 'std::logic_error'
  what():  Unable to load XML file "/usr/local/share/wiliwili/resources/xml/activity/main.xml": error 3
[1]    97538 IOT instruction (core dumped)  wiliwili
```
会不会因为我用的是Wayland的原因，我贴上系统信息：

![图片](https://user-images.githubusercontent.com/39483347/227688872-6244afd2-606d-49eb-95fa-1a37be3744a2.png)

**Comment by xfangfang** [comment]
@Wind134 我看log猜测，你应该是cmake的时候添加了 -DINSTALL=ON 但是编译好之后，并没有执行 make install，直接运行的编译结果。

**Comment by xfangfang** [comment]
默认构建的是 x11程序，如果需要wayland，可以：-DGLFW_BUILD_WAYLAND=ON -DGLFW_BUILD_X11=OFF

**Comment by Wind134** [comment]
> @Wind134 我看log猜测，你应该是cmake的时候添加了 -DINSTALL=ON 但是编译好之后，并没有执行 make install，直接运行的编译结果。

应该不会，AUR会自动处理make install的吧，我待会去看看构建文件

**Comment by xfangfang** [comment]
哦哦，包管理并不是我在维护，这个要去问问维护的那位热心朋友啦

**Comment by xfangfang** [comment]
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=wiliwili-git

我猜是cmake指令少了一个 “-“ 导致的

DCMAKE_INSTALL_PREFIX=/usr/

通过log可以看出，这条配置并没有生效。

- - -

@yuioto 辛苦啦，貌似目前的构建指令存在问题，有空时候可以检查看看～

**Comment by Wind134** [comment]
我加上了`-`，同时加上了`-DGLFW_BUILD_WAYLAND=ON -DGLFW_BUILD_X11=OFF`
但还是报错：
```
12:10:48.161[INFO] wiliwili 
12:10:48.161[INFO] Set app locale: zh-Hans
12:10:48.225[INFO] Using platform GLFW
12:10:48.225[ERROR] Cannot load locale en-US: directory /usr/share/wiliwili/resources/i18n/en-US doesn't exist
12:10:48.225[ERROR] Cannot load locale zh-Hans: directory /usr/share/wiliwili/resources/i18n/zh-Hans doesn't exist
12:10:48.283[INFO] glfw: GL Vendor: Intel
12:10:48.283[INFO] glfw: GL Renderer: Mesa Intel(R) Xe Graphics (TGL GT2)
12:10:48.283[INFO] glfw: GL Version: 4.6 (Core Profile) Mesa 23.0.0
12:10:48.283[INFO] glfw: GLFW Version: 3.4.0
12:10:48.289[ERROR] GLFW 65548: Wayland: The platform does not provide the window position
12:10:48.289[WARNING] Cannot find custom gamepad db, (Searched at: /home/ping/.config/wiliwili/gamecontrollerdb.txt)
12:10:48.289[WARNING] Cannot find custom font, (Searched at: /home/ping/.config/wiliwili/font.ttf)
12:10:48.289[INFO] Using internal font: /usr/share/wiliwili/resources/font/switch_font.ttf
12:10:48.289[WARNING] "regular" font couldn't be located (searched at "/usr/share/wiliwili/resources/font/switch_font.ttf")
12:10:48.289[WARNING] Cannot find keymap icon, (Searched at: /usr/share/wiliwili/resources/font/keymap_xbox.ttf)
12:10:48.289[WARNING] Icons may not be displayed, for more information please refer to: https://github.com/xfangfang/wiliwili/discussions/38
12:10:48.289[WARNING] "material" font couldn't be located (searched at "/usr/share/wiliwili/resources/material/MaterialIcons-Regular.ttf")
12:10:48.289[ERROR] switch: could not load Material icons font from resources
12:10:48.289[INFO] createWindow done
12:10:48.289[ERROR] Fatal error: Unable to load XML file "/usr/share/wiliwili/resources/xml/activity/main.xml": error 3
terminate called after throwing an instance of 'std::logic_error'
  what():  Unable to load XML file "/usr/share/wiliwili/resources/xml/activity/main.xml": error 3
[1]    145035 IOT instruction (core dumped)  wiliwili
```
看报错是`Unable to load XML file "/usr/share/wiliwili/resources/xml/activity/main.xml": error 3
terminate called after throwing an instance of 'std::logic_error'`，会不会是这里的问题？

**Comment by xfangfang** [comment]
如果还是存在问题，那就是下面package()的部分存在问题，这个报错的原因就是 resources目录没有复制到正确的位置。

可以检查一下报错的位置有没有这个文件。

如果从源码直接安装的话，make install 就可以了，我对arch不是很了解，不太清楚为什么需要手动复制安装的文件（可能是权限要求或者默认安装的目录位置不对？）

**Comment by Eitetsu0** [comment]
我也遇到了同样的问题。

补上前面说的 `-` 
再照下面修改一下`PKGBUILD` 的`pakage()`函数可以修复这个问题
```
package() {
    install -Dm755 build/"$_pkg" -t "$pkgdir/usr/bin/"
    install -Dm755 "$_pkg/scripts/linux/cn.xfangfang.wiliwili.desktop" -t "$pkgdir/usr/share/applications/"
    install -Dm644 "build/resources/icon/cn.xfangfang.wiliwili.png" -t "$pkgdir/usr/share/icons/hicolor/scalable/apps/"
    mkdir -p -m755 "$pkgdir/usr/share/$_pkg"
    cp -dr --no-preserve=ownership "build/resources" -t "$pkgdir/usr/share/$_pkg/"
}
```

我稍后去AUR上提一下😹

**Comment by Wind134** [comment]
> 如果还是存在问题，那就是下面package()的部分存在问题，这个报错的原因就是 resources目录没有复制到正确的位置。
> 
> 可以检查一下报错的位置有没有这个文件。
> 
> 如果从源码直接安装的话，make install 就可以了，我对arch不是很了解，不太清楚为什么需要手动复制安装的文件（可能是权限要求或者默认安装的目录位置不对？）



> 我也遇到了同样的问题。
> 
> 补上前面说的 `-` 再照下面修改一下`PKGBUILD` 的`pakage()`函数可以修复这个问题
> 
> ```
> package() {
>     install -Dm755 build/"$_pkg" -t "$pkgdir/usr/bin/"
>     install -Dm755 build/"$_pkg" -t "$pkgdir/usr/share/$_pkg"
>     install -Dm755 "$_pkg/scripts/linux/cn.xfangfang.wiliwili.desktop" -t "$pkgdir/usr/share/applications/"
>     install -Dm644 "build/resources/icon/cn.xfangfang.wiliwili.png" -t "$pkgdir/usr/share/icons/hicolor/scalable/apps/"
>     cp -dr --no-preserve=ownership "build/resources" -t "$pkgdir/usr/share/$_pkg/"
> }
> ```
> 
> 我稍后去AUR上提一下joy_cat

感谢两位，可以成功运行了，但是界面真的好大啊哈哈哈，是因为Wayland的原因吗？

**Comment by xfangfang** [comment]
> 感谢两位，可以成功运行了，但是界面真的好大啊

不用客气，这个软件是给游戏主机设计的，界面比较适合掌机，平板，电视这样的显示设备。

**Comment by yuioto** [comment]
> 如果从源码直接安装的话，make install 就可以了，我对arch不是很了解，不太清楚为什么需要手动复制安装的文件（可能是权限要求或者默认安装的目录位置不对？）

关于这个问题，之前是因为make会将glfw的文件也一并复制导致和glfw包冲突，并且只能在local中安装，现在我改为先使用`DESTDIR=$pkgdir cmake —install “build”`与之后手动删除多余文件来解决。

@Wind134 很奇怪，我无法在本地复现这个问题，但是现在我尝试修复了，现在应当不会再出现这个问题，可以的话请帮助我测试。

**Comment by xfangfang** [comment]
> 因为make会将glfw的文件也一并复制导致和glfw包冲突

这个问题我之前也发现了，在dev分支已经把那部分多余的内容删除了。我会尽快把dev分支合并进主分支的～

**Comment by Eitetsu0** [comment]
各位反应真快😽

**Comment by Wind134** [comment]
> > 如果从源码直接安装的话，make install 就可以了，我对arch不是很了解，不太清楚为什么需要手动复制安装的文件（可能是权限要求或者默认安装的目录位置不对？）
> 
> 关于这个问题，之前是因为make会将glfw的文件也一并复制导致和glfw包冲突，并且只能在local中安装，现在我改为先使用`DESTDIR=$pkgdir cmake —install “build”`与之后手动删除多余文件来解决。
> 
> @Wind134 很奇怪，我无法在本地复现这个问题，但是现在我尝试修复了，现在应当不会再出现这个问题，可以的话请帮助我测试。

我看到了新的PKGBUILD文件，应该是没问题了，辛苦维护啦！(话说我也没想到AUR会上这个包了哈哈哈哈)

**Comment by Wind134** [comment]
> > 
> > 关于这个问题，之前是因为make会将glfw的文件也一并复制导致和glfw包冲突，并且只能在local中安装，现在我改为先使用`DESTDIR=$pkgdir cmake —install “build”`与之后手动删除多余文件来解决。
> > @Wind134 很奇怪，我无法在本地复现这个问题，但是现在我尝试修复了，现在应当不会再出现这个问题，可以的话请帮助我测试。
> 
> 我看到了新的PKGBUILD文件，应该是没问题了，辛苦维护啦！(话说我也没想到AUR会上这个包了哈哈哈哈)
会有提示：-Wno-dev：未找到命令，导致报错！
