### ISSUE TITLE
在Wayland上，wiliwili分辨率以及缩放异常

### ISSUE THREAD

**Issue by Wind134** [xfangfang/wiliwili#104]
终端窗口可以看到，分辨率直接*2了，这部分变化逻辑可以在终端记录上看到：
```
15:00:43.781[INFO] Using internal font: /usr/share/wiliwili/resources/font/switch_font.ttf
15:00:43.783[INFO] Load keymap icon: /usr/share/wiliwili/resources/font/keymap_xbox.ttf
15:00:43.783[INFO] createWindow done
15:00:43.794[INFO] Write config to: /home/ping/.config/wiliwili/wiliwili_config.json
15:00:43.886[INFO] Window position changed to 0x0
15:00:43.936[INFO] Window size changed to 5760x3600, content size: 1280.0x800.0 factor: 4.5
15:00:43.936[INFO] scale factor: 2.0
```
显示屏原始分辨率为2880*1800，Wayland下设置了2倍缩放，而且content size会不会多少也有些问题？
怎么样可以手动设置软件的缩放呢？

**Comment by xfangfang** [comment]
我认为你应该把实际的画面发出来看一下，我因为没有在对应的平台测试过，所以不是很了解会不会有问题，以及最好也试一试x11下的效果，互相对比看看。

不同桌面环境下的缩放是由glfw来处理的，wiliwili并不会去控制这些内容，如果存在问题，只能拉源码尝试修复了

**Comment by Wind134** [comment]
作者回复好快，下面这张图就是在我笔记本上的全屏效果，再结合终端运行的log，应该是存在缩放问题。

![Screenshot_20230325_152416](https://user-images.githubusercontent.com/39483347/227703479-41a038db-370d-4590-99a1-9dbe734051f9.png)

我后续再以X11进行编译看看是啥情况

**Comment by xfangfang** [comment]
看起来像是软件超出了屏幕只显示了左上角四分之一的画面。

可以在这个页面按 f1/f2 具体哪个我不记得了，进入设置页面，在设置页尝试关闭全屏看看效果。

- - -

我认为这个问题应该是你使用的桌面环境或者是glfw导致的，这个就需要多测试看看才能知道了。

可以分别测试：1倍和2倍缩放下开启软件时，全屏，窗口化，全屏设置内转窗口化，窗口化设置内转全屏，共八种情况的状态和log，主要看 “Window size changed to” 的内容即可。

- - -

对应的控制窗口创建的代码位于：https://github.com/xfangfang/borealis/blob/wiliwili/library/lib/platforms/glfw/glfw_video.cpp

如果要自行修改，可以着重看看这里的代码

**Comment by Wind134** [comment]
> 

了解了解，辛苦作者啦

**Comment by Wind134** [comment]
> 看起来像是软件超出了屏幕只显示了左上角四分之一的画面。
> 
> 可以在这个页面按 f1/f2 具体哪个我不记得了，进入设置页面，在设置页尝试关闭全屏看看效果。
> 
> 我认为这个问题应该是你使用的桌面环境或者是glfw导致的，这个就需要多测试看看才能知道了。
> 
> 可以分别测试：1倍和2倍缩放下开启软件时，全屏，窗口化，全屏设置内转窗口化，窗口化设置内转全屏，共八种情况的状态和log，主要看 “Window size changed to” 的内容即可。
> 
> 对应的控制窗口创建的代码位于：https://github.com/xfangfang/borealis/blob/wiliwili/library/lib/platforms/glfw/glfw_video.cpp
> 
> 如果要自行修改，可以着重看看这里的代码

了解了解，刚刚关闭全屏，确实可以正常使用了，感谢作者的辛勤劳动，比electron的流畅很多！

**Comment by xfangfang** [comment]
我比较好奇的是在窗口化的情况下开启全屏还会存在问题吗？

也就是这个问题是只有第一次打开时存在还是只要全屏就有问题

**Comment by Wind134** [comment]
> 

你说的是窗口化的情况下全屏播放视频吗？这个没有任何问题，唯一可能不是那么完美的是全屏视频播放状态下标题栏不会消失，但我认为这个不怎么影响使用；
其次，我测试了，如果是设置中开启全屏，那么这个问题同样会复现，然后我拔掉其中一个屏幕再接上去，会恢复正常，当我关闭再打开，全屏又是异常。

**Comment by Wind134** [comment]
> 我比较好奇的是在窗口化的情况下开启全屏还会存在问题吗？
> 
> 也就是这个问题是只有第一次打开时存在还是只要全屏就有问题

你说的是窗口化的情况下全屏播放视频吗？这个没有任何问题，唯一可能不是那么完美的是全屏视频播放状态下标题栏不会消失，但我认为这个不怎么影响使用；
其次，我测试了，如果是设置中开启全屏，那么这个问题同样会复现，然后我拔掉其中一个屏幕再接上去，会恢复正常，当我关闭再打开，全屏又是异常。

**Comment by xfangfang** [comment]
如果设置中开启全屏存在问题，而且可以稳定复现，就说明wayland下确实是存在问题的。

欢迎有时间看看代码尝试修复，或者尝试定位问题（我暂时没有时间来研究linux上的小问题啦）

**Comment by Wind134** [comment]
> 如果设置中开启全屏存在问题，而且可以稳定复现，就说明wayland下确实是存在问题的。
> 
> 欢迎有时间看看代码尝试修复，或者尝试定位问题（我暂时没有时间来研究linux上的小问题啦）

理解理解，现在已经很好用了，感谢奉献！后续也会跟着研究下有关代码。
(然后可能我又要开个新issue了，因为好像硬件加速没起作用......)

**Comment by xfangfang** [comment]
@Wind134 最新dev分支的代码同步了底层glfw的更新，glfw最近做了很多wayland下的修改，可以看看之前说的全屏显示过大的问题还存在不。

**Comment by Wind134** [comment]
> @Wind134 最新dev分支的代码同步了底层glfw的更新，glfw最近做了很多wayland下的修改，可以看看之前说的全屏显示过大的问题还存在不。

现在双屏下，在我的显示屏1也就是笔记本内置显示屏下是很正常的，但是到了显示屏2好像无法自动调整缩放

**Comment by xfangfang** [comment]
@Wind134 好的，那这种情况可能需要哪天我有具体的设备测试看看了

**Comment by xfangfang** [comment]
因为太长时间没有更新，准备先关闭这个issue，如果后续有更新欢迎随时重新开启。

我在steam deck的桌面模式测试(虽然他好像不是wayland)，即使是系统应用，在拥有不同缩放比例的显示器下切换时也不会自动改变应用内的缩放。
但在 Mac或者windows下，应用内会收到调整窗口大小的事件，所以这个问题要么是操作系统某些功能还不完善，要么就是GLFW做的适配还不够好（也可以切换到SDL来试一试，具体可以看项目的wiki），可以先编译一些GLFW的示例代码来在你的环境下测试看看。

**Comment by xfangfang** [comment]
我刚刚在 Wayland 下测试了一下，好像GLFW 下 应用默认打开的时候确实分辨率不太对，少调用了一次glviewport 导致的，最新dev分支包含了修复。
https://nightly.link/xfangfang/wiliwili/workflows/build.yaml/dev
