### ISSUE TITLE
视频播放的硬件加速未生效

### ISSUE THREAD

**Issue by Wind134** [xfangfang/wiliwili#105]
已经根据[Archwiki说明](https://wiki.archlinux.org/title/Hardware_video_acceleration)安装了VA-API，在mpv视频播放，firefox浏览器视频播放下都能正常启用硬件加速。
操作系统上可能唯一比较特殊的点是使用了Wayland窗口协议，不知道会不会跟这个有关系，我判断硬件加速是否开启的方式是根据指令`sudo intel_gpu_top`来判断的，使用了硬件加速`video`部分会有占用，且`Render/3D`部分的占用相对较低，但是使用wiliwili的情况下没有启用硬件加速的迹象；
设置中已开启硬件加速；

**Comment by xfangfang** [comment]
我刚刚把dev分支的代码同步到了主分支。（务必要使用最新的代码）

硬件加速受到系统、硬件甚至是显卡驱动的影响，软件内默认使用 mpv 的硬件加速的 auto-safe 选项但是可能不能正常工作，尤其是在 Linux 上。

关于这个问题，详细的调试与配置修改方式，请见：https://github.com/xfangfang/wiliwili/wiki#自定义硬解

**Comment by Wind134** [comment]
> 我刚刚把dev分支的代码同步到了主分支。（务必要使用最新的代码）
> 
> 硬件加速受到系统、硬件甚至是显卡驱动的影响，软件内默认使用 mpv 的硬件加速的 auto-safe 选项但是很可能不能正常工作，尤其是在 Linux 上。
> 
> 关于这个问题，详细的调试与配置修改方式，请见：[https://github.com/xfangfang/wiliwili/wiki#自定义硬解](https://github.com/xfangfang/wiliwili/wiki#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%A1%AC%E8%A7%A3)

好，我后面研究下详细配置！

**Comment by Wind134** [comment]
> > 我刚刚把dev分支的代码同步到了主分支。（务必要使用最新的代码）
> > 硬件加速受到系统、硬件甚至是显卡驱动的影响，软件内默认使用 mpv 的硬件加速的 auto-safe 选项但是很可能不能正常工作，尤其是在 Linux 上。
> > 关于这个问题，详细的调试与配置修改方式，请见：[https://github.com/xfangfang/wiliwili/wiki#自定义硬解](https://github.com/xfangfang/wiliwili/wiki#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%A1%AC%E8%A7%A3)
> 
> 好，我后面研究下详细配置！

您好啊，又来打扰了，我今天上午详细研究了有关硬件解码的配置问题，有一个比较奇怪的现象是，我已经将vaapi解码写入了mpv的配置文件，mpv播放视频也可**正确进行硬件加速**，写入：
```
    "player_hwdec": true,
    "player_hwdec_custom": "vaapi",
```
进wiliwili的配置文件，终端运行wiliwili
```
11:52:55.314[INFO] Write config to: /home/ping/.config/wiliwili/wiliwili_config.json
11:52:55.314[INFO] trying delete fbo
11:52:55.314[INFO] trying delete shader
11:52:55.314[INFO] trying free mpv context
11:52:55.314[INFO] trying terminate mpv
11:52:55.324[INFO] set memory cache: 50MB
11:52:55.324[INFO] MPV hardware decode: true/vaapi
11:52:55.329[INFO] MPV Version: mpv 0.35.1-dirty
11:52:55.329[INFO] FFMPEG Version: n6.0
11:52:55.354[INFO] Write config to: /home/ping/.config/wiliwili/wiliwili_config.json
11:52:55.359[INFO] ========> core-idle: 1
11:52:55.359[INFO] ========> LOADING
```
貌似是正确显示了vaapi解码，但是`sudo intel_gpu_top`命令显示视频播放依然是软解，使用`qsv`解码也是类似的情形；
驱动设置应该是没问题的，硬件加速正常可以启用的都能启用，这个问题确实比较奇怪；

**Comment by xfangfang** [comment]
我理解你的意思是：

1. 在命令行中输入：`mpv --msg-level="all=v" --hwdec="vaapi" "https://www.w3schools.com/html/movie.mp4"`
2. 通过 intel_gpu_top 能看到使用了硬解
3. 配置了 wiliwili 再使用 intel_gpu_top 发现没有正常调用硬解

我也不清楚这这其中的区别，建议是从源码按照 README 所说编译 wiliwili（默认是debug编译，可以看到更多的log），然后重新配置 wiliwili （debug编译配置文件在 wiliwili 的执行目录），并把播放视频时的log发出来。

- - - 
你现在的安装方式，wiliwili 使用的 mpv 应该和命令行中的mpv是同一个，我认为软件上的问题应该不大，或许是有两个显卡或许是测量硬解的方式或时机不正确。

**Comment by Wind134** [comment]
> 我理解你的意思是：
> 
> 1. 在命令行中输入：`mpv --msg-level="all=v" --hwdec="vaapi" "https://www.w3schools.com/html/movie.mp4"`
> 2. 通过 intel_gpu_top 能看到使用了硬解
> 3. 配置了 wiliwili 再使用 intel_gpu_top 发现没有正常调用硬解
> 
> 我也不清楚这这其中的区别，建议是从源码按照 README 所说编译 wiliwili（默认是debug编译，可以看到更多的log），然后重新配置 wiliwili （debug编译配置文件在 wiliwili 的执行目录），并把播放视频时的log发出来。
> 
> 你现在的安装方式，wiliwili 使用的 mpv 应该和命令行中的mpv是同一个，我认为软件上的问题应该不大，或许是有两个显卡或许是测量硬解的方式或时机不正确。

理解太准确了，那我后续接着试试源码编译！

**Comment by xfangfang** [comment]
有任何更新嘛？编译的过程中有任何问题都欢迎随时询问，因为准备发布下一个版本了，比较希望能在新版本发布前把可疑的问题都解决掉～

**Comment by xfangfang** [comment]
@Wind134 
dev分支最新代码，支持设置视频源的编码类型，在焦点位于播放器时可以按 F1 获得详细的视频数据，可以通过这个来快速的判断是否使用了硬解。

<img width="1148" alt="image" src="https://user-images.githubusercontent.com/16631584/230543414-d4e79277-c5f4-49e5-b668-2fea655f0ab2.png">

**Comment by Wind134** [comment]
> 有任何更新嘛？编译的过程中有任何问题都欢迎随时询问，因为准备发布下一个版本了，比较希望能在新版本发布前把可疑的问题都解决掉～

抱歉才看到邮件信息，我切换到了dev分支并且成功编译，通过解码信息确实看到硬件解码未启用，头疼！

**Comment by xfangfang** [comment]
@Wind134 

可以在设置中切换视频编码试一试，一般来说显卡都应该是支持默认的 AVC/H.264 硬解的。我对这些也不是特别了解，用我的steam deck试了试，AVC/H.264 和 HEVC/H.265 都能硬解，AV1有部分视频不能（我也不太了解为什么）

也有可能是你装的mpv并不是编译用到的mpv，或者是其他莫名其妙的原因不支持硬解，这个还得是看看应用log才能分辨，同时也推荐试一试安装wiliwili flatpak的安装包，至少这个我是确认过在硬解上没问题的了。

**Comment by Wind134** [comment]
> @Wind134
> 
> 可以在设置中切换视频编码试一试，一般来说显卡都应该是支持默认的 AVC/H.264 硬解的。我对这些也不是特别了解，用我的steam deck试了试，AVC/H.264 和 HEVC/H.265 都能硬解，AV1有部分视频不能（我也不太了解为什么）
> 
> 也有可能是你装的mpv并不是编译用到的mpv，或者是其他莫名其妙的原因不支持硬解，这个还得是看看应用log才能分辨，同时也推荐试一试安装wiliwili flatpak的安装包，至少这个我是确认过在硬解上没问题的了。

我准备重新编译一下ffmpeg试试，之前用的是系统包自带的，怕弄坏依赖就没试，视频编码我用的就是AVC，感觉问题还是最有可能出在ffmpeg上

**Comment by xfangfang** [comment]
@Wind134 感觉这个问题应该和wiliwili没有太大的关系了，我先关闭这个issue了

**Comment by calico-cat-3333** [comment]
遇到了同样的问题，将`player_hwdec_custom`设置为`vaapi-copy`可以解决
参考[mpv文档的vaapi部分](https://man.archlinux.org/man/mpv.1#vaapi) , 要将hwdec设置为vaapi, 需要vo设置为gpu, vaapi或者dmabuf-wayland. 而wiliwili使用的mpv的vo是libmpv, 故不能设置hwdec为vaapi.

**Comment by xfangfang** [comment]
@calico-cat-3333 比较好奇默认的情况下，比如auto auto-safe auto-copy auto-copy-safe 这几种情况在你的设备上是可以触发硬解的吗？
现在wiliwili默认使用auto-safe，我在想改成auto-copy-safe会不会在linux可以自动识别成正确的硬解方式？

**Comment by Wind134** [comment]
> auto-copy

我测试了，都无法自动识别正确的硬解，只有vaapi-copy可行

**Comment by Wind134** [comment]
> @calico-cat-3333 比较好奇默认的情况下，比如auto auto-safe auto-copy auto-copy-safe 这几种情况在你的设备上是可以触发硬解的吗？ 现在wiliwili默认使用auto-safe，我在想改成auto-copy-safe会不会在linux可以自动识别成正确的硬解方式？

我测试了，都无法自动识别正确的硬解，只有vaapi-copy可行

**Comment by calico-cat-3333** [comment]
> @calico-cat-3333 比较好奇默认的情况下，比如auto auto-safe auto-copy auto-copy-safe 这几种情况在你的设备上是可以触发硬解的吗？ 现在wiliwili默认使用auto-safe，我在想改成auto-copy-safe会不会在linux可以自动识别成正确的硬解方式？

我有两台设备，设备信息及测试结果如下：
七彩虹X15-AT 2022：Intel Nvidia双显卡，系统Debian testing，N卡使用闭源驱动，桌面用的openbox，X11协议，在这台设备上均触发使用nvdec-copy硬解
台电X80Plus：仅Intel集显，系统Mobian(修改版Debian testing），桌面为Phosh，wayland协议，这台设备上表现比较奇怪，似乎与驱动也有关：
如果用i965-va-driver驱动则均不能触发硬解，包括直接设置为vaapi-copy也不能，用系统mpv播放视频, vaapi可以硬解，vaapi-copy不行
如果用i965-va-driver-shaders驱动则均触发vaapi-copy硬解，用系统mpv播放视频, vaapi和vaapi-copy都可以硬解。wiliwili用vaapi-copy播放画面会有黑块，mpv用vaapi-copy播放本地视频则不会。
根据Debian软件包上的说明，[i965-va-driver-shaders](https://packages.debian.org/bookworm/i965-va-driver-shaders)这个包包含闭源内容。另外这么看的话，我今早上发的解决只是个巧合，真正解决问题的是我瞎试的时候把驱动给换了。

**Comment by xfangfang** [comment]
@calico-cat-3333 感谢详细反馈，我待会儿把这个issue写在wiki里，这样可以帮助其他Linux用户少走很多弯路了！

**Comment by Eitetsu0** [comment]
vaapi-copy 比 vaapi 占用资源高好多。

甚至部分4k hdr视频，vaapi-copy 会有较严重的卡顿。

比如 `https://www.bilibili.com/video/BV1n84y137P9` 这个视频，4k hdr格式，hevc编码，在我的笔记本上（i5-1135g7 核显，wayland）：
使用 `you-get` 获取地址后，直接用 mpv 打开（没弹幕），使用vaapi硬解播放流畅，cpu占用在5%以下；使用vaapi-copy硬解播放卡顿丢帧，cpu占用在15%左右。
wiliwili使用 vaapi-copy 硬解播放卡顿丢帧，cpu占用在18%左右。
（补充：写完时候重新试了一段时间，发现这个有点玄学，虽然大多时候会卡顿，但有时候很流畅，同个视频片段连丢帧都没有）
软解倒是两者都可以流畅，只是cpu占用大概在30%～60%间波动，看一会风扇呼呼的。

@xfangfang ，这个看起来是无解了吗？


另外:

> @calico-cat-3333 比较好奇默认的情况下，比如auto auto-safe auto-copy auto-copy-safe 这几种情况在你的设备上是可以触发硬解的吗？ 现在wiliwili默认使用auto-safe，我在想改成auto-copy-safe会不会在linux可以自动识别成正确的硬解方式？

在我的系统上都会识别，并使用 vaapi-copy ，貌似跟`mpv`的`--hwdec=`参数效果相同，当然区别是`mpv`会自动使用vaapi 。@Wind134 跟我硬件记得似乎是一样的，可能是系统配置有问题。

**Comment by Eitetsu0** [comment]
播放卡顿时的  `intel_gpu_top` 截屏。`Render/3D` 部分占用100%了，不过我不太明白这些信息，这说明显卡的某个性能太差了吗？

![sc_20230428_15:07:33](https://user-images.githubusercontent.com/6576065/235079289-e021beab-86eb-43a6-a134-3b89bea087d7.png)

**Comment by Eitetsu0** [comment]
> wiliwili使用 vaapi-copy 硬解播放卡顿丢帧，cpu占用在18%左右。
> （补充：写完时候重新试了一段时间，发现这个有点玄学，虽然大多时候会卡顿，但有时候很流畅，同个视频片段连丢帧都没有）
> 

今天下午折腾了一下，发现了不卡顿的复现步骤，虽然可能跟wiliwili没关系。

1. 切换到另一个开着firefox的工作区，
2. 然后在里面快速滚动页面，
3. 然后切换回wiliwili，
4. 迅速点开视频，并且在加载完成前点开全屏。
5. 这时候视频就会流畅播放，最多开头丢个10几帧。

**Comment by xfangfang** [comment]
@Eitetsu0 感谢详细反馈，不过我也没什么好的办法，有几个小的问题：

1. 你的设备是只有一个cpu核显吗？如果有多个显卡可以试试 mpv 的 vaapi-device 来切换
2. 根据文档 *-copy 可以保证硬解的画质和软解一致，或许试试把wiliwili设置中的低画质解码打开，看看能不能稍微降低一些cpu占用 （不见得有用）
3. 播放同一个视频，在播放卡顿和播放流畅时分别记录 显卡的频率和占用情况（video/render），我感觉有可能是播放流畅时，是之前的某些操作让系统提升了显卡频率。

**Comment by Eitetsu0** [comment]
是只有一个核显，不过性能不够的好像不是解码器。另：i5-1135g7 好像是第一代Xe核显，之前使用dota2测试过opengl游戏性能大概相当于桌面rx560d的样子。
另外，又用台式机试了一下，3700x + rx6800xt ，大概是性能够了，确实完全没有卡顿存在。

不得不说真是有点玄学了，刚刚测试发现基本不出现卡顿了。我以为是因为我刚才关了外接显示器，然后打开结果还是不卡。
以前的时候还出现过外屏不卡，内屏持续轻微掉帧的现象，当时没在意。现在窗口在内外屏播放上面这个4k hdr片源都只有偶尔出现掉帧了。
我电脑一直开着没动，也没开关其他软件，真是奇了怪了。

关于显卡频率，似乎没有问题，我在这打字的时候 5 ～50MHz ，切到 wiliwili 会跳到500M左右，播放时1300左右。

有一个卡顿场景是把播放中的 wiliwili 放到后台，然后切回来的时候 A-V 会很高，然后会疯狂丢帧一段时间，把 A-V 追回来。这个我猜可能跟wayland也有一点关系，后台窗口不渲染，显卡频率也掉下去了。


当然这里提到的所有卡顿/丢帧都只针对上面提到的 4k HDR 视频，在4k清晰度上就没有了。

**Comment by xfangfang** [comment]
@Eitetsu0 看起来我能做的事很有限了，而且问题貌似和桌面环境比较相关。

其他的解决方案（通过修改wiliwili来试图解决问题的方案）或许是通过修改图形api来更好的适应系统，有两个方案：
1. 直接切换wiliwili的图形api，比如改到 vulkan，不过需要对应修改libmpv的接口，工作量应该会很大，这个得等mpv官方更新了。
2. 从 opengl 切换到opengl es，搭配 ANGLE 实现切换图形api，这个目前看起来比较可行，不过不一定会有提升。‘

**Comment by Hs-Yeah** [comment]
反馈：commit 4f93823ce14aeee23c4dd2db7f53bd616efb031d 对 `vaapi-copy` 方式的播放性能改善挺大。此 commit 前使用 `vaapi-copy` 播放 1080P60 视频会有明显卡顿掉帧，现在可以流畅播放。

测试环境：
未设置 `player_hwdec_custom`，在视频播放器中按 F1 可以看到 mpv 自动侦测后使用了 `vaapi-copy` 进行硬解。
OS: Arch Linux x86_64
Kernel: 6.5.9-arch2-1
CPU: Intel i5-5287U (4) @ 3.300GHz 
GPU: Intel Iris Graphics 6100

**Comment by xfangfang** [comment]
@Hs-Yeah 感谢反馈，我写的时候就在想应该有一些性能改善，但是很遗憾我这边的设备倒是都没有太大的效果。

mpv 的 vd-lavc-dr 这个选项默认是auto，但是之前的实现方式不支持开启dr。 你发的那个提交正好可以让某些系统上的这个选项生效。

另外一个可能会影响性能的选项是 opengl-pbo ，如果有效果的话，效果应该在 dr 和 native(就是最开始的那个效果）之间。

附：给wiliwili设置mpv配置可以见项目 wiki，具体的配置含义可以看 mpv.io
