### ISSUE TITLE
aarch64 OpenGL ES支持

### ISSUE THREAD

**Issue by Hvliam** [xfangfang/wiliwili#106]
1，下载wiliwili-Linux-aarch64.flatpak

2，在终端输入：
sudo flatpak install --system ./wiliwili-Linux-aarch64.flatpak

3，成功安装了

4，无法运行，出现闪退

不知道是缺了什么，希望您能在NS-Ubuntu上看下是什么问题并进行适配

**Comment by xfangfang** [comment]
@Hvliam 

我之前测试的时候，switch上的Ubuntu还不能运行flatpak安装包，后续就没再关注了。

可以使用命令行运行来查看log：
```
flatpak run cn.xfangfang.wiliwili 
```

**Comment by Hvliam** [comment]
> 
可以运行flatpak安装包的，只要您在L4T工具箱→scripts，运行安装auto update和pi-app，就可以运行flatpak安装包了，目前国外大佬也是利用flatpak来安装以太模拟器的

**Comment by Hvliam** [comment]
> flatpak run cn.xfangfang.wiliwili 

这个我回去后试下 然后截图给您看看

**Comment by Hvliam** [comment]
![fad61f8d82446cb](https://user-images.githubusercontent.com/127581769/227777276-f0a91da7-65fa-4bf2-a77b-e8bf450f6779.png)
![-32eeb03e42c9cc1](https://user-images.githubusercontent.com/127581769/227777302-45297c61-8c79-4ac7-b71b-ee1871b69075.png)

您好，这两张是安装完和运行的图片，麻烦您看下的

**Comment by Hvliam** [comment]
![fad61f8d82446cb](https://user-images.githubusercontent.com/127581769/227777447-af4bc1bf-97fd-4b81-b5b8-84573585c7c6.png)

**Comment by Hvliam** [comment]
![-32eeb03e42c9cc1](https://user-images.githubusercontent.com/127581769/227777509-c6042eb9-ab02-4c25-9ee8-c6a44ef657fc.png)

**Comment by Hvliam** [comment]
您好，这是安装完成和运行的图，麻烦您看下的

**Comment by xfangfang** [comment]
@Hvliam 似乎是因为这个系统只支持opengl es，但是wiliwili是使用opengl的。

这个支持起来倒是不复杂，但是我短时间不会做这样的调整，除非未来有更多的arm linux用户提出类似的需求，或者哪天空闲时间比较多。


添加opengl es的支持可以参考项目wiki中提及的树莓派opengl2.1支持流程，如果有人愿意为此添加支持，过程中有任何问题都可以随时来问我

**Comment by cheftchen** [comment]
那么 wiliwili-Linux-aarch64.flatpak 在哪里下载呢？

**Comment by xfangfang** [comment]
@Hvliam 周末研究了一下switchroot ubuntu，最终打包了一份 AppImage.

默认情况下他的 flatpak 应该是不支持 opengl 的，找到了相关的说明和开启的方式：
[flatpak-switch-ubuntu-hwacc.zip](https://github.com/xfangfang/wiliwili/files/11928805/flatpak-switch-ubuntu-hwacc.zip)

但是因为 flatpak 打包时候编译的 mpv 需要的环境和 switchroot ubuntu 的 flatpak 环境不符，且flatpak内的 ffmpeg 不支持 l4t 平台硬解，所以我选择更改打包方式到 AppImage.

这里是打包的说明：[Build wiliwili on Switchroot Ubuntu](https://gist.github.com/xfangfang/c253580fb036c73549cbd237634c6d52)

这里是打包的文件：[wiliwili-aarch64-switchroot-20230702.AppImage](https://github.com/xfangfang/wiliwili/releases/download/v0.1.0/wiliwili-aarch64-switchroot-20230702.AppImage)

如果上边的不好用，也可以试一下这个（可能老版本的系统需要这个）：[wiliwili-aarch64-switchroot-20230702-with-drm-gbm.AppImage](https://github.com/xfangfang/wiliwili/releases/download/v0.1.0/wiliwili-aarch64-switchroot-20230702-with-drm-gbm.AppImage)
