### ISSUE TITLE
能问下mcdn的视频是不是不可以播放么？

### ISSUE THREAD

**Issue by csmagics** [xfangfang/wiliwili#11]
我用postman 获取播放地址 返回 https://xy123x246x199x18xy.mcdn.bilivideo.cn:4483xxxxxxxx。我放在vlc 播放失败。但是我看你的代码好像没有特殊处理 好像就是调用mpv的样子

**Comment by xfangfang** [comment]
b站某些接口获取到的视频需要设置请求header

在初始化mpv的代码中有写：

    mpv_set_option_string(mpv, "referrer", "https://www.bilibili.com/");

**Comment by csmagics** [comment]
@xfangfang 
好使哈哈多谢
