### ISSUE TITLE
[咨询]windows下使用msys2编译出来的二进制文件直接打开时缺少各种动态链接库

### ISSUE THREAD

**Issue by protosskai** [xfangfang/wiliwili#110]
我使用msys2成功编译出来了二进制文件，并且在msys2的终端环境下可以正确打开这个程序。
但是我再windows的文件资源管理器中，直接双击wiliwili.exe打开的时候。提示找不到各种dll，例如libwinpthread-1.dll，libstdc++-6.dll等等，怀疑可能是直接再win中运行的时候，系统搜索dll的目录中缺少msys2环境中的dll。
请问有大佬知道解决方案吗？或者有什么办法可以直接将这些dll直接打包到可执行文件中吗？

**Comment by xfangfang** [comment]
@protosskai 
有人问过类似的问题了：https://github.com/xfangfang/wiliwili/issues/16

问题中的回答思路是没问题的，具体操作可能略有不同，以你正在使用的源码分支下的 github/workflows/build.yaml 文件中的内容为准

**Comment by protosskai** [comment]
> @protosskai 有人问过类似的问题了：#16
> 
> 问题中的回答思路是没问题的，具体操作可能略有不同，以你正在使用的源码分支下的 github/workflows/build.yaml 文件中的内容为准

感谢大佬的回复！刚刚看了下 #16，大概明白了解决的思路，我尝试一下，多谢。
