### ISSUE TITLE
希望增加桌面端平台切换全屏状态的快捷键

### ISSUE THREAD

**Issue by domexie** [xfangfang/wiliwili#111]
大佬开发的wiliwili占用内存很小，反应很迅速，在桌面平台非常适合同时打开多个窗口进行浏览。目前切换全屏状态需要退出视频播放，然后进入设置进行切换。希望能够增加一个切换应用全屏状态的快捷键，比如F11。

**Comment by xfangfang** [comment]
@domexie 不好意思，这几天在开发评论图片的功能没来得及回复。

在windows和linux确实存在这个问题，我在这两个平台上使用的时候也遇到过这样的不便。

我之前的想法是：双击视频播放器来切换 全屏/窗口 的状态；或者在点击播放器的全屏按钮时自动进入全屏。

因为这个软件是为手柄设计的，所以所有键盘快捷键都需要和手柄按键匹配。如果把之前的设定推倒重写，单独搞一个按键来切换全屏需要花亿点点时间，我有时间再仔细琢磨琢磨怎么做最优雅再说吧～

**Comment by xfangfang** [comment]
@domexie 简单地在播放器右上角的菜单里添加了一个全屏选项（仅限 Windows 和 Linux），或者之后直接再做一个额外的按钮放在播放器上，这样比做一个全局的快捷键省事，不了解快捷键或者忘记了快捷键的朋友也可以看出来如何在播放页全屏。我感觉是比快捷键更好的处理方式。（因为我老是记不住快捷键）

在这里可以下载测试：https://github.com/xfangfang/wiliwili/actions/runs/4702961505

欢迎反馈

**Comment by domexie** [comment]
这个快捷设置基本解决了问题，并且同时能兼容手柄操控，好评。
但是大部分桌面端软件都使用F11按键作为全屏切换的按键，这已经是约定俗成的习惯了，我觉得隐性地添加F11作为切换软件全屏快捷键不会给用户带来困扰。
而Switch端并不支持窗口化显示，因此无需考虑此快捷键对应的NS按键。

**Comment by xfangfang** [comment]
@domexie 这个真的不是我不愿意加快捷键，而是UI框架的限制（因为这个框架就是面向手柄用户的），如果要增加这样的全局快捷键，需要花时间来修改。

当然可以堆一些垃圾代码来快速支持这个功能，比如增加一个叫“F11”的手柄按键，但是我还是希望少做这样的事。而且我感觉可能桌面端大部分用户还是会用官方的客户端，wiliwili的windows用户大多数可能还是掌机用户（我的猜测，没有统计过）。

这个功能对我来说倒不是特别关键，因为我确实是很少按快捷键，而且和增加这个快捷键相比花时间用来增加更多全平台用户都能体验到的功能性价比会更高，所以我应该不会做这样的修改了。

欢迎给这个项目提交PR，对于这个功能应该几乎不需要修改wiliwili的代码，只去更改 borealis 按键处理的部分就可以了。

**Comment by xfangfang** [comment]
添加了快捷键：
1. F： 全屏 （大多数页面均可用，部分对话框下无效）
2. 空格：播放暂停


测试链接：https://github.com/xfangfang/wiliwili/actions/runs/7956528455

**Comment by shugo-chara** [comment]
> 添加了快捷键：
> 
> 1. F： 全屏 （大多数页面均可用，部分对话框下无效）
> 2. 空格：播放暂停
> 
> 测试链接：https://github.com/xfangfang/wiliwili/actions/runs/7956528455

@xfangfang 
空格暂停好评！！
反馈：
1.测试版播放会跟按住空格键一样不停的在暂停和播放之间切换，需要按住空格才能正常播放。感觉是长按空格
和松开空格写反了。

2.win下如果开启hdr的状态下，全屏后再退出全屏显示器画面会异常变暗。需要手动关闭系统的hdr再重新打开才能恢复正常。


话说d3d版本不同步构建更新吗

**Comment by xfangfang** [comment]
@shugo-chara https://github.com/xfangfang/wiliwili/actions/runs/7964242708
1. 空格的问题解决了，我感觉可能是不同平台编译器优化的问题。
2. hdr 暂时无法解决，glfw 现在也不支持 hdr，开了应该也没有效果 颜色可能还更不准。从全屏退出后显示器状态变更了没准和显卡驱动也有关系，如果方便可以自己调试看看。

**Comment by shugo-chara** [comment]
@xfangfang 
更新太勤奋了！测试空格问题已解决。
hdrshi因为平时显示器默认就开启hdr所以才发现的。解决方案是窗口化全屏就OK。
现在F是显示器全屏，个人平时用的少基本都是窗口化全屏。

~~强烈推荐d3d随build构建常驻hhh~~😆

**Comment by xfangfang** [comment]
@shugo-chara 
对于windows下究竟怎么控制全屏，我不是很了解，这里是一些信息，欢迎提交 pr：

1. 关于wiliwili全屏模式的讨论
https://github.com/xfangfang/wiliwili/issues/171

2. wiliwili 使用这个 pr 中所说的 “GLFW_SOFT_FULLSCREEN” 来让输入法显示在全屏下 （我猜没准把这个选项关闭能解决你说的问题，但是会影响到输入法的显示）
https://github.com/clear-code/glfw/commit/36ff2b3588aa2b745a59bc4f2a7b522cc21a220a

3. wiliwili 支持使用 GLFW（默认） 和 SDL 来控制窗口，如果 GLFW 没有相关的功能你可以在编译时切换到 SDL 测试看看。

4. 我的另外一个猜测是切换到 `无边框窗口全屏` 也能解决问题，不过这个问题因为我平时不怎么用 windows 所以大概率要靠大家的 pr 了，如果有人做的话最好不要简单的指定一个固定的全屏方案，而是在 borealis 的 application.hpp （或者其他方便的位置）里给出选项供开发者切换。

**Comment by letheva1** [comment]
大佬，视频播放按右下角扩大到整个窗口后，空格键暂停播放会失效

**Comment by xfangfang** [comment]
> 大佬，视频播放按右下角扩大到整个窗口后，空格键暂停播放会失效

@letheva1 3/12 之后的测试版都修复这个问题了，我猜测你可能下载的不是最新的测试版。
