### ISSUE TITLE
老大，这几天不晓得为啥，头像 和图片，尤其个人页面 显示极其慢。动不动就是network error，特别难受

### ISSUE THREAD

**Issue by kingskill** [xfangfang/wiliwili#112]
如题。奇葩的是偶尔视频可以播放，连弹幕也有，但旁边 的评论一片network error。

本人机子deepin20.9，（debian10系的 ），i3 6100, 核显hd530。
使用网页bilibili没有任何问题。网络是通畅的。

不知道是 哪里 的 问题？哔哩哔哩 的api有状况 吗 ？

![截图_wiliwili_20230416165656](https://user-images.githubusercontent.com/43365116/232288190-8ef995a1-19a3-46d0-9dab-b6b7e25f9d05.jpg)
![截图_wiliwili_20230416165735](https://user-images.githubusercontent.com/43365116/232288193-d275e285-8687-4aa8-9e82-385683016383.jpg)
![截图_wiliwili_20230416165722](https://user-images.githubusercontent.com/43365116/232288194-c28bb6b7-e713-4ea3-b15c-16f11bdb83ae.jpg)
![截图_wiliwili_20230416165631](https://user-images.githubusercontent.com/43365116/232288195-45f4e194-d4e4-4154-80bf-f9775c681c6f.jpg)
![截图_wiliwili_20230416165645](https://user-images.githubusercontent.com/43365116/232288196-77cea92f-fb40-4c15-a410-c1d600f94272.jpg)
![截图_wiliwili_20230416165711](https://user-images.githubusercontent.com/43365116/232288198-ee2aac4d-70c8-4046-9f63-6bfb36bfa4c7.jpg)

**Comment by xfangfang** [comment]
@kingskill 我这里没有这样的情况，甚至因为加载速度快基本看不到图片加载的过程。

可以下载测试版测试: https://github.com/xfangfang/wiliwili/wiki

在应用设置中把图片加载线程数适当调大（比如8）, 测试版支持webp图片，图片大小会更小，理论上会更快。

api 和网页端不一定一致，没有可比性。可以试试用测试版重新扫码登录看看，测试版使用了新的登录方式，或许会和这个有关系（我感觉关系不大）。

如果还是存在问题，那就应该是其他问题导致的，比如：就是网慢，DNS配置不对，有什么神奇的代理，或者是路由器搞的问题（开了dns防污染也可能会导致加载速度慢）。
这时候可以做两件事：
1. 同一网络环境下换一个其他设备使用 wiliwili 查看能不能复现；
2. 同一个设备换一个网络环境使用 wiliwili 查看能不能复现

总之就是控制变量地去找到问题，因为我这边确实是没有这种情况，只给我发这样的截图我也没有办法帮助你。

**Comment by kingskill** [comment]
我这机子直接连在光猫上的，没有路由的问题。之前也都是快速秒连。就这几天，感觉是4月12日前后出现的。我怀疑可能是运营商，我宽带是200m上海移动。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月16日(周日) 下午5:29
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xfangfang/wiliwili] 老大，这几天不晓得为啥，头像 和图片，尤其个人页面 显示极其慢。动不动就是network error，特别难受 (Issue #112)




 
@kingskill 我这里没有这样的情况，甚至因为加载速度快基本看不到图片加载的过程。
 
可以下载测试版测试: https://github.com/xfangfang/wiliwili/wiki
 
在应用设置中把图片加载线程数适当调大（比如8）, 测试版支持webp图片，图片大小会更小，理论上会更快。
 
api 和网页端不一定一致，没有可比性。可以试试用测试版重新扫码登录看看，测试版使用了新的登录方式，或许会和这个有关系（我感觉关系不大）。
 
如果还是存在问题，那就应该是其他问题导致的，比如：就是网慢，DNS配置不对，有什么神奇的代理，或者是路由器搞的问题（开了dns防污染也可能会导致加载速度慢）。
 这时候可以做两件事：
  
同一网络环境下换一个其他设备使用 wiliwili 查看能不能复现；
 
同一个设备换一个网络环境使用 wiliwili 查看能不能复现
  
总之就是控制变量地去找到问题，因为我这边确实是没有这种情况，只给我发这样的截图我也没有办法帮助你。

**Comment by Eitetsu0** [comment]
+1 我也有同样的情况，经常 network error ，然后刷新一下又秒刷出来emm。

另外给视频点赞的时候会报错 `[ERROR] code: -403; msg: 账号异常,操作失败`

**Comment by xfangfang** [comment]
> 另外给视频点赞的时候会报错 [ERROR] code: -403; msg: 账号异常,操作失败

@Eitetsu0 有另一个issue提及过这个问题，我前面也有说过。使用测试版重新登录可以解决。

**Comment by Eitetsu0** [comment]
额，我是觉得这个是不是跟这个issue里猜想的API有关，于是就提了一下。在 2023年4月16日，19:50，xfangfang ***@***.***> 写道：﻿

另外给视频点赞的时候会报错 [ERROR] code: -403; msg: 账号异常,操作失败

@Eitetsu0 有另一个issue提及过这个问题，我前面也有说过。使用测试版重新登录可以解决。

**Comment by xfangfang** [comment]
@Eitetsu0 哦哦，明白啦，我以为你现在还有这个问题呢。

**Comment by Eitetsu0** [comment]
😂确实是有，刚刚重新登录，现在没有了。在 2023年4月16日，20:18，xfangfang ***@***.***> 写道：﻿
@Eitetsu0 哦哦，明白啦，我以为你现在还有这个问题呢。
