### ISSUE TITLE
长视频标题长度超过视频宽度

### ISSUE THREAD

**Issue by Eitetsu0** [xfangfang/wiliwili#113]
平台：Linux + wayland
commit: [8e4c296](https://github.com/xfangfang/wiliwili/commit/8e4c2963926429560cb0be22283ff923c58186ff)

过长标题的“...”会延伸到评论栏：
![sc_20230420_08:31:03](https://user-images.githubusercontent.com/6576065/233228608-4641904e-17ba-4b27-ac32-43955614904c.png)

不过焦点移到标题上，滚动的时候，宽度是跟视频对齐的：
![sc_20230420_08:31:15](https://user-images.githubusercontent.com/6576065/233228720-2151e6d9-0bbc-4696-a9cf-37528acecaf8.png)

**Comment by xfangfang** [comment]
@Eitetsu0 这个问题一直都有的，borealis对中文和特殊字符的分割不太准确，我有时间会研究研究的

**Comment by xfangfang** [comment]
@Eitetsu0 问题修复，可以下载测试版体验：https://github.com/xfangfang/wiliwili/actions/runs/4887061151

**Comment by Eitetsu0** [comment]
是不是改的太短了:joy:
![sc_20230505_18:02:45](https://user-images.githubusercontent.com/6576065/236429892-c7bb49f3-88e3-464a-94f5-0f5cae8990f9.png)

**Comment by xfangfang** [comment]
我也注意到了这样的问题，其实这种情况往往就是再多加一个字就擦边了，我试过好几次了

**Comment by Eitetsu0** [comment]
不加 “...” ，把过长的部分截断；或者直接默认动画滚动标题，如何？


另外：
点击标题的时候，也把完整标题显示在弹出窗口里，可以吗？感觉这样更符合直觉。

**Comment by xfangfang** [comment]
这个我之后再看看怎么微调一下文字分割的算法就行了，如果不是故意看这里的话，可能不是特别明显。

点标题弹出来简介这个功能之后可能还得改一改，我还在想怎么可以更好的把用户主页或者其他一些信息（比如用户正在直播）显示出来，方便点击操作。

**Comment by xfangfang** [comment]
![image](https://user-images.githubusercontent.com/16631584/236455292-e0bc3855-7e42-4924-ad33-f5e4d9340423.jpeg)![image](https://user-images.githubusercontent.com/16631584/236455307-9df8c73c-9a6c-4ca4-bbbc-c46191090229.jpeg)
刚刚用手机客户端随机点开两个视频，看到也有相似的问题，不过之前眼神没有关注过这里，所以从来没有发现

**Comment by Eitetsu0** [comment]
手机端右边还有个对齐的小箭头吧:dog:，把箭头看成标题一部分的话就对称了。
![狗头](https://i0.hdslb.com/bfs/emote/3087d273a78ccaff4bb1e9972e2ba2a7583c9f11.png)


不过确实这样已经不明显了。
