### ISSUE TITLE
动态错误

### ISSUE THREAD

**Issue by newcovid** [xfangfang/wiliwili#114]
今天看动态发现这个错误,尝试了重新登录和重启软件都无效
![image](https://user-images.githubusercontent.com/96228495/233338008-d73f2383-3c5d-4cff-a468-3804472e9aa0.png)

**Comment by xfangfang** [comment]
@letianpai-lpt 感谢反馈。
20号中午的时候我使用还没有问题的，应该是B站API变更导致的。
已经于测试版修复了这个问题，可以下载测试：https://github.com/xfangfang/wiliwili/actions/runs/4753417774

**Comment by xfangfang** [comment]
@letianpai-lpt 另外，我发现在我这边之前的版本这个问题也消失了，或许是B站发现了类似的问题已经调整了

**Comment by newcovid** [comment]
> @letianpai-lpt 另外，我发现在我这边之前的版本这个问题也消失了，或许是B站发现了类似的问题已经调整了

是的，我的也正常了，看起了是暂时性的错误

**Comment by xfangfang** [comment]
@letianpai-lpt 是的，我刚刚确认了一下，B站自己修复了这个问题，那么先关闭这个issue了。
