### ISSUE TITLE
switch测试版看视频有时候会蓝屏

### ISSUE THREAD

**Issue by mkai1123** [xfangfang/wiliwili#115]
大佬。尝试删除重装，重新登陆，也还是会出现蓝屏

**Comment by xfangfang** [comment]
@mkai1123 你下载的是哪个测试版呢？下载最新的试一试

**Comment by mkai1123** [comment]
好像是241145，新版本暂时没问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月22日(周六) 晚上8:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xfangfang/wiliwili] switch测试版看视频有时候会蓝屏 (Issue #115)




 
@mkai1123 你下载的是哪个测试版呢？下载最新的试一试

**Comment by xfangfang** [comment]
@mkai1123 好的，那先关闭这个issue了
