### ISSUE TITLE
两个关于UI逻辑的建议

### ISSUE THREAD

**Issue by Eitetsu0** [xfangfang/wiliwili#116]
### 1. 自动播放下一视频的时候保持全屏状态。
特别是全屏追剧/看番的时候，打开自动播放下一集一般来讲就是不太想手动介入，现在播完退出全屏还要手动再点一下。

### 2. 非全屏状态播放页打开 播放设置/弹幕设置/评论详情 的时候，不让窗口其它部分变暗。
非全屏状态弹出的侧边栏并不会影响视频框，而屏幕变暗就有点强行降低观看体验了。
少数时候为了突出显示可以理解，但有时候就想看看评论回复，这时候给视频罩一层黑，我觉得是不是就有点过头了啊:joy:

**Comment by xfangfang** [comment]
1. 可以进播放器右上角设置修改

2. 这么写是因为弹出的页面是在当前页面之上的，即使不加这个遮罩，左侧的页面也是无法点击的，我比较担心有用户这个时候不知道需要退出评论详情。有几个解决办法，可能要花一些时间来允许弹出页面时可以点击左侧。这个或许以后有时间会研究研究看看

当然，一个简单的做法是直接把现在的遮罩删除。可以看一看咱们项目的wiki：https://github.com/xfangfang/wiliwili/wiki

里面有提及如何自定义修改页面

对于这个问题，只需要删掉 resources/xml/fragment/player_single_comment.xml 根元素的backgroundColor 就可以了

**Comment by Eitetsu0** [comment]
1.  OK
2.  原来如此，我明白原因了。感谢投入。那么这个issue我先关掉了
