### ISSUE TITLE
自动更新v1.0.1后点击个人动态tab会出现api error

### ISSUE THREAD

**Issue by lyhkkk** [xfangfang/wiliwili#117]
平台: Win10 22H2 X64
独立显卡：AMD 5700XT
硬件加速：开启

个人动态tab显示：Api error. [jason.exception.type_error.302] type must be number, but is null

**Comment by xfangfang** [comment]
@lyhkkk 可以进应用设置看一下详细的版本号吗？这个应用并没有做自动更新，只有更新提示。

**Comment by xfangfang** [comment]
@lyhkkk 
我先关闭这个issue了，因为我猜大概率是你还没有更新软件，把更新提醒当成了自动更新。

根据这一点，我调整了更新提醒的内容，尽量避免其他人产生相似的误解，感谢反馈。
