### ISSUE TITLE
加载程序时黑屏时间太长，建议加一个加载动画或者提示

### ISSUE THREAD

**Issue by Askwind** [xfangfang/wiliwili#12]
在大气层中R加载wiliwili，第一次加载程序时黑屏时间太长，我都以为是程序死了，需要40秒左右才能进入界面。

建议增加一个加载动画或者带有提示的画面。

**Comment by xfangfang** [comment]
我从来没有遇到过加载时间过长的情况，第一次加载和之后的每一次加载一样，并不存在额外的操作。

可以尝试将内存卡 config/wiliwili 文件夹删除重新进入软件以复现问题。

（我猜大概率是switch偶尔抽风）

**Comment by xfangfang** [comment]
@Askwind 请问这个问题还有后续吗？

**Comment by Askwind** [comment]
> 我从来没有遇到过加载时间过长的情况，第一次加载和之后的每一次加载一样，并不存在额外的操作。
> 
> 可以尝试将内存卡 config/wiliwili 文件夹删除重新进入软件以复现问题。
> 
> （我猜大概率是switch偶尔抽风）

删除config后就好了！搞定！

**Comment by xfangfang** [comment]
@Askwind 打扰一下，又有两个用户和我反馈这个问题，了解过之后发现他们都是用的512G的内存卡，请问您使用的内存卡也是如此吗？顺便询问一下内存卡的格式是exfat还是fat32呢？

我会把相关的信息统计一下总结在说明文档中，避免其他人遇到类似的问题，感谢～

---

补充他们还都是白色 三星卡，不知道这一点和您的卡是不是也是一样的

**Comment by Askwind** [comment]
> @Askwind 打扰一下，又有两个用户和我反馈这个问题，了解过之后发现他们都是用的512G的内存卡，请问您使用的内存卡也是如此吗？顺便询问一下内存卡的格式是exfat还是fat32呢？
> 
> 我会把相关的信息统计一下总结在说明文档中，避免其他人遇到类似的问题，感谢～
> 
> 补充他们还都是白色 三星卡，不知道这一点和您的卡是不是也是一样的

我的是 [闪迪（SanDisk）128GB TF 存储卡 U1 C10 A1 至尊高速移动版内存卡](https://item.jd.com/1887518.html)
用的Fat32格式

**Comment by xfangfang** [comment]
> > @Askwind 打扰一下，又有两个用户和我反馈这个问题，了解过之后发现他们都是用的512G的内存卡，请问您使用的内存卡也是如此吗？顺便询问一下内存卡的格式是exfat还是fat32呢？
> > 我会把相关的信息统计一下总结在说明文档中，避免其他人遇到类似的问题，感谢～
> > 补充他们还都是白色 三星卡，不知道这一点和您的卡是不是也是一样的
> 
> 我的是 [闪迪（SanDisk）128GB TF 存储卡 U1 C10 A1 至尊高速移动版内存卡](https://item.jd.com/1887518.html) 用的Fat32格式

万分感谢详细回复！
