### ISSUE TITLE
v0.6.0点击个人动态tab会出现api error

### ISSUE THREAD

**Issue by lyhkkk** [xfangfang/wiliwili#121]
平台: Win10 22H2 X64
独立显卡：AMD 5700XT
硬件加速：开启

个人动态tab显示：Api error. [jason.exception.type_error.302] type must be number, but is null

![image](https://user-images.githubusercontent.com/60431195/236003116-4f8d4383-aec2-44b9-8591-3a5d243db34b.png)
![image](https://user-images.githubusercontent.com/60431195/236003207-5afbbb8a-4518-4ee4-a2a8-44ae125a3c2c.png)

**Comment by xfangfang** [comment]
@lyhkkk 更新软件

**Comment by xfangfang** [comment]
https://github.com/xfangfang/wiliwili/releases/tag/v1.0.1
