### ISSUE TITLE
16.0.2系统大气层1.5.2进入后安Y就卡死

### ISSUE THREAD

**Issue by rexhang** [xfangfang/wiliwili#123]
16.0.2系统大气层1.5.2进入后安Y就卡死，只能强制关机。大神，希望解决一下。

**Comment by xfangfang** [comment]
@rexhang 遇到问题可以先看一看项目wiki

[wiliwili/wiki#switch-打开输入法报错](https://github.com/xfangfang/wiliwili/wiki#switch-打开输入法报错)

这个问题不是某个自制软件造成的，一般来说你在同一个系统上用任何一个自制软件打开系统输入法都会出现相似的问题。
