### ISSUE TITLE
当前dev分支在switch选择安装桌面图标会崩溃退出

### ISSUE THREAD

**Issue by 4fuu** [xfangfang/wiliwili#126]
我在删除软件重试直播弹幕功能时发现。或许是否有遗留的文件需要删除

**Comment by xfangfang** [comment]
安装桌面图标需要在resources目录下有编译好的nsp文件，如果是自己手动编译，且cmake编译参数设置了nsp，但是没有放置nsp，那么就会出现找不到的问题，这里当时没有写太多的代码来检验。

可以分别测试一下 github action下载的dev分支编译结果和release有没有这个问题

具体的编译指令可以参考 .github 下的编译配置。

- - -

如果在成功安装桌面图标的情况下应用闪退的话：可以检查一下 switch/wiliwili.nro/ 和 switch/wiliwili/wiliwili.nro/ 保证这两个路径不是目录。（我感觉这种可能性不高）

wiliwili 的桌面的图标会优先打开前者，在前者不存在时打开后者，在后者不存在时打开hbmenu。
检查存在不存在的函数只检查了路径是否存在，没有检查路径是不是目录，如果是目录也会造成开启闪退。（是的，虽然我想不明白，但是真的有人这么做过）

**Comment by 4fuu** [comment]
确实是nsp的问题，我就说为什么文件包体积不一样
