### ISSUE TITLE
安卓版什么时候可以上线？

### ISSUE THREAD

**Issue by Jeephan** [xfangfang/wiliwili#127]
希望可以开发一个安卓版，安卓平板可以使用。

**Comment by xfangfang** [comment]
友情提示：在github提issue之前应该先搜索一遍历史issue，这个是这个社区的规则，也可以节约大家的时间。

---

我已经在issue区内评论过很多次了，任何安卓版的支持都会导致wiliwili的其他任何全平台版一起被封禁，作者会被连累律师函，已经有相当多的实例案件。

wiliwili从来都是丰富官方客户端不支持的平台而不是在某些平台替代官方客户端，尤其是安卓端的替代，会导致官方损失大量利益，被封禁是必然。

在这里我再次声明，我从未以任何方式发布过wiliwili的安卓版，并且只要有任何wiliwili的安卓版出现在互联网，我都会立即关闭wiliwili的github仓库不再维护。
