### ISSUE TITLE
在PC模式下安装wiliwili需要在微软商店安装新程序（但是找不到该应用）

### ISSUE THREAD

**Issue by KaiyeYang-git** [xfangfang/wiliwili#129]
但是这个程序并不存在在微软商城，以至于软件一直打不开

**Comment by xfangfang** [comment]
@KaiyeYang-git 可以详细描述一下问题看看。

**Comment by KaiyeYang-git** [comment]
问题主要是在安装wiliwili的时候，会有一个链接指向微软商店，要求你安装一个应用（插件？）来帮助wiliwili安装。
此问题在升级了windows版本：2023-05 Cumulative Update for Windows 11 Version 22H2 for x64-based Systems (KB5026372)，2023-04 Cumulative Update Preview for Windows 11 Version 22H2 for x64-based Systems (KB5025305)后已解决。
