### ISSUE TITLE
Steam Deck 提示找不到 libmpv.so.1

### ISSUE THREAD

**Issue by bao3** [xfangfang/wiliwili#13]
我已经在 debian 下编译完成，然后现在是放到 Steam Deck 里。
缺少这个 libmpv 我其实是知道怎么解决的。

我的问题：能不能编译时就包含这个东西，打包成 Appimapge 。我不太熟悉这个，只是 Steam Deck 是掌机，所以对于普通人可能 AppImage 更好更方便。而我弱鸡一只，只好先厚着脸问一下。

**Comment by xfangfang** [comment]
这个应该是可以的，debian下用包管理器拉到的mpv和ffmpeg是动态的库，所以并没有编译进最终的文件中。

只需要手动编译ffmpeg和mpv成静态库再编译wiliwili就可以了，ffmpeg和mpv不要用默认的参数编译，因为默认会引入很多第三方库，一是没有用，二是这些第三方库用包管理器安装下来还是动态库 也就是还需要一一编译成静态库。

编译参数可以参考：https://github.com/xfangfang/wiliwili/issues/6#issuecomment-1236321540

上面的是在switch上的编译参数，不要直接复制，只需要关注那些 disable 和 enable 相关的配置项即可，字幕相关的内容也可以关闭。

（我感觉最简单的办法还是在Steam Deck上安装mpv）


我在windows下编译过，很好奇能不能在Steam Deck上跑起来：
https://github.com/xfangfang/OpenWrt-DIY/actions/runs/3017458475


---
打包成 Appimapge 这个我就不太了解了

**Comment by bao3** [comment]
@xfangfang 使用你的 windows 版本，可以正常在 Steam Deck 上运行。不过仍然有一些问题：

1. 左下设置那个图标的 2 个字是方块，我猜可能是“设置”
2. 视频可以播放，可以看弹幕。不过很多视频打开就导致软件死掉，需要重开软件。没有特别的规律，大部分这些视频是 60fps 的。而且这些导致死掉的视频，重开 wiliwili 后却可以正常观看。
3. 由于不是 Switch 所以下面那一行“充电”和“无线”一直在闪。
4. 视频的进度条，手指不能拖动。

**Comment by xfangfang** [comment]
@bao3 

> 左下设置那个图标的 2 个字是方块，我猜可能是“设置”

方块是图标，还有其他一些看起来不太正确的都是图标，在switch内加载机器自带的字体就能正常显示了，若想在外部正确显示，需要找替代的字体文件，重命名为 switch_icons.ttf 放在 resources/font 目录下。因为我没找到可以合法使用的字体，所以就没放。

> 视频可以播放，可以看弹幕。不过很多视频打开就导致软件死掉，需要重开软件。没有特别的规律，大部分这些视频是 60fps 的。而且这些导致死掉的视频，重开 wiliwili 后却可以正常观看。

这个不见得哪里的问题，我这边直接用windows运行是没啥问题的，我认为如果在steam deck 上原生编译应该也不会出问题。

> 由于不是 Switch 所以下面那一行“充电”和“无线”一直在闪。
> 视频的进度条，手指不能拖动。

正常现象，windows客户端这个我当时就是尝试一下看能不能正常编译，对于细节并没有做适配，还有更多的小细节问题。

**Comment by Masaiki** [comment]
> 方块是图标，还有其他一些看起来不太正确的都是图标，在switch内加载机器自带的字体就能正常显示了，若想在外部正确显示，需要找替代的字体文件，重命名为 switch_icons.ttf 放在 resources/font 目录下。因为我没找到可以合法使用的字体，所以就没放。

试了几个大字符集的 TrueType 字体，发现都不行
感觉可能是用到了 Unicode 的私人使用区，类似于苹果公司用 U+F8FF 来显示他的图标

**Comment by xfangfang** [comment]
@Masaiki https://github.com/XITRIX/borealis/raw/main/resources/font/switch_icons.ttf

**Comment by Masaiki** [comment]
> @Masaiki https://github.com/XITRIX/borealis/raw/main/resources/font/switch_icons.ttf

把这个字体和思源黑的 TrueType 版本合并了以下，应该算是可用了？
[switch_font.zip](https://github.com/xfangfang/wiliwili/files/9741827/switch_font.zip)

**Comment by xfangfang** [comment]
> > @Masaiki https://github.com/XITRIX/borealis/raw/main/resources/font/switch_icons.ttf
> 
> 把这个字体和思源黑的 TrueType 版本合并了以下，应该算是可用了？ [switch_font.zip](https://github.com/xfangfang/wiliwili/files/9741827/switch_font.zip)

@Masaiki 抱歉前面那条我没有收到通知。

前面说过了：
> 方块是图标，还有其他一些看起来不太正确的都是图标，在switch内加载机器自带的字体就能正常显示了，若想在外部正确显示，需要找替代的字体文件，重命名为 switch_icons.ttf 放在 resources/font 目录下。因为我没找到可以合法使用的字体，所以就没放。

只需要把图标字体放在指定目录就可以了，这个目录下可以存放两个字体文件的，不需要自己来合并。

**Comment by xfangfang** [comment]
我尝试编译了一下flatpak的安装包，在kde neon上测试是没什么大问题的（不过好像图标没显示出来），steam deck应该也没问题，大家如果还感兴趣的话可以安装试试，简单的使用流程写在了：https://github.com/xfangfang/wiliwili/releases/tag/v0.5.0

**Comment by bao3** [comment]
太好了，今天安装。辛苦了发自我的 iPhone在 2022年11月30日，07:00，xfangfang ***@***.***> 写道：﻿
我尝试编译了一下flatpak的安装包，在kde neon上测试是没什么大问题的（不过好像图标没显示出来），steam deck应该也没问题，大家如果还感兴趣的话可以安装试试，简单的使用流程写在了：https://github.com/xfangfang/wiliwili/releases/tag/v0.5.0

**Comment by bao3** [comment]
> 

反馈一下, 如果使用普通用户 `deck` 安装，Steam deck flatpak 无法安装。


```
(deck@steamdeck common)$ flatpak install ./wiliwili-Linux-9e3fe05.flatpak

cn.xfangfang.wiliwili permissions:
    ipc          network              pulseaudio      wayland      x11
    devices      file access [1]

    [1] ~/.var/app/cn.xfangfang.wiliwili/config:create


        ID                         Branch     Op     Remote               Download
 1. [|] cn.xfangfang.wiliwili      master     i      wiliwili1-origin     0 bytes

Installing…error: Failed to install bundle cn.xfangfang.wiliwili: Flatpak system operation InstallBundle not allowed for user

```

需要使用 root 权限：

```

(deck@steamdeck common)$ sudo flatpak install ./wiliwili-Linux-9e3fe05.flatpak
[sudo] password for deck:

cn.xfangfang.wiliwili permissions:
    ipc          network              pulseaudio      wayland      x11
    devices      file access [1]

    [1] ~/.var/app/cn.xfangfang.wiliwili/config:create


        ID                         Branch     Op     Remote               Download
 1. [✓] cn.xfangfang.wiliwili      master     i      wiliwili2-origin     0 bytes

Warning: Not exporting file cn.xfangfang.wiliwili.appdata.xml of unsupported type.

Note that '/var/lib/flatpak/exports/share' is not in the search path
set by the XDG_DATA_HOME and XDG_DATA_DIRS
environment variables, so applications may not
be able to find it until you set them. The
directories currently searched are:

        ID                         Branch     Op     Remote               Download
 1. [✓] cn.xfangfang.wiliwili      master     i      wiliwili2-origin     0 bytes

Warning: Not exporting file cn.xfangfang.wiliwili.appdata.xml of unsupported type.
Installation complete.

```

**Comment by xfangfang** [comment]
@bao3 直接flatpak install是安装在系统目录，需要root权限也正常，可以试试安装时添加 --user 这样或许就不需要了。
后面的warning是版本不兼容出现的警告，可以直接忽视掉

**Comment by bao3** [comment]
> 

已经验证，可行，太感谢了。目前就是有一个问题，播放时，会随机发生卡死，但是瑕不掩瑜，已经很赞了。

```
(deck@steamdeck common)$ flatpak install --user ./wiliwili-Linux-9e3fe05.flatpak

cn.xfangfang.wiliwili permissions:
    ipc          network              pulseaudio      wayland      x11
    devices      file access [1]

    [1] ~/.var/app/cn.xfangfang.wiliwili/config:create


        ID                         Branch      Op     Remote              Download
 1. [✓] cn.xfangfang.wiliwili      master      i      wiliwili-origin     0 bytes

Warning: Not exporting file cn.xfangfang.wiliwili.appdata.xml of unsupported type.
Installation complete.
```

**Comment by xfangfang** [comment]
> 已经验证，可行，太感谢了。目前就是有一个问题，播放时，会随机发生卡死，但是瑕不掩瑜，已经很赞了。

卡死可能是在主页按了y吧，这里需要输入文字，但是这个功能没有做pc端适配

**Comment by bao3** [comment]
非常感谢，Issue Closed.
