### ISSUE TITLE
希望能加个音量控制的功能

### ISSUE THREAD

**Issue by rexhang** [xfangfang/wiliwili#134]
希望能加个音量控制的功能，因为平时都底座模式 插电视看番剧，但是底座模式下 switch pro手柄是没法通过长按 去调节机器输出音频的声音大小的，如果能在软件层面加上音量控制的话 那简直就 **泰酷啦**

**Comment by xfangfang** [comment]
@rexhang 这个功能在计划之内，同时我也很好奇，那对于其他游戏您是怎么调节音量的呢？

再次提醒：在github 提 issue，要先搜索一遍历史issue，看看有没有其他人已经提过了。

https://github.com/xfangfang/wiliwili/issues/62

**Comment by rexhang** [comment]
其他游戏有内置的音量调节，如果没有的 只能电视机调控音量了，但是很不方便

**Comment by rexhang** [comment]
我看目前已有相关issue了，正在feature中，感谢回复，closed

**Comment by xfangfang** [comment]
@rexhang 最新测试版支持了这个功能：https://nightly.link/xfangfang/wiliwili/workflows/build.yaml/dev

**Comment by rexhang** [comment]
> @rexhang最新版本测试支持了这个功能：https://nightly.link/xfangfang/wiliwili/workflows/build.yaml/dev

感谢支持
