### ISSUE TITLE
能支持直播弹幕功能吗

### ISSUE THREAD

**Issue by w88975** [xfangfang/wiliwili#14]
目前直播没有弹幕, 这个特性能支持吗?

**Comment by xfangfang** [comment]
目前我没有相应的开发计划，如果您对这方面有需求的话可以尝试增加一下相关的功能。

目前直播页面复用了普通的播放器组件，虽然普通的播放组件提供了弹幕的支持，不过并没有对实时插入弹幕做考虑。

考虑到直播播放器还会有其他不同的功能，所以可以独立于普通的播放器组件单独进行开发。

**Comment by w88975** [comment]
👌🏻, 顺便再问一句, 这个可以编译到Android吗? 想用来替代电视盒子里B站客户端

**Comment by xfangfang** [comment]
@w88975 目前只支持linux mac windows和switch，在修改一部分底层opengl的调用代码后或许可以运行在android ios tvos上，但是我并没有相应的计划完成适配，同样欢迎提交pr

**Comment by 4fuu** [comment]
@xfangfang  我今天在研究如何在直播中加入弹幕。我原本是想复用原有弹幕组件，但是我后来发现直播的弹幕与视频的弹幕有所不同，直播的弹幕是接收一条显示一条，并没有时间等其他信息。我看到DanmakuCore::addSingleDanmaku这个函数，是否能完成类似效果？

**Comment by xfangfang** [comment]
@maye174 addSingleDanmaku这个就是考虑直播或者用户手动发送弹幕的时候可以使用，当时简单做了一下我并没有验证过能不能正常使用，如果要用的话保证在主线程调用应该就可以的，有什么需要改动的欢迎联系我。

我注意到之前有其他人做过类似的事，但是他貌似做到一半就删掉代码没有继续了：https://github.com/zhangxinwu/wiliwili/commits/d4c9f1a140f4ed85bf07ec72f3c9ad6e584240f8

直播弹幕可能要用到websocket，这个最好还是不要引入太多的外部库，在switch上可能会有问题（有问题的话解决起来也很麻烦）。

这个链接是目前switch上已有的移植好的库，尽量使用里面有的东西来做，如果引入了其他库要验证一下switch上能不能正常使用，其他pc系统基本不会有什么大问题：https://github.com/devkitPro/pacman-packages/tree/master/switch

**Comment by 4fuu** [comment]
@xfangfang  直播的弹幕是没有时间信息的，我想知道初始化DanmakuItem第二个参数我应该怎么填？颜色什么的我暂时不弄。

**Comment by xfangfang** [comment]
@maye174 时间应该填当前视频播放的时间即可，也就是 MPVCore::instance().playback_time

主要还是应该看 DanmakuCore::drawDanmaku 里面的逻辑来判断究竟填什么

注意我最近在dev分支微调过弹幕相关的代码，如果要改动的话应该以dev分支为准。

**Comment by 4fuu** [comment]
> 



> @maye174 addSingleDanmaku这个就是考虑直播或者用户手动发送弹幕的时候可以使用，当时简单做了一下我并没有验证过能不能正常使用，如果要用的话保证在主线程调用应该就可以的，有什么需要改动的欢迎联系我。
> 
> 我注意到之前有其他人做过类似的事，但是他貌似做到一半就删掉代码没有继续了：https://github.com/zhangxinwu/wiliwili/commits/d4c9f1a140f4ed85bf07ec72f3c9ad6e584240f8
> 
> 直播弹幕可能要用到websocket，这个最好还是不要引入太多的外部库，在switch上可能会有问题（有问题的话解决起来也很麻烦）。
> 
> 这个链接是目前switch上已有的移植好的库，尽量使用里面有的东西来做，如果引入了其他库要验证一下switch上能不能正常使用，其他pc系统基本不会有什么大问题：https://github.com/devkitPro/pacman-packages/tree/master/switch

@xfangfang  我倒是想引入外部库，我找了几个，一个都不支持，看样子还得从头写个websocket  :(，这工作量一下就上去了

**Comment by xfangfang** [comment]
@maye174 

下面的内容可以参考看看：

我注意到devkitpro里面有一个叫wslay的库，不过这个用起来可能不太方便（我没有仔细研究过）。

前面那位兄弟是用 websocketpp 来做的。

我刚刚搜到了mongoose 也不错，而且这个库貌似还支持创建http服务和其他一些协议，未来可以继续在这个库基础上实现B站那个私有的投屏协议，可以研究研究这个看看（当然还是看你的意愿来）。

**Comment by 4fuu** [comment]
@xfangfang  我一开始就是用的websocketpp，这个库在switch上不可用，需要大量的底层移植和重写。现在使用的是wslay+curl的组合，但是现在有一些问题需要解决，距离能用不远了

**Comment by 4fuu** [comment]
@xfangfang  能帮我测试一下这个吗[nsweb](https://github.com/maye174/nsweb)，send功能用不了，一用就崩溃，不知道是什么问题

**Comment by xfangfang** [comment]
@maye174 可以先试试用gdb调试看看崩溃时候堆栈的状态，我今天晚上有点事要看的话得等到周一晚了（明晚）

**Comment by 4fuu** [comment]
> @maye174 可以先试试用gdb调试看看崩溃时候堆栈的状态，我今天晚上有点事要看的话得等到周一晚了（明晚）

没办法调试，win系统编译不了这个程序，而我的wsl也有问题 ：(

**Comment by xfangfang** [comment]
@maye174 还是得能让他在pc上跑起来，只靠switch调试东西很困难的。

可以尝试用后面链接中说的办法(PC and Backtrace)看switch上的崩溃原因：https://switch.homebrew.guide/homebrew_dev/app_dev.html

**Comment by 4fuu** [comment]
@xfangfang  websocket客户端应该是没问题了（大概），但是我不知道是不是直播的进房请求有问题还是其他的什么问题，数据成功发送出去没反应，你可以看我的[fork](https://github.com/maye174/wiliwili-fork)的live部分

**Comment by xfangfang** [comment]
@maye174 哇，很棒！
可以找找其他B站客户端参考看看有没有哪些细节不太对。

我最近在做评论区表情包的功能，把这部分搞好之后才有时间去研究别的问题，加油！

**Comment by xfangfang** [comment]
@maye174 发布新版本之后，有了一点空闲，我刚刚尝试了一下 mongoose，稍微修改了一下配置，就能支持到switch上，在switch上测试了 http server 和 websocket client 都是正常可用的。

https://github.com/xfangfang/mongoose

如果要支持直播弹幕的话，我倾向于使用 mongoose 来做，因为之后可以基于他的代码实现B站的 `哔哩必连` ，同时支持 http server 或许也能带来更多的可玩性 ，比如可以用它搭配腾讯视频的[前端页面](https://film.qq.com/h5/p/switch)来快速实现一个腾讯视频的自制客户端（如果对这个感兴趣也欢迎联系我）。

我因为看直播不多，接下来还是暂时先不看直播弹幕的部分，准备基于 mongoose 研究一下 DLNA 投屏。关于直播弹幕的问题有什么我能帮助到的欢迎继续交流。

**Comment by 4fuu** [comment]
@xfangfang 那既然这样，正好我之前写的无法正常运行，我会研究一下替换成mongoose来实现。现成的客户端应该不会耗费太多精力

**Comment by 4fuu** [comment]
@xfangfang 现在有个问题，我在程序中尝试开一个单独的线程，但是程序会在switch上崩溃

**Comment by xfangfang** [comment]
@maye174 不要调用 detach

**Comment by 4fuu** [comment]
@xfangfang 检查出是一个指针的问题，已经解决了。。现在我的测试程序在win上是可以运行的，也接收到了弹幕。但是我将程序放在ns上跑，还是不显示弹幕，我不清楚是不是我用错了addSingleDanmaku这个函数。如果你有空的话，请帮我看一下我的用法是否正确([直达链接](https://github.com/maye174/wiliwili-dev/blob/dev/wiliwili/source/live/danmaku_live.cpp#L165))，这里是测试程序[地址](https://github.com/maye174/nsweb)
另外我还修改了[这个](https://github.com/maye174/wiliwili-dev/blob/dev/wiliwili/source/activity/live_player_activity.cpp#L45)

**Comment by xfangfang** [comment]
@maye174 感谢，我刚刚拉代码在mac和switch上测试了一下，感觉很棒！

1. 关于弹幕的问题这么修改一下，应该就可以了：
```diff
void DanmakuCore::addSingleDanmaku(const DanmakuItem &item) {
    danmakuMutex.lock();
    this->danmakuData.emplace_back(item);
+    this->danmakuLoaded = true;
    danmakuMutex.unlock();

    // 通过mpv来通知弹幕加载完成
    MPVCore::instance().getCustomEvent()->fire("DANMAKU_LOADED", nullptr);
}
```

2. 根目录的 CmakeLists.txt 里依赖加上zlib，switch下宏定义需要添加 -DMG_ARCH=14

```diff
 if (BUILTIN_NSP)
        list(APPEND PLATFORM_LIBS nsp)
        set(PLATFORM_OPTION -DBUILTIN_NSP)
    endif ()
+    list(APPEND PLATFORM_OPTION -DMG_ARCH=14)
    list(APPEND MAIN_SRC ${CMAKE_SOURCE_DIR}/library/borealis/library/lib/platforms/switch/switch_wrapper.c)
```

```diff
target_link_libraries(${PROJECT_NAME} PRIVATE
        cpr::cpr
        qrcode
        borealis
        lunasvg
        pystring
        mongoose
+        z
        ${PLATFORM_LIBS}
        )
```

3. 多线程不要用 brls::async，这个方法内只用一个子线程运行相对比较轻量的异步事件，使用它会导致其他异步事件被阻塞住。可以用 std::thread 直接写
4. 我刚刚运行的时候 LiveDanmaku::connect 中的 brls::Threading::async 中的 mg_mgr_free(this->mgr); 偶尔会报错。出现在第N次打开直播页时，视频刚刚加载不足一秒就会报错退出，这里可以好好检查下是什么原因。
5. 同时也会出现关闭页面直播间还是持续连接着的问题。（3 4 5 可能是同一个问题，换到 std::thread 应该就好了）
6. 如果可以的话我比较希望把live文件夹换个位置（单独放置有点突兀），比如放在 api 文件夹下，这样B站 api 相关的内容就都放在一起了。不过这么放的话 LiveDanmaku::onMessage 就不应该放在这里面了，可以看看怎么能好好设计下。

感谢贡献，或许之后直播也需要添加弹幕的设置按钮了，这个等你这边基本都做好之后我再来调整也可以～

**Comment by 4fuu** [comment]
@xfangfang 感谢你的测试
1. 你说的1、2点我已经修改。但是或许添加zlib是不需要的，因为b站现阶段已经移除了zlib压缩包，改用brotli了。我会在live的代码中删除zlib的部分

2. 第3点我也改掉了，当时代码有问题我就尝试了`brls::async`

3. 关于第4点有可能是我写的错误处理的缘故，我也修改了，但还需要测试以排除此原因

4. 第5点应该是在`live_player_activity.cpp`这个文件的修改不得当，你可以看到我在连接前会调用disconnect函数一次，这也是权宜之计，因为我对整个项目不熟悉，disconnect函数或许应该在退出的时候调用。或许应该跟下一个点结合考虑

5. 第6点我明白你的意思，放入api中是比较合理的做法。我想说的是，live部分还有很多都没有写：弹幕颜色，特殊弹幕、礼物、醒目留言、人气榜、投票、抽奖等等。这个之后需要我们进行讨论，因为如果挪动进api某些文件可能要重写。

6. 还有，因为直播间是可以发送主播设置的表情包的，所以如果在协议里选择接收带有压缩包的图片就涉及brotli。但是我没有找到直接可以用于switch的brotli库，这可能会涉及到移植问题。

7. 目前这份代码在windows是不可用的(某些架构不同的设备可能也会出错)，我想知道的是，我在完善了上述问题后，是否可以提交pr到dev分支。

最后，我尝试将编译后的文件放入switch上运行，我依旧看不到弹幕。在你的测试中是可用的？我有点摸不着头脑

**Comment by xfangfang** [comment]
@maye174 
重新拉了一下你那边的代码，发现是 parse_packet 里直接把 case 2 删掉了，直接运行会报错：`Unknown protocol version: 2`

LiveDanmaku::instance().disconnect(); 是不是可以放在 LiveActivity 的析构函数里，这样页面关闭了的同时也可以关闭连接。

只要能保证 linux/mac/windows/switch 这四个平台能正常运行，就可以往dev里合并啦，你可以把你那边仓库的github action打开，这样每次提交代码都能触发自动编译，可以快速地发现不同平台的问题。

如果zlib相关的弹幕获取方式暂时是可用的，我建议可以先保证他在各个平台下能用，然后再研究 brotli 相关的内容。毕竟后者如果涉及到表情包的话，现有的弹幕显示方式肯定是不能使用的。
或者即使是使用 brotli 也先完成单色弹幕功能即可，还是要优先让各个平台有一份最基本能跑的代码，不然出了问题只用switch调试起来太慢了。

关于live放置的位置，我感觉只移动到api目录下就行，不需要改太多内容。 LiveDanmaku 可以提供设置回调的函数，回调用来在  LiveDanmaku::onMessage 里调用。这样就可以在 LiveActivity 里设置这样的回调，如果之后涉及到更多和前端相关的内容，就都可以在 LiveActivity 里处理了。

**Comment by 4fuu** [comment]
@xfangfang 会调用zlib是我没想到的，因为单独使用zlib的协议没办法连接服务器，使用纯文本的协议反而会使用zlib。看来网上的资料也过期了。。。目前更新了代码，添加回了zlib，移动了LiveDanmaku::instance().disconnect();进析构函数。

我现在会尝试将代码移动到api，并将设置回调函数onMessage为接口

我的switch程序跑起来依旧没有弹幕，如果可以，我想要一份你的编译后的nro文件。。我要排除是我的环境问题

**Comment by xfangfang** [comment]
@maye174 你可以把你那边仓库的github action打开，然后手动触发一次编译吗？那个应该和我这边是一样的，我现在没办法把文件发给你（要我发得等晚上的）。

仅供提醒一下，我猜你可能不知道可以用 `nxlink -s wiliwili.nro` 来快速的把文件发送到switch上，使用这种方式可以查看switch上的log。如果已经知道的话就可以忽视我这段话啦。

**Comment by xfangfang** [comment]
@maye174 抱歉，我发现一个问题，你需要把 `.github/workflows/build.yaml` 文件中的 `repository: 'xfangfang/wiliwili'` 删掉才能编译自己的仓库（一共有五处，其中第一处包含前面的 `with:` 一起删除）这个变更可以之后一起提交进dev分支来

---
或者把 `'xfangfang/wiliwilli'` 改成 `${{ github.repository }}`

**Comment by 4fuu** [comment]
@xfangfang 已经修改，我也将文件移至api内，也为win准备了不同的头文件。你看一下移动的位置是否合理

但是现在github action过不了，这里是[问题明细](https://github.com/maye174/wiliwili-dev/actions/runs/4912335891/jobs/8771243813)

**Comment by xfangfang** [comment]
@maye174 好的，我晚上的时候研究一下看看是什么问题

**Comment by xfangfang** [comment]
@maye174 合并进dev了，问题是msys2的gcc前两天更新到了13，gcc13要求手动引入 cstdint，依赖的一个库没有引入。
我还发现 ws_utils.hpp 里面有用到 uint8_t 也没有引入 cstdint，刚刚也简单修复了一下。

**Comment by zeromake** [comment]
> @maye174 合并进dev了，问题是msys2的gcc前两天更新到了13，gcc13要求手动引入 cstdint，依赖的一个库没有引入。
> 我还发现 ws_utils.hpp 里面有用到 uint8_t 也没有引入 cstdint，刚刚也简单修复了一下。

我有空把uwp处理一下

**Comment by 4fuu** [comment]
@xfangfang 我在switch上清除了wiliwili在config下的json文件后，我的弹幕终于可以显示了。。。可能有遗留的bug，我会将json文件发给你。但在此之前我想知道，这里面的内容应该不涉及别人能够使用我的b站账号吧。。

**Comment by xfangfang** [comment]
> @xfangfang 我在switch上清除了wiliwili在config下的json文件后，我的弹幕终于可以显示了。。。可能有遗留的bug，我会将json文件发给你。但在此之前我想知道，这里面的内容应该不涉及别人能够使用我的b站账号吧。。

如果里面有cookie信息的话确实是能被别人看到的，所以可以把cookie删除掉。（如果之前不小心分享过，可以在手机设置中把对应的登录退出）

我猜大概率是开了弹幕过滤，比如过滤了滚动弹幕，或者弹幕过滤等级设置了非1的值

**Comment by 4fuu** [comment]
> > @xfangfang 我在switch上清除了wiliwili在config下的json文件后，我的弹幕终于可以显示了。。。可能有遗留的bug，我会将json文件发给你。但在此之前我想知道，这里面的内容应该不涉及别人能够使用我的b站账号吧。。
> 
> 如果里面有cookie信息的话确实是能被别人看到的，所以可以把cookie删除掉。（如果之前不小心分享过，可以在手机设置中把对应的登录退出）
> 
> 我猜大概率是开了弹幕过滤，比如过滤了滚动弹幕，或者弹幕过滤等级设置了非1的值

@xfangfang [wiliwili_config.txt](https://github.com/xfangfang/wiliwili/files/11437459/wiliwili_config.txt)

**Comment by xfangfang** [comment]
@maye174 

"danmaku_filter_level": 2,

弹幕过滤等级设置成了2，这样过滤等级小于2的弹幕都不会显示。

现在应该是初始化成了1吧，可以改成10或者11等更大的数字来避免被过滤掉

**Comment by 4fuu** [comment]
@xfangfang 哦对，是的。。我目前对所有直播弹幕设定的等级都为1
