### ISSUE TITLE
建议播放视频时播放器能够分离2个以上窗口播放！！！

### ISSUE THREAD

**Issue by Aubreyos** [xfangfang/wiliwili#140]
![微信截图_20230526164832](https://github.com/xfangfang/wiliwili/assets/35827906/8f5c98ef-24f4-4dc5-816a-6ee7cb854c9d)
![微信截图_20230526165334](https://github.com/xfangfang/wiliwili/assets/35827906/aa901818-3ef1-40b2-bfc4-eb4c7b39de0e)
![微信图片_20230526164520](https://github.com/xfangfang/wiliwili/assets/35827906/533a9de4-aaef-4031-8fa1-5a8187e4718f)

**Comment by xfangfang** [comment]
@Aubreyos  感谢提出建议

1. 这个软件主要是面向手柄用户的，可以把它当作是运行在电脑或者游戏机上的tv端，分离窗口这个需求目前还不在我的考虑之内。不过如果可以做到在应用设置内添加一个选项用来设置是否开启窗口分离，我是很愿意接受这样的pr的。
2. deepin是支持安装flatpak安装包的，安装方式在 [flatpak官网](https://www.flatpak.org/setup/Deepin) 有写
3. 针对任何系统的任何形式安装包，都欢迎仿照现有的 [github action](https://github.com/xfangfang/wiliwili/blob/dev/.github/workflows/build.yaml) 脚本来完成针对系统的安装包打包脚本，并提交pr，linux系统众多，这个需要靠大家。
4. 播放页右侧有一个叫 “投稿” 的tab，那里就是同一个用户的所有投稿了。
5. 简介有长有短，往下放置该怎么布局呢？
6. 不能复制这个问题确实存在，之后可能考虑做链接的自动识别，允许直接在应用内调用浏览器打开，也可以给pc平台增加一键复制的操作，但是要是想选中文字来复制，那暂时还做不到，ui框架限制，这个功能不支持，需要花时间去写。

在ui上，主要是考虑尽可能地希望所有功能都可以通过 触屏 手柄 键盘 鼠标 这四个输入方式来操作，所以有些地方会比较受限制。

**Comment by Aubreyos** [comment]
你的回复看到了，感谢！！！！
正好 deepin 出了新的包格式，写了个 deepin&nbsp; 玲珑包(linglong)应用应用的构建脚本，你帮忙看下合不合格，看看能不能打包？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xfangfang/wiliwili"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月27日(星期六) 中午11:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xfangfang/wiliwili] 建议播放视频时播放器能够分离2个以上窗口播放！！！ (Issue #140)





 
感谢提出建议
  
这个软件主要是面向手柄用户的，可以把它当作是运行在电脑或者游戏机上的tv端，分离窗口这个需求目前还不在我的考虑之内。不过如果可以做到在应用设置内添加一个选项用来设置是否开启窗口分离，我是很愿意接受这样的pr的。
 
deepin是支持安装flatpak安装包的，安装方式在 flatpak官网 有写
 
针对任何系统的任何形式安装包，都欢迎仿照现有的 github action 脚本来完成针对系统的安装包打包脚本，并提交pr，linux系统众多，这个需要靠大家。
 
播放页右侧有一个叫 “投稿” 的tab，那里就是同一个用户的所有投稿了。
 
简介有长有短，往下放置该怎么布局呢？
 
不能复制这个问题确实存在，之后可能考虑做链接的自动识别，允许直接在应用内调用浏览器打开，也可以给pc平台增加一键复制的操作，但是要是想选中文字来复制，那暂时还做不到，ui框架限制，这个功能不支持，需要花时间去写。
  
在ui上，主要是考虑尽可能地希望所有功能都可以通过 触屏 手柄 键盘 鼠标 这四个输入方式来操作，所有有些地方会比较受限制。

**Comment by xfangfang** [comment]
@Aubreyos 正确的流程是：
1. fork 项目
2. 给自己的项目开启 github action
3. 提交脚本修改
4. 向我的项目提交pr

如果操作正确，那么在第三步之后就能看到自己项目的github action页产生自动构建的结果。以那个结果为准，如果构建出了正确的安装包并且安装无误，那么可以进行第四步。

可能是您发了邮件附件，我现在看不到前面说的构建脚本。即使能看到，我因为没有具体的系统也没办法来验证是否正确，这个要靠您自己了。

**Comment by xfangfang** [comment]
因为这个需求不太可能会实现，所以先把这个issue关闭了
