### ISSUE TITLE
一个不成熟的小意见.希望在pc平台界面缩放可以小点

### ISSUE THREAD

**Issue by tangqiu0205** [xfangfang/wiliwili#142]
在电脑上ui有点大了, 不太适合键盘鼠标操作.

**Comment by domexie** [comment]
反对。wiliwili目前的UI缩放使用起来十分舒适，可以充分合理地展现信息。如果缩小界面，你也只会得到更窄更长的列表，并不会对你的使用有多少好处。

**Comment by xfangfang** [comment]
@tangqiu0205 感谢提出建议

受框架限制，wiliwili的各个组件只能有一个相对窗口大小的固定比例的尺寸，这个比例尺寸如果修改了，那么所有平台就会受到影响。

目前的尺寸大小主要考虑掌机、掌机外接显示器、电视...... wiliwili 本身也不是官方PC端的替代品，对我来说主要还是当作在掌机或者pc端的电视客户端来用。

从用户群的角度上讲，目前最多的用户来源是switch，所以尺寸是不能修改的。

---

不过，因为使用xml来布局，所以用户可以很方便地做自己想要的自定义（尤其是Windows平台）。  
详情请见：https://github.com/xfangfang/wiliwili/wiki#自定义界面布局

比如要修改首页的视频卡片大小：

修改 `resources/xml/fragment/home_recommends.xml` 文件

```diff
<brls:Box
        axis="column"
        marginTop="10"
        marginBottom="8"
        width="auto"
        height="auto">
    <RecyclingGrid
            paddingLeft="20"
            paddingRight="20"
-           itemHeight="250"
+           itemHeight="200"
            grow="1"
            preFetchLine="2"
-           spanCount="4"
+           spanCount="5"
            wireframe="false"
            id="home/recommends/recyclingGrid"/>
</brls:Box>
```

其他的修改也是大同小异。

**Comment by xfangfang** [comment]
@tangqiu0205 如果对这个修改感兴趣，欢迎提交PR，我可以单独开一个分支来存放缩小UI的代码，这样之后每次更新rebase一下应该就可以了。

**Comment by tangqiu0205** [comment]
好的呀,我空闲的时间改一下.

**Comment by xfangfang** [comment]
@tangqiu0205 有任何更新吗，没有的话我就先把这个issue关闭了

**Comment by tangqiu0205** [comment]
抱歉我太菜了, xml布局我了解的不多,按照提示修改虽然显示的条数和卡片大小变了,但他还会根据窗口的大小等比例缩放, 我搞了两天还是无法实现根据窗口大小来动态展示条数并且缩放无论窗口大小都不应改变.

**Comment by zeromake** [comment]
@tangqiu0205 
这个是wiliwili本身的限制，用的ui框架没有做常规的缩放，而是固定高宽来布局，然后直接全局缩放。

**Comment by xfangfang** [comment]
@tiansongyu 做了一个小功能，方便大家使用自定义布局来定制化自己的软件界面。

<img width="400" alt="image" src="https://github.com/xfangfang/wiliwili/assets/16631584/31db68c6-3bed-4a54-8a31-7fcc8b861d04">

<img width="400" alt="image" src="https://github.com/xfangfang/wiliwili/assets/16631584/6702a6e2-e6ac-4736-a565-044ee285e182">

<img width="400" alt="image" src="https://github.com/xfangfang/wiliwili/assets/16631584/1d96e11d-e39e-4328-926e-b11aa1017872">

<img width="400" alt="image" src="https://github.com/xfangfang/wiliwili/assets/16631584/aea0a254-0526-448d-8d03-8c675a7ed55e">


自定义布局仓库：https://github.com/xfangfang/wiliwili_theme

按照仓库中的说明使用即可，欢迎给这个自定义布局仓库提交代码来完善布局。

需要搭配测试版使用：https://nightly.link/xfangfang/wiliwili/workflows/build.yaml/dev

**Comment by xfangfang** [comment]
除了前面说的自定义布局，现在的版本还支持手动调节画面缩放，在应用设置中提供了几个预设选项，貌似应该可以满足需求了，同时受限于UI框架，这几乎也是能做到的极限了，先关闭这个issue啦。
