### ISSUE TITLE
-DGLFW_BUILD_WAYLAND 时 glfwInitHint 优先使用 Wayland

### ISSUE THREAD

**Issue by mochaaP** [xfangfang/wiliwili#143]
rt，给 Flatpak 默认启用 Wayland。

需要更改的有：

- `--socket=x11` -> `--socket=fallback-x11`
- ~~somehow 自动设定 GLFW_USE_WAYLAND=1~~ hint to use Wayland
- build 时给 glfw 启用 wayland 支持（需要 `wayland-protocols` 和 [`-DGLFW_BUILD_WAYLAND`][ref]）

[ref]: https://github.com/xfangfang/glfw/blob/wiliwili/CMakeLists.txt#L34

**Comment by xfangfang** [comment]
@mochaaP 感谢提醒，欢迎提交PR到dev分支

**Comment by mochaaP** [comment]
我在打 Fedora 的包，要不要我加一個「盡量使用系統包」的 cmake 選項？

**Comment by xfangfang** [comment]
@mochaaP 感觉是可以的，可以默认把这个选项设置为关闭，方便打包时候使用即可。

因为最开始时只支持switch，直接把源码放在一起比较方便调试，所以这么写的。

要注意glfw不能用用户系统上的包，修改版增加了输入法和win下的触摸支持，这两个pr还没有合并进glfw，我先拿来用着了。

非常感谢，如果还了解其他linux包的打包也欢迎提交～

**Comment by mochaaP** [comment]
好的 ;)
#145

**Comment by mochaaP** [comment]
@xfangfang

https://copr.fedorainfracloud.org/coprs/mochaa/wiliwili/

**Comment by xfangfang** [comment]
@mochaaP 非常感谢

我更新了wiki中的说明，希望能让其他需要的朋友也看到：https://github.com/xfangfang/wiliwili/discussions/92#discussioncomment-6150000

[wiki#1-下载安装/从包管理器安装](https://github.com/xfangfang/wiliwili/wiki#1-下载安装)

**Comment by xfangfang** [comment]
在 [madoka773](https://github.com/madoka773) 的帮助下已经上架 flathub，我注意到他做了一些wayland相关的修改，可以测试看看有没有解决您的问题（应该是解决了）：https://flathub.org/apps/cn.xfangfang.wiliwili
