### ISSUE TITLE
如何在Switch上debug

### ISSUE THREAD

**Issue by xbw12138** [xfangfang/wiliwili#149]
大佬，请教一下如何debug，在windows上或者switch上

**Comment by xfangfang** [comment]
https://switch.homebrew.guide/homebrew_dev/app_dev.html#debugging

https://gist.github.com/jam1garner/c9ba6c0cff150f1a2480d0c18ff05e33


我主要用第一条链接中的两种方式（nxlink / addr2line），第二条链接说的gdb感觉不是很好用（也可能是我不太会用），有看到说ida可以直接连到大气层的gdb服务上去，那样的话或许会好用一些。（但是我没有试过）

如果是使用borealis开发，绝大部分问题都可以从pc上来解决，依赖switch去调试将是漫长且煎熬的。

**Comment by xbw12138** [comment]
好的，谢谢大佬
