### ISSUE TITLE
支持一下有线连接的图标显示

### ISSUE THREAD

**Issue by HuaJi2333DaDa** [xfangfang/wiliwili#15]
![image](https://user-images.githubusercontent.com/30079825/193087212-6b6980a2-12e9-4d0b-94f0-4259b3e6a0d3.png)
如图，已经有线连接了，提示栏显示的还是 WiFi 图标

**Comment by xfangfang** [comment]
因为我现在没有相应的设备来开启有线连接，所以短时间是完善不了了

**Comment by xfangfang** [comment]
@HuaJi2333DaDa 
终于借到了可以用的底座，最新的测试版支持显示有线连接的图标了（我更推荐在熟悉键位后在设置中关闭低栏）

编译好之后，可以在这里下载到：
https://github.com/xfangfang/wiliwili/actions/runs/4644268318

**Comment by HuaJi2333DaDa** [comment]
好耶，终于等到了（

**Comment by xfangfang** [comment]
那么先关闭这个issue啦～
