### ISSUE TITLE
debian10下编译提示-Werror=pedantic

### ISSUE THREAD

**Issue by kero990** [xfangfang/wiliwili#156]
目前的报错如下，看了下cpr的项目，似乎已经不支持debian10这个过旧的平台？或者gcc版本不符？
```
[ 59%] Building CXX object library/cpr/cpr/CMakeFiles/cpr.dir/multipart.cpp.o
/root/wiliwili/library/cpr/cpr/file.cpp:9:2: error: extra ‘;’ [-Werror=pedantic]
 };
  ^

```
虽然我是在arm平台编译的，但我猜即使amd64也应该一样吧
这个项目还能在debian10上编译吗？

**Comment by xfangfang** [comment]
这个问题和你用的编译器以及本地环境有关系，cpr在那个位置确实是多写了一个分号，正常来说这个是可以被忽视的，一定是编译器的默认设置或者是你的环境变量强制不允许这个分号出现。

解决方法有：
1. 可以和 cpr 反馈一下，确实这个不应该存在
2. 或者百度看看 cmake 项目如何添加编译参数 `-Wno-error=pedantic` ，我猜可以在 cpr/cpr/CMakeLists.txt 里 34 行之后 添加： target_compile_options(cpr PRIVATE -Wno-error=pedantic)
3. 直接到这个文件把多余的分号删除

这个问题与 wiliwili 无关。
