### ISSUE TITLE
windows build error

### ISSUE THREAD

**Issue by SilverFT** [xfangfang/wiliwili#16]
![image](https://user-images.githubusercontent.com/26131495/198889556-8f93a421-ed21-4a39-985c-d5cafc153984.png)
![image](https://user-images.githubusercontent.com/26131495/198889584-92a97c53-9b1b-4b22-ba40-eb3a91a62d2a.png)
![image](https://user-images.githubusercontent.com/26131495/198889587-08677534-0bb6-4cd4-91c0-b30626579760.png)
![image](https://user-images.githubusercontent.com/26131495/198889591-36749e5f-a4ad-4096-80e5-d3d4fab7bfb0.png)

windows下编译完成后，打开报错，这个怎么解决

**Comment by xfangfang** [comment]
应该是有两个解决办法：
1. 直接从MIGW64的环境中通过命令启动wiliwili，大概就是cd到bulid目录然后 `./wiliwili` ；这种方法适合开发时候调试使用。（我不是很确定需不需要配置环境变量）
2. 如果需要从桌面双击打开，显然是需要将一部分wiliwili需要的MINGW64的dll文件也拷贝到wiliwil.exe所在的同级目录的，可以参考Github Actions的构建脚本（没有使用MINGW64环境中的mpv是因为MINGW64安装的mpv依赖太多了）：https://github.com/xfangfang/wiliwili/blob/e9803e0df665cc690f3fc4736b4bc05e37be0d7f/.github/workflows/build.yaml#L123-L129

--- 

避免没有注意到，如果只是想在win下运行，可以直接从Github Actions下载打包好的Windows客户端：https://github.com/xfangfang/wiliwili/actions/runs/3148219523

**Comment by SilverFT** [comment]
感谢，这个打包的版本如果能放在 Readme 或者 Releases 应该会挺不错的

**Comment by xfangfang** [comment]
> 感谢，这个打包的版本如果能放在 Readme 或者 Releases 应该会挺不错的

@SilverFT 因为目前pc版本并不完善，所以pc构建方法主要还是写给潜在的开发者的，Github Actions那个是因为我主要在Linux和macOS下开发，但是有些c++关键字和Mingw64下不太一样，为了避免出现Windows下编译失败而我又不知道的情况出现所以才加上的。

有一天可以完美的支持了pc平台的话会加在Release里的～

先关闭这个问题了
