### ISSUE TITLE
Feature request: 单集循环

### ISSUE THREAD

**Issue by mio-19** [xfangfang/wiliwili#166]

**Comment by Li-4** [comment]
我也想要

**Comment by xfangfang** [comment]
@mio-19 @Li-4 可以下载测试版体验: https://nightly.link/xfangfang/wiliwili/workflows/build.yaml/dev

<img width="1280" alt="截屏2023-12-13 04 58 39" src="https://github.com/xfangfang/wiliwili/assets/16631584/36a689ad-8544-48ca-b588-d9952a001404">
