### ISSUE TITLE
安装应用内置桌面图标启动程序报错无法打开。

### ISSUE THREAD

**Issue by michael-moon-lee** [xfangfang/wiliwili#17]
在wiliwili设置中安装内置前端启动程序报错无法打开。

启动hbmenu前端进入hbmenu界面后运行wiliwili正常。

使用环境：大气层14.0 固件15.0 sd卡FAT32

**Comment by xfangfang** [comment]
请详读readme或者是下载的压缩包内的说明，正确放置wiliwili.nro

**Comment by xfangfang** [comment]
@michael-moon-lee 关于这个问题有任何更新吗？

**Comment by michael-moon-lee** [comment]
> @michael-moon-lee 关于这个问题有任何更新吗？

没有了。我从hbAppstone下载安装的，默认装在了switch下新建同名目录里。换到switch下正常了。另外今天更新了最新版，可以选1080p和4k。但4k明显画面声音不同步，switch机能hold不住。换1080p没问题。感谢更新

**Comment by xfangfang** [comment]
好的，那先关闭这个issue了
