### ISSUE TITLE
NSP Forwarder 禁用用户选择和存档生成

### ISSUE THREAD

**Issue by dragonflylee** [xfangfang/wiliwili#172]
NSP Forwarder 会生成一个 64MB 的存档，但是 tinfoil 并不会。
不知道他怎么搞的，感觉和 hbmenu.json 有关系

https://nsp-forwarder.n8.io/?advanced 这里生成的也没有存档

**Comment by xfangfang** [comment]
我没有注意过这个存档。

我好奇过另外一个事 tinfoil 按住 R 是不会打开hbmenu的，拥有同样行为的还有那个修改版的youtube，不知道这是为什么

或许得在 discord 上问问大佬们了

**Comment by dragonflylee** [comment]
@xfangfang  似乎找到办法了，这里的 `StartupUserAccount` 设置为 0 就可以跳过用户选择了，也不会生成存档

https://github.com/The-4n/hacBrewPack/blob/master/nacp.h#L17
