### ISSUE TITLE
uwp闪退

### ISSUE THREAD

**Issue by JokerHuu1** [xfangfang/wiliwili#174]
经过测试，从https://github.com/xfangfang/wiliwili/actions/runs/5471642332之后的uwp都会闪退，之前的则没有问题

电脑配置：
5600x+1080ti
系统 windows11 23H2 25393.1

不知道日志怎么看

**Comment by zeromake** [comment]
是打开直播闪退吗？

**Comment by JokerHuu1** [comment]
打开app直接闪退

对了 我电脑显示器是带鱼屏，分辨率3440*1440，打开app默认全屏，能看到主页大概2到3秒后闪退

**Comment by xfangfang** [comment]
同一台电脑x86-64版本有没有这个问题呢？

**Comment by zeromake** [comment]
@xfangfang 
本地调试了一下发现，是 borealis 那边的网络调用报错了，我看看是怎么回事
brls::DesktopPlatform::hasWirelessConnection(void)

**Comment by xfangfang** [comment]
这个问题可能要 @dragonflylee 也来看看

**Comment by zeromake** [comment]
@xfangfang @dragonflylee 
~~已经找到问题了，我电脑没有无线网卡 `WiFiAdapter::FindAllAdaptersAsync().get()` 会抛出异常 ，改成 wait_for 再 GetResults 我试试看。~~
是清单里没加 wiFiControl 权限，不过没有加权限也不能出现调用抛出异常的

**Comment by zeromake** [comment]
@xfangfang @JokerHuu1 
应该可以了
https://github.com/xfangfang/wiliwili/actions/runs/5670049619

**Comment by dragonflylee** [comment]
@zeromake  感觉以后还是加上 try catch 更靠谱一些

**Comment by JokerHuu1** [comment]
> @xfangfang @JokerHuu1 应该可以了 https://github.com/xfangfang/wiliwili/actions/runs/5670049619

可以了 不闪退了 感谢大佬
