### ISSUE TITLE
v1.1.0经常会先出现这个图中的警告提示，然后退出播放

### ISSUE THREAD

**Issue by kingskill** [xfangfang/wiliwili#176]
![截图_wiliwili_20230726110810](https://github.com/xfangfang/wiliwili/assets/43365116/332db55d-4ea8-4628-bcfb-e85fac9dc8a8)

**Comment by kingskill** [comment]
我机子：i3  6100，核显hd530。系统：deepin-linux，基于debian10。

**Comment by domexie** [comment]
我这边也是一样，甚至现在任何视频都播放不了了，都是这个提示，直播可以正常播放

**Comment by newcovid** [comment]
确实如此

**Comment by coolmoon327** [comment]
从昨天开始，我测试 steamdeck （Windows 11）和 macbook pro （i9 5500M）都有这个提示，昨天是概率性出现，今天几乎是 100%

**Comment by xfangfang** [comment]
下载测试版：https://nightly.link/xfangfang/wiliwili/workflows/build.yaml/dev

我会尽快发一个新的正式版的

**Comment by xfangfang** [comment]
正式版已经更新
