### ISSUE TITLE
视频倍速设置有问题

### ISSUE THREAD

**Issue by leqy** [xfangfang/wiliwili#178]
开2倍速之后只对单个视频有效，分集里的其他视频仍按原速播放，但显示却显示2倍速，实际要再点击设置一下才生效

**Comment by xfangfang** [comment]
@leqy 可以把操作步骤的详细流程说一下吗，我刚刚测试：
1. 打开一个分集内的视频
2. 全屏
3. 手柄选到倍速菜单开启2x倍速
4. 等待播放结束切换下一个视频
5. 新视频倍速切换到1x，但是图标显示是正常的

我找了一下官方的软件，确实在分集内倍速是不变的，之后我也会按这个逻辑重新实现一下。但是前面说的这个 显示与实际倍速不匹配的问题该怎么触发呢？

**Comment by leqy** [comment]
用鼠标改2倍速，播放下一个视频显示的是倍速（也就是原速），点击倍速，弹出的窗口是2倍速。触屏修改倍速没有这个问题。
再提两个可以改进的建议仅供参考。1.没有手柄或键盘的暂停键  2.用键盘快进时R键在键盘的左边，L键反而在右边。交互有点拧巴

**Comment by xfangfang** [comment]
@leqy 我还是没办法复现，最好可以传个视频之类的。

全屏下，确定键充当了暂停的功能。对于PC来说是Return/Enter，对于手柄来说是 A/(索尼手柄是 X)

进度跳转之后可能会有其他改变，我现在的设想是全屏下 OSD隐藏的时候使用方向键来控制进度，顺带着可以把预览图实现了。

对于其他PC快捷键建议，因为这个软件最初只是给手柄设计的，快捷键太多我也记不住，所以简单地使用了和手柄一样的按键来充当快捷键，如果有想要自定义修改的想法，可以看项目的wiki。

**Comment by leqy** [comment]
https://github.com/xfangfang/wiliwili/assets/122550695/9a36f6ca-c49d-422d-b81a-ecc91dbeb6fa

**Comment by xfangfang** [comment]
这回看懂了，我在Mac上还是没有这个问题，等我稍晚一些换到win看看

**Comment by xfangfang** [comment]
我换到win也没有这个问题，可以确认一下你现在正在用的客户端的版本号是不是最新版

还有可以提供一下其他你认为能有帮助的详细的信息

**Comment by xfangfang** [comment]
因为太久没有反馈，先把这个issue关闭了，如果后续还有类似问题欢迎重开。
