### ISSUE TITLE
播放过程中出现类似拖影的情况，然后软件发生崩溃退出

### ISSUE THREAD

**Issue by AZ663** [xfangfang/wiliwili#18]
系统是14.1.2 大气层 1.3.2

**Comment by AZ663** [comment]
由于发生错误，软件已关闭

**Comment by xfangfang** [comment]
@AZ663 0.4.0及之后的版本应该不会出现这个问题了，不知道您用的是什么版本，什么清晰度，看的什么视频，大概在多长时间的位置出现的问题？

**Comment by AZ663** [comment]
> 

用的是最新的0.4.2版本
看的是这个视频
https://www.bilibili.com/video/BV1eD4y1b7Jv/?vd_source=867e24ad3354b7e6d8bf89960488532c
播放过程中崩溃了三次还是四次？没有具体的哪个位置崩溃。
清晰度是1080p60，1080p好像也崩过一次

**Comment by AZ663** [comment]
额，看了下磁盘格式是exfat，不支持那就没办法了

**Comment by xfangfang** [comment]
exfat不是不兼容，是exfat在switch上很容易会因为应用报错而损坏到内存卡的其他文件。
这个视频确实会出现问题，我这边测试也是这样

**Comment by xfangfang** [comment]
@AZ663 这个问题目前是依旧存在的。昨天发布的0.5.0版本，可以通过关闭设置中的解码缓存来临时避免此类bug发生。

同步一下目前的进度，在bug发生前会出现如下的log：
```
[lavf] error reading packet: Not enough space.
```
看起来像是什么空间不够用了，即使我设置很小的缓存也会出现此类问题，关闭缓存就不会发生。

因为我对ffmpeg或者mpv研究的没有那么透彻，所以目前还不知道原因，欢迎对此有了解的程序员们加入研究～

**Comment by zyqq** [comment]
关闭缓存，看久了视频、声音不同步

**Comment by xfangfang** [comment]
> 关闭缓存，看久了视频、声音不同步

@zyqq 我倒是没有遇到过这种情况，如果有的话想必也是switch性能太差软解速度跟不上导致的。

简单看了一下mpv的文档，默认的模式应该是以音频为基准，播放时如果解码跟不上会舍弃一些视频帧，所以我理解是应该不会产生音画不同步的情况的。

如果感兴趣的话，可以拉项目编译一下，通过调整mpv的配置参数来看看关于这个问题使用什么配置会更好一些。

这里是mpv的文档：https://mpv.io/manual/stable/#options-video-sync
这里是wiliwili配置mpv参数的位置：https://github.com/xfangfang/wiliwili/blob/a8eb01f98491e1ba8c0ae91c455658ef16ee3e15/wiliwili/source/view/mpv_core.cpp#L71-L126

**Comment by xfangfang** [comment]
@AZ663 这个问题应该是被解决了，问题可能出在mpv使用的switch SDL的音频驱动上，最新的更新移除了SDL的音频支持，直接调用switch的音频输出，测试了一阵目前都是正常的。

可以前往这里下载最新的测试版来验证：https://github.com/xfangfang/wiliwili/actions/runs/5365699796

**Comment by xfangfang** [comment]
@AZ663 如果没有反馈我就准备关闭这个issue了
