### ISSUE TITLE
[Feature Request]:  Android Port

### ISSUE THREAD

**Issue by FayeSpica** [xfangfang/wiliwili#182]
初衷：虽然已经有BBLL了，但是有些特殊设备没法硬件解码，移植wiliwili到安卓，主要是想在开源掌机上运行（用的联发科的弱鸡芯片，软解完全跑不动）

进展：
2023/07/30
周末尝试用大佬移植的borealis库，把wiliwili的界面在安卓上完整跑起来了。现在主要是播放存在问题，mpv init的时候报错了，正在定位中

**Comment by xfangfang** [comment]
本项目不提供安卓支持，也不接受安卓相关的PR和类似的讨论。如果完成了相关的移植希望不要分享，目前wiliwili只希望运行在不受官方支持的设备上，如果搞到了安卓上就会有人往电视上安装，首先是不符合广电的要求，其次是影响了B站官方电视会员的收益，这两点都会导致 wiliwili 没办法继续开发。
所以请不要将你的移植内容发送给任何人。

---

我已经在issue区内评论过很多次了，任何安卓版的支持都会导致wiliwili的其他任何全平台版一起被封禁，作者会被连累律师函，已经有相当多的实例案件。

wiliwili从来都是丰富官方客户端不支持的平台而不是在某些平台替代官方客户端，尤其是安卓端的替代，会导致官方损失大量利益，被封禁是必然。

在这里我再次声明，我从未以任何方式发布过wiliwili的安卓版，并且只要有任何wiliwili的安卓版出现在互联网，我都会立即关闭wiliwili的github仓库不再维护。

**Comment by FayeSpica** [comment]
> 本项目不提供安卓支持，也不接受安卓相关的PR和类似的讨论。如果完成了相关的移植希望不要分享，目前wiliwili只希望运行在不受官方支持的设备上，如果搞到了安卓上就会有人往电视上安装，首先是不符合广电的要求，其次是影响了B站官方电视会员的收益，这两点都会导致 wiliwili 没办法继续开发。
> 
> 所以请不要将你的移植内容发送给任何人。

了解了，这块确实是红线，还是不搞为妙
