### ISSUE TITLE
评论区报错[Status code:504]，太惨了之前25号api报错，现在评论区出现报错。

### ISSUE THREAD

**Issue by liufuyou** [xfangfang/wiliwili#183]
就在最近这段时间，观看视频的时候突然发现评论区报错。
然后试了几遍，下载了最新版，跟重启都是一样，
不知道为什么。会不会跟之前api报错一样？
![image](https://github.com/xfangfang/wiliwili/assets/47191057/38ebf3e6-7b46-44ec-be98-4f585c48b88c)

**Comment by liufuyou** [comment]
尴尬，恢复了

**Comment by xfangfang** [comment]
不是很确定原因，但是如果还是存在的话可以尝试重新登陆一下看看
