### ISSUE TITLE
一个简单推测：某些视频，uwp容易闪崩，可能和弹幕设置有关 

### ISSUE THREAD

**Issue by kingskill** [xfangfang/wiliwili#184]
搜索“舞台2023 ，人是，周深 ”，由up主“追光情报鹅”上传的周深的这个最新视频，按照默认设置打开，每次 都会闪崩。在设置中做各种调整也都无效。后来调整弹幕设置，从100%全屏改成80%屏幕，就不崩了。

**Comment by xfangfang** [comment]
感谢反馈问题。
其实正常使用的话 用x86(64)版本就可以了，uwp版本目前应该不会有什么特殊的性能提升。尤其在视频绘制上，相比于目前的x86版从理论上讲是略有不足的。
这个问题看起来确实可能是弹幕实现的问题，但是弹幕部分的代码后来更改过好几次，已经不能确定同样的问题是否还存在了，所以我先将这个issue关闭了，后续有相似的问题发生的话，欢迎随时反馈。
