### ISSUE TITLE
直播弹幕数量不足

### ISSUE THREAD

**Issue by xfangfang** [xfangfang/wiliwili#185]
刚刚收到用户反馈直播间弹幕显示的数量和手机端看到的不一致。

测试的直播间：https://live.bilibili.com/7777

同一时刻，wiliwili 和官方PC端截图对比（左侧为官方PC端）：

  
<img width="312" alt="257274992-c1ea21be-a1b8-4c4c-b393-8b9a308476ee" src="https://github.com/xfangfang/wiliwili/assets/16631584/98a4c7fc-dcea-4b08-9883-a19f1571ad28">

<img width="361" alt="257276373-4acacb96-6e3f-43c4-9751-88d81c58852e" src="https://github.com/xfangfang/wiliwili/assets/16631584/376beb4b-fe93-4211-9bcc-ee7b52551e4e">

cc @maye174

**Comment by 4fuu** [comment]
我明天检查一下，有可能是一次发过来的包过大溢出缓冲区了

**Comment by 4fuu** [comment]
> 我明天检查一下，有可能是一次发过来的包过大溢出缓冲区了

弹幕少的直播间应该不会有这个情况

**Comment by xfangfang** [comment]
好的辛苦啦，不着急，这个问题应该只有很少的情况才能遇到

**Comment by TengCa** [comment]
pc端的主题好像并不能随系统更改深色或浅色

**Comment by xfangfang** [comment]
@TengCa 不要在issue下面评论无关的问题，如果遇到了其他问题，可以重开一个issue，并详细描述你的问题。
