### ISSUE TITLE
[BUG] 主题配色 "跟随系统"失败

### ISSUE THREAD

**Issue by FBIKdot** [xfangfang/wiliwili#188]
如题, 跟随系统没有按照理想情况工作

![image](https://github.com/xfangfang/wiliwili/assets/83176414/acce2037-4ab7-4aec-bdc7-3c546f68f59d)

![image](https://github.com/xfangfang/wiliwili/assets/83176414/2a370e1c-8210-4f08-8822-fc45851615e8)

**Comment by xfangfang** [comment]
@BovineBeta 之前没有做windows和Linux下的主题识别，刚刚合并了一个PR，我还没有实机测试，可以下载测试版体验看看

https://nightly.link/xfangfang/wiliwili/workflows/build.yaml/dev

**Comment by FBIKdot** [comment]
大佬您好, 非常抱歉提前关闭了issues. 您的PR在windows上起作用了, 感谢(*ゝω・)ﾉ.

![image](https://github.com/xfangfang/wiliwili/assets/83176414/ba33a985-118e-4c07-ab2b-2c0ae28c2c16)
