### ISSUE TITLE
[Maybe bug] 简体中文语言选择菜单，所有语言选项均为简中汉字，可能引起不便

### ISSUE THREAD

**Issue by happytommyl** [xfangfang/wiliwili#189]
在简体中文环境下，语言选择菜单内所有语言选项均为简中汉字，而非对应显示对应语言文字，可能引起不便。
可以参考在其他语言环境下，语言选择菜单显示为对应文字。

**Comment by xfangfang** [comment]
在某些系统下无法正确显示韩语（现在在linux下好像还有这个问题，需要设置自定义字体）
所以如果那里显示对应的语言就会出现两个框框。

考虑到B站主要视频都是中文的，所以使用者应该都是了解中文的，应该不会有什么困扰吧。

说到多语言支持，如果您感兴趣的话可以给评论加个翻译的功能，类似youtube那种，可以加个按钮放在和点赞评论并列的位置。
