### ISSUE TITLE
[Feature Request]MPRIS支持

### ISSUE THREAD

**Issue by Yuyuyuyu-an** [xfangfang/wiliwili#192]
希望支持MPRIS，以实现如键盘媒体控制键等功能。

**Comment by xfangfang** [comment]
@Yuyuyuyu-an wiliwili使用mpv播放视频，据我所知mpv是支持mpris的，你可以自己尝试配置一下。

https://github.com/hoyon/mpv-mpris

**Comment by xfangfang** [comment]
因为没有得到后续反馈，先把这个issue关闭了，如果有类似需求并成功实现的朋友欢迎留言，我会将内容及时更新到wiki中的。

**Comment by pugaizai** [comment]
看样子并不支持https://github.com/flathub/cn.xfangfang.wiliwili/pull/7

**Comment by pugaizai** [comment]
当然也可能是我哪里弄错了

**Comment by xfangfang** [comment]
@madoka773 感觉可以先不用flatpak试一试，就纯本地环境看看能不能用。
插件放置的路径可以测试分别放在mpv的全体用户目录和wiliwili的配置目录，看看是不是都有用，或者都没用。

**Comment by pugaizai** [comment]
感觉不是这个问题，我看 celluliid player 和 haruna player (都是mpv 的前端)的 mpris 都是有另外的代码实现的

**Comment by pugaizai** [comment]
感觉对于一个在线视频软件来说mpris可有可无
