### ISSUE TITLE
使用 vscode 和 clion 编译 linux 版本都会遇到 ‘mpv_event_to_node’ 的错误

### ISSUE THREAD

**Issue by Strive-Sun** [xfangfang/wiliwili#193]
ubuntu version: 20.04

分支：tag v1.1.1 

报错信息：

 home/xxx/wiliwili/wiliwili/source/view/mpv_core.cpp: In member function ‘void MPVCore::eventMainLoop()’:
/home/xxx/wiliwili/wiliwili/source/view/mpv_core.cpp:632:17: error: ‘mpv_event_to_node’ was not declared in this scope; did you mean ‘mpv_event_hook’?
  632 |                 mpv_event_to_node(&dst, event);
      |                 ^~~~~~~~~~~~~~~~~
      |                 mpv_event_hook
make[2]: *** [CMakeFiles/wiliwili.dir/build.make:1285: CMakeFiles/wiliwili.dir/wiliwili/source/view/mpv_core.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:624: CMakeFiles/wiliwili.dir/all] Error 2

vs code 编译出错截图：
![image](https://github.com/xfangfang/wiliwili/assets/50010647/6195571a-d8c3-44fc-a375-872cc0287b29)

clion 编译出错截图：
![image](https://github.com/xfangfang/wiliwili/assets/50010647/77bb3c40-8ee0-431a-899b-6238d054fdd1)

**Comment by Strive-Sun** [comment]
另外，我注意到 @maye174 使用 vscode 编译的项目，已经研究两天了，实在不知道咋解决，希望大佬们能帮忙看下这个问题，太奇怪了

**Comment by Strive-Sun** [comment]
编译的顺序是按照 README 中给出的方法，cmake -> make

**Comment by xfangfang** [comment]
@Strive-Sun 遇到问题可以先搜索一下历史issue，这样会比较节省时间

https://github.com/xfangfang/wiliwili/issues/78#issuecomment-1657782444

言简意赅地说，换到 dev 分支，或者更新 mpv

**Comment by Strive-Sun** [comment]
确实如此，切到 dev 分支后问题消失了
