### ISSUE TITLE
[Feature Request]全屏播放视频时自动隐藏鼠标指针

### ISSUE THREAD

**Issue by TomoeMami** [xfangfang/wiliwili#195]
Windows版本，开启了Wiliwili的全屏模式。

点进视频，再点击开始全屏播放时，虽然进度条已经隐藏了，鼠标指针依然显示在画面中央。

**Comment by xfangfang** [comment]
@TomoeMami 是的，这个功能没有做。如果您感兴趣欢迎为项目提交PR

**Comment by TomoeMami** [comment]
目前用第三方软件实现了自动移动光标

https://github.com/LostByteSoft/AutoMouseHide
