### ISSUE TITLE
希望加入邮件功能

### ISSUE THREAD

**Issue by MaxenRace** [xfangfang/wiliwili#197]
bilibili会有一些消息，比如有人回复、点赞、系统消息。但是在这个客户端上没有邮件功能，希望在以后可以加入邮件功能。

**Comment by dragonflylee** [comment]
@MaxenRace 这个可以关了吧

**Comment by MaxenRace** [comment]
?





***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xfangfang/wiliwili"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月13日(星期五) 晚上9:22
***@***.***&gt;;
抄送:&nbsp;"wang ying ***@***.******@***.***&gt;;
主题:&nbsp;Re: [xfangfang/wiliwili] 希望加入邮件功能 (Issue #197)





 
@MaxenRace 这个可以关了吧
