### ISSUE TITLE
视频加载播放问题

### ISSUE THREAD

**Issue by ZMLH** [xfangfang/wiliwili#199]
页面等其他信息显示都加载很快，但是当打开视频的时候就会出现正在加载中而无法播放
![QQ图片20230902210926](https://github.com/xfangfang/wiliwili/assets/52843953/a920d1ba-c7cf-4548-91ca-dbedf2117e63)

**Comment by ZMLH** [comment]
大部分视频都会有这种情况，运气好的话才会点开视频就直接播放

**Comment by xfangfang** [comment]
@ZMLH 

请阅读：[README#反馈问题前要做的事](https://github.com/xfangfang/wiliwili#反馈问题前要做的事)

或者阅读: [wiki#无法播放视频](https://github.com/xfangfang/wiliwili/wiki#无法播放视频)

或者阅读: 下载压缩包内附带的 `安装前必读.txt`

**Comment by ZMLH** [comment]
很抱歉我没有讲清楚，部分视频加载缓慢，但有的视频加载没有问题，dns我并没有进行设置，而是使用了默认，如果要设置dns是否有指定的dns地址


问题:部分视频很流畅的能够播放，令我疑惑的是有些视频却始终处于加载中并且播放卡顿


网络方面我都采用的是默认设置


家里的网络很好，手机电脑使用都很流畅，这不是网络问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月3日(周日) 凌晨0:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xfangfang/wiliwili] 视频加载播放问题 (Issue #199)




 
@ZMLH
 
请阅读：README#反馈问题前要做的事
 
或者阅读下载压缩包内附带的安装前必读的内容

**Comment by xfangfang** [comment]
@ZMLH 那么可以按照README所说提供一下网络诊断的截图嘛？

> 1. 网络相关的问题附加 网络诊断截图，入口：应用内设置/实用工具/网络诊断

**Comment by ZMLH** [comment]
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月3日(周日) 凌晨1:13
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xfangfang/wiliwili] 视频加载播放问题 (Issue #199)




 
@ZMLH 那么可以按照README所说提供一下网络诊断的截图嘛？
   
网络相关的问题附加 网络诊断截图，入口：应用内设置/实用工具/网络诊断

**Comment by xfangfang** [comment]
@ZMLH 建议到github回复，通过邮件好像发送不了图片（如果你刚刚发送了图片的话）

**Comment by xfangfang** [comment]
@ZMLH 如果问题解决了的话，可以关闭这个issue了；如果没有解决欢迎按照前面所说，提供必备截图
