### ISSUE TITLE
一直都提示网络错误

### ISSUE THREAD

**Issue by hegeo** [xfangfang/wiliwili#20]
一直都提示网络错误，使用移动热点也不行，换DNS也不行

**Comment by xfangfang** [comment]
@hegeo 

来自readme的说明：

# 反馈问题前要做的事

仅在最新 大气层 + 最新 固件 + FAT32 内存卡测试，其他组合出现的问题不进行处理。

首先确保 大气层、固件、内存卡 三者符合要求
确保switch系统时间正常，如果进入应用弹出 网络错误 一般是由这个问题导致的。
重置switch系统网络设置，尤其是DNS配置，某些DNS服务器无法正确解析API域名和视频地址
完整且详细地描述你的问题，最好附加演示视频、截图。
网络相关的问题附加网络诊断截图，入口：设置/实用工具/网络诊断
尝试复现问题，尽力找到BUG出现的规律

---

系统或者大气层不是最新的问题倒是也不大，但是：`网络相关的问题附加网络诊断截图，入口：设置/实用工具/网络诊断`

**Comment by hegeo** [comment]
谢谢，是时间错了，系统时间不知道怎么变成2021年了
