### ISSUE TITLE
[Feature Request] Share to clipboard 分享至剪贴板

### ISSUE THREAD

**Issue by happytommyl** [xfangfang/wiliwili#201]
It would be convenient to be able to share video link to clipboard in one way or another. 

It seems that the underlying framework (aka. borealis) does not have an obvious way to support text selection/copy-pasting. So I think the implementation would be platform specific.

**Comment by happytommyl** [comment]
When building on dev branch, I encontered the following error:

`error: 'ORIGINAL_WINDOW_HEIGHT' is not a member of 'brls::Application'`

I think `ORIGINAL_WINDOW_HEIGHT` should be under namespace `brls` rather than `brls::Application`.

**Comment by xfangfang** [comment]
@happytommyl 
https://git-scm.com/book/en/v2/Git-Tools-Submodules#_switching_branches_2

```shell
# method 1
git checkout dev
git submodule update --init --recursive

# method 2
git checkout --r dev
```

**Comment by happytommyl** [comment]
Ok, I can make it work on Windows. But I am not able to work on other platforms.

**Comment by xfangfang** [comment]
只提供单独某个或某几个平台的支持也是可以的，比如在borealis中获取设备电量：同时提供了是否支持获取电量的函数和具体的获取电量的函数。
对应的复制文本功能也可以这么做。

在前端，可以模仿官方界面来开发：

<img width="491" alt="image" src="https://github.com/xfangfang/wiliwili/assets/16631584/dc155968-2cb2-4698-98e7-90241937a747">

可以顺便把 空间、微博、微信、qq 这四个调用浏览器的功能也一并完成，同时根据平台是否支持复制链接来显示复制链接按钮

**Comment by happytommyl** [comment]
好，我有时间研究下其他平台的接口

**Comment by happytommyl** [comment]
How can I add mouse click listener to `SVGImage` ?

I tried to use `registerClickAction` on `SVGImage`, but it doesn't seem to work on a mouse click. Should I use  `registerAction` instead? Or is it because `SVGImage` on its own can't get focus?

I'm now using `brls::Button` as a parent and add the `SVGImage` to the button view as a workaround, but the result is vey ugly.

**Comment by xfangfang** [comment]
Done by https://github.com/xfangfang/wiliwili/pull/277
