### ISSUE TITLE
请问能增加港澳台漫游脚本吗？ 

### ISSUE THREAD

**Issue by catalysia** [xfangfang/wiliwili#202]
港澳台番剧现在没法看能增加港澳台番剧漫游的解除限制吗？

**Comment by xfangfang** [comment]
经过同胞测试，本身人在港澳台的话是可以正常使用的。因为作者平时不怎么看番剧，所以这个需求大概率不会被实现。

顺便提醒一下，使用第三方代理需要共享用户的cookie，可能会被不法分子盗用账号在广告视频下发评论或者自动转发动态之类的。
