### ISSUE TITLE
搜索关键词不能为3个英文字母或2个中文汉字

### ISSUE THREAD

**Issue by chenxiex** [xfangfang/wiliwili#203]
Manjaro Linux，1.1.1 x86_64 flatpak
搜索关键词恰为3个英文字母或2个中文汉字时显示错误：
![截图 2023-09-21 20-22-39](https://github.com/xfangfang/wiliwili/assets/28776935/1935f12c-cd31-450f-bb07-c5848b18a342)

**Comment by xfangfang** [comment]
这个问题修复了，原因是b站API把课程视频和普通视频放在一起了，想顺便支持一下课程视频，发现官方客户端也没有这个支持，所以就正大光明的放弃了。

可以在这里下载测试版（如果没问题的话等一会就构建好了）：https://github.com/xfangfang/wiliwili/actions/runs/6666954491
