### ISSUE TITLE
switch版播放下一个视频的快捷键无效

### ISSUE THREAD

**Issue by CBCBA** [xfangfang/wiliwili#207]
Y+R向前跳转视频这个快捷键，按了没有效果
![2023100319150500-C41888B7F8FF46D1FE6EB8F592903715](https://github.com/xfangfang/wiliwili/assets/21093644/3ed18a43-933f-43b0-aecb-477e53e0a0e0)

**Comment by xfangfang** [comment]
@CBCBA 可以拍个视频展示一下

**Comment by CBCBA** [comment]
> @CBCBA 可以拍个视频展示一下


https://github.com/xfangfang/wiliwili/assets/21093644/cbae7173-3390-42e8-ba06-1de0181bb1af

**Comment by CBCBA** [comment]
> @CBCBA 可以拍个视频展示一下


https://github.com/xfangfang/wiliwili/assets/21093644/7fc4db1f-c2b7-48a0-9dd1-62edf3101d33

**Comment by xfangfang** [comment]
@CBCBA 是的，你视频中演示的就是这个功能的作用。为什么说：“Y+R向前跳转视频这个快捷键，按了没有效果” 呢？

**Comment by CBCBA** [comment]
> @CBCBA 是的，你视频中演示的就是这个功能的作用。为什么说：“Y+R向前跳转视频这个快捷键，按了没有效果” 呢？

跳转视频不是“播放下一个视频“的意思吗？视频里变成倒退了。。。。没有切换下一个视频

**Comment by CBCBA** [comment]
> @CBCBA 是的，你视频中演示的就是这个功能的作用。为什么说：“Y+R向前跳转视频这个快捷键，按了没有效果” 呢？

额，好像是我理解错了。。。那有没有切换上一集和下一集的快捷键呢？

**Comment by xfangfang** [comment]
这里“向前跳转视频”指的是“向前跳转视频（进度）”，UI上没有展示的就是没有的。
