### ISSUE TITLE
可以添加进度条拖拽以及倍速功能么

### ISSUE THREAD

**Issue by NeinL** [xfangfang/wiliwili#21]
感觉这些个可能需求比较大

**Comment by xfangfang** [comment]
@NeinL 最近一段时间不会有功能上的修改，目前的任务还是提升稳定性

**Comment by xfangfang** [comment]
打破了我自己的话😂，发现这两个功能写起来比较简单，新发布的版本已经支持了这两个功能，先关闭这个issue了。
