### ISSUE TITLE
PC版打开评论区无法关闭

### ISSUE THREAD

**Issue by fbstorm** [xfangfang/wiliwili#210]

**Comment by fbstorm** [comment]
PC版打开评论区无法关闭

**Comment by fbstorm** [comment]
![image](https://github.com/xfangfang/wiliwili/assets/100028477/2c3ed810-9521-4c52-8719-d8ca3bab6378)
如图所示，Esc、右键、点击空白都无法关闭评论区

**Comment by xfangfang** [comment]
@fbstorm 在设置中把“隐藏下方提示栏”关掉，就能看到快捷键提示了。这个位置我之前想改来着，一直没抽出空。

f2 保存/提交
f1 返回

**Comment by fbstorm** [comment]
> @fbstorm 在设置中把“隐藏下方提示栏”关掉，就能看到快捷键提示了。这个位置我之前想改来着，一直没抽出空。
> 
> f2 保存/提交 f1 返回

万分感谢😍♥♥
