### ISSUE TITLE
windows上面搜索功能异常

### ISSUE THREAD

**Issue by jianghaodn** [xfangfang/wiliwili#212]
搜索关键词存在部分英文字母的时候，会提示
`Api error.
json.exception.out_of_range.403] key 'season_id' not found`
![image](https://github.com/xfangfang/wiliwili/assets/54367720/60f6f4e5-3dfe-4d5c-b656-2d6bc01cfc2f)

搜索内容仅为中文+一些符号的时候是正常的。
![image](https://github.com/xfangfang/wiliwili/assets/54367720/c6d2941b-75a5-4077-aceb-f76ed60c4a8c)

windows版本：windows11 22621.2283

wiliwili 版本：v1.1.1

**Comment by xfangfang** [comment]
感谢提醒，应该已经有类似的issue了：https://github.com/xfangfang/wiliwili/issues/203

这是个小问题，我会在下次更新的时候顺便修复一下。最近在花时间做wiliwili到其他平台的移植，所以短时间还不会发新的版本。

因为已经有相同的issue了，所以先将这个关闭了。
