### ISSUE TITLE
Feature request: 能不能加一个全屏的快捷键，同时处理一下全屏时无法切换页面的问题

### ISSUE THREAD

**Issue by simplified-world** [xfangfang/wiliwili#216]
现在全屏只能去设置里改，但是改了之后无法切出wiliwili的页面，无法看其他页面，解决办法除了去设置把全屏改回关，就是直接退出wili。这样对pc用户很不方便。如果有现成的解决方法最好不过，如果没有，请作者大大加一个快捷键或是修复一下这个问题。有劳了

**Comment by xfangfang** [comment]
可以在播放页面的设置菜单中稍微便捷一点的切换全屏。

因为ui框架的问题，wiliwili 不是能很方便地添加快捷键，这个设定目前只能是这样了。

我有考虑添加鼠标双击视频区域来切换全屏，但是还有一些其他的小问题可能导致这个事又不太好实现。

> 但是改了之后无法切出wiliwili的页面，无法看其他页面

我这边貌似是能正常切换的，不能切的话可能是别的原因导致的，比如：https://github.com/xfangfang/wiliwili/issues/171#issuecomment-1751210759

已经有相同的issue，所以我先把这个关闭了：https://github.com/xfangfang/wiliwili/issues/111

**Comment by simplified-world** [comment]
好的，有劳了。那应该是我的问题。我去看看
