### ISSUE TITLE
UWP 构建出错

### ISSUE THREAD

**Issue by xfangfang** [xfangfang/wiliwili#217]
使用相同的 wiliwili 代码进行构建。

这一次构建，能够命中依赖缓存，构建是成功的：
https://github.com/xfangfang/wiliwili/actions/runs/6704158499/job/18216312792

这一次构建，手动把缓存删了，重新编译的依赖，构建失败了：
https://github.com/xfangfang/wiliwili/actions/runs/6708294314/job/18230623342

貌似是 SDL 相关的构建问题，这个只能麻烦 @zeromake 看看是什么原因了～

- - -

顺便一提，今天刷到一个搞xbox的up主，他教大家在 xbox 上升级开发者账号然后安装 retroarch 之类的第三方软件。
私信了他，我猜他或者他的粉丝中应该会有愿意在xbox上测试 wiliwili 的朋友 （我到现在也不知道究竟能不能正常运行到xbox上）

安装应用的流程我大概看了一眼，不太知道为什么 retroarch 的安装包没有带证书，希望xbox上有安装证书的地方吧 : ）

https://www.bilibili.com/video/BV1r84y117Wc

**Comment by zeromake** [comment]
应该是我xrepo的sdl刷了版本号和添加了sdl_main，我看看

**Comment by zeromake** [comment]
已经修复了sdl的编译，重试了一下看到 sdl 已经正常编译了，先去上班了
https://github.com/xfangfang/wiliwili/actions/runs/6708294314/job/18246075924
正常编译了

**Comment by xfangfang** [comment]
@zeromake 感谢感谢～ 那我先关闭这个issue啦
