### ISSUE TITLE
UWP 构建报错

### ISSUE THREAD

**Issue by xfangfang** [xfangfang/wiliwili#229]
@zeromake 抱歉再次打扰，borealis合并了一个一个PR，将 yoga 的版本更新到了2.0:

https://github.com/xfangfang/borealis/commit/5100a717dccc2f67742f3887ad063dea0682702a

有一个API不兼容，导致UWP构建出错：https://github.com/xfangfang/wiliwili/actions/runs/6805290367/job/18508519414

看起来xmake的仓库需要更新一下yoga啦～

**Comment by zeromake** [comment]
已经合并了：[dragonflylee](https://github.com/dragonflylee): https://github.com/zeromake/xrepo/pull/3

**Comment by xfangfang** [comment]
感谢～
