### ISSUE TITLE
switch端wiliwili观看csgo直播分区无法载入

### ISSUE THREAD

**Issue by ghost** [xfangfang/wiliwili#231]
switch端wiliwili观看csgo直播分区无法正常载入，黑屏转圈。其他直播分区正常观看

**Comment by xfangfang** [comment]
@npuWang666 这个问题刚好前些天研究了一下，可以下载测试版体验：https://nightly.link/xfangfang/wiliwili/workflows/build.yaml/dev

关于测试版的更新内容，请持续关注：https://github.com/xfangfang/wiliwili/wiki

**Comment by xfangfang** [comment]
已经发布了新版本，这个问题解决啦
