### ISSUE TITLE
希望提供 “使用帐号密码登录” 的选项 

### ISSUE THREAD

**Issue by just-a-pony** [xfangfang/wiliwili#24]
虽说在国内环境下  互联网大厂哪怕在其他平台登录也离不开手机已经成为常态
但还是希望能提供一个使用帐号密码登录的选项     对于不方便使用手机  或者并没有安装手机客户端的人来说 会更方便些
感谢

**Comment by xfangfang** [comment]
非常棒的想法，欢迎为这个项目提交代码。

**Comment by xfangfang** [comment]
考虑到没人回复，我也没有添加相关功能的动力，暂时先关闭这个issue了。
