### ISSUE TITLE
信息流加载缓慢甚至失败

### ISSUE THREAD

**Issue by TomoeMami** [xfangfang/wiliwili#243]
![图片](https://github.com/xfangfang/wiliwili/assets/16950305/93d8fa97-05f8-4e04-a30b-3cee7ceff475)

信息流加载缓慢

![图片](https://github.com/xfangfang/wiliwili/assets/16950305/41850d6e-e2f4-4c2e-ae01-51a0722ffcc0)

图片加载缓慢

![图片](https://github.com/xfangfang/wiliwili/assets/16950305/6cd07d85-e845-4701-b963-70016bb02030)

加载失败

但是如果用浏览器或者官方PC客户端可以正常速度加载

![图片](https://github.com/xfangfang/wiliwili/assets/16950305/3eaeb7ef-8a7c-4bd8-8cd1-ce8bd59166d7)

网络诊断信息

**Comment by xfangfang** [comment]
@TomoeMami 很遗憾我也不太清楚为什么，唯一我能想到的可能是你挂了梯子，浏览器或者官方客户端自动走了梯子，或者至少用了梯子提供的dns导致网络速度和wiliwili呈现出差异（因为wiliwili不会走系统代理）

针对这种情况我建议改个电脑或者路由器的dns后等一会再试一试，比如改到 223.5.5.5。

**Comment by TomoeMami** [comment]
> @TomoeMami 很遗憾我也不太清楚为什么，唯一我能想到的可能是你挂了梯子，浏览器或者官方客户端自动走了梯子，或者至少用了梯子提供的dns导致网络速度和wiliwili呈现出差异（因为wiliwili不会走系统代理）
> 
> 针对这种情况我建议改个电脑或者路由器的dns后等一会再试一试，比如改到 223.5.5.5。

重启入户光猫后问题解决了
