### ISSUE TITLE
大佬！希望能够有安卓版本，支持手柄和无广告实在太棒了！

### ISSUE THREAD

**Issue by 17347348339** [xfangfang/wiliwili#244]
多亏了大佬开发wilwili，我已经在Switch OLED上完美使用手柄看B站了，有UI适配，免费无广告实在太棒了！我有拉伸手柄，可以插在手机和平板上，要是能在安卓设备上有wiliwili实在太疯狂了！

**Comment by 17347348339** [comment]
看了以前已关闭的评论，安卓这块确实是红线，这个项目估计都要被叫停

**Comment by xfangfang** [comment]
感谢支持，关于安卓的讨论已经进行过很多次了，请见：

https://github.com/xfangfang/wiliwili/issues/182
https://github.com/xfangfang/wiliwili/issues/127
https://github.com/xfangfang/wiliwili/issues/98
https://github.com/xfangfang/wiliwili/issues/91
https://github.com/xfangfang/wiliwili/issues/60
https://github.com/xfangfang/wiliwili/issues/55


---

我已经在issue区内评论过很多次了，任何安卓版的支持都会导致wiliwili的其他任何全平台版一起被封禁，作者会被连累律师函，已经有相当多的实例案件。

wiliwili从来都是丰富官方客户端不支持的平台而不是在某些平台替代官方客户端，尤其是安卓端的替代，会导致官方损失大量利益，被封禁是必然。

在这里我再次声明，我从未以任何方式发布过wiliwili的安卓版，并且只要有任何wiliwili的安卓版出现在互联网，我都会立即关闭wiliwili的github仓库不再维护。
