### ISSUE TITLE
[Bug] 投币时假如取消勾选“同时点赞”会导致投币失败

### ISSUE THREAD

**Issue by AlphonseZetta10** [xfangfang/wiliwili#246]
RT
版本是1.2.2，在Windows 10系统中运行，键鼠操作

**Comment by xfangfang** [comment]
@AlphonseZetta10 
我刚刚在switch上使用是没问题的，如果你是从0.6.0或之前的版本升级上来的，在这之后没有重新扫码登录过，那么问题应该是你需要重新扫码登录一下。（相关说明 https://github.com/xfangfang/wiliwili/wiki#无法点赞 ）

如果不是（在手机客户端里查看登录设备能看到wiliwili），那么可以下载这个版本查看log：https://github.com/xfangfang/DIY/actions/runs/6747288577

并将投币附近的log发过来。

**Comment by AlphonseZetta10** [comment]
很奇怪，不同的视频有不同的结果
https://www.bilibili.com/video/BV1i34y1F7HJ 这个视频失败

> 11:01:08.340[INFO] ========> PAUSE0%) A-V:  0.000 Dropped: 19 Cache: 103s/10MB                                          
[add coin] aid: 833974026; coin: 1; select_like: 0;                                                                     
11:01:11.325[ERROR] code: -401; msg: 非法访问
[cplayer] EOF code: 4
[ffmpeg] tcp: ffurl_write returned 0xffffd8ba                                                                           
[cplayer] finished playback, success (reason 2)   

https://www.bilibili.com/video/BV1k94y1J7nE 这个视频成功

> [cplayer] Set property: volume=38 -> 1
[cplayer] Set property: volume=38 -> 1
11:02:53.850[INFO] Write config to: D:\00_TEMP\wiliwili\config\wiliwili/wiliwili_config.json
[add coin] aid: 366343725; coin: 1; select_like: 0;
[cplayer] EOF code: 4
[cplayer] finished playback, success (reason 2)

**Comment by xfangfang** [comment]
@AlphonseZetta10 我这边都是可以正常投币的，可以详细反馈一下我前面说的内容（包括历史用过什么版本的客户端，最近一次登录时间），只是看结果我确实不是很清楚原因。

**Comment by xfangfang** [comment]
可以通过阅读配置文件来简单确认一下登录的版本：

如果配置文件中包含 `refreshToken` 那么应该是0.6.0后登录的，如果还包含 `buvid3` 那么应该是 1.2.0 之后登录的。（请反馈您的配置文件是否包含）

建议先备份配置文件，然后使用最新版重新登录一下，问题应该会解决。

如何打开配置文件：https://github.com/xfangfang/wiliwili/wiki#3-合理配置


---

我确认了一下，如果我手动把配置文件内的 buvid3 删除，确实会发生投币失效的问题。

**Comment by AlphonseZetta10** [comment]
> @AlphonseZetta10 我这边都是可以正常投币的，可以详细反馈一下我前面说的内容（包括历史用过什么版本的客户端，最近一次登录时间），只是看结果我确实不是很清楚原因。

我是从1.2.0开始用的，登录应该是半个月前。况且我用debug版测试是用另外一个账号在另外一个全新的wiliwili实例中进行的。两个账号在那个视频都遇到了无法单独投币的问题。

~一个想法，会不会是B站的风控？~

**Comment by AlphonseZetta10** [comment]
> 可以通过阅读配置文件来简单确认一下登录的版本：
> 
> 如果配置文件中包含 `refreshToken` 那么应该是0.6.0后登录的，如果还包含 `buvid3` 那么应该是 1.2.0 之后登录的。（请反馈您的配置文件是否包含）
> 
> 建议先备份配置文件，然后使用最新版重新登录一下，问题应该会解决。
> 
> 如何打开配置文件：[https://github.com/xfangfang/wiliwili/wiki#3-合理配置](https://github.com/xfangfang/wiliwili/wiki#3-%E5%90%88%E7%90%86%E9%85%8D%E7%BD%AE)
> 
> 我确认了一下，如果我手动把配置文件内的 buvid3 删除，确实会发生投币失效的问题。

我看了一下配置文件，有 `refreshToken`但是没有 `buvid3`

**Comment by AlphonseZetta10** [comment]
> 如果不是（在手机客户端里查看登录设备能看到wiliwili），那么可以下载这个版本查看log：https://github.com/xfangfang/DIY/actions/runs/6747288577

这个debug版本也是1.2.0，所以也遇到了相同的问题（有 refreshToken但是没有 buvid3）

**Comment by xfangfang** [comment]
@AlphonseZetta10 不好意思，我又检查了一下代码，需要 1.2.1 重新扫码登录

debug 版：https://github.com/xfangfang/DIY/actions/runs/6988566817

**Comment by AlphonseZetta10** [comment]
> @AlphonseZetta10 不好意思，我又检查了一下代码，需要 1.2.1 重新扫码登录
> 
> debug 版：https://github.com/xfangfang/DIY/actions/runs/6988566817

<img width="660" alt="Snipaste_2023-11-26_17-56-03" src="https://github.com/xfangfang/wiliwili/assets/111181772/ffe9a2c3-b594-4fe0-8f1c-4b9023151e20">

**Comment by xfangfang** [comment]
这我也不知道原因了， 如果说官方的客户端没问题，那确实是咱们实现的问题，但是这玩意也很难说具体是怎么回事。

我感觉应该还是登录的过程中某些cookie没有记录导致的

**Comment by AlphonseZetta10** [comment]
我觉得是风控的问题，视频放一会儿再投币基本能成功
