### ISSUE TITLE
wiliwili能不能移植到3ds上？

### ISSUE THREAD

**Issue by destiny188** [xfangfang/wiliwili#248]
wiliwili能不能移植到3ds上？

**Comment by xfangfang** [comment]
@destiny188 很遗憾我认为wiliwili做不到向3ds的移植，3ds的可用内存太少了，wiliwili的psv移植都很艰难，更不要说3ds了。

如果您有在3ds使用bilibili的动力可以考虑修改这个项目，来支持bilibili，这个应该是可以做到的：
https://github.com/windows-server-2003/ThirdTube

如果有什么需要帮助的欢迎随时联系。
