### ISSUE TITLE
能否提供windows 32位的版本

### ISSUE THREAD

**Issue by winterwhisper** [xfangfang/wiliwili#249]
能否提供windows 32位的版本，谢谢。

**Comment by xfangfang** [comment]
项目readme中已经写了：

> Windows: 不提供 x86 安装包，如有需求可以自行编译

如果您愿意提供一个适配GitHub action的x86编译脚本，那么我确实愿意接收这样的pr，这样之后的版本就会一同发布x86。

因为现在还是32位处理器的设备可能还是运行着win7或者xp，所以对于老设备的适配我多说两句，需要在编译时开启 opengl2 的支持才能支持windows xp sp2，但是msys2的编译出来的东西现在已经不支持windows xp运行了，你需要修改一些msys2的内容来支持。如果是win7 且显卡不支持opengl3.2 同样需要在编译时开启opengl2 的支持才能正常运行。

如果编译中遇到了问题欢迎随时咨询。

**Comment by dragonflylee** [comment]
@winterwhisper  可以测试一下这个能不能正常使用 https://nightly.link/xfangfang/wiliwili/actions/runs/7042604448/wiliwili-Windows-3ee045f-GL2.zip

**Comment by winterwhisper** [comment]
> 项目readme中已经写了：
> 
> > Windows: 不提供 x86 安装包，如有需求可以自行编译
> 
> 如果您愿意提供一个适配GitHub action的x86编译脚本，那么我确实愿意接收这样的pr，这样之后的版本就会一同发布x86。
> 
> 因为现在还是32位处理器的设备可能还是运行着win7或者xp，所以对于老设备的适配我多说两句，需要在编译时开启 opengl2 的支持才能支持windows xp sp2，但是msys2的编译出来的东西现在已经不支持windows xp运行了，你需要修改一些msys2的内容来支持。如果是win7 且显卡不支持opengl3.2 同样需要在编译时开启opengl2 的支持才能正常运行。
> 
> 如果编译中遇到了问题欢迎随时咨询。

抱歉没有仔细看Readme。我是win8的平板，安装32位的系统是因为内存不大。原来有尝试过64位的win10，但还是勉强了点所以改回了原装的win8。我没咋用过msys和mingw，等空了试试在单位电脑的ubuntu里交叉编译一个看看，谢谢你的回答。

**Comment by winterwhisper** [comment]
> @winterwhisper 可以测试一下这个能不能正常使用 https://nightly.link/xfangfang/wiliwili/actions/runs/7042604448/wiliwili-Windows-3ee045f-GL2.zip

@dragonflylee 试了，不行，打开就停止工作。

**Comment by dragonflylee** [comment]
> > @winterwhisper 可以测试一下这个能不能正常使用 https://nightly.link/xfangfang/wiliwili/actions/runs/7042604448/wiliwili-Windows-3ee045f-GL2.zip
> 
> @dragonflylee 试了，不行，打开就停止工作。

 用管理员权限打开呢？我这边 Win7 32位是可以运行的

![image](https://github.com/xfangfang/wiliwili/assets/6219280/91486995-2c69-434d-9de2-f4b96aaa5eb8)

**Comment by winterwhisper** [comment]
> > > @winterwhisper 可以测试一下这个能不能正常使用 https://nightly.link/xfangfang/wiliwili/actions/runs/7042604448/wiliwili-Windows-3ee045f-GL2.zip
> > 
> > 
> > @dragonflylee 试了，不行，打开就停止工作。
> 
> 用管理员权限打开呢？我这边 Win7 32位是可以运行的

@dragonflylee 也还是不行

**Comment by dragonflylee** [comment]
建议将下载到的文件，右键属性，勾上 "解除锁定" 后再解压

![image](https://github.com/xfangfang/wiliwili/assets/6219280/6a8166c5-8cf0-41e5-93b5-f223db3f8785)

**Comment by xfangfang** [comment]
@dragonflylee 要不要先临时构建一个有windows那个log窗口的版本，看看有没有什么信息。没准是和opengl相关的问题导致初始化失败，又或者是和配置文件目录权限有关的问题。

@winterwhisper 与此同时可以做：
1. 回复一下详细的windows版本信息和处理器信息 
2. 在文件管理器输入 %HOMEPATH%\AppData\Local\xfangfang\wiliwili 看看能不能打开这个目录。
3. 检查系统账户是管理员账户（administrator）还是普通账户。

**Comment by dragonflylee** [comment]
@winterwhisper 麻烦再测试一下这个 build  https://nightly.link/xfangfang/wiliwili/actions/runs/7057763362/wiliwili-Windows-5db9a8a-GL2.zip

启动的时候可以从 cmd 中追加参数打印日志 `wiliwili.exe -d -o wiliwili.log` 获取更多调试信息

**Comment by winterwhisper** [comment]
> @dragonflylee 要不要先临时构建一个有windows那个log窗口的版本，看看有没有什么信息。没准是和opengl相关的问题导致初始化失败，又或者是和配置文件目录权限有关的问题。
> 
> @winterwhisper 与此同时可以做：
> 
> 1. 回复一下详细的windows版本信息和处理器信息
> 2. 在文件管理器输入 %HOMEPATH%\AppData\Local\xfangfang\wiliwili 看看能不能打开这个目录。
> 3. 检查系统账户是管理员账户（administrator）还是普通账户。

@xfangfang 我是dell v8p平板，cpu是intel z3740D，看了intel的wiki，opengl最高是支持到4.0的。windows版本是8.1，内部版本9600。

> @winterwhisper 麻烦再测试一下这个 build https://nightly.link/xfangfang/wiliwili/actions/runs/7057763362/wiliwili-Windows-5db9a8a-GL2.zip
> 
> 启动的时候可以从 cmd 中追加参数打印日志 `wiliwili.exe -d -o wiliwili.log` 获取更多调试信息

@dragonflylee  这个版本ok了！试了下，没有什么大问题，就是直播点开默认是全屏播放的，但右下角的缩小按钮点了没反应，就退出不了了，只能退出整个程序。

**Comment by dragonflylee** [comment]
@winterwhisper  直播里的全屏按钮确实没有作用，可以按ESC或者右键返回

**Comment by winterwhisper** [comment]
> @winterwhisper 直播里的全屏按钮确实没有作用，可以按ESC或者右键返回

好的，那就没问题了，感谢大佬！

**Comment by xfangfang** [comment]
感谢大家反馈，但是我有点没太看懂，改的都是mpv的内容，为什么会影响到应用不闪退呢？

**Comment by dragonflylee** [comment]
> 感谢大家反馈，但是我有点没太看懂，改的都是mpv的内容，为什么会影响到应用不闪退呢？

其实相当于给 -DUSE_GL2=ON 追加了 -DMPV_USE_FB=ON 选项，我猜之前因为没有 MPV_USE_FB 编译参数导致创建 fb 的时候崩溃的

**Comment by xfangfang** [comment]
这段我理解了，但是之前说的是： “试了，不行，打开就停止工作。"

我感觉他的意思应该是打开应用而不是打开视频？

**Comment by winterwhisper** [comment]
> 这段我理解了，但是之前说的是： “试了，不行，打开就停止工作。"
> 
> 我感觉他的意思应该是打开应用而不是打开视频？

@xfangfang  是的，上一个版本是打开应用就停止工作了，完全没看到界面

**Comment by dragonflylee** [comment]
@winterwhisper 有空的帮忙测测这个版本能不能正常使用， 直播全屏按钮的BUG已经被 xfangfang 大佬修复了

https://nightly.link/xfangfang/wiliwili/actions/runs/7125015052/wiliwili-Windows-3e202ea-GL2.zip
