### ISSUE TITLE
PC版鼠标滚轮滚动灵敏度太低了，滚几圈都翻不了一行视频。

### ISSUE THREAD

**Issue by HumanMus1c** [xfangfang/wiliwili#25]
希望可以改进一下这个问题.

**Comment by xfangfang** [comment]
@HumanMusicX 这个软件目前是针对手柄操作设计的，并没有针对其他问题进行优化。如果有需求，欢迎为项目提交代码进一步完善。

**Comment by xfangfang** [comment]
@HumanMusicX  刚刚看了一下代码，在 `library/borealis/library/lib/platform/glfw/glfw_input.cpp` 117行附近：

原本是：
```c++
    self->scrollOffset.x += xoffset * 10;
    self->scrollOffset.y += yoffset * 10;
```

修改为下列内容可以临时解决一下这个问题：
```c++
#ifdef _Win32
    self->scrollOffset.x += xoffset * 100;
    self->scrollOffset.y += yoffset * 100;
#else
    self->scrollOffset.x += xoffset * 10;
    self->scrollOffset.y += yoffset * 10;
#endif
```

可以fork我的项目，然后直接在网页上修改一下，github actions会自动构建客户端，感觉这个只是临时修复一下，还是应该实现一下滚动平滑，之前一直在mac上开发倒是没注意到这个问题，所以我先不提交修改了，等到完美实现时候再说。

**Comment by xfangfang** [comment]
@HumanMusicX  最新的构建解决了这个问题，可以测试看看，没问题的话就关闭这个issue了

**Comment by xfangfang** [comment]
因为没有回应 先关闭了这个issue
