### ISSUE TITLE
Publish wiliwili to flathub.

### ISSUE THREAD

**Issue by pugaizai** [xfangfang/wiliwili#252]
Publishing wiliwili on Flathub can provide a streamlined and user-friendly way to distribute and maintain your application across various Linux distributions, enhancing its accessibility and user reach within the open-source community.

**Comment by xfangfang** [comment]
Thank you very much.
If you have successfully submitted wiliwili to Flathub, please feel free to bring me into the repo.

**Comment by pugaizai** [comment]
@xfangfang 你收到 flathubbot 那个邀请了吗

**Comment by xfangfang** [comment]
@madoka773 貌似没发给我

**Comment by pugaizai** [comment]
> @madoka773 貌似没发给我

现在有吗？没有的话我发 issue 试试看能不能加了

**Comment by xfangfang** [comment]
暂时还没有收到，不过按他们维护的速度看，可能要一两天才会回应？

**Comment by pugaizai** [comment]
> 暂时还没有收到，不过按他们维护的速度看，可能要一两天才会回应？

要开 issue 才会回应，应该很快就有了

**Comment by pugaizai** [comment]
@xfangfang 有兴趣通过flathub的官方认证吗？

相关链接 https://docs.flathub.org/docs/for-users/verification

好像有点费劲

**Comment by xfangfang** [comment]
对用户来说使用起来没有区别的话，就不用麻烦认证了吧，如果原来是用的io.github可能还稳定一些，但是用的我自己的域名，万一什么时候我没办法续充域名了我怕会比较麻烦。
