### ISSUE TITLE
打开wiliwili后进相册会白屏卡死，只能按电源键12秒强制关机

### ISSUE THREAD

**Issue by fansID512** [xfangfang/wiliwili#254]
wiliwili1.2.2版本在最新的大气层17.0.1下运行时返回主页面再打开相册会卡死，下面是我现在正在使用的1.6.2的大气层固件包，看能不能排查出是哪方面的原因引起的
https://www.123pan.com/s/f2Q8Vv-VDp5d

**Comment by xfangfang** [comment]
@fansID512 可以检查看看是不是中文特斯拉导致的问题，我有记得在哪看到有人提过这个问题，但是解决问题的人没有和我讨论过，所以我也不是很清楚具体的来龙去脉。
我能确认的是官方的特斯拉在我这里是没有问题的（虽然我现在系统还不是最新版，但是这个问题因为我早有耳闻，所以应该和版本无关）

**Comment by fansID512** [comment]
我排查出原因所在了，因为我安装了sysdvr串流，并设置了自启动，所以导致开启wiliwili后进相册会卡死，我完全删掉串流后就不会再卡了，感觉有点玄学，之前也是有的固件装了串流后进游戏再进相册会卡死，这次我单独测试了新固件进游戏再进相册不会卡，但没想到还是和wiliwili冲突了。

**Comment by xfangfang** [comment]
非常感谢详细的反馈，我会把这个内容同步在wiki中的，感谢。

我猜还是 sysdvr 内存占用太大了导致的问题，如果 wiliwili 搭配你正在使用的 sysdvr 存在这样的问题，那我猜肯定还会有其他的软件或者游戏存在类似的情况。

如果某个游戏能兼容你的上述操作（而且要保证这个游戏可以通过 sysdvr 串流），那么你可以尝试按住 肩键R 的同时打开这个游戏，在开启的 hbmenu 中选择 wiliwili 打开，然后回桌面进入相册，测试有没有类似的情况出现。

如果能正常开启相册 hbmenu，那么可能是 wiliwili 的桌面图标某些配置导致的。
如果不能，那么可能是某些代码导致的，你可以从新到旧依次测试wiliwili，看看旧版本会不会有更好的情况，这会帮助更快的定位根本原因。
