### ISSUE TITLE
请问一下mpv的deko3d版本可以参考一下吗

### ISSUE THREAD

**Issue by kelvin8906** [xfangfang/wiliwili#256]
最近在尝试把一些switch的串流app优化为deko3d版本，但是可参考的文档太少了。

项目内的mpv版本也是编译好的mpv-deko3d，想知道ffmpeg硬解出frame后如何实现0拷贝渲染，感恩~

**Comment by xfangfang** [comment]
mpv 的 deko3d 版本不是我制作的，它是由 ffmpeg 在 hos 硬解的作者 https://github.com/averne/FFmpeg 制作的，作者非常的热心，nxmp moonlight 还有 wiliwili 的 ffmpeg 或 mpv 相关的问题都有作者的参与。

如果需要帮助你可以在这个群组 https://discord.gg/erNC4FB ， 的 programming 分区下找到他。

https://github.com/switchbrew/libnx/issues/580#issuecomment-1685091938

非常期待你的作品诞生了，顺便我也好奇一下你会不会做 chiaki 的deko3d移植，如果要做的话可能需要更新一下 chiaki 代码里的borealis版本。

如果用 https://github.com/xfangfang/borealis 这个borealis的话，可以同时支持 chiaki 目前还不支持的 iOS。（如果感兴趣的话可以尝试）

**Comment by kelvin8906** [comment]
我今天刚在gba发布了averne的ffmpeg的硬解的移植版，就在chiaki的homebrew帖子里。但是硬解还是需要从显存转到内存做处理。

我也问了一下averne有没有deko3d的绘制视频的demo，也没有，我先尝试能不能跑起来纯deko3d的环境，毕竟不是写c++的，纯粹是最近客厅电视被占了😭

**Comment by kelvin8906** [comment]
https://gbatemp.net/threads/chiaki-ps5-ps4-remote-play-homebrew.564553/page-48

这个帖子~其实能做到ffmpeg硬解我看着cpu load减少了一半，而且也能有效减少卡顿，也实现了hevc画质，其实deko3d也就是再优化一下cpu，对720p的提升不大了

**Comment by xfangfang** [comment]
只是720P的话，感觉不做deko3d版效果也是很可以的了，貌似只有到 4k 的时候才不得不需要deko3d。

**Comment by xfangfang** [comment]
您修改的这个有在哪里开源嘛？我去学习学习代码 : )

**Comment by kelvin8906** [comment]
我完善一下配置就问问honeybadger怎么提pr，他不在github，我也不知道chiaki的流程，一定发

**Comment by kelvin8906** [comment]
虽迟但到，终于最近抄moonlight的作者把deko3d给做了。

这个borealis还是你和俄国小哥一起写的，感恩fangfang的贡献

https://git.sr.ht/~kkwong/chiaki/refs/download/v2.2.0-deko3d/chiaki-deko3d.nro.zip

**Comment by xfangfang** [comment]
感谢分享，终于支持deko3d了。borealis还包含了 dragonflylee 和 zeromake 的功劳，还有其他不少开发者的贡献，不敢居功。
