### ISSUE TITLE
每次播放番剧或者分集视频下一集都会直接跳过一集

### ISSUE THREAD

**Issue by 195680144195** [xfangfang/wiliwili#258]
我看没人反馈，难道只有我遇到这个问题了吗？
win10
还有就是合集视频播放下一集会显示重复的标签
![image](https://github.com/xfangfang/wiliwili/assets/68938017/d038c10c-f9b4-4fa5-9465-c08b344af837)

**Comment by xfangfang** [comment]
@kaway147 测试版有修复：
https://github.com/xfangfang/wiliwili/wiki

**Comment by xfangfang** [comment]
没有后续反馈，我先关闭这个issue了
