### ISSUE TITLE
make succeed but cannot run in Ubuntu 22.04 virtual machine(VMware)

### ISSUE THREAD

**Issue by BebopChain** [xfangfang/wiliwili#26]
![image](https://user-images.githubusercontent.com/100358043/203488377-4e0c6acf-888a-4c15-a9c4-4ba307a0a48a.png)

make succeed but failed to run.
is that because i'm lack of some libs or need to config some files?

**Comment by xfangfang** [comment]
https://stackoverflow.com/a/39214184/8892048

Maybe it will be solved after update your gpu driver.

Or just edit `library/borealis/library/lib/platform/glfw/glfw_video.cpp`

line65:
```c++
    // Create window
#if defined(__APPLE__) || defined(_WIN32)
```

to

```c++
    // Create window
#if defined(__APPLE__) || defined(_WIN32) || defined(__linux__)
```

If it doesn't work, change the following `3` and `2` to a smaller value suitable for your current environment, but other problems may occur.

**Comment by BebopChain** [comment]
many thanks! 
your advice fix my problem perfectly! After adding the macro __linux__ and re make the project, the wiliwili runs smoothly.
