### ISSUE TITLE
期望能多加些视频分类

### ISSUE THREAD

**Issue by zlyxiaozhu** [xfangfang/wiliwili#260]
期望能多加些视频分类，像科技数码这种

**Comment by xfangfang** [comment]
@zlyxiaozhu 希望可以描述的清晰一些：
1. 具体是在哪里加分类。
2. 官方的客户端是否有类似的功能；如果有，在哪里，长什么样。

**Comment by zlyxiaozhu** [comment]
不好意思，我看的是网页端，客户端确实没有分类，打扰了（哈哈）
![屏幕截图 2023-12-27 211902](https://github.com/xfangfang/wiliwili/assets/54766774/e1a2e869-55ab-4eef-855d-b0545f620533)

**Comment by xfangfang** [comment]
网页有这个功能的话，咱们确实是可以实现的（混用不同平台的API可能会有鉴权问题），这个短时间应该不会实现了，目前软件主要是日常维护，不会新增太多新东西，不过欢迎提交PR。
