### ISSUE TITLE
直播页面api error

### ISSUE THREAD

**Issue by chenxiex** [xfangfang/wiliwili#265]
![图片](https://github.com/xfangfang/wiliwili/assets/28776935/4fa60738-113e-48c8-a8aa-84a763be2fb2)
推荐、热门等页面都能正常加载，但是直播页面异常。

**Comment by xfangfang** [comment]
@chenxiex 命令行运行，直到显示这里的报错，然后复制一下 log

**Comment by xfangfang** [comment]
顺便可以从手机看一下关注的人里谁正在直播，截一下图

**Comment by chenxiex** [comment]
[wiliwili_log.txt](https://github.com/xfangfang/wiliwili/files/13787712/wiliwili_log.txt)
![Screenshot_2023-12-28-23-35-05-13_149003a2d400f6adb210d7e357a3a646](https://github.com/xfangfang/wiliwili/assets/28776935/b48cacf5-fb1c-42fc-bdd8-30031d0664bb)

**Comment by xfangfang** [comment]
是这个up主的直播间数据造成的问题：宴宁ccccc

但是他现在没在直播，所以我没办法实际验证一下。

这里是修复后的版本，代码在dev分支：https://github.com/xfangfang/wiliwili/actions/runs/7349206177

**Comment by xfangfang** [comment]
没有后续反馈，我先关闭这个issue了

**Comment by chenxiex** [comment]
这两天都没遇到能够触发这个bug的场景。如果后续有bug再重开issue吧。
