### ISSUE TITLE
steam deck视频画面一直在闪

### ISSUE THREAD

**Issue by Tartaruseyes** [xfangfang/wiliwili#273]
这两天才发现有更新于是更新了一下，直播能看了，但是无论是看普通视频还是直播，画面都跟快进了似的一闪一闪的，但是声音是正常的。

**Comment by xfangfang** [comment]
@Tartaruseyes 我的steamdeck没有这样的问题，可以详细描述一下使用环境（游戏模式还是桌面模式），安装方式与系统版本。尝试更新系统或重启。

**Comment by Tartaruseyes** [comment]
@xfangfang 无论是游戏模式还是桌面模式都会闪，是双击安装包安装的，系统就是最新版本。

**Comment by xfangfang** [comment]
@Tartaruseyes 对于flatpak，咱们还都是同一款机器按道理是不应该出现问题的，我也想不出来有什么出现问题的可能。

下面是我的建议：

1. 可以试一试重启机器看一看，有可能重启后就好了。
2. 在桌面模式，调整应用为窗口模式，并随意调整一下窗口大小看看问题还依旧存在不。
3. 重新安装旧版本确认一下旧版本是否存在问题（这个很关键，有可能你现在用旧版本也有问题，这样就可以彻底排除是wiliwili自身的问题了）
4. 重新安装新版本确认问题是否消失
5. 卸载，并从应用商店内直接搜索下载，确认问题是否消失
6. 调整软解/硬解/h264/h265/av1等设置，查看情况是否有变化
7. 检查是不是某些第三方插件造成了冲突
8. 检查是不是调整过某些系统设置

按照建议可以从第一项向后逐步测试，我认为这个问题应该不是应用本身导致的。

**Comment by xfangfang** [comment]
如果方便的话，可以发一下出现问题时的录屏

**Comment by xfangfang** [comment]
最新测试版已经解决了这个问题。  
测试版：https://nightly.link/xfangfang/wiliwili/workflows/build.yaml/dev  
更新内容：https://github.com/xfangfang/wiliwili/wiki#测试版更新内容
