### ISSUE TITLE
Steamdeck播放视频跳帧、卡顿

### ISSUE THREAD

**Issue by Gczaizi** [xfangfang/wiliwili#278]
使用release下载的文件安装后，Steamdeck播放视频跳帧、卡顿，请问如何查看log？

**Comment by xfangfang** [comment]
flatpak run cn.xfangfang.wiliwili -t

https://github.com/xfangfang/wiliwili/discussions/41

**Comment by xfangfang** [comment]
可以同时参考这里：https://github.com/xfangfang/wiliwili/issues/273#issuecomment-1899395324

**Comment by xfangfang** [comment]
您好，请问还有后续反馈吗？

**Comment by pugaizai** [comment]
也许你可以试试
`flatpak install ffmpeg-full`

**Comment by pugaizai** [comment]
或者设置里把硬解关掉试试看

**Comment by quantumDCS** [comment]
我使用命令行在steamdeck上安装1.3.0版本linux安装包也遇到了这个问题，尝试调整解码方式等没有效果，卸载后在应用商店内下载的没有这个问题

**Comment by xfangfang** [comment]
@quantumDCS 感谢反馈，或许可以尝试卸载后重装一下本地安装包？我感觉没准是从商店更新的时候顺便更新了什么底层依赖，然后就没问题了。如果卸载商店版本然后重装本地安装包之后问题消失了，那么很有可能是这个问题。
我在我的steam deck上一直是在使用安装包的版本（因为我一直在用[测试版](https://nightly.link/xfangfang/wiliwili/workflows/build.yaml/dev)）一直也没遇到过类似的问题的。

**Comment by xfangfang** [comment]
最新测试版已经解决了这个问题。  
测试版：https://nightly.link/xfangfang/wiliwili/workflows/build.yaml/dev  
更新内容：https://github.com/xfangfang/wiliwili/wiki#测试版更新内容
