### ISSUE TITLE
希望在switch投屏时增加十字键的功能

### ISSUE THREAD

**Issue by 1746534404** [xfangfang/wiliwili#279]
掌机模式下可以通过滑动屏幕调整声音和进度，主机模式下看视频时调整声音仍然很麻烦 希望给十字键加个调节声音的功能

**Comment by xfangfang** [comment]
@1746534404 
首先明确一下全屏下音量调节方式：
Y ➡ ➡ A 左右调整 B

或者

B A ➡ A 左右调整 B

1. 因为音量调节应该不会太频繁，所以我想先确认一下前面提到比较麻烦的音量调节是否是我上面说的这个步骤？

2. 如果要调整，我倾向于将音量调节的快捷键设置为 RT(ZR) + 上下，这样右侧单个joycon也能调整音量。

**Comment by xfangfang** [comment]
新的快捷键添加好了，ZR/RT/R2 + 上下 调整音量。
