### ISSUE TITLE
【Bug】视频的部分评论emoji乱码

### ISSUE THREAD

**Issue by MengNianxiaoyao** [xfangfang/wiliwili#281]
![Clip_2024-02-10_14-14-20](https://github.com/xfangfang/wiliwili/assets/103258286/1839a779-2c58-4750-aefa-31f0929b5f94)
![Clip_2024-02-10_14-14-26](https://github.com/xfangfang/wiliwili/assets/103258286/010234ef-51b9-4ba3-9de9-31896f1b0680)

视频链接：https://www.bilibili.com/video/av1700272006?p=1

**Comment by xfangfang** [comment]
可以在配置目录（看项目wiki)下放置自定义的emoji.ttf，这样应用启动后加载的就不是内置的emoji了。

需要注意的是目前emoji应该是不支持那种带颜色的。

如果你找到了更合适的emoji字体欢迎推荐

**Comment by MengNianxiaoyao** [comment]
我现在用的emoji是win系统自带的，在fonts文件夹内搜索`emoji`，复制这个ttf文件并改名然后粘贴到配置目录

**Comment by xfangfang** [comment]
@MengNianxiaoyao 感谢，更新在文档中了：https://github.com/xfangfang/wiliwili/discussions/38#discussioncomment-8957593

**Comment by xfangfang** [comment]
这个确实是个bug，windows 下打包成单个可执行文件之后忽略内置emoji加载了，其实内置emoji已经覆盖了前面示例视频评论的的emoji。

**Comment by xfangfang** [comment]
这个版本修复了前面的问题：https://github.com/xfangfang/wiliwili/actions/runs/8903724171
