### ISSUE TITLE
鼠标点击无法切换焦点到播放窗口

### ISSUE THREAD

**Issue by Eitetsu0** [xfangfang/wiliwili#287]
平台：archlinux + wayland 
至少从 `7f13f79` 出现这个问题。

复现：
焦点移到右侧栏后，鼠标点击视频窗口。此时因为点了鼠标，焦点框是不显示的，按`R`或`L`键 ，焦点框会出现在右侧边栏上面的标签上，并且切换标签。

**Comment by xfangfang** [comment]
dev分支最新版应该修复了：https://github.com/xfangfang/wiliwili/actions/runs/8017912742

**Comment by Eitetsu0** [comment]
确认,已修复
