### ISSUE TITLE
[bug] 播放画面自带鬼畜

### ISSUE THREAD

**Issue by lanbairua** [xfangfang/wiliwili#298]
在steam deck上使用 wiliwili  观看视频会自带鬼畜效果
使用flatpak 下载的最新的 wiliwili 卸载重新安装还是会出现

**Comment by xfangfang** [comment]
@lanbairua  run `flatpak list` and send the output to here.

**Comment by lanbairua** [comment]
> @lanbairua跑`flatpak list`把输出发送到这里。

(deck@steamdeck ~)$ flatpak list
名称                                             应用程序 ID                                   版本               分支                  安装AnyDesk                                          com.anydesk.Anydesk                           6.3.0              stable                system
Studio 翻译                                      com.obsproject.Studio.Locale                                     stable                system
Freedesktop Platform                             org.freedesktop.Platform                      23.08.13           23.08                 system
Mesa                                             org.freedesktop.Platform.GL.default           23.3.5             22.08                 system
Mesa (Extra)                                     org.freedesktop.Platform.GL.default           23.3.5             22.08-extra           system
Mesa                                             org.freedesktop.Platform.GL.default           24.0.2             23.08                 system
Mesa (Extra)                                     org.freedesktop.Platform.GL.default           24.0.2             23.08-extra           system
openh264                                         org.freedesktop.Platform.openh264             2.1.0              2.2.0                 system
Freedesktop SDK                                  org.freedesktop.Sdk                           23.08.13           23.08                 system
GNOME Application Platform version 45            org.gnome.Platform                                               45                    system
Breeze GTK theme                                 org.gtk.Gtk3theme.Breeze                      5.27.8             3.22                  system
KDE Application Platform                         org.kde.Platform                                                 5.15-23.08            system
KDE Application Platform                         org.kde.Platform                                                 6.5                   system
yuzu 翻译                                        org.yuzu_emu.yuzu.Locale                                         stable                system

**Comment by xfangfang** [comment]
@lanbairua 
1. 你这也没装wiliwili呀，重装一下wiliwili，确认问题依旧存在，然后再发
2. 发的时候注意把网页翻译插件关了，你发的东西好像被翻译过了？

**Comment by lanbairua** [comment]
> @lanbairua
> 
> 1. 你这也没装wiliwili呀，重装一下wiliwili，确认问题依旧存在，然后再发
> 2. 发的时候注意把网页翻译插件关了，你发的东西好像被翻译过了？

确实安装了 如果卸载文都是从本地文件删了再安装的 
flatpak 好像检测不到安装应用
![Image_1709975564415](https://github.com/xfangfang/wiliwili/assets/89310348/f8f9cc77-439a-4314-bbec-68dad1fa5f16)

**Comment by xfangfang** [comment]
@lanbairua 

> 如果卸载文都是从本地文件删了再安装的

1. 这句话什么意思？


2. 正常情况下的输出应该是:


```shell
(deck@steamdeck ~)$ flatpak uninstall wiliwili
Found installed ref ‘app/cn.xfangfang.wiliwili/x86_64/master’ (system). Is this correct? [Y/n]: 


        ID                           Branch        Op
 1. [-] cn.xfangfang.wiliwili        master        r

Uninstall complete.
(deck@steamdeck ~)$ flatpak install cn.xfangfang.wiliwili
Looking for matches…

cn.xfangfang.wiliwili permissions:
    ipc    network    fallback-x11    pulseaudio    wayland    x11   devices   dbus access [1]

    [1] org.freedesktop.PowerManagement, org.freedesktop.ScreenSaver, org.gnome.SessionManager, org.mate.SessionManager


        ID                             Branch          Op          Remote          Download
 1. [✓] cn.xfangfang.wiliwili          stable          i           flathub         18.5 MB / 15.6 MB

Installation complete.
(deck@steamdeck ~)$ flatpak list
Name                                              Application ID                                   Version                     Branch                 Installation
wiliwili                                          cn.xfangfang.wiliwili                            1.3.0                       stable                 system

```

3. 请问您之前是如何安装的？如果是通过命令行，具体的命令是什么

4. 可以运行一下: `flatpak remotes` ，我在想是不是您之前配置过什么镜像之类的？

**Comment by lanbairua** [comment]
> @lanbairua
> 
> > 如果卸载文都是从本地文件删了再安装的
> 
> 1. 这句话什么意思？
> 2. 正常情况下的输出应该是:
> 
> ```shell
> (deck@steamdeck ~)$ flatpak uninstall wiliwili
> Found installed ref ‘app/cn.xfangfang.wiliwili/x86_64/master’ (system). Is this correct? [Y/n]: 
> 
> 
>         ID                           Branch        Op
>  1. [-] cn.xfangfang.wiliwili        master        r
> 
> Uninstall complete.
> (deck@steamdeck ~)$ flatpak install cn.xfangfang.wiliwili
> Looking for matches…
> 
> cn.xfangfang.wiliwili permissions:
>     ipc    network    fallback-x11    pulseaudio    wayland    x11   devices   dbus access [1]
> 
>     [1] org.freedesktop.PowerManagement, org.freedesktop.ScreenSaver, org.gnome.SessionManager, org.mate.SessionManager
> 
> 
>         ID                             Branch          Op          Remote          Download
>  1. [✓] cn.xfangfang.wiliwili          stable          i           flathub         18.5 MB / 15.6 MB
> 
> Installation complete.
> (deck@steamdeck ~)$ flatpak list
> Name                                              Application ID                                   Version                     Branch                 Installation
> wiliwili                                          cn.xfangfang.wiliwili                            1.3.0                       stable                 system
> ```
> 
> 3. 请问您之前是如何安装的？如果是通过命令行，具体的命令是什么
> 4. 可以运行一下: `flatpak remotes` ，我在想是不是您之前配置过什么镜像之类的？

1. flatpak install cn.xfangfang.wiliwili 演示一下，确实安装了
2. flatpak uninstall  cn.xfangfang.wiliwili 和 flatpak list 命令 单纯演示一下flatpak确实又找不到 wiliwili 
3. 卸载我是通过 sudo rm -rf /var/lib/flatpak/app/cn.xfangfang.wiliwili/* 卸载的 然后再通过 flatpak install cn.xfangfang.wiliwili安装的 
4. 系统确实崩溃，通过官方镜像恢复过 使用的桌面两个工具 Clear local user data 和  reinstall steam 恢复过系统
5. 之前使用没有遇到这个问题

**Comment by xfangfang** [comment]
@lanbairua 
我还是不能完全理解前面这些话的中文含义，但是也不影响，无论怎么做，最终目的是让 wiliwili 能正常显示在 `flatpak list` 的列表中，`sudo rm -rf` 显然不是 卸载的正确方式，我建议可以运行 `flatpak repair` 尝试修复一下。

然后把带有 wiliwili 的 `flatpak list` 结果 和 `flatpak remotes`发出来。

我主要是想比对一下咱们的环境是不是一致的，因为我正在用 steam deck 和你一模一样的操作方式是可以正常使用的。

**Comment by xfangfang** [comment]
如果方便的话，最好也可以发一下鬼畜的录屏，有点好奇是什么状态的鬼畜。

**Comment by yanlz84** [comment]
自带鬼畜我也遇到过，以前是通过flatpak包安装的，后来卸了重新在flatpak商店上装就正常了。

**Comment by xfangfang** [comment]
@yanlz84 这个类似的情况我听到过三次反馈了，但是之前的反馈者大都没有后续信息了，如果大家不在出问题的时候反馈足够的信息，那这个问题可能就会持续下去。

比如您现在重新安装离线的 flatpak 包还会出问题吗？

**Comment by lanbairua** [comment]
> 如果方便的话，最好也可以发一下鬼畜的录屏，有点好奇是什么状态的鬼畜。


> 如果方便的话，最好也可以发一下鬼畜的录屏，有点好奇是什么状态的鬼畜。


https://github.com/xfangfang/wiliwili/assets/89310348/2d211e13-e17a-447b-a9a9-2f8bca7d4c7e

这个视频压缩过

**Comment by yanlz84** [comment]
> @yanlz84 这个类似的情况我听到过三次反馈了，但是之前的反馈者大都没有后续信息了，如果大家不在出问题的时候反馈足够的信息，那这个问题可能就会持续下去。
> 
> 比如您现在重新安装离线的 flatpak 包还会出问题吗？

试过，无法复现。

**Comment by xfangfang** [comment]
@lanbairua 
这个问题看起来像是 pts 没解析对导致的，本质应该还是 ffmpeg 的问题，但是我看你那边 ffmpeg 版本和我这里是一样的，所以我也不是很确定具体的原因。
在设置中有一些控制播放的选项，可以分别测试，软解/硬解 搭配 h264/h265 等选项，把所有组合测试一遍看看再反馈。


cc @madoka773 看来 steam deck 上的这个问题不是个例

**Comment by pugaizai** [comment]
感觉还是没有什么有用的信息，也帮不上忙啊。
其实播放画面出问题我也碰到过，但是也只是在360P下才会有，480P以上就没问题了，而且也不是这种抖动的问题。

**Comment by pugaizai** [comment]
@lanbairua 你试试卸载了openh264再运行wiliwili

**Comment by pugaizai** [comment]
我以前用flatpak版的firefox也碰到过这种问题，那会儿的解决方法是flatpak安装ffmpeg-full就好了。后来新版firefox会自动带上ffmpeg之后就没这问题了

**Comment by lanbairua** [comment]
> @lanbairua 你试试卸载了openh264再运行wiliwili

OK了 正常了

**Comment by pugaizai** [comment]
@xfangfang 也许这就是答案？顺带一提openh264是跟随着org.freedesktop.Platform一起安装的。

**Comment by xfangfang** [comment]
@madoka773 这更像是玄学吧，卸载 openh264 再运行 wiliwili 正常情况会报错无法播放视频的。（除非切到 av1 播放？）

我知道一种复现问题的方法，在只安装 org. freedesktop.Platform. ffmpeg-full 22.08 的情况下，通过离线的 flatpak 安装包安装应用，不会自动安装 23.08，导致后面这个视频抖动问题出现了。

或者同时安装有 org. freedesktop.Platform. ffmpeg-full 22.08 和 23.08 的情况下，强制卸载 23.08 也会出现类似问题。

我的想法是恢复之前的做法，将ffmpeg直接包含在安装包里避免类似的情况再出现，至少离线的安装包要这么做。

**Comment by pugaizai** [comment]
那我待会儿把ffmpeg加回来

**Comment by xfangfang** [comment]
@madoka773 感谢感谢，wiliwili 这个仓库这边我正好在改 flatpak，所以我待会顺手改一下就行，flathub 那边好像不用改也行，这个看你的想法啦。我感觉可能出现问题的情况就是有用户手动去删除 ffmpeg-full，不然应该也没啥事。

**Comment by pugaizai** [comment]
@xfangfang 顺带一提现在flathub改finish-args的时候会触发个审核，如果要必要的话还需要你去说明。到时候在邮件会看到

**Comment by xfangfang** [comment]
@madoka773 如果指的是 `- --filesystem=~/.steam` 这条的话，我感觉就不用往 flathub 那边加了，感觉访问其他应用的目录应该不符合审核的规定。

**Comment by xfangfang** [comment]
最新测试版已经解决了这个问题。  
测试版：https://nightly.link/xfangfang/wiliwili/workflows/build.yaml/dev  
更新内容：https://github.com/xfangfang/wiliwili/wiki#测试版更新内容
