### ISSUE TITLE
PC端全屏的一些操作逻辑问题。

### ISSUE THREAD

**Issue by sujieico0** [xfangfang/wiliwili#299]
首先是全屏部分。

假设使用鼠标操作，将应用全屏显示（非视频全屏，也不是最大化），此时会丢失鼠标指针，但鼠标仍然可以以右键进行操作，左键进行确定。

此时想要退出全屏，则必须要用键盘或者其他设备，进行操作，大致步骤会如下：

1，假设已经将视频全屏（非应用全屏，也不是应用最大化），鼠标左键的功能是暂停，右键是退出，需要退出全屏则需要用键盘方向键移动到全屏视频的选项上进行操作。

2，假设视频没有全屏，此时需要先按回车将视频全屏，然后按照上面的方法操作。

3，若是在设置中操作将应用全屏，则也会丢失鼠标指针，此时也需要通过键盘进行操作。

这些操作非常繁琐且反直觉，建议大佬修改操作逻辑，或者将某个按键作为全屏的快捷键。

其次是进入视频在应用中全屏的操作逻辑

假设在视频详情页，要进入视频应用中全屏，提示操作方法是回车，但实际上需要按两下回车（第一下为选中，第二下为执行）

在已经应用中全屏的视频里，刚才全屏的回车键功能变为了暂停，要切换非全屏的操作变成了ESC键，（猜测逻辑是返回）此时如果不小心误点则会再次返回上一级，且丢失播放进度（这部分原因不明，照例说不会丢失，但我测试了几次都会丢失进度）。

所以这个应用中全屏的操作和退回，逻辑不统一的情况下使用起来很容易有怪问题，请大佬参阅。

**Comment by xfangfang** [comment]
1. 鼠标指针不应该会丢失，我在本地测试时各个系统下都没有遇到过类似的情况。是不是显示器开了hdr？或者什么奇怪的原因导致的，同理我猜你那边应用全屏时是不是输入法也不显示？（如果是的话 这也是不应该出现的行为）但是我也没什么好办法来解决，可以试试测试版，不行的话就只能自己调试看看了。
2. 在两种输入方式切换时(比如鼠标或者触摸操作换到键盘或者手柄操作），会存在避免误触的情况，体现为你说的 “提示操作方法是回车，但实际上需要按两下回车” 这是正常的。（这个应用的操控设计是，任何一种操作方式都能完整控制应用，所以正常情况下只使用一种操控方式即可，你的问题还应该是鼠标消失导致的）
3. 测试版之前做了全屏快捷键和播放暂停快捷键，详细更新说明见项目 wiki
4. 进入视频全屏和退出视频全屏使用 enter 和 esc 我认为是符合逻辑的，因为这里enter/esc不是以快捷键的形式存在的，而是通用的按键。在这个应用中所有出现的焦点框都是按enter进入 esc退出的。
5. 至于为什么进入之后enter同时负责了播放暂停，主要是考虑到手柄用户，在测试版设置中有一个新的操作模式，主要是为电视遥控器设计的，不过也可以试试。
6. 从视频全屏按esc到取消全屏，视频进度会消失是我没遇到过的，建议录个屏传上来，我看看到底是怎么回事。

我的建议是在pc端能用鼠标操作尽量鼠标操作，搭配测试版 f 和 空格 两个快捷键使用，我自己用还是挺舒服的。

**Comment by sujieico0** [comment]
我自行测试后，发现原因是因为我双显示器导致的。但是发生具有不确定性，并不是每一次都消失鼠标，发生概率大约8成。
