### ISSUE TITLE
鼠标位置和实际点击位置不符合

### ISSUE THREAD

**Issue by 1294403205** [xfangfang/wiliwili#30]
鼠标位置和实际点击位置不符，鼠标在实际点击的位置左上

**Comment by xfangfang** [comment]
不知道您用的是什么屏幕设备？

位置在：`library/borealis/library/lib/platforms/glfw/glfw_input.cpp` updateMouseStates 285行

我注意到在mac上，视网膜屏幕应该乘2，非视网膜屏幕应该乘1或者删除这一行，我不太知道要怎么获取屏幕的这个参数，所以没有修改。

**Comment by 1294403205** [comment]
MacBook Pro 13
外接一个非视网膜屏显示器

**Comment by xfangfang** [comment]
> MacBook Pro 13
> 外接一个非视网膜屏显示器

那样的话，应该在macbook屏幕上点击是正常的，在外接显示器上点击不正确，我有测试如果外接显示器开启hidpi也是和视网膜屏幕一样的。最近时间不是很富裕，欢迎研究研究这个问题然后提交pr～

**Comment by xfangfang** [comment]
@1294403205 最新的构建解决了这个问题，可以测试看看，没问题的话就关闭这个issue了

**Comment by xfangfang** [comment]
因为没有回应 先关闭了这个issue
