### ISSUE TITLE
windows 11编译后闪退

### ISSUE THREAD

**Issue by happytommyl** [xfangfang/wiliwili#301]
- 编译环境：Windows 11, Mingw
- 代码分支：dev, yoga
- 问题描述：
  - 成功编译后在Mingw shell中可以正常运行；
  - 在Powershell中有运行闪退，没有输出任何信息；
  - 双击build/wiliwili.exe报错：无法定位程序输入点XXXXX于动态链接库~/.../mysys2/.../mingw64/bin/libsrt.dll上。

已尝试过将mingw64/lib和mingw64/bin添加到环境变量和将相关依赖dll文件复制到wiliwili.exe所在文件，都是一样的问题。
release版本可以正常运行。

![image](https://github.com/xfangfang/wiliwili/assets/9802681/1171a90f-9612-49da-b4d1-1366d6aebe5a)
![image](https://github.com/xfangfang/wiliwili/assets/9802681/c89beffb-9052-450c-8784-c77199c211ed)

**Comment by happytommyl** [comment]
不知是否`-static-libgcc` `-static-libstdc++`没有生效的原因？

**Comment by xfangfang** [comment]
仔细参考 github action编译脚本即可，只要一模一样，就几乎不可能出现问题。

我猜原因是你直接用了mingw环境里的mpv，又没有把依赖复制全导致的，解决方法是去下载官方的 “all in one”版 libmpv.dll 或者使用wiliwili github action 脚本中的精简版 libmpv dll，放在软件同目录。

**Comment by dragonflylee** [comment]
从报错路径来看，msys2 也没有使用官方安装包 [msys2-x86_64-20240113.exe](https://github.com/msys2/msys2-installer/releases/download/2024-01-13/msys2-x86_64-20240113.exe)，而是使用了 `scoop` 安装的，

会不会你那里有不止一套的 `msys2` 环境，而且把 `scoop` 安装的这套配置到环境变量中了。

建议使用 `pacman -Rs ${MINGW_PACKAGE_PREFIX}-mpv` 卸载掉 msys2 自带的 mpv，安装CI使用的这个版本 https://github.com/xfangfang/wiliwili/releases/download/v0.1.0/mingw-w64-x86_64-mpv-0.36.0-4-any.pkg.tar.zst
