### ISSUE TITLE
ns1.3版本播放bug?

### ISSUE THREAD

**Issue by yeweiyuni** [xfangfang/wiliwili#303]
ns版本1.7.0.1在播放视频乃至直播室画面会变为彩色色块,类似某一帧画面暂停,变为彩色遮罩在原画面上面y
![2024032000233800-C41888B7F8FF46D1FE6EB8F592903715](https://github.com/xfangfang/wiliwili/assets/121843707/0db5dcd8-7b41-42a7-b8b9-9303bcffd0fd)

**Comment by xfangfang** [comment]
https://github.com/xfangfang/wiliwili/wiki#已知问题
