### ISSUE TITLE
能否增加窗口固定在最前面的功能

### ISSUE THREAD

**Issue by uiiang** [xfangfang/wiliwili#309]
windows下小窗播放时，能否增加一个把窗口固定在最前面的功能

**Comment by xfangfang** [comment]
@uiiang wiliwili 底层依赖的ui库不支持这个操作，不过欢迎提交PR到: https://github.com/xfangfang/borealis

用百度搜索了一下，或许这个工具可以满足你的需求：https://www.sordum.org/9182/window-topmost-control-v1-3

**Comment by dragonflylee** [comment]
根据 https://github.com/glfw/glfw/commit/3ce7bfef073c44f632acfafaaa102b774dfed10d ，glfw 似乎可以通过 `glfwWindowHint(GLFW_FLOATING, GL_TRUE)` 创建总在最上的窗口

SDL 这边是 [SDL_SetWindowAlwaysOnTop](https://wiki.libsdl.org/SDL2/SDL_SetWindowAlwaysOnTop)

https://github.com/xfangfang/borealis/pull/76

**Comment by xfangfang** [comment]
感谢 dragonflylee 的PR，这个功能即将更新于新版本，先关闭这个issue了。
