### ISSUE TITLE
请教一下，关于视频的进度调节如何实现的

### ISSUE THREAD

**Issue by ChasonJiang** [xfangfang/wiliwili#31]
请教一下，关于视频的进度调节如何实现的，即如何seek到视频时间轴的某个时间点。 期待您的解答，感激不尽

**Comment by xfangfang** [comment]
https://github.com/xfangfang/wiliwili/blob/803466a4507302c3d50eba8ee61ec96b92806d5e/wiliwili/source/view/video_view.cpp#L94-L99

关于如何控制的更多的信息可以去看mpv的文档～

**Comment by ChasonJiang** [comment]
> https://github.com/xfangfang/wiliwili/blob/803466a4507302c3d50eba8ee61ec96b92806d5e/wiliwili/source/view/video_view.cpp#L94-L99
> 
> 关于如何控制的更多的信息可以去看mpv的文档～

好的，谢谢
