### ISSUE TITLE
PSV版播放视频会随机黑屏

### ISSUE THREAD

**Issue by BlackLongPrime** [xfangfang/wiliwili#313]
PSV版播放视频的时候会随机黑屏只有声音，但是前进后退一下又恢复正常

**Comment by xfangfang** [comment]
我暂时没有遇到过类似的问题，可以在出现黑屏时查看一下内存占用看看是不是内存不够用了。

**Comment by BlackLongPrime** [comment]
> 我暂时没有遇到过类似的问题，可以在出现黑屏时查看一下内存占用看看是不是内存不够用了。

![68f4daed83eb00d3c9c78340a50a179](https://github.com/xfangfang/wiliwili/assets/167045400/3c968068-8aaa-48f3-b0f3-b0222731e582)
内存没有占满

**Comment by xfangfang** [comment]
这个问题因为我没有遇到，所以我感觉有可能是设备或者网络环境相关的，可以按条补充下面的信息：

1. 你正在使用什么版本的wiliwili，如果是旧版本那么需要更新到最新版 1.3.0
2. 具体发生的频率大概是多大？
3. 如果一个视频会遇到这样的问题，重新播放这个视频还会遇到相同的问题吗？如果会可以把视频链接发过来。
4. 在发生问题时，切换全屏与非全屏会有变化吗？
5. 在发生问题时，全屏按 select 键并发送显示的内容
6. 在发生问题前，是否刚刚将机器从休眠中唤醒（也就是说视频曾经留在过后台）

可以参考这里提及的两种获取log的方式，在问题发生时连接上电脑，看看会不会有什么报错：https://github.com/xfangfang/borealis#building-the-demo-for-psv

**Comment by xfangfang** [comment]
更新，我刚刚确实遇到了一次，内存使用正常，没有额外的报错，大概5秒左右什么也不干就自动恢复正常了，这个问题可能和播放器或者硬解相关，暂时我也无法解决。

这条视频从头播放至 14分钟时触发（没有反复测试）：https://www.bilibili.com/video/BV1fz421z7x9

**Comment by xfangfang** [comment]
我最近测试好像这个现象消失了，考虑到确实更新了播放器相关的内容，所以先关闭这个issue啦～
