### ISSUE TITLE
使用mpv 0.38.0时，视频卡在加载界面

### ISSUE THREAD

**Issue by LTSlw** [xfangfang/wiliwili#318]
## 问题描述

系统更新后，视频卡在加载界面，在更新的包中，mpv（0.37.0 -> 0.38.0）和libwebp（1.3.2 -> 1.4.0）被使用，推测是mpv更新导致的问题

![1](https://github.com/xfangfang/wiliwili/assets/38352100/01ee6f13-494b-4c93-b3e3-8b330d9562e4)

## 系统环境

系统：Arch Linux x86_64
Kernel：6.8.7-zen1-1-zen
桌面环境：KDE Plasma 6.0.4

## 终端输出

终端没有任何报错

```
01:05:39.658[INFO] Using internal font: /usr/share/wiliwili/resources/font/switch_font.ttf
01:05:39.660[INFO] Load emoji font: /usr/share/wiliwili/resources/font/emoji.ttf
01:05:39.660[INFO] Load keymap icon: /usr/share/wiliwili/resources/font/keymap_keyboard.ttf
01:05:39.660[INFO] createWindow done
01:05:39.786[INFO] Window size changed to 2496x1404, content size: 1920x1052 factor: 1.3
01:05:39.786[INFO] scale factor: 1
01:05:40.016[INFO] max_thread_num: 4
01:05:40.177[INFO] Window position changed to 0x0
01:05:42.382[INFO] App is up to date
01:05:50.578[INFO] set memory cache: 10MB
01:05:50.578[INFO] MPV hardware decode: auto-safe
01:05:50.643[INFO] MPV Version: mpv v0.38.0
01:05:50.643[INFO] FFMPEG Version: n6.1.1
01:05:50.653[INFO] disableDimming: false
```

## 问题排查

1. 在mpv 0.38.0环境下重新编译，编译通过，但问题不变
2. 在mpv 0.38.0环境下编译dev分支，可以播放，但mpv弹出了一个窗口播放
    ![image](https://github.com/xfangfang/wiliwili/assets/38352100/810e4d5d-1246-4459-83df-37a9258a380d)
3. 在flatpak中构建mpv 0.37.0的主分支和dev分支，工作均正常
4. 在flatpak中构建mpv 0.38.0的主分支和dev分支，问题复现

> flatpak的测试使用各自分支的`.flatpak-manifest.yml`，mpv 0.38.0的测试只提升了libmpv到0.38.0、libplacebo到6.338.2

## 其他信息

dev分支和mpv 0.38.0一起工作时打开设置会闪退

**Comment by xfangfang** [comment]
这个提交应该修复了：https://github.com/xfangfang/wiliwili/commit/b90c99efb5ff0969d18ad2cf208670adc7fa11f1

可以在这里下载：https://github.com/xfangfang/wiliwili/actions/runs/8743077443

**Comment by LTSlw** [comment]
好快的修，测试可以使用了

libmpv的url： `https://github.com/mpv-player/mpv/archive/refs/tags/v0.38.0.tar.gz`
sha256：`86d9ef40b6058732f67b46d0bbda24a074fae860b3eaae05bab3145041303066`

libplacebo的tag：`v6.338.2`
commit：`64c1954570f1cd57f8570a57e51fb0249b57bb90`

如果`.flatpak-manifest.yml`需要提升mpv版本，这些信息应该有所帮助

可以关闭issue了，非常感谢
