### ISSUE TITLE
尝试编译linux版本，42%报错‘glfwJoystickIsGamepad’ was not declared

### ISSUE THREAD

**Issue by kero990** [xfangfang/wiliwili#32]
编译环境：debian10，编译版本：linux版

> [ 43%] Building CXX object library/CMakeFiles/borealis.dir/borealis/library/lib/platforms/glfw/glfw_input.cpp.o
> /root/wiliwili/library/borealis/library/lib/platforms/glfw/glfw_input.cpp: In function ‘void brls::glfwJoystickCallback(int, int)’:
> /root/wiliwili/library/borealis/library/lib/platforms/glfw/glfw_input.cpp:84:13: error: ‘glfwJoystickIsGamepad’ was not declared in this scope
>          if (glfwJoystickIsGamepad(jid))
>              ^~~~~~~~~~~~~~~~~~~~~
> /root/wiliwili/library/borealis/library/lib/platforms/glfw/glfw_input.cpp:84:13: note: suggested alternative: ‘glfwJoystickCallback’
>          if (glfwJoystickIsGamepad(jid))
>              ^~~~~~~~~~~~~~~~~~~~~
>              glfwJoystickCallback
> /root/wiliwili/library/borealis/library/lib/platforms/glfw/glfw_input.cpp:86:71: error: ‘glfwGetGamepadName’ was not declared in this scope
>              Logger::info("glfw: joystick {} is gamepad: \"{}\"", jid, glfwGetGamepadName(jid));
>                                                                        ^~~~~~~~~~~~~~~~~~
> /root/wiliwili/library/borealis/library/lib/platforms/glfw/glfw_input.cpp:86:71: note: suggested alternative: ‘glfwGetGammaRamp’
>              Logger::info("glfw: joystick {} is gamepad: \"{}\"", jid, glfwGetGamepadName(jid));
>                                                                        ^~~~~~~~~~~~~~~~~~
>                                                                        glfwGetGammaRamp
> /root/wiliwili/library/borealis/library/lib/platforms/glfw/glfw_input.cpp: In constructor ‘brls::GLFWInputManager::GLFWInputManager(GLFWwindow*)’:
> /root/wiliwili/library/borealis/library/lib/platforms/glfw/glfw_input.cpp:156:13: error: ‘glfwJoystickIsGamepad’ was not declared in this scope
>          if (glfwJoystickIsGamepad(i))
>              ^~~~~~~~~~~~~~~~~~~~~
> /root/wiliwili/library/borealis/library/lib/platforms/glfw/glfw_input.cpp:156:13: note: suggested alternative: ‘glfwJoystickCallback’
>          if (glfwJoystickIsGamepad(i))
>              ^~~~~~~~~~~~~~~~~~~~~
>              glfwJoystickCallback
> /root/wiliwili/library/borealis/library/lib/platforms/glfw/glfw_input.cpp:159:69: error: ‘glfwGetGamepadName’ was not declared in this scope
>              Logger::info("glfw: joystick {} is gamepad: \"{}\"", i, glfwGetGamepadName(i));
>                                                                      ^~~~~~~~~~~~~~~~~~
> /root/wiliwili/library/borealis/library/lib/platforms/glfw/glfw_input.cpp:159:69: note: suggested alternative: ‘glfwGetGammaRamp’
>              Logger::info("glfw: joystick {} is gamepad: \"{}\"", i, glfwGetGamepadName(i));
>                                                                      ^~~~~~~~~~~~~~~~~~
>                                                                      glfwGetGammaRamp
> /root/wiliwili/library/borealis/library/lib/platforms/glfw/glfw_input.cpp: In member function ‘virtual void brls::GLFWInputManager::updateControllerState(brls::ControllerState*, int)’:
> /root/wiliwili/library/borealis/library/lib/platforms/glfw/glfw_input.cpp:207:5: error: ‘GLFWgamepadstate’ was not declared in this scope
>      GLFWgamepadstate glfwState = {};
>      ^~~~~~~~~~~~~~~~
> /root/wiliwili/library/borealis/library/lib/platforms/glfw/glfw_input.cpp:207:5: note: suggested alternative: ‘GLFWgammaramp’
>      GLFWgamepadstate glfwState = {};
>      ^~~~~~~~~~~~~~~~
>      GLFWgammaramp
> /root/wiliwili/library/borealis/library/lib/platforms/glfw/glfw_input.cpp:208:38: error: ‘glfwState’ was not declared in this scope
>      glfwGetGamepadState(controller, &glfwState);
>                                       ^~~~~~~~~
> /root/wiliwili/library/borealis/library/lib/platforms/glfw/glfw_input.cpp:208:38: note: suggested alternative: ‘KeyState’
>      glfwGetGamepadState(controller, &glfwState);
>                                       ^~~~~~~~~
>                                       KeyState
> /root/wiliwili/library/borealis/library/lib/platforms/glfw/glfw_input.cpp:208:5: error: ‘glfwGetGamepadState’ was not declared in this scope
>      glfwGetGamepadState(controller, &glfwState);
>      ^~~~~~~~~~~~~~~~~~~
> /root/wiliwili/library/borealis/library/lib/platforms/glfw/glfw_input.cpp:208:5: note: suggested alternative: ‘glfwGetGammaRamp’
>      glfwGetGamepadState(controller, &glfwState);
>      ^~~~~~~~~~~~~~~~~~~
>      glfwGetGammaRamp
> /root/wiliwili/library/borealis/library/lib/platforms/glfw/glfw_input.cpp:223:48: error: ‘GLFW_GAMEPAD_AXIS_LEFT_TRIGGER’ was not declared in this scope
>      state->buttons[BUTTON_LT] = glfwState.axes[GLFW_GAMEPAD_AXIS_LEFT_TRIGGER] > 0.1f;
>                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /root/wiliwili/library/borealis/library/lib/platforms/glfw/glfw_input.cpp:223:48: note: suggested alternative: ‘GLFW_GAMEPAD_AXIS_MAX’
>      state->buttons[BUTTON_LT] = glfwState.axes[GLFW_GAMEPAD_AXIS_LEFT_TRIGGER] > 0.1f;
>                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>                                                 GLFW_GAMEPAD_AXIS_MAX
> /root/wiliwili/library/borealis/library/lib/platforms/glfw/glfw_input.cpp:224:48: error: ‘GLFW_GAMEPAD_AXIS_RIGHT_TRIGGER’ was not declared in this scope
>      state->buttons[BUTTON_RT] = glfwState.axes[GLFW_GAMEPAD_AXIS_RIGHT_TRIGGER] > 0.1f;
>                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /root/wiliwili/library/borealis/library/lib/platforms/glfw/glfw_input.cpp:224:48: note: suggested alternative: ‘GLFW_GAMEPAD_AXIS_MAX’
>      state->buttons[BUTTON_RT] = glfwState.axes[GLFW_GAMEPAD_AXIS_RIGHT_TRIGGER] > 0.1f;
>                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>                                                 GLFW_GAMEPAD_AXIS_MAX
> /root/wiliwili/library/borealis/library/lib/platforms/glfw/glfw_input.cpp:226:55: error: ‘GLFW_GAMEPAD_AXIS_LEFT_Y’ was not declared in this scope
>      state->buttons[BUTTON_NAV_UP]    = glfwState.axes[GLFW_GAMEPAD_AXIS_LEFT_Y] < -0.5f || state->buttons[BUTTON_UP];
>                                                        ^~~~~~~~~~~~~~~~~~~~~~~~
> /root/wiliwili/library/borealis/library/lib/platforms/glfw/glfw_input.cpp:226:55: note: suggested alternative: ‘GLFW_GAMEPAD_AXIS_MAX’
>      state->buttons[BUTTON_NAV_UP]    = glfwState.axes[GLFW_GAMEPAD_AXIS_LEFT_Y] < -0.5f || state->buttons[BUTTON_UP];
>                                                        ^~~~~~~~~~~~~~~~~~~~~~~~
>                                                        GLFW_GAMEPAD_AXIS_MAX
> /root/wiliwili/library/borealis/library/lib/platforms/glfw/glfw_input.cpp:227:55: error: ‘GLFW_GAMEPAD_AXIS_LEFT_X’ was not declared in this scope
>      state->buttons[BUTTON_NAV_RIGHT] = glfwState.axes[GLFW_GAMEPAD_AXIS_LEFT_X] > 0.5f || state->buttons[BUTTON_RIGHT];
>                                                        ^~~~~~~~~~~~~~~~~~~~~~~~
> /root/wiliwili/library/borealis/library/lib/platforms/glfw/glfw_input.cpp:227:55: note: suggested alternative: ‘GLFW_GAMEPAD_AXIS_MAX’
>      state->buttons[BUTTON_NAV_RIGHT] = glfwState.axes[GLFW_GAMEPAD_AXIS_LEFT_X] > 0.5f || state->buttons[BUTTON_RIGHT];
>                                                        ^~~~~~~~~~~~~~~~~~~~~~~~
>                                                        GLFW_GAMEPAD_AXIS_MAX
> make[3]: *** [library/CMakeFiles/borealis.dir/build.make:1028：library/CMakeFiles/borealis.dir/borealis/library/lib/platforms/glfw/glfw_input.cpp.o] 错误 1
> make[3]: 离开目录“/root/wiliwili/build”
> make[2]: *** [CMakeFiles/Makefile2:511：library/CMakeFiles/borealis.dir/all] 错误 2
> make[2]: 离开目录“/root/wiliwili/build”
> make[1]: *** [CMakeFiles/Makefile2:413：CMakeFiles/wiliwili.dir/rule] 错误 2
> make[1]: 离开目录“/root/wiliwili/build”
> make: *** [Makefile:189：wiliwili] 错误 2
> make: 离开目录“/root/wiliwili/build”

**Comment by xfangfang** [comment]
@kero990 

readme 构建指令有指出，需要glfw3.3，我猜你那边的版本肯定不是3.3

**Comment by kero990** [comment]
> @kero990
> 
> readme 构建指令有指出，需要glfw3.3，我猜你那边的版本肯定不是3.3

啊没看到那行字，我的版本是3.2.1。装了3.3.2之后继续在58%报错

> [ 58%] Building CXX object _deps/cpr-build/cpr/CMakeFiles/cpr.dir/multiperform.cpp.o
> /root/wiliwili/build/_deps/cpr-src/cpr/multiperform.cpp: In member function ‘void cpr::MultiPerform::DoMultiPerform()’:
> /root/wiliwili/build/_deps/cpr-src/cpr/multiperform.cpp:79:26: error: ‘curl_multi_poll’ was not declared in this scope
>              error_code = curl_multi_poll(multicurl_->handle, nullptr, 0, timeout_ms, nullptr);
>                           ^~~~~~~~~~~~~~~
> /root/wiliwili/build/_deps/cpr-src/cpr/multiperform.cpp:79:26: note: suggested alternative: ‘curl_multi_wait’
>              error_code = curl_multi_poll(multicurl_->handle, nullptr, 0, timeout_ms, nullptr);
>                           ^~~~~~~~~~~~~~~
>                           curl_multi_wait

**Comment by xfangfang** [comment]
> curl_multi_poll() was introduced in 7.66.0.

这个问题应该是你的curl版本太低了

**Comment by kero990** [comment]
终于编译成功了，但是这个程序文件足足有135M大小，这不对吧？这是哪里有问题吗？还是全部内置静态库啊？

**Comment by xfangfang** [comment]
emm... c或者c++编译出来都是这样的，默认是带调试信息的所以比较大。

可以在cmake那条指令里添加参数，来取消掉调试信息： `-DCMAKE_BUILD_TYPE=Release`

或者用其他指令删除调试信息：`strip wiliwili`

**Comment by kero990** [comment]
好家伙一下剩8.8m了，离谱
用起来感觉不错，不过有部分文字显示不出来，比如设置俩字是俩带x的方块。
而且，好像是没有硬解是吧？因为官方那个electron的就没硬解，我说试试这个。。。。。

**Comment by xfangfang** [comment]
部分图标显示不出来，在readme的 `开发` 一节中有写。

应该是有硬解的，如果认为没有硬解可以将 `mpv_core.cpp` 中 ` mpv_set_option_string(mpv, "msg-level", "all=no");` 改成 
`mpv_set_option_string(mpv, "msg-level", "all=v");` 然后看log怎么说

**Comment by kero990** [comment]
linux我水平一般，mpv，vlc播放器我会看是不是硬解，你这个我不知道咋看硬解软解，播普通视频好像没有明显的CPU波动。

**Comment by xfangfang** [comment]
有没有硬解要看log

**Comment by xfangfang** [comment]
比如我在mac上能看到这两行log：

```
[vd] Looking at hwdec h264-videotoolbox...
[vd] Trying hardware decoding via h264-videotoolbox.
```

**Comment by kero990** [comment]
不知道怎么看log，log在哪？
我从终端运行，只能看到少量信息。

> 22:50:46.707[ERROR] "switch" font couldn't be located (searched at "./resources/font/switch_icons.ttf")
> 22:50:48.862[ERROR] check update failed: 0  [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal
> mesa: for the -simplifycfg-sink-common option: may only occur zero or one times!
> mesa: for the -global-isel-abort option: may only occur zero or one times!
> 22:51:46.662[ERROR] cellHeightCache.size() cannot be zero in flow mode 0 0
> 22:51:46.662[ERROR] cellHeightCache.size() cannot be zero in flow mode 0 0

**Comment by xfangfang** [comment]
> 部分图标显示不出来，在readme的 `开发` 一节中有写。
> 
> 应该是有硬解的，如果认为没有硬解可以将 `mpv_core.cpp` 中 ` mpv_set_option_string(mpv, "msg-level", "all=no");` 改成 `mpv_set_option_string(mpv, "msg-level", "all=v");` 然后看log怎么说

@kero990 您看见我前面发的内容了吗

**Comment by xfangfang** [comment]
@kero990 还有任何更新吗？没有了的话可以关闭这个issue了

**Comment by kero990** [comment]
没有了，打扰，非常感谢
