### ISSUE TITLE
请问播放倍速调整是否可以锁定或者记忆。倍速页面增加自定义档位。

### ISSUE THREAD

**Issue by ghost** [xfangfang/wiliwili#325]
请问播放倍速调整是否可以锁定或者记忆
锁定：配置给预设值
记忆：记住之前的播放倍速

2x~3x~4x
中间档位没有粒度，习惯2.25或者2.65倍的人会感觉不舒适，单独增加选项会导致选单才太长，保留0.5x,1x,2x增加3个可配置档位，这样可以保持倍速菜单不用滚动就能一次点击完成选择。

**Comment by xfangfang** [comment]
https://github.com/xfangfang/wiliwili/discussions/47

按键 P

**Comment by xfangfang** [comment]
抱歉刚才不小心给关了，欢迎提交 PR，如果有自定义倍速功能的话确实会好一些，现在的倍速列表已经很长了。

这里是倍速功能的历史讨论：https://github.com/xfangfang/wiliwili/discussions/293

修改的方式：https://github.com/xfangfang/wiliwili/commit/3d92b91cb7b1cc4c6c59fe573618e8dc47cf57fd

我感觉如果有特殊需求的话，fork代码然后直接改也还挺方便的，有github action 也不需要本地配环境。

**Comment by xfangfang** [comment]
如果要做的话，我感觉这个功能加在配置文件里即可（有特殊需求的朋友可以手动改配置来自由调整），似乎这个需求不是那么必须（毕竟官方提供的倍速选项更少）。

这样实现起来也容易，用户界面也相对简洁。

**Comment by ghost** [comment]
> 修改的方式：[3d92b91](https://github.com/xfangfang/wiliwili/commit/3d92b91cb7b1cc4c6c59fe573618e8dc47cf57fd)
> 我感觉如果有特殊需求的话，fork代码然后直接改也还挺方便的，有github action 也不需要本地配环境。

github action 等周末看一下怎么用，如果vscode甚至notepad2这种轻量级的就能改就方便很多

>如果要做的话，我感觉这个功能加在配置文件里即可（有特殊需求的朋友可以手动改配置来自由调整），似乎这个需求不是那么必须（毕竟官方提供的倍速选项更少）。
这样实现起来也容易，用户界面也相对简洁。

长期看还是把允许用户干预的配置选项单拎出来更加省事。测试版新增了pdb文件，没有合适的编辑器还是打不开，不想写ui又能快速配置，相关内容明文存在xml里就很方便自己折腾了。不论掌机pc或者手机有手就能改。

**Comment by xfangfang** [comment]
直接 fork 项目，仓库设置里开启github action，然后直接在网页上按照前面的提交来修改，等一会就自动构建好了。

**Comment by dragonflylee** [comment]
> > 修改的方式：[3d92b91](https://github.com/xfangfang/wiliwili/commit/3d92b91cb7b1cc4c6c59fe573618e8dc47cf57fd)
> > 我感觉如果有特殊需求的话，fork代码然后直接改也还挺方便的，有github action 也不需要本地配环境。
> 
> github action 等周末看一下怎么用，如果vscode甚至notepad2这种轻量级的就能改就方便很多
> 
> > 如果要做的话，我感觉这个功能加在配置文件里即可（有特殊需求的朋友可以手动改配置来自由调整），似乎这个需求不是那么必须（毕竟官方提供的倍速选项更少）。
> > 这样实现起来也容易，用户界面也相对简洁。
> 
> 长期看还是把允许用户干预的配置选项单拎出来更加省事。测试版新增了pdb文件，没有合适的编辑器还是打不开，不想写ui又能快速配置，相关内容明文存在xml里就很方便自己折腾了。不论掌机pc或者手机有手就能改。

pdb 文件用于调试windows下的崩溃问题 与配置无关
