### ISSUE TITLE
点赞投币收藏按钮逻辑优化：一键三连/单次点击收藏到默认

### ISSUE THREAD

**Issue by ghost** [xfangfang/wiliwili#326]
===简单适配===
和pipe类似，收藏按钮单次点击即收藏到默认收藏夹，再次点击弹出当前【选择收藏夹】菜单。
===进阶功能===
长按功能可能代码量比较多，用的人也不多
一键三连
长按/点击/双击/拖动响应不同逻辑，这样收藏上按住A和方向键就可以响应8个不同的收藏夹

**Comment by ghost** [comment]
一键三连 [相关串](https://github.com/xfangfang/wiliwili/issues/6)

**Comment by xfangfang** [comment]
这个应用的操作逻辑要同时考虑到鼠标键盘手柄和触屏，有些想法是没办法落地的，比如“点按加入收藏，长按选择具体的收藏夹” 这在手机和平板上是默认操作，但是如果有用户使用鼠标可能就想不到可以长按（一般的PC应用不会设计鼠标长按），所以这种情况就只能迁就鼠标用户，明明白白地弹出一个窗口，以实现所有用户都能无障碍地使用某个功能。（但我确实感觉这个可以加个配置项来让用户决定使用哪种逻辑）

有一些简单的适配方式确实能保证实现部分用户的需求，但是我认为对于大多数用户来说还是有学习的成本的，如果一个功能需要一些文字来解释，那么我认为这个功能最好还是放在配置文件里让小部分有需求的朋友来自己配置，虽然对大家来说可能操作上会略显复杂，但是至少大家都能第一时间明白该怎么操作（用过一些操作复杂又很难从UI上看懂该怎么使用又或是菜单很多但是三言两语也不明白具体是什么功能的应用，我希望 wiliwili 不是其中一员，但不得不承认确实有一部分设置项不太容易被理解，这些内容未来也需要一点点改进）。

有些功能即使可以实现，也有实现的理由，但是因为实现起来比较复杂目前也只能接受PR，比如长按一键三连，我甚至在本地也有写到一半的代码，但是三连的动画绘制起来比较复杂，wiliwili用到的UI库画动画写起来相对费劲，我感觉暂时没必要在这上花太多时间。

---

说回收藏，目前有一个隐藏的快捷键可以让收藏过程稍微轻松一些，在选好收藏夹之后 按手柄右侧功能键（PC上是F2）可以快速保存。
