### ISSUE TITLE
win无法播放视频

### ISSUE THREAD

**Issue by zxk2099** [xfangfang/wiliwili#327]
win10专业版1909，18363.592，播放任意一个视频都闪退，最新版1.4.0。
1.3.0没事，下载最新版后直接将willwill.exe替换原目录中的文件，打开后所有视频直播点进去都闪退

**Comment by dragonflylee** [comment]
请将 `wiliwili.exe` 所在目录里的 `libmpv-2.dll` 删掉

**Comment by zxk2099** [comment]
> 请将 `wiliwili.exe` 所在目录里的 `libmpv-2.dll` 删掉

感谢！问题解决！

**Comment by xfangfang** [comment]
每个版本都是独立的，不需要替换覆盖的。
