### ISSUE TITLE
bug反馈：关闭电视模式搜索页时默认搜索栏本文缺失

### ISSUE THREAD

**Issue by ghost** [xfangfang/wiliwili#328]
![image](https://github.com/xfangfang/wiliwili/assets/29087287/f144d683-1a55-4b73-8144-e933c9598739)
![image](https://github.com/xfangfang/wiliwili/assets/29087287/d566da7f-c189-4666-a593-45a40f59025d)
![image](https://github.com/xfangfang/wiliwili/assets/29087287/0c9a0466-a818-4f45-a12c-d2cbdbe0bc09)

搜索条这里默认载入上次搜索
或者和官方一样弄个猜你喜欢

**Comment by xfangfang** [comment]
可以展示一下详细的步骤，是如何触发这一页？（注意用最新的dev或者release版本）

**Comment by ghost** [comment]
===故障复现=====
![image](https://github.com/xfangfang/wiliwili/assets/29087287/8507c847-3eef-4a01-b808-8cacbd1ecc60)
![image](https://github.com/xfangfang/wiliwili/assets/29087287/39607368-9aa0-45ac-8cb5-fc1005e07ed9)
![image](https://github.com/xfangfang/wiliwili/assets/29087287/f42ef202-abb6-4989-8ee1-4b3727525086)
![image](https://github.com/xfangfang/wiliwili/assets/29087287/eec70b85-b2c1-45d8-96e7-c1ffc20f7e18)
![image](https://github.com/xfangfang/wiliwili/assets/29087287/8e9e8b96-2cee-4a8c-bfe9-fe8700cc711d)
版本1.4.0（d3d11）





===修正提议===
![image](https://github.com/xfangfang/wiliwili/assets/29087287/f844d305-9660-4347-b798-29acea482d0b)

**Comment by xfangfang** [comment]
感谢详细截图反馈，我可能会倾向于在什么也不填的情况发生时取消跳转到搜索页的动作，正常来说当输入框弹出来的时候意味着程序需要用户进行输入。

**Comment by ghost** [comment]
补充两种设想
![image](https://github.com/xfangfang/wiliwili/assets/29087287/a7e8ae6d-3b19-49e1-8d6f-7a1bc9467ec5)
增加快捷面板，展示上三次搜索，就能2次点击完成操作


![image](https://github.com/xfangfang/wiliwili/assets/29087287/3d0922fc-7725-4d2a-9ae0-728ef0f48386)
留空以后点确定直接跳转历史页，默认光标在最后一次搜索结果上。这样只用连续按 yaa 就能搜索成功


感觉还不成熟，先提出来，看后面小伙伴有没有其他想法

**Comment by xfangfang** [comment]
最新测试版在搜索空白内容时会直接忽视。
