### ISSUE TITLE
直播界面轮播视频时不断弹出停播对话框

### ISSUE THREAD

**Issue by 4fuu** [xfangfang/wiliwili#329]
hi 又见面了，我是之前的maye174，由于一些原因我改了名字，然后也是鸽了好久的直播界面。

我这次是发现了一个bug，直播界面的对话框如果一直不点，会因为反复刷新重复申请内存显示，导致内存泄露

![image](https://github.com/xfangfang/wiliwili/assets/96584640/2890106d-4d5d-409c-9961-4a21f6cad554)

**Comment by xfangfang** [comment]
在什么情况下会反复刷新？

**Comment by 4fuu** [comment]
直播看着看着主播关播了，会弹出来未开播的那个对话框

**Comment by xfangfang** [comment]
哦哦，我还是倾向于解决这个反复刷新的问题，这也可以避免在这种情况下进行不必要的网络请求。

只是重复添加的话，应该不存在内存泄露吧。

**Comment by xfangfang** [comment]
顺便一提，那个PR在有对话框显示的情况下关闭对话框会导致应用崩溃（至少macOS下会崩溃）。是不需要手动删除 dialog的，对话框关闭的时候会自动清理。

**Comment by 4fuu** [comment]
> 哦哦，我还是倾向于解决这个反复刷新的问题，这也可以避免在这种情况下进行不必要的网络请求。
> 
> 只是重复添加的话，应该不存在内存泄露吧。

> 顺便一提，那个PR在有对话框显示的情况下关闭对话框会导致应用崩溃（至少macOS下会崩溃）。是不需要手动删除 dialog的，对话框关闭的时候会自动清理。

哦哦，我并不知道他会自动清理。我触发这个bug的时候已经3000mb+的内存占用了（睡了一觉）然后软件也卡死了。我修改了
