### ISSUE TITLE
Ubuntu20端无法播放

### ISSUE THREAD

**Issue by youwyu** [xfangfang/wiliwili#33]
`cmake -B build -DPLATFORM_DESKTOP=ON -DINSTALL=ON -DCMAKE_BUILD_TYPE=Release

make -C build -j$(nproc)

sudo make install

sudo xargs -a build/install_manifest.txt rm`

编译和install都正常，弹幕和放大键正常，点击播放无反应，乱按键盘触发播放后不播放。
![wili-bug](https://user-images.githubusercontent.com/60796213/205437073-56292789-f097-4449-8a30-49cfcd72f88c.png)

**Comment by xfangfang** [comment]
命令行输入wiliwili查看log，如果是所有视频都有问题，那很可能是你的dns的问题

**Comment by xfangfang** [comment]
@hannibal051 关于这个问题还有任何更新吗？比如解决了没有，怎么解决的。

**Comment by youwyu** [comment]
蟹蟹博主。目前解决方法是把翻墙软件全部关掉。

**Comment by xfangfang** [comment]
> 蟹蟹博主。目前解决方法是把翻墙软件全部关掉。

好的，那应该就是播放链接使用的域名被错误识别成境外域名了，先关闭这个issue了。
