### ISSUE TITLE
windows版几个优化建议

### ISSUE THREAD

**Issue by uiiang** [xfangfang/wiliwili#332]
windows版
搜索结果没有显示视频时长
搜索流程建议在主界面点击搜索，进入搜索界面后，直接将焦点定位在输入框上。现在还需要再点一下输入框才能弹出真正的输入框才能输入文字
视频播放界面点击up主头像，建议进入up主的视频列表，而不是执行关注/取消关注的操作
窗口置顶功能建议只在小窗播放时生效，而不是在任何界面都生效

**Comment by xfangfang** [comment]
1. 测试版添加了搜索结果的视频时长
2. 可以在设置中把“电视风格搜索页”关闭，默认的设置是方便手柄用户使用关键词来搜索的。
3. UP主视频列表可以在右侧直接查看，未来会做主页，这是重复的issue：https://github.com/xfangfang/wiliwili/issues/64
4. 测试版添加了新的置顶选项可以在窗口尺寸较小时自动置顶，相关内容见：https://github.com/xfangfang/wiliwili/wiki#自定义自动窗口置顶的触发范围
