### ISSUE TITLE
[windows][1.4.0] 启动闪退

### ISSUE THREAD

**Issue by rtrobin** [xfangfang/wiliwili#338]
windows 10，x64，1.4.0 启动闪退，1.3.0 可以正常使用。附上 dump 文件。
[crash-20240505-000727.dmp](https://github.com/xfangfang/wiliwili/files/15210288/crash-20240505-000727.dmp)

**Comment by Yuuki-Rin** [comment]
试试x86的
我用x86-64也闪退

**Comment by xfangfang** [comment]
@rtrobin @Yuuki-Rin 抱歉造成困扰，正常来说 x86 x86-64 不应该有区别，可以尝试运行 

```shell
wiliwili.exe -d -t -o wiliwili.log
```

并把log上传到这里。

**Comment by rtrobin** [comment]
@xfangfang 看起来是新版本开始使用 d3d11，我电脑太古老初始化就失败了？
[wiliwili.log](https://github.com/xfangfang/wiliwili/files/15250142/wiliwili.log)
[wiliwili_gpu.log](https://github.com/xfangfang/wiliwili/files/15250144/wiliwili_gpu.log)
[wiliwili_1.3.0.log](https://github.com/xfangfang/wiliwili/files/15250155/wiliwili_1.3.0.log)

**Comment by xfangfang** [comment]
可以发一下具体的显卡型号。

与此同时也可以使用 OpenGL 版：https://nightly.link/xfangfang/wiliwili/workflows/build.yaml/dev

顺便一问，不带gpu的这个log是怎么收集来的？不插显卡？

**Comment by rtrobin** [comment]
古老的笔记本，cpu: i7-640m, gpu: nv GT 425m，那个时代的笔记本可以选择用集显或独显
但是按说我这个显卡是支持一定程度的 d3d11 的，我用 LAV filter 是可以设置独显用 d3d11 硬解的
OpenGL 版可以运行。log在附件
[wiliwili_1.4.0.dev.gpu.log](https://github.com/xfangfang/wiliwili/files/15250420/wiliwili_1.4.0.dev.gpu.log)
[wiliwili_1.4.0.dev.log](https://github.com/xfangfang/wiliwili/files/15250421/wiliwili_1.4.0.dev.log)



> [](https://nightly.link/xfangfang/wiliwili/workflows/build.yaml/dev)
> 
> 顺便一问，不带gpu的这个log是怎么收集来的？不插显卡？

**Comment by rtrobin** [comment]
> 与此同时也可以使用 OpenGL 版：https://nightly.link/xfangfang/wiliwili/workflows/build.yaml/dev

从这里下载的 nightly 的 dx 版本，使用集显直接crash，和1.4.0一致；使用独显程序 hang 住，应该也是 d3d11 初始化 hang 了

**Comment by xfangfang** [comment]
发布之后没做什么修改，现在测试版和正式版区别不是特别大。

正常来说硬件只要支持 d3d9 就能用起来，可以看看更新显卡驱动（如果有的话）有没有帮助。如果还是不行我暂时也没有什么解决办法，这个可能需要有对应的硬件才能方便排查。

可以试着跑一下这个项目的demo，如果这个项目能正常运行起来，wiliwili 应该就能跑起来：https://github.com/cmaughan/nanovg

---

D3D11 版我测试显卡占用能比OpenGL最大降低30%左右，最好还是能运行起来，对老电脑来说效果会更好。

**Comment by dragonflylee** [comment]
> @xfangfang 看起来是新版本开始使用 d3d11，我电脑太古老初始化就失败了？ [wiliwili.log](https://github.com/xfangfang/wiliwili/files/15250142/wiliwili.log) [wiliwili_gpu.log](https://github.com/xfangfang/wiliwili/files/15250144/wiliwili_gpu.log) [wiliwili_1.3.0.log](https://github.com/xfangfang/wiliwili/files/15250155/wiliwili_1.3.0.log)

建议收集log时把 wiliwili.pdb 和 https://cn.dll-files.com/dbghelp.dll.html 一并放在 wiliwili.exe 所在目录后运行，这样日志中就会打印详细的堆栈信息

**Comment by xfangfang** [comment]
因为太长时间没有反馈先关闭掉这个问题啦。

**Comment by rtrobin** [comment]
> 因为太长时间没有反馈先关闭掉这个问题啦。

关闭吧，看起来是我老电脑的问题。我停留在使用1.3.0好了

**Comment by xfangfang** [comment]
@rtrobin 没必要停留在老版本的，可以一直从下面的链接下载到Windows的OpenGL版：
正式版：https://nightly.link/xfangfang/wiliwili/workflows/build.yaml/yoga
测试版：https://nightly.link/xfangfang/wiliwili/workflows/build.yaml/dev

**Comment by rtrobin** [comment]
> @rtrobin 没必要停留在老版本的，可以一直从下面的链接下载到Windows的OpenGL版： 正式版：https://nightly.link/xfangfang/wiliwili/workflows/build.yaml/yoga 测试版：https://nightly.link/xfangfang/wiliwili/workflows/build.yaml/dev

我看到有1.4.1的版本了，试了下弹窗 d3d11 init 报错了。这些 windows OpenGL 版本，能否也放在正式 release 的 package list 中

**Comment by dragonflylee** [comment]
@rtrobin 有空能帮忙测一下这个版本能不能正常启动 https://nightly.link/dragonflylee/wiliwili/actions/runs/10217409251/wiliwili-Windows-ad4fa9a-d3d-x86_64.zip

**Comment by rtrobin** [comment]
> @rtrobin 有空能帮忙测一下这个版本能不能正常启动 https://nightly.link/dragonflylee/wiliwili/actions/runs/10217409251/wiliwili-Windows-ad4fa9a-d3d-x86_64.zip

仍然是 init d3d11 failed 参数错误。
不用为我这个情况搞了，我这个老电脑应该是少数情况

**Comment by xfangfang** [comment]
下面是最新测试版，我在虚拟机内的windows 7 sp1上测试，d3d版本是可以正常运行的了。

win+r 输入 dxdiag 运行，可以弹出 DirectX 诊断工具，在虚拟机windows 7 sp1上测试时，DirectX 版本显示为 11。

(针对 windows 7 sp1 还需要安装 [kb2670838](https://www.catalog.update.microsoft.com/Search.aspx?q=kb2670838) 更新和 [DirectX End-User Runtime](https://www.microsoft.com/en-us/download/details.aspx?id=35) )

https://nightly.link/xfangfang/wiliwili/workflows/build.yaml/dev/wiliwili-Windows-c3ae64c-d3d-x86_64.zip

如果这个测试版 d3d 还是无法使用的话，那么以后就只能使用 OpenGL 版了（或许 d3d9 也可以实现一下，那就只能之后再说了）

**Comment by rtrobin** [comment]
> https://nightly.link/xfangfang/wiliwili/workflows/build.yaml/dev/wiliwili-Windows-c3ae64c-d3d-x86_64.zip

这个链接失效了。
dxdiag 的诊断不准，或者应该说，我这种老笔记本的显卡，支持dx11，但不是完整支持。我用 lav filters，是可以设置显卡 d3d11 的硬解的，但可能就是有些d3d11是无法完整支持的。

**Comment by xfangfang** [comment]
https://nightly.link/xfangfang/wiliwili/actions/runs/10751084915/wiliwili-Windows-2ebe90e-d3d-x86_64.zip

那有可能是只支持 dx11，但是咱们这个应用好像需要dx11.1

**Comment by dragonflylee** [comment]
https://www.intel.com/content/www/us/en/support/articles/000005524/graphics.html

根据intel的官方文档 至少需要4代酷睿的核显才会支持dx11.1

**Comment by rtrobin** [comment]
> https://nightly.link/xfangfang/wiliwili/actions/runs/10751084915/wiliwili-Windows-2ebe90e-d3d-x86_64.zip
> 
> 那有可能是只支持 dx11，但是咱们这个应用好像需要dx11.1

这个链接的也不行。不用挣扎了吧，gl 那个版本用的也挺好的

**Comment by rtrobin** [comment]
> https://www.intel.com/content/www/us/en/support/articles/000005524/graphics.html
> 
> 根据intel的官方文档 至少需要4代酷睿的核显才会支持dx11.1

我用的是笔记本上的独显 NV GT 425m。我找了个 spec 链接， @xfangfang 好像猜的对，它似乎只支持 11_0
https://www.techpowerup.com/gpu-specs/geforce-gt-425m.c1498

**Comment by dragonflylee** [comment]
实测 i5-3337u+GT610m 核显和独显都只支持到 11_0 依然可以正常启动 DX11 版本并能实现硬件解码

![image](https://github.com/user-attachments/assets/bce3e8f3-39c9-49de-bf3e-2a043f2e6da7)

![image](https://github.com/user-attachments/assets/93db6b06-6535-4f2c-a0af-e649c9900b59)


建议更新到 Win10 最新的 22h2 版本号 10.0.19045 的版本

**Comment by dragonflylee** [comment]
@rtrobin 建议发一个 dxdiag 截图，注意 Direct3D DDI 的版本支持

[wiliwili-Windows-2ebe90e-d3d-x86_64.zip](https://github.com/user-attachments/files/16918691/wiliwili-Windows-2ebe90e-d3d-x86_64.zip)

**Comment by rtrobin** [comment]
> @rtrobin 建议发一个 dxdiag 截图，注意 Direct3D DDI 的版本支持
> 
> [wiliwili-Windows-2ebe90e-d3d-x86_64.zip](https://github.com/user-attachments/files/16918691/wiliwili-Windows-2ebe90e-d3d-x86_64.zip)

我的dxdiag中，不显示独显那个tab。。
