### ISSUE TITLE
谁能提供一个windows 上的编译版本

### ISSUE THREAD

**Issue by longzekai** [xfangfang/wiliwili#34]
大佬能不能直接放一个编译好的Windows 版本啊，多谢了。

**Comment by xfangfang** [comment]
@longzekai https://github.com/xfangfang/wiliwili/releases/tag/v0.5.0

**Comment by longzekai** [comment]
> @longzekai https://github.com/xfangfang/wiliwili/releases/tag/v0.5.0
已经看到了，多谢大佬，早点休息，哈哈。
