### ISSUE TITLE
⚡这种Emoji图标在视频标题里显示☒

### ISSUE THREAD

**Issue by Nyte2016** [xfangfang/wiliwili#340]
有的UP会在视频标题里加一些Emoji图标，就像⚡这种，[wiliwili-Windows-x86_64] v1.140版本无法正常显示，显示为☒
<img width="227" alt="屏幕截图 2024-05-06 134532" src="https://github.com/xfangfang/wiliwili/assets/20374655/275223d0-3f7a-46a9-a317-f39edf347c14">
正常显示
![PixPin_2024-05-06_13-52-37](https://github.com/xfangfang/wiliwili/assets/20374655/1834fa71-4a41-484a-8fad-d2d4910f6c8e)

**Comment by xfangfang** [comment]
https://github.com/xfangfang/wiliwili/wiki#测试版更新内容
