### ISSUE TITLE
为啥播放后第一次用鼠标单击就是双击，之后就没事，然后过一会又是第一次单击变双击

### ISSUE THREAD

**Issue by zxk2099** [xfangfang/wiliwili#342]

**Comment by xfangfang** [comment]
@zxk2099 不太清楚原因，如果要反馈问题最好可以附加上一个具体的操作流程，避免我花了很多时间去琢磨最后发现是鼠标按键坏了导致的问题。

**Comment by zxk2099** [comment]
> @zxk2099 不太清楚原因，如果要反馈问题最好可以附加上一个具体的操作流程，避免我花了很多时间去琢磨最后发现是鼠标按键坏了导致的问题。

https://github.com/xfangfang/wiliwili/assets/103583307/24f4fa11-aff4-4790-9919-aaab865be695

录了个视频，正好有个点击特效软件，20s之前是鼠标点击特效，20s之后是视频

这个是滑动的

https://github.com/xfangfang/wiliwili/assets/103583307/79fb7f29-b2ae-4949-ab32-9d898755f50f

**Comment by zxk2099** [comment]
可以稳定复现的就是点进一个视频后第一次单击必定是双击的暂停效果

**Comment by xfangfang** [comment]
很有意思的现象，我刚刚用windows试了一下倒是没有这个问题，我注意的下方的 fps显示是1，所以我猜测你应该开启了 wiki中说的：“自定义帧数限制”，这个功能当时并没有完整做好，所以默认是关闭的（标注出了 不稳定功能）

考虑到这是个视频播放软件，其实播起视频来的话这个功能就没有任何作用了。

---

如果没有开启的话，那就是显示器的帧数识别错了

**Comment by zxk2099** [comment]
@xfangfang 这个吗？这个一直没改过，因为我的屏幕是60帧的，所以这个没管过。我又试了一下，切换成任何一个选项都没用
![screenshot-1715677070167](https://github.com/xfangfang/wiliwili/assets/103583307/ba9a6157-c313-493e-a2b1-a13964563bb5)
这个是配置也是0
![screenshot-1715677176322](https://github.com/xfangfang/wiliwili/assets/103583307/96866947-ca5c-498e-b62d-c0b5d900e699)
这些是其他所有设置
![1](https://github.com/xfangfang/wiliwili/assets/103583307/cf1a51e8-6fd6-4178-9d1f-616c1eba9307)
![2](https://github.com/xfangfang/wiliwili/assets/103583307/145fe07f-8990-40f6-bef8-772683debc9d)

**Comment by xfangfang** [comment]
@zxk2099 如果是 60帧的屏幕，开启了垂直同步，那不应该下面会显示 1帧呀。感觉可能是帧数识别错了，导致计算点击的时候产生了问题。

FPS计算可能和获取系统时间的方法有关，可能和系统版本有关。

所以可以反馈一下具体的系统版本和软件的版本。

如果这个系统或者电脑的某些配置有什么特殊的也可以顺便提及一下。

**Comment by zxk2099** [comment]
@xfangfang 光影精灵5，win10专业版，1909，18363.592，软件就是最新版1.4.0

**Comment by xfangfang** [comment]
@zxk2099 
应该是获取时间函数返回了错误的值导致的。
应用了这个来修复：https://github.com/libretro/RetroArch/pull/10173

希望问题会解决，可以顺便注意一下软件下方的FPS是否正确。

测试版下载链接：https://github.com/xfangfang/wiliwili/actions/runs/9696685708

**Comment by zxk2099** [comment]
@xfangfang 
确实和帧数有关，1就出现问题，60就没问题，偶尔变成1，偶尔变成60。
下载了测试版，目前是60了，也没出现这个问题了

**Comment by xfangfang** [comment]
太棒啦，那我先把这个issue关闭啦，会尽快发布一个新版本的～
