### ISSUE TITLE
[debian系统]wiliwili搜索框无法使用输入法

### ISSUE THREAD

**Issue by WangJianG584** [xfangfang/wiliwili#345]
![截图 2024-05-15 10-25-51](https://github.com/xfangfang/wiliwili/assets/21231145/01467522-f1f3-419f-b99f-61acfb2633ba)
桌面右上角没有显示输入法角标，其他软件则可以正常显示

**Comment by dragonflylee** [comment]
请问使用的 Debian 具体版本是什么 11/12 ？输入法使用的是 ibus 还是 fcitx ? 桌面使用的是 xorg 还是 wayland。
这时候有个 `neofetch` 的截图最能说明问题了

**Comment by WangJianG584** [comment]
使用是debian12，输入法用的是系统自带
![截图 2024-05-16 10-45-41](https://github.com/xfangfang/wiliwili/assets/21231145/e06e8e20-4f71-4379-82ff-7bb5cbb2e102)
![截图 2024-05-16 10-43-33](https://github.com/xfangfang/wiliwili/assets/21231145/1df372c0-c907-41d3-87b5-e5d2b6c422a6)

**Comment by WangJianG584** [comment]
![截图 2024-05-16 10-52-07](https://github.com/xfangfang/wiliwili/assets/21231145/20d67ecf-9315-4aeb-b812-c84f76a04fec)

**Comment by xfangfang** [comment]
可能和这个问题相关：https://github.com/xfangfang/wiliwili/issues/306

**Comment by dragonflylee** [comment]
[borealis_demo_xorg.zip](https://github.com/xfangfang/wiliwili/files/15330789/borealis_demo_xorg.zip)
[borealis_demo_wl.zip](https://github.com/xfangfang/wiliwili/files/15330653/borealis_demo_wl.zip)

我这边在 Debian 12 测试了 xorg 和 wayland 版本的 demo，使用 ibus-sunpinyin 都能正常输入中文

**Comment by dragonflylee** [comment]
@WangJianG584 虚拟机测试了 Debian 12 下的 flatpak 版本的 wiliwili,

输入法 `ibus-sunpinyin` 正常可用 （窗口系统为 Wayland）

![image](https://github.com/xfangfang/wiliwili/assets/6219280/87d56b01-b153-409f-a82d-be060f79b458)

**Comment by WangJianG584** [comment]
请核对我们用的是同一种输入法吗？debian在安装的时候选择简体中文，只选择gnome，默认就是这个输入法
![截图 2024-05-16 21-03-13](https://github.com/xfangfang/wiliwili/assets/21231145/c3ecae05-18f2-4216-a650-3ef0e52316d9)

**Comment by WangJianG584** [comment]
![image](https://github.com/xfangfang/wiliwili/assets/21231145/a3e86785-b8d4-4708-8475-69fa8a350a97)

**Comment by dragonflylee** [comment]
@WangJianG584 VMware下测试 `ibus-libpinyin` 也是正常的

![image](https://github.com/xfangfang/wiliwili/assets/6219280/b58fb2c1-a793-47bd-9f80-e9e170bf5063)

![image](https://github.com/xfangfang/wiliwili/assets/6219280/e106ace5-54e6-4358-af11-d393efe6a149)

**Comment by WangJianG584** [comment]
可以关闭了，搜索框可以打字
