### ISSUE TITLE
steamdeck启动wiliwili闪退

### ISSUE THREAD

**Issue by hzh98** [xfangfang/wiliwili#347]

**Comment by dragonflylee** [comment]
能提供一下终端中运行 `flatpak run cn.xfangfang.wiliwili -d` 后的运行日志吗

**Comment by xfangfang** [comment]
盲猜下载了arm版的flatpak，要不然就是下载了windows版的没配置proton。

**Comment by hzh98** [comment]
重启steamdeck后可以登录进wiliwili，但是我登录了waydroid后，再次开启wiliwili就失败了。wiliwili是从steamos桌面版商店里下载的。
deck@steamdeck ~)$ flatpak run cn.xfangfang.wiliwili -d
21:46:37.770[INFO] XDG_CURRENT_DESKTOP: KDE
21:46:37.770[INFO] CURRENT_DESKTOP: KDE 5
21:46:37.773[INFO] wiliwili v1.4.0
21:46:37.775[INFO] Current working directory: /home/deck
21:46:37.775[INFO] setting: {"home_window_state":"0,1280x720,0x0","video_quality":16}
21:46:37.775[INFO] Load config from: /home/deck/.var/app/cn.xfangfang.wiliwili/config/wiliwili/wiliwili_config.json
21:46:37.775[INFO] Load window state: 1280x720,0x0
21:46:37.775[INFO] Set app locale: zh-Hans
21:46:37.778[ERROR] GLFW 65550: Failed to detect any supported platform
21:46:37.778[ERROR] glfw: failed to initialize
21:46:37.778[INFO] Using platform GLFW
21:46:37.779[ERROR] GLFW 65550: Failed to detect any supported platform
21:46:37.780[ERROR] Fatal error: glfw: failed to initialize
terminate called after throwing an instance of 'std::logic_error'
what(): glfw: failed to initialize
(134)(deck@steamdeck ~)$

**Comment by xfangfang** [comment]
那应该问题和wiliwili就无关了，可以考虑一下是不是waydroid在开启的过程中修改了什么。
