### ISSUE TITLE
【bug反馈】请求视频地址失败

### ISSUE THREAD

**Issue by ghost** [xfangfang/wiliwili#348]
![image](https://github.com/xfangfang/wiliwili/assets/29087287/2d20a913-f4be-4f01-839e-e652e44bf0c8)

报错

`请求视频地址失败
Key: 'PlayurlArg.Cid' Error:Field validation
for 'Cid' failed on the 'min' tag
确定
`

![image](https://github.com/xfangfang/wiliwili/assets/29087287/fdf8a48d-0b48-47d8-b5fa-b3477784b719)

故障复现
搜索
10寸笔记本松下rz6
或
视频地址
https://www.bilibili.com/video/BV1ZiuHeGEPi/

猜测原因
合集或者短视频格式兼容性问题

**Comment by xfangfang** [comment]
@hinum009 感谢反馈，看起来是B站将新视频的cid调整到64位了（示例：500001549598127）

因为代码中涉及到的位置较多，可能会有遗漏，可以广泛测试看看不同的功能是否都正常（点赞 收藏 投币 评论 各种类型的视频 收藏夹等内容）

修复提交：https://github.com/xfangfang/wiliwili/commit/b553bcc6306e4c50b80db01edcfd6fde6d236e43
测试版下载：https://github.com/xfangfang/wiliwili/actions/runs/9168168451
