### ISSUE TITLE
【功能请求】评论区，能否支持从底部弹出？

### ISSUE THREAD

**Issue by ystyle** [xfangfang/wiliwili#353]
评论区，能否支持从底部弹出？弹出后可以保持半屏播放，或者小窗播放（类似pc网页版那种）
官方版本我两年提交了几次反馈也没改。。。

**Comment by xfangfang** [comment]
我没听太懂，但是现在评论区的设计我挺满意的，和ipad端那种出现在视频下方的设计来比我还是更喜欢现在的版本

我挺理解的，官方版本不会因为哪一个人的请求而更改，你可能感觉有更好的做法，但是现在的版本已经被很多人熟悉使用了，如果不是特别好的设计，我感觉任何调整都会导致很多人不满

**Comment by ystyle** [comment]
> 我没听太懂，但是现在评论区的设计我挺满意的，和ipad端那种出现在视频下方的设计来比我还是更喜欢现在的版本
> 
> 我挺理解的，官方版本不会因为哪一个人的请求而更改，你可能感觉有更好的做法，但是现在的版本已经被很多人熟悉使用了，如果不是特别好的设计，我感觉任何调整都会导致很多人不满



可以加个选项， 默认不开。 主要是大屏（我的是带鱼屏）右边弹出要纽头看，看得很累， 用分屏工具让它只占中间2k的分辨率，也是要纽过头来看，虽然幅度没那么大，但也挺累的。

或者可以向左拉评论区宽度到3/4屏也行

**Comment by xfangfang** [comment]
https://github.com/xfangfang/wiliwili/blob/1662ec48ad73f3e18dff4f203b2e1c59d15c74b2/wiliwili/source/utils/register_helper.cpp#L208


你可以修改这一行获取自己想要的宽度

**Comment by xfangfang** [comment]
我感觉当前的设计还是比较合适的，如果按你说的设计为上下分屏（上半部分是视频下半部分是评论），这个可能就是官方平板端使用的方案，我实际用起来很不舒服，我的观点是：评论看不全 浪费了很多屏幕空间。
先关闭这个issue了，在可以预见的未来一段时间都没有足够的人力来实现这个想法，不过欢迎PR
