### ISSUE TITLE
请问是否可以增加安卓版本？

### ISSUE THREAD

**Issue by jayofstella** [xfangfang/wiliwili#356]
安卓版本的推荐机制很不好，导致关注up多了以后，就看不到新的up内容了，但是wiliwili的推荐机制就没问题，希望可以在安卓上用wiliwili

**Comment by zeromake** [comment]
@jayofstella 
关于安卓的讨论已经进行过很多次了，请见：

#336
#182
#127
#98
#91
#60
#55

可以考虑其它的：
https://github.com/xiaye13579/BBLL
https://github.com/aaa1115910/bv
