### ISSUE TITLE
请问是否可以增加PS3版本？

### ISSUE THREAD

**Issue by SilentNocturne** [xfangfang/wiliwili#357]
请问是否可以增加PS3版本？我有一台ps3 2510系列，完美软解，系统是“[Rebug 4.86.1 LITE – Cobra 8.2 – Toolbox 2.03.04 – April Fools. 2020](https://web.archive.org/web/20200903224127/https://rebug.me/)”现在基本玩一些老游戏，要是能看B站就更好了

**Comment by xfangfang** [comment]
移植 wiliwili 需要opengl 2+，SDL2，ffmpeg，mpv，nanovg，curl等依赖

https://github.com/ps3dev/PSL1GHT
https://github.com/gzorin/RSXGL
https://github.com/sergiou87/SDL2_PSL1GHT
https://github.com/ps3dev/ps3libraries

简单搜索了一下，看起来像是除了 ffmpeg 和 mpv 外其他依赖都可以使用的样子。所以结论是可能出现这样的移植，但是因为我本人没有对应的设备所以没办法来验证是否有可行性。

即使我有设备，因为身体健康问题，暂时不太想在空闲时间写太多代码，欢迎大家提交PR : )
