### ISSUE TITLE
[bug] PC: Can't use X refresh on startup

### ISSUE THREAD

**Issue by yuioto** [xfangfang/wiliwili#358]
When starting wiliwili, the refresh icon button is displayed, but the "X refresh" button is not displayed.

High probability of recurrence.

The "Y search" button may not be displayed after switching windows.

This may happen again with a small chance.

Like this: 
![2024-06-12-11-27-36-713.jpg](https://github.com/xfangfang/wiliwili/assets/68138727/2502a376-1974-491f-ba65-6becd195697c)

But after clicking the refresh icon button, the "X refresh" button reappears.

Guess(X button): The PC environment and the touch screen environment are misidentified.

Description: I was using a tablet but it was not connected when wiliwili started.

This problem has been around for a while. If I remember correctly, it has been around since v1.2.0.

OS: ArchLinux

**Comment by xfangfang** [comment]
因为这个项目主要使用者都是中文用户，所以使用中文反馈问题是可以的。

y 快捷键，在首页几个页面是共享的，所以绑定在了整个首页和左侧的按钮上。

x 快捷键，是针对每个独立的页面的 刷新/切换，所以只绑定在单独的页面和页面的顶部tab，这也是提供了 刷新/切换 按钮的原因。

如果你一定需要使用快捷键来操作，可以将焦点转移到对应的顶栏。当然也可以调整代码，在首页切换到不同页面时绑定不同的页面的刷新事件到左上角的图标上，欢迎提交PR。

---

如果底栏没有按照你的想法来显示快捷键，多半是和焦点相关的问题，这种时候需要反馈具体的截图来判断是否是代码存在问题。（以我的经验，目前显示的还是比较准确的）

**Comment by xfangfang** [comment]
这个问题应该不是bug，所以我先关闭了。

欢迎实现当焦点位于左侧图标时，可以使用x快捷键相关的功能，期待你的PR。
