### ISSUE TITLE
万人血书  求ps4版kodi

### ISSUE THREAD

**Issue by TomYule** [xfangfang/wiliwili#360]
万人血书  求ps4版kodi
非常想在PS4上看4K视频; 电视机是4k分辨率  但是安卓设备不支持4k 没钱买4k机顶盒 哎
希望能有个PS4 kodi  我就可以局域网 alist看视频了 非常感谢
https://github.com/xbmc/xbmc
1/10000
有希望的在下面+1

大佬 没空  可以跟我说一下 思路  怎么做 怎么编译 我去学习
https://github.com/xfangfang/wiliwili/blob/dev/scripts/ps4/Dockerfile
怎么制作ps4  的pkg

**Comment by xfangfang** [comment]
kodi 我估计是不太好移植，我感觉一个相对容易做的移植是 jellyfin 的客户端：https://github.com/dragonflylee/switchfin

作者也是 wiliwili 的重要贡献者之一，我们两个应用使用了相同的底层UI库，参考 wiliwili 适配 ps4（在代码中搜索 PS4），估计调整一点点代码就能在 ps4上正常使用了。

编译的话我感觉直接用 wiliwili 编译用的 docker 镜像就行了，需要的依赖应该都是满足的，需要修改一下 cmake 给 switchfin 添加类似的内容来开启 ps4 的编译：
https://github.com/xfangfang/wiliwili/blob/1662ec48ad73f3e18dff4f203b2e1c59d15c74b2/CMakeLists.txt#L274-L282

---

直接做前面这些可能难度略高，可以先在本地编译这个项目来体验看看：https://github.com/xfangfang/borealis

---

如果还是感觉有难度，可以在 linux 下编译这个项目来入门：https://github.com/PacBrew/ps4-openorbis-sample

**Comment by xfangfang** [comment]
或者你可以直接安装 plex: https://pkg-zone.com/details/CUSA01850

**Comment by xfangfang** [comment]
或者你可以配置一下ps4启动linux，在linux里运行kodi（我没测试过，不过感觉比较可行）

---

反正不论哪种做法，如果只是单纯想获得一个机顶盒的替代品的话，花出去时间的价值都会大大超过一个机顶盒的价格。

**Comment by TomYule** [comment]
哦哦 我以为 kodi  可以直接编译成ps4版 适配一下 手柄就行了  UI没法移植吗

**Comment by TomYule** [comment]
> 或者你可以配置一下ps4启动linux，在linux里运行kodi（我没测试过，不过感觉比较可行）
> 
> 反正不论哪种做法，如果只是单纯想获得一个机顶盒的替代品的话，花出去时间的价值都会大大超过一个机顶盒的价格。

Linux 装kodi 会冲突桌面程序 导致 进去就是kodi    我在ps4 Linux 装过 最后卸载了

**Comment by dragonflylee** [comment]
PS4目前有一个 https://github.com/Cpasjuste/pplay 可以用

**Comment by xfangfang** [comment]
编译一下就直接能运行到其他系统上，是最理想的状态。现实应该很少会有这种情况发生，尤其是gui应用，可能性就更低了。

而且kodi这种级别的项目依赖了大量的第三方库，表面移植一个kodi，其实还要移植他依赖的那么多第三方库，这里面完全不遇到任何问题的可能性太低了。

---

kodi在linux下应该有不同的安装方式，不一定替代桌面环境的。

**Comment by dragonflylee** [comment]
https://emby.media/emby-ps4.html

emby 也是有 PS4 版的

**Comment by TomYule** [comment]
> https://emby.media/emby-ps4.html
> 
> emby 也是有 PS4 版的


大佬很厉害 
但是  可能您没有体会到alist 的强大  我在家软路由上 可以装alist   阿里网盘保存的电影 在电视机上kodi秒看 而且不卡  这个有多香
唯一的遗憾电视安卓软件不支持4k  电视是4k 哎
https://alist.nn.ci/zh/

**Comment by TomYule** [comment]
> PS4目前有一个 https://github.com/Cpasjuste/pplay 可以用

我看了一下 没有smb 共享的

**Comment by dragonflylee** [comment]
@TomYule 基于 alist 的 小雅我也在用啊，电视端可以用 [TVBox](http://tvbox.clbug.com/) 来播放，

**Comment by TomYule** [comment]
> @TomYule 基于 alist 的 小雅我也在用啊，电视端可以用 [TVBox](http://tvbox.clbug.com/) 来播放，

感谢大佬介绍
这个软件果然强大 但是估计不能4K  我电视机的问题

**Comment by dragonflylee** [comment]
> > PS4目前有一个 https://github.com/Cpasjuste/pplay 可以用
> 
> 我看了一下 没有smb 共享的

可以使用 [rclone](https://rclone.org/commands/rclone_serve_ftp/)  把 webdav 转成 ftp 协议
