### ISSUE TITLE
linux flatpak版wiliwili进入后无法连接网络，关闭TLS后依旧无法联网

### ISSUE THREAD

**Issue by Merlin23-3** [xfangfang/wiliwili#363]
![image](https://github.com/xfangfang/wiliwili/assets/121683056/fb243b57-f8a0-4bde-9b1f-44706d2e7c07)

**Comment by xfangfang** [comment]
1.
https://github.com/xfangfang/wiliwili?tab=readme-ov-file#反馈问题前要做的事

> 网络相关的问题附加 网络诊断截图，入口：应用内设置/实用工具/网络诊断

2. 命令行运行一下，发一下log

**Comment by xfangfang** [comment]
因为太长时间没有反馈，先关闭这个issue了。（这个问题没有办法在我本地复现出来）
