### ISSUE TITLE
[BUG] “应援团”类消息显示不正常

### ISSUE THREAD

**Issue by Puqns67** [xfangfang/wiliwili#371]
应援团的头像与消息名显示不正常，点进去后其中消息的发送者同样显示不正常（应该显示在左侧并且正确显示头像）。

考虑到此功能在如今已经十分边缘化，最简单的解决方法也许是直接屏蔽此类消息？

wiliwili v1.4.1 中的显示状况：
![image](https://github.com/xfangfang/wiliwili/assets/57405236/af6a07b2-728c-41a3-962c-5e1386c3fbe6)
![image](https://github.com/xfangfang/wiliwili/assets/57405236/de678e30-0b91-4254-9ca0-0ae59119d7cf)

官方客户端的显示状况（码住的区域均显示正常）：
![image](https://github.com/xfangfang/wiliwili/assets/57405236/c3584f05-8a33-43e2-9f92-a825a98ce330)

**Comment by xfangfang** [comment]
最新的dev分支应该“修复”（屏蔽）了这个问题：https://github.com/xfangfang/wiliwili/commit/696a5f0f6efaf44f1b2ca4f589942f319dd08439
