### ISSUE TITLE
[网易公开课] 有计划给网易公开课做一个类似的程序吗 🍑

### ISSUE THREAD

**Issue by xiaoxpai** [xfangfang/wiliwili#374]
看到开源哔哩哔哩已经实现了，感觉使用起来很棒，非常感谢！
日常刷这个网易公开课较多，所以提了一个issue，是否有考虑为这个也做一个类似的程序呢

**Comment by xfangfang** [comment]
@xiaoxpai 没有这样的计划，如果感兴趣可以参考wiliwili的代码来做个差不多的，有任何问题可以随时交流。
