### ISSUE TITLE
本身是大会员但提示“大会员限制”

### ISSUE THREAD

**Issue by gaozi321** [xfangfang/wiliwili#375]
没法播放大会员视频，请问是因为诶呦更新到最新版的原因嘛

**Comment by xfangfang** [comment]
@gaozi321 
首先反馈问题应该使用最新版，这可以避免一些简单的错误。

如果wiliwili内无法播放某视频，可以立刻使用手机尝试播放同一个视频，如果手机能播wiliwili不能，那么可以将对应的视频链接发过来。

我猜这个问题大概率，你现在使用手机也播不出来，如果B站发现频繁切换IP（或者还有什么其他的逻辑）会临时封禁30分钟大会员。
