### ISSUE TITLE
1.4.1 macOS版本解码假性花屏

### ISSUE THREAD

**Issue by maskmark** [xfangfang/wiliwili#377]
版本：1.4.1 macOS（1.4.0测试无该问题）
环境：macOS Mojave 10.14.6
现象：打开任意视频出现复数黑色矩形或不规则形状渲染错误（类似显存出错的现象），但只要任意resize一下窗口或切换全屏/窗口现象即告消失。诊断模式扩展测试显存内存均无问题，换机测试问题现象相同。回滚1.4.0版本，问题消失。同配置参数升级1.4.1，问题复现。
![屏幕快照 2024-07-11 下午9 59 45](https://github.com/xfangfang/wiliwili/assets/42833659/1471d253-5bef-4ac3-ad5c-49c1d58441fe)

**Comment by xfangfang** [comment]
@maskmark 感谢反馈，1.4.1 更新了依赖版本，我们猜测可能会导致10.11-10.15之间（不包括10.15）的系统出现问题，但是因为找不到真机来测试，所以没有修改readme相关的内容。不过看起来情况还好，至少软件还能正常启动。

从 mpv 0.37 开始，最低的支持版本从 10.8 提升到了 10.15，wiliwili在1.4.0及之前使用0.36，在1.4.1升级到了0.38。根据 iina 作者发布的信息，新版本mpv移除了旧系统的支持代码。

虽然我也不知道 mpv 都更新了什么macos相关的功能，但是wiliwili更新的趋势肯定是要跟随mpv的最新版来升级的。既然已经被证明存在问题，那么我预计下个版本会在构建时移除10.15之前的支持。

---

同时您也可以试用一下 @dragonflylee 编译的这个版本：https://github.com/dragonflylee/wiliwili/actions/runs/9854771416 他目前还在使用旧版本mpv，所以暂时是可以正常运行的。

---

我还是很希望能继续支持 10.15之前的系统，但是因为没有真机来测试，所以有些事还需要您来帮助测试一下，如果您时间不富裕，那么在没有其他人反馈的情况下，下个版本开始就会移除旧系统的支持。

**Comment by maskmark** [comment]
如果下个版本继续保留对遗留系统版本的支持，我会继续测试兼容性表现（其实移除了也会测试看看），我这边没用的老机器保留了各种旧版本macos，笑。另外感谢给switch和psv写了这么有用的应用。

**Comment by xfangfang** [comment]
@maskmark 

专门为低版本mac准备了一个版本，不确定有没有问题，可以试试，欢迎反馈，如果没问题的话，之后发布新版本的时候就会带上这个：

https://nightly.link/xfangfang/wiliwili/actions/runs/11307613029/wiliwili-macOS-IntelChip_10.11-4ecdfec.zip

**Comment by maskmark** [comment]
> @maskmark
> 
> 专门为低版本mac准备了一个版本，不确定有没有问题，可以试试，欢迎反馈，如果没问题的话，之后发布新版本的时候就会带上这个：
> 
> https://nightly.link/xfangfang/wiliwili/actions/runs/11307613029/wiliwili-macOS-IntelChip_10.11-4ecdfec.zip

反馈一下：
1、在出现问题最顽固的机器上用该版本测试了一些设置组合下的情况（包括软硬解码/视频容器格式/视频编码格式），每种组合测试推荐页前三个视频各两次，现象消失，完美解决。

2、之前提交后也用1.4.1的标准release版本继续测试了一些其它情况，多数机器都能在某个设置组合下（包括同配置不同屏幕分辨率、软硬解、系统版本）暂时消除解码花屏问题（甚至尤为古老的air11 2010升10.14后关了硬解也能行），
今天也附带测试了一下这些机器，使用该版本无论如何设置，均无再发生花屏）。

总之：大成功。感谢。

**Comment by xfangfang** [comment]
感谢反馈，这个之后可能还要再有一些变动，项目依赖的libcurl和libcpr新版本也开始不支持老系统了，估计下下个版本还得花时间折腾测试一次才行。（有点懒了，等下下个版本的时候再说）
