### ISSUE TITLE
无法响应数字键盘回车键操作

### ISSUE THREAD

**Issue by maskmark** [xfangfang/wiliwili#379]
【版本】1.4.1（其它版本未测试）
【环境】Windows10 x64 21h2
【现象】大键盘区域回车键（ASCII 0x0D，即换行回车）可正常进行确认操作；数字小键盘区域回车键（ASCII 0x0A，即不换行回车），按下后无法对任何焦点框内容进行操作，包括进入视频、进入全屏、发送等确认操作。由于某些键盘并无独立数字键盘区域，但唯一的回车键的键值却对应数字小键盘回车键，造成在这些键盘上无法正常使用键盘操作。建议对这两个不同键值的回车键同时进行监听响应。

**Comment by xfangfang** [comment]
您的标题写的是：“无法响应数字键盘回车键操作”，正文中却写着：“唯一的回车键的键值却对应数字小键盘回车键”

所以在您的设备上到底哪个回车键可以使用？

我们使用 GLFW_KEY_ENTER 作为确定键，在没改过键盘键位的情况下，应该代表键盘主区域的回车键。

---

我正在使用 60%配列的HHKB，这个正常用是没有问题的，之前也测试过带小键盘区域的键盘，主区域的回车也是没问题的。

**Comment by maskmark** [comment]
> 您的标题写的是：“无法响应数字键盘回车键操作”，正文中却写着：“唯一的回车键的键值却对应数字小键盘回车键”
> 
> 所以在您的设备上到底哪个回车键可以使用？
> 
> 我们使用 GLFW_KEY_ENTER 作为确定键，在没改过键盘键位的情况下，应该代表键盘主区域的回车键。

我的表述可能还不够清楚。
有这样一些键盘，它在布局上是87/88/89键，没有数字小键盘区域，只有一个回车键，但这个唯一的回车键对应的键值却是数字键盘回车键的键值（0X0A)，因此无法在wiliwili只监听主键盘回车（0x0D)的情况下进行正常操作。
(即原文说的由于某些键盘并无独立数字键盘区域，但唯一的回车键的键值却对应数字小键盘回车键，造成在这些键盘上无法正常使用键盘操作）。

并非是同时存在两个回车时主键盘回车无法操作，而是一些键盘只有一个回车，但这个回车键值却不是主键盘回车，而是小键盘回车。可能有些绕，但却是有这样的键盘。

**Comment by xfangfang** [comment]
竟然还有这种键盘，这真的不是工程师做错了吗?

代码调整了，正在构建中：https://github.com/xfangfang/wiliwili/actions/runs/10029365935

**Comment by maskmark** [comment]
> 竟然还有这种键盘，这真的不是工程师做错了吗?
> 
> 代码调整了，正在构建中：https://github.com/xfangfang/wiliwili/actions/runs/10029365935


感谢。我也是因为不同机器上有的能用有的不能用，感到莫名其妙，最后看了键盘扫描码才发现。神了……

**Comment by maskmark** [comment]
> 竟然还有这种键盘，这真的不是工程师做错了吗?
> 
> 代码调整了，正在构建中：https://github.com/xfangfang/wiliwili/actions/runs/10029365935


感谢。我也是因为不同机器上有的能用有的不能用，感到莫名其妙，最后看了键盘扫描码才发现。神了……
