### ISSUE TITLE
期望NS版的推荐列表能和手机官方版保存一致

### ISSUE THREAD

**Issue by Smith9527** [xfangfang/wiliwili#380]
经过一段时间的高强度使用发现，NS版的推荐视频列表没有手机版那么人性化而且同样的视频经常能出现重复推荐在首页，有些在手机版经常能刷到的视频类型在NS版根本刷不到（比如最近比较火的动漫的切片），怀疑是请求参数之类的不一致导致的。

还有一个问题有些视频在画质大会员的1080p60或者1080p+上会很卡，重启wiliwili后再打开该视频依然能复现，切换到720P能有所好转，而同个视频用手机官方版打开相同画质完全不会卡顿，还不清楚是不是我这边的网络设置问题，不知道你这边有没有什么好的建议

**Comment by jayofstella** [comment]
如果推荐和安卓一样我觉得反而不好，网页端的推荐机制就很好~

**Comment by Smith9527** [comment]
> 如果推荐和安卓一样我觉得反而不好，网页端的推荐机制就很好~

我不知道你有没有使用过NS版，现在的推荐很明显没手机版那么懂用户喜好，经常会出现我使用手机能一直刷到感兴趣视频，而NS版刷了好一会都找不到想看的，所以我现在的使用场景会经常变成先用手机刷一些想看的视频后再用NS上的历史记录去打开然后通过该视频下方的二级推荐列表去找感兴趣的视频，而这里又有个问题是手机端这块的推荐列表是能无限上拉加载更多的，而NS上的条目数是固定的，如果这些固定视频没找到想看的就只能再退回历史记录页面然后去随缘选视频来刷推荐，希望这个二级推荐列表也能和手机版一样能无限加载更多。

**Comment by jayofstella** [comment]
> > 如果推荐和安卓一样我觉得反而不好，网页端的推荐机制就很好~
> 
> 我不知道你有没有使用过NS版，现在的推荐很明显没手机版那么懂用户喜好，经常会出现我使用手机能一直刷到感兴趣视频，而NS版刷了好一会都找不到想看的，所以我现在的使用场景会经常变成先用手机刷一些想看的视频后再用NS上的历史记录去打开然后通过该视频下方的二级推荐列表去找感兴趣的视频，而这里又有个问题是手机端这块的推荐列表是能无限上拉加载更多的，而NS上的条目数是固定的，如果这些固定视频没找到想看的就只能再退回历史记录页面然后去随缘选视频来刷推荐，希望这个二级推荐列表也能和手机版一样能无限加载更多。

第一个不太理解你说的推荐是固定的，我记得ns上x按键不是可以刷新吗？第二个其实我和你相反，很多关注让手机版太过极端的理解了我的喜好，反而推送不到新鲜的视频了，这个应该是大数据算法的问题。。。所以如果NS版和手机版一样，那我觉得我都要关掉偏好推荐功能了（手机上有这个功能可以关掉），所以如果要调整，可以在ns上加一个这个功能，1、按照现有推荐机制； 2、按照手机版推荐机制； 3、按照网页版推荐机制； 4、关掉偏好推荐

**Comment by Smith9527** [comment]
> > > 如果推荐和安卓一样我觉得反而不好，网页端的推荐机制就很好~
> > 
> > 
> > 我不知道你有没有使用过NS版，现在的推荐很明显没手机版那么懂用户喜好，经常会出现我使用手机能一直刷到感兴趣视频，而NS版刷了好一会都找不到想看的，所以我现在的使用场景会经常变成先用手机刷一些想看的视频后再用NS上的历史记录去打开然后通过该视频下方的二级推荐列表去找感兴趣的视频，而这里又有个问题是手机端这块的推荐列表是能无限上拉加载更多的，而NS上的条目数是固定的，如果这些固定视频没找到想看的就只能再退回历史记录页面然后去随缘选视频来刷推荐，希望这个二级推荐列表也能和手机版一样能无限加载更多。
> 
> 第一个不太理解你说的推荐是固定的，我记得ns上x按键不是可以刷新吗？第二个其实我和你相反，很多关注让手机版太过极端的理解了我的喜好，反而推送不到新鲜的视频了，这个应该是大数据算法的问题。。。所以如果NS版和手机版一样，那我觉得我都要关掉偏好推荐功能了（手机上有这个功能可以关掉），所以如果要调整，可以在ns上加一个这个功能，1、按照现有推荐机制； 2、按照手机版推荐机制； 3、按照网页版推荐机制； 4、关掉偏好推荐

能提供这些的选项那当然是最好的，我说的固定是指二级推荐下视频的数量，往下滑到很快就到底没有更多视频了，我手机版这样看起来的确和你是相反的需求，手机版上我基本能一直刷个不停的，但NS上的其他体验完爆手机，能更方便的看视频和看评论区、更大的屏幕和更好的握持感、还有现在很多手机难以满足的真双扬声器（为此我还专门去魔改了扬声器），真的希望推荐这块能优化下

**Comment by xfangfang** [comment]
> 我说的固定是指二级推荐下视频的数量

wiliwili 使用的是 PC 客户端的API（部分PC客户端API与Web端相同），这里PC客户端返回的就是固定数量的推荐，这是我无法调整的

> NS版的推荐视频列表没有手机版那么人性化

我确实注意到，有时使用手机搜索过相关内容后，wiliwili的首页推荐也会随之改变。我相信肯定有什么数据被用于个性化推荐，但是wiliwili没有统计这种类型的数据，非常欢迎提交代码来完善。（因为事情太多，我不太想把时间花在琢磨B站API上）

> 有些视频在画质大会员的1080p60或者1080p+上会很卡

设置里打开硬解（默认是开的），正常来说 4K 30fps 播放是无压力的，如果哪个视频播放卡顿，可以发过来。如果单纯是网络卡，那我也无能为力了。
