### ISSUE TITLE
WIN8.1 32位 打开软件报错：无法找到入口

### ISSUE THREAD

**Issue by jayofstella** [xfangfang/wiliwili#381]

**Comment by jayofstella** [comment]
---------------------------
wiliwili.exe - 无法找到入口
---------------------------
无法定位程序输入点 GetDpiForWindow 于动态链接库 C:\Users\kaka\Desktop\wiliwili.exe 上。 
---------------------------
确定   
---------------------------

**Comment by dragonflylee** [comment]
D3D版本需要 Win10 以上才支持 `GetDpiForWindow` 的调用，可以在 [![nightly.link](https://img.shields.io/badge/nightly.link-%E6%B5%8B%E8%AF%95%E7%89%88-green)](https://nightly.link/xfangfang/wiliwili/workflows/build.yaml/dev) 下载 opengl 的版本使用

**Comment by jayofstella** [comment]
> D3D版本需要 Win10 以上才支持 `GetDpiForWindow` 的调用，可以在 [![nightly.link](https://camo.githubusercontent.com/4a597212bf0be58e0237003d76867e7ec360f5bfb27925a9bdad7db6da12cdca/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f6e696768746c792e6c696e6b2d2545362542352538422545382541462539352545372538392538382d677265656e)](https://nightly.link/xfangfang/wiliwili/workflows/build.yaml/dev) 下载 opengl 的版本使用

太感谢了，问题解决了，你说的32位OpenGL版本，可以在win8,1运行，我的老本子又可以发挥余热了~~

**Comment by dragonflylee** [comment]
@jayofstella  https://nightly.link/dragonflylee/wiliwili/actions/runs/10217409251/wiliwili-Windows-ad4fa9a-d3d-x86.zip

这里编译的 d3d 版本应该解决了 Win10  以下系统报错的问题

**Comment by xfangfang** [comment]
下面是最新测试版，我在虚拟机内的windows 7 sp1上测试，d3d版本是可以正常运行的了。

win+r 输入 dxdiag 运行，可以弹出 DirectX 诊断工具，在虚拟机windows 7 sp1上测试时，DirectX 版本显示为 11。

(针对 windows 7 sp1 还需要安装 [kb2670838](https://www.catalog.update.microsoft.com/Search.aspx?q=kb2670838) 更新和 [DirectX End-User Runtime](https://www.microsoft.com/en-us/download/details.aspx?id=35) )

https://nightly.link/xfangfang/wiliwili/workflows/build.yaml/dev/wiliwili-Windows-c3ae64c-d3d-x86_64.zip

win7 都能运行的话，win8.1 应该也可以了，欢迎反馈后续情况。
