### ISSUE TITLE
Request：提供winget安装方式

### ISSUE THREAD

**Issue by AlphonseZetta10** [xfangfang/wiliwili#382]
要是能上架[winget](https://github.com/microsoft/winget-pkgs)，下载和更新会方便很多

**Comment by xfangfang** [comment]
@AlphonseZetta10 https://github.com/xfangfang/wiliwili/discussions/92#discussioncomment-6213521 已经有朋友上架到scoop了，如果有winget需求欢迎提交到他们的仓库

**Comment by happytommyl** [comment]
wiliwili is now on winget.

https://github.com/microsoft/winget-pkgs/issues/171555

**Comment by xfangfang** [comment]
@happytommyl 感谢贡献，也可以把信息同步到这个页面来：https://github.com/xfangfang/wiliwili/discussions/92
