### ISSUE TITLE
Windows PC端，播放视频到某个位置发生卡顿，且一直卡顿

### ISSUE THREAD

**Issue by biewenwoaaaa** [xfangfang/wiliwili#384]
现象频发，可复现。
播放视频至某个地方后，画面显示为缓冲，但是一直缓冲，不会继续播放，除非拖动进度条或者再次点击分集栏下的该视频。
测试视频“程池Cached模式设计实现二_ev”，bilibili下的地址为：https://www.bilibili.com/video/BV1Fb421H7ep?p=23&vd_source=37d35fbc3bc7b6384f36ee3feeca65bd，采用2倍速播放。
本机为windows10，64位操作系统。

[wiliwili_config.json](https://github.com/user-attachments/files/16530353/wiliwili_config.json)
[wiliwili.log](https://github.com/user-attachments/files/16530373/wiliwili.log)
截取log图如下
![2024-08-07_223609](https://github.com/user-attachments/assets/62c56637-4e74-4440-8932-19b1d33513c9)

**Comment by maskmark** [comment]
1.4.1 windows x64版本遇到同样问题，应为多段文件的视频切换时发生（非多P），退出播放页后重新进入可继续播放。

**Comment by ameizi3** [comment]
wiliwili-Windows-x86_64版本遇到同样问题，一般在播放长视频时出现，在WiFi环境下出现一次小卡顿之后就会一直处于加载状态

**Comment by Nyte2016** [comment]
同遇到相同问题特来寻求帮助，也是播放长视频播放一会就卡住，非常影响观看体验。

**Comment by dragonflylee** [comment]
@biewenwoaaaa 可以尝试下载 https://github.com/dragonflylee/mingw-mpv/releases/download/mingw/mpv-dev-x86_64.7z 并解压其中的 `libmpv-2.dll` 到 `wiliwili.exe` 所在目录，看看问题有没有改善

**Comment by Nyte2016** [comment]
> @biewenwoaaaa 可以尝试下载 https://github.com/dragonflylee/mingw-mpv/releases/download/mingw/mpv-dev-x86_64.7z 并解压其中的 `libmpv-2.dll` 到 `wiliwili.exe` 所在目录，看看问题有没有改善

确实有用！

**Comment by jianghaodn** [comment]
> @biewenwoaaaa 可以尝试下载 https://github.com/dragonflylee/mingw-mpv/releases/download/mingw/mpv-dev-x86_64.7z 并解压其中的 `libmpv-2.dll` 到 `wiliwili.exe` 所在目录，看看问题有没有改善

操作后没有再遇到播放卡住的问题

**Comment by liming123qq** [comment]
> @biewenwoaaaa 可以尝试下载 https://github.com/dragonflylee/mingw-mpv/releases/download/mingw/mpv-dev-x86_64.7z 并解压其中的 `libmpv-2.dll` 到 `wiliwili.exe` 所在目录，看看问题有没有改善

不能下载了，有新的下载链接吗

**Comment by dragonflylee** [comment]
@liming123qq  链接已修复，另外最新的 1.5.0 版本已经修复了该问题

**Comment by liming123qq** [comment]
> @liming123qq 链接已修复，另外最新的 1.5.0 版本已经修复了该问题

好的，谢谢
