### ISSUE TITLE
希望增加进入视频页手动开始播放功能

### ISSUE THREAD

**Issue by Destiny4073** [xfangfang/wiliwili#387]
![Screenshot_20240813_114212](https://github.com/user-attachments/assets/f65150ab-d404-4e2e-83d3-597c28e6adab)
对应手机客户端的这个功能

**Comment by xfangfang** [comment]
这个我之前留好了位置，就是没做配置文件读写和前端选项，最近时间有限欢迎PR，相关代码位置在：
https://github.com/xfangfang/wiliwili/blob/904387c62060078d661770dc2de2c5fd2259a29d/wiliwili/source/utils/config_helper.cpp#L473-L474

顺便一提，为什么会有这种需求？

**Comment by happytommyl** [comment]
> 这个我之前留好了位置，就是没做配置文件读写和前端选项，最近时间有限欢迎PR，相关代码位置在：
> 
> https://github.com/xfangfang/wiliwili/blob/904387c62060078d661770dc2de2c5fd2259a29d/wiliwili/source/utils/config_helper.cpp#L473-L474
> 
> 顺便一提，为什么会有这种需求？

有时进入合集时想跳转到指定视频再播放，而不是自动播放第一集。或者有时只想看评论区

**Comment by xfangfang** [comment]
最新测试版，设置中添加了此选项
