### ISSUE TITLE
Switch下部分视频无法播放

### ISSUE THREAD

**Issue by kuangyl0212** [xfangfang/wiliwili#388]
系统信息：固件18.1；大气层17.1
wiliwili版本v1.4.1
问题：
某些视频点了之后无法播放，显示如下信息：
![7219cb135aed71522c3fd48db595479](https://github.com/user-attachments/assets/5d3f43b7-136c-45dd-87cb-077dcc671ae0)

视频的链接：https://www.bilibili.com/video/BV1YYeyeZEtz/

**Comment by xfangfang** [comment]
@kuangyl0212 方便打开设置页拍一下“关于更多”这个页面吗？


比如这样：
<img width="480" alt="image" src="https://github.com/user-attachments/assets/7895e72e-4632-4685-b402-a9cc093f794a">

**Comment by kuangyl0212** [comment]
抱歉，看起来我是版本没更新，我的实际上是1.4.0版本
