### ISSUE TITLE
Switch版本 出现无封面的占位视频0播放0弹幕

### ISSUE THREAD

**Issue by WE1ZARD** [xfangfang/wiliwili#397]
Switch版本会出现0播放0弹幕无封面的占位视频
AMS: 1.7.1
HOS: 18.1.0
Wiliwili: 1.4.1

![2024090909075700-C41888B7F8FF46D1FE6EB8F592903715](https://github.com/user-attachments/assets/1bd3f2a2-39c8-4a4e-8f01-89c51ccc8b26)
![2024090909080000-C41888B7F8FF46D1FE6EB8F592903715](https://github.com/user-attachments/assets/f5dfe294-64f5-4079-835e-a3aaaf565ddd)

**Comment by dragonflylee** [comment]
最新的 [![nightly.link](https://img.shields.io/badge/nightly.link-%E6%B5%8B%E8%AF%95%E7%89%88-green)](https://nightly.link/xfangfang/wiliwili/workflows/build.yaml/dev) 已经修复了该问题

**Comment by dragonflylee** [comment]
@xfangfang 似乎 https://github.com/xfangfang/wiliwili/commit/1521150d4631dc3146e326857bc9876fba3da6e8 的修改会导致某些推广视频也会通过浏览器打开

**Comment by xfangfang** [comment]
@dragonflylee dev分支最新的提交修复了这个问题。https://github.com/xfangfang/wiliwili/commit/abd19b81f897eca10f99c0c15615dcdb6fd2cdf1

广告推广视频的up主名称前会添加 ![](https://i0.hdslb.com/bfs/sycp/mng/202203/3621990414ef2de04c5730f1002d8dae.png) 用来标记

还有一种视频是 创作推广，他也会显示一个图标但是比例不同，我只刷出来过一次，后面刷不到了，希望创作推广也能正常显示，如果刷到了创作推广欢迎反馈一下显示的是不是正常的。

**Comment by yangyang19851115** [comment]
> dev分支最新的提交修复了这个问题。[ABD19B8](https://github.com/xfangfang/wiliwili/commit/abd19b81f897eca10f99c0c15615dcdb6fd2cdf1)
> 
> 广告推广视频的up主名称前会添加 ![](https://camo.githubusercontent.com/af8838af8a5bf2022faface7780065fb5fc3cf10b8df1b0e8c334fc3fe790b7d/68747470733a2f2f69302e6864736c622e636f6d2f6266732f737963702f6d6e672f3230323230332f33363231393930343134656632646530346335373330663130303264386461652e706e67) 用来标记
> 
> 还有一种视频是 创作推广，他也会显示一个图标但是比例不同，我只刷出来过一次，后面刷不到了，希望创作推广也能正常显示，如果刷到了创作推广欢迎反馈一下显示的是不是正常的。

作者·您好·，请问dev版本怎么更新呢？

**Comment by xfangfang** [comment]
@yangyang19851115 在 issue 下留言请只发送和该issue相关的问题，如果有疑问可以重新发一个新的 issue 或 在 [Discussions](https://github.com/xfangfang/wiliwili/discussions) 提问 ，在这个issue下的回复会给每个参与issue的人发送邮件提醒，不相干的回复会造成issue参与者的困扰，感谢理解。

测试版安装方式见：https://github.com/xfangfang/wiliwili/wiki#1-下载安装
