### ISSUE TITLE
SUPER RESOLUTION

### ISSUE THREAD

**Issue by Luoyacheng** [xfangfang/wiliwili#400]
有可能支持上N卡的RTX视频增强嘛？
或者说用MPC渲染器

**Comment by xfangfang** [comment]
mpv 在三周前合并了 N卡超分辨率支持的PR https://github.com/mpv-player/mpv/pull/14698

我没有能跑的显卡，就没办法自己测试啦，你可以按以下步骤来尝试（以 Windows 举例）：
1. 根据上面的PR中的配置说明，把配置写入到 wiliwili 配置目录下的 mpv.conf 文件 ( https://github.com/xfangfang/wiliwili/wiki#自定义播放器配置 )
2. 下载 libmpv 的最新构建 （ https://github.com/shinchiro/mpv-winbuild-cmake/releases ）
3. 下载 opengl 版wiliwili （ https://nightly.link/xfangfang/wiliwili/workflows/build.yaml/dev ）
4. 把 libmpv-2.dll 放在 wiliwili 同目录
5. 运行 wiliwili，设置中开启硬解

如果上面的步骤无法成功，那么将上面的 2/3步替换为下面的内容，重新尝试一遍：
2. 使用这个仓库中提供的libmpv补丁，给mpv最新的源码打上，编译一下mpv ( https://github.com/dragonflylee/mingw-mpv )
3. 下载 d3d 版 wiliwili （1.4.1 默认就是 d3d 版）

如果还是无法成功，那我就也不知道解决办法啦。
如果成功了，那么我之后会做一下自定义的支持，放在播放器设置里供大家自定义调整，就像：https://github.com/xfangfang/wiliwili/wiki#自定义着色器

**Comment by dragonflylee** [comment]
@Luoyacheng 最新的 libmpv 构建 https://github.com/dragonflylee/mingw-mpv/releases/download/mingw/mingw-w64-x86_64-mpv-master-1-any.pkg.tar.zst

**Comment by Luoyacheng** [comment]
> mpv 在三周前合并了 N卡超分辨率支持的PR [mpv-player/mpv#14698](https://github.com/mpv-player/mpv/pull/14698)
> 
> 我没有能跑的显卡，就没办法自己测试啦，你可以按以下步骤来尝试（以 Windows 举例）：
> 
> 1. 根据上面的PR中的配置说明，把配置写入到 wiliwili 配置目录下的 mpv.conf 文件 ( [https://github.com/xfangfang/wiliwili/wiki#自定义播放器配置](https://github.com/xfangfang/wiliwili/wiki#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%92%AD%E6%94%BE%E5%99%A8%E9%85%8D%E7%BD%AE) )
> 2. 下载 libmpv 的最新构建 （ https://github.com/shinchiro/mpv-winbuild-cmake/releases ）
> 3. 下载 opengl 版wiliwili （ https://nightly.link/xfangfang/wiliwili/workflows/build.yaml/dev ）
> 4. 把 libmpv-2.dll 放在 wiliwili 同目录
> 5. 运行 wiliwili，设置中开启硬解
> 
> 如果上面的步骤无法成功，那么将上面的 2/3步替换为下面的内容，重新尝试一遍： 2. 使用这个仓库中提供的libmpv补丁，给mpv最新的源码打上，编译一下mpv ( https://github.com/dragonflylee/mingw-mpv ) 3. 下载 d3d 版 wiliwili （1.4.1 默认就是 d3d 版）
> 
> 如果还是无法成功，那我就也不知道解决办法啦。 如果成功了，那么我之后会做一下自定义的支持，放在播放器设置里供大家自定义调整，就像：[https://github.com/xfangfang/wiliwili/wiki#自定义着色器](https://github.com/xfangfang/wiliwili/wiki#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%9D%80%E8%89%B2%E5%99%A8)

感谢成功了，按照12345的步骤，成功了。
如下图
![image](https://github.com/user-attachments/assets/85ff2e41-183d-42bd-b710-44d5e0761f2c)
1、配置目录下新增该文件
![image](https://github.com/user-attachments/assets/16984292-f745-4bb8-aa5c-897495e19dce)
2、使用 opengl 版wiliwili，并且把libmpv-2.dll放在一起
![image](https://github.com/user-attachments/assets/0647bbca-e615-4516-a74e-4038be34aeb9)

**Comment by xfangfang** [comment]
@Luoyacheng 感谢及时反馈，我稍后研究一下怎么把这些配置做进wiliwili里

**Comment by dragonflylee** [comment]
题外话 这里有其他的FSR相关Shader

https://gist.github.com/agyild/82219c545228d70c5604f865ce0b0ce5
https://gist.github.com/agyild/7e8951915b2bf24526a9343d951db214

**Comment by xfangfang** [comment]
@Luoyacheng
在之前 anime4K 着色器配置文件的基础上，增加了 mpv 参数设置功能，https://github.com/xfangfang/wiliwili/wiki#自定义着色器

测试版：
https://nightly.link/xfangfang/wiliwili/workflows/build.yaml/dev

可以测试一下是否 d3d 版本和 opengl 版本都能正常使用。
