### ISSUE TITLE
希望加个自动播放推荐视频的开关 

### ISSUE THREAD

**Issue by HuaJi2333DaDa** [xfangfang/wiliwili#401]
如题，不希望它一直播放推荐的视频。合集续播还行，但推荐视频就算了吧

**Comment by xfangfang** [comment]
@HuaJi2333DaDa 如果有这样的设置，你希望他做在哪个位置呢？

**Comment by HuaJi2333DaDa** [comment]
> @HuaJi2333DaDa 如果有这样的设置，你希望他做在哪个位置呢？

设置里？

**Comment by xfangfang** [comment]
@HuaJi2333DaDa 那就去设置里找一找

- - -

播放器，右上角的设置里

**Comment by HuaJi2333DaDa** [comment]
> @HuaJi2333DaDa 那就去设置里找一找
> 
> 播放器，右上角的设置里

对了，现在这个全屏逻辑也感觉有点怪，不开全屏显示的话视频点全屏还是窗口显示
![image](https://github.com/user-attachments/assets/c7d39b08-934f-4a29-8374-529b2335f64b)
还有就是用键盘的话快进快退能不能变成方向键控制，用 L 和 R 总感觉有点怪

**Comment by xfangfang** [comment]
@HuaJi2333DaDa 可以找找看历史的issue，这些内容之前都讨论过。

这个项目主要是为掌机设计的，放在windows上默认也是以全屏的形式呈现的，在这个设定下其实不太奇怪。

不过欢迎贡献pr，让这个应用能适合更多的使用场景
