### ISSUE TITLE
希望增加一个控制《全屏显示》的快捷键，谢谢

### ISSUE THREAD

**Issue by yangyang19851115** [xfangfang/wiliwili#402]
作者您好！希望增加一个控制是否《全屏显示》的快捷键，支持手柄和键盘控制，这样切换会更方便一些，谢谢您！

**Comment by xfangfang** [comment]
@yangyang19851115 

https://github.com/xfangfang/wiliwili/wiki#应用内未显示在下方提示栏中的快捷键

快捷键：`F`
