### ISSUE TITLE
switch版 1.4.1 网络连接问题

### ISSUE THREAD

**Issue by xuekai1991** [xfangfang/wiliwili#403]
系统18.1.0 ，大气层1.7.1 

任何页面下，连续刷新几次，页面直接显示无网络，包括首页推荐下拉，也会导致无网络。无网络稍等几分钟后又恢复，首页推荐视频看完一个，第二个视频稳定请求地址失败，人坐在路由器边上测试，排除自家网络问题

**Comment by xuekai1991** [comment]
就是可以理解为稳定的频繁掉线，系统时间和网络时间误差大概1秒

**Comment by xuekai1991** [comment]
各种现象是持续而且稳定的，不是一时间的网络波动

**Comment by xfangfang** [comment]
请参考readme，在反馈网络相关问题时提供足够的信息。

如果你在国内，那一般是dns或者switch wifi模块的问题。

我建议可以用pc端客户端，网线连接的方式来测试一下，如果pc客户端有相同问题，那也可以排查一下自家的路由器设置。

**Comment by xuekai1991** [comment]
> 请参考readme，在反馈网络相关问题时提供足够的信息。
> 
> 如果你在国内，那一般是dns或者switch wifi模块的问题。
> 
> 我建议可以用pc端客户端，网线连接的方式来测试一下，如果pc客户端有相同问题，那也可以排查一下自家的路由器设置。

试了下用手机热点做wifi连接，解决了上述问题，看来是自家路由器设置问题，但是路由器什么设置会导致以上原因，不懂，日常使用没有问题。（家里2台路由器有线mesh组网+软路由(未开启科学模式)）。求解

**Comment by xfangfang** [comment]
也可能是switch修改过dns导致的，或者是代理阴差阳错被误开了，既然和应用无关，就先关闭这个issue啦。

**Comment by xuekai1991** [comment]
> 也可能是switch修改过dns导致的，或者是代理阴差阳错被误开了，既然和应用无关，就先关闭这个issue啦。

switch端的网络我也删除，重现连接过的，dns应该是重置了的，代理我是确定没有开的。头大

**Comment by xfangfang** [comment]
我的建议还是按照我前面说的，提供足够的信息，网络不畅的原因翻来覆去就是那几条。但是很多人排查的不仔细就会错过，比如我见了太多人反馈说自己没改dns，但是一按readme中所说提供信息就发现自己改过。

没有本地pc的测试结果就没办法清晰的知道具体问题是路由器还是switch。

如果不方便提供这些信息，那么可以读一读wiki。

---
另外一个可能的原因是wifi信道不兼容

**Comment by xuekai1991** [comment]
> 我的建议还是按照我前面说的，提供足够的信息，网络不畅的原因翻来覆去就是那几条。但是很多人排查的不仔细就会错过，比如我见了太多人反馈说自己没改dns，但是一按readme中所说提供信息就发现自己改过。
> 
> 没有本地pc的测试结果就没办法清晰的知道具体问题是路由器还是switch。
> 
> 如果不方便提供这些信息，那么可以读一读wiki。
> 
> 另外一个可能的原因是wifi信道不兼容

![诊断](https://github.com/user-attachments/assets/b2a66c8b-d4eb-43d7-8b9f-94a3f296e484)

PC端的已经测试了，没有问题，网络诊断如上，信道看了下是44，大佬麻烦看下，苦恼

**Comment by xfangfang** [comment]
或许可以试试连2.4gwifi，或者切换一下5gwifi信道，或者直接用有线连接switch，如果都没有改善，那应该就可以肯定是路由器的问题了。

**Comment by xuekai1991** [comment]
> 或许可以试试连2.4gwifi，或者切换一下5gwifi信道，或者直接用有线连接switch，如果都没有改善，那应该就可以肯定是路由器的问题了。

唉，就是找不到路由器哪里的问题会导致这样，其他用网设备功能都是正常的，2.4G和5g都存在这个问题。我看B站也有一部分人反应。
![诊断2](https://github.com/user-attachments/assets/7d76eef8-a1d3-4555-bdc1-1d972f9a3374)

**Comment by xuekai1991** [comment]
> 或许可以试试连2.4gwifi，或者切换一下5gwifi信道，或者直接用有线连接switch，如果都没有改善，那应该就可以肯定是路由器的问题了。

![诊断2](https://github.com/user-attachments/assets/37043c11-7995-43b7-a110-3545db1b3c4c)

**Comment by xfangfang** [comment]
如果刷新速度过快，然后出现无网络连接，也可能是b站对账号或者ip限流了，但是我目前还没遇到这种情况。

或许可以试试下载一下测试版，那个没准能有更详细的报错提示，测试版下载链接见wiki。

不过你说切换到热点就好了，那我感觉还是路由器的问题。

**Comment by xfangfang** [comment]
一般那种显示“啥都木有”的报错都是挂了代理导致的，我感觉前面的b站评论截图大概都是这一类问题，可能是挂了港澳台代理看番剧，忘了退，然后再看国内的影视作品，就会出现这种报错。
应该和你的问题不是一个类型。

**Comment by xuekai1991** [comment]
> 如果刷新速度过快，然后出现无网络连接，也可能是b站对账号或者ip限流了，但是我目前还没遇到这种情况。
> 
> 或许可以试试下载一下测试版，那个没准能有更详细的报错提示，测试版下载链接见wiki。
> 
> 不过你说切换到热点就好了，那我感觉还是路由器的问题。

能做的都做了，放弃了，找不到原因，谢谢
