### ISSUE TITLE
能否在SteamGridDB上传一下封面、大宣传图、库主页图、徽标和图标？谢谢🙏

### ISSUE THREAD

**Issue by Hao0920** [xfangfang/wiliwili#404]
SteamGridDB只有B站的版本.

**Comment by xfangfang** [comment]
@Hao0920 欢迎自己上传，这里有一些用户整理的图片：https://github.com/xfangfang/wiliwili/discussions/41#discussioncomment-5821742

**Comment by Hao0920** [comment]
将 #41 的部分图片放大裁剪丢到SteamGridDB了，同时备注了来源。
但官方什么时候审核通过就不知道了。

**Comment by Hao0920** [comment]
今天无聊看了眼SteamGridDB，已经过审了。搜索wiliwili发现有大佬上传了自制的一套图标，我决定把我上传的删了，顺便提交了 Steamcommunity 302 🫣
