### ISSUE TITLE
win8.1打开出现  无法定位程序输入点getdpiforwindow与动态链接库C:\Users\ADMIN\Desktop\wiliwili.exe上

### ISSUE THREAD

**Issue by alex1072014251** [xfangfang/wiliwili#405]
![QQ截图20240928051736](https://github.com/user-attachments/assets/ba7c26a9-dbe2-4cb9-8d1b-a4b204becc26)

是不是win8.1不适合

**Comment by alex1072014251** [comment]
网上查了不知道啥问题 修复了dll文件还是这样 不知道是不是WIN8.1出现这个问题还是 我把一些启动项给禁止了

**Comment by dragonflylee** [comment]
请下载最新的 [![nightly.link](https://img.shields.io/badge/nightly.link-%E6%B5%8B%E8%AF%95%E7%89%88-green)](https://nightly.link/xfangfang/wiliwili/workflows/build.yaml/dev) 已经修复了该问题

**Comment by dragonflylee** [comment]
@alex1072014251 请问问题解决了吗

**Comment by carrothu-cn** [comment]
> @alex1072014251 请问问题解决了吗

同win8.1遇到相同问题，使用wiliwili-Windows-81c7a11-d3d-x86版本，可以正常打开，但是主界面点击任何视频都会报错“0x0bc2ff2e指令引用的0x00000004内存。该内存不能为read。“，附上dmp文件供排查。
[crash-20240930-191051.dmp](https://github.com/user-attachments/files/17192228/crash-20240930-191051.dmp)

**Comment by alex1072014251** [comment]
> @alex1072014251 请问问题解决了吗

谢谢，我才看到，我不知道作者回复那么及时，很感谢已经完美解决。 作者可以适配mac10.9.5吗，我本子macbook air2014 太老了，用10.15太费电了，10.9.5很省电，当然如果很费力那就算了，毕竟是免费的东西。很感谢开发这个软件，官方的太费cpu，打开看一会儿总是风扇转。

**Comment by alex1072014251** [comment]
> @alex1072014251 请问问题解决了吗

还有一个问题我的是macbook双系统，mac打开画面会有黑杠，但是如果把页面放大缩小在还原黑粗横杠就会消失很多，当然不影响体验，这应该是显卡不适配问题吧。我只是说说，也没啥影响，我的配置是macbook air 2014初  显卡是HD5000。我平常用的是WIN 占用发热少，产品体验不错。

**Comment by xfangfang** [comment]
@alex1072014251 macOS 问题请参考：https://github.com/xfangfang/wiliwili/issues/377

很意外，我一直以为低于 10.11完全运行不起来，因为项目依赖的播放器持续更新，为了更好地支持新系统，wiliwili被迫也需要更新最低支持的系统版本，预计会在下个版本将最低支持的macOS系统彻底提升到 10.15。

对于老系统，如果我有时间可能会在下个版本更新时单独提供一个版本，目前也可以尝试去 https://github.com/dragonflylee/wiliwili/actions 下载，我印象中 dragonflylee 编译的还在依赖老版本播放器。

**Comment by alex1072014251** [comment]
> @alex1072014251 macOS 问题请参考：#377
> 
> 很意外，我一直以为低于 10.11完全运行不起来，因为项目依赖的播放器持续更新，为了更好地支持新系统，wiliwili被迫也需要更新最低支持的系统版本，预计会在下个版本将最低支持的macOS系统彻底提升到 10.15。
> 
> 对于老系统，如果我有时间可能会在下个版本更新时单独提供一个版本，目前也可以尝试去 https://github.com/dragonflylee/wiliwili/actions 下载，我印象中 dragonflylee 编译的还在依赖老版本播放器。

好吧，谢谢。

**Comment by xfangfang** [comment]
@alex1072014251 

专门为低版本mac准备了一个版本，不确定10.9能不能跑起来，可以试试，欢迎反馈，如果没问题的话，之后发布新版本的时候就会带上这个：

https://nightly.link/xfangfang/wiliwili/actions/runs/11307613029/wiliwili-macOS-IntelChip_10.11-4ecdfec.zip

**Comment by alex1072014251** [comment]
> @alex1072014251
> 
> 专门为低版本mac准备了一个版本，不确定10.9能不能跑起来，可以试试，欢迎反馈，如果没问题的话，之后发布新版本的时候就会带上这个：
> 
> https://nightly.link/xfangfang/wiliwili/actions/runs/11307613029/wiliwili-macOS-IntelChip_10.11-4ecdfec.zip
不好意思，我刚看见。试了下还是跟以前的一样。10.9不合适，需要10.12版本。哎，已经不指望了，毕竟这个版本Safari浏览器打开网页都卡，有些视频都不能播放，我都用firefox才能很好的打开网页。谢谢，up辛苦了
