### ISSUE TITLE
最新测试版貌似在windows系统的150%缩放下触屏会偏移不准，希望大佬修复

### ISSUE THREAD

**Issue by 346896312** [xfangfang/wiliwili#407]
最新测试版貌似在windows10系统的150%缩放下触屏会偏移不准，希望大佬修复，鼠标点击是正常的

**Comment by xfangfang** [comment]
@346896312 感谢反馈，最新测试版修复了这个问题，欢迎测试反馈：https://nightly.link/xfangfang/wiliwili/workflows/build.yaml/dev
