### ISSUE TITLE
[BUG] 评论点踩显示为点赞

### ISSUE THREAD

**Issue by AiraNadih** [xfangfang/wiliwili#408]
目前我在网页或其他客户端中对评论进行点踩后，在 wiliwili 中显示为点赞，这不符合预期。

另外，能否添加对评论进行点踩的操作？

**Comment by xfangfang** [comment]
@AiraNadih 感谢反馈，最新测试版修复了这个问题，欢迎测试反馈：https://nightly.link/xfangfang/wiliwili/workflows/build.yaml/dev

**Comment by AiraNadih** [comment]
> @AiraNadih 感谢反馈，最新测试版修复了这个问题，欢迎测试反馈：https://nightly.link/xfangfang/wiliwili/workflows/build.yaml/dev

已经正常了，而且现在能点踩了 👌
