### ISSUE TITLE
升级到19.0.1以后，启动报错

### ISSUE THREAD

**Issue by kele-tao** [xfangfang/wiliwili#413]
升级到19.0.1以后，启动报错

**Comment by xfangfang** [comment]
可以下载测试：

https://github.com/xfangfang/wiliwili/actions/runs/11414795546

（从相册打开 wiliwili，重新安装桌面图标）

等到libnx/atmosphere 发布稳定版后，就会更新正式版

**Comment by dragonflylee** [comment]
补充一下是 nsp forwarder 的问题导致报错，任意游戏按 R 键方式进入是没问题的
