### ISSUE TITLE
【PC IME】反馈pc上使用的一个问题

### ISSUE THREAD

**Issue by winq2008** [xfangfang/wiliwili#42]
用了下，很好用。但是有搜索不能用啊。一点就一片空白。也打不进去文字？这是怎么回事呢？
我用的是fedora 37
用flatpak安装的最新版

**Comment by xfangfang** [comment]
https://github.com/xfangfang/wiliwili/discussions/41#discussioncomment-4322094

glfw还不支持系统输入法，不过已经马上要支持了。

另一个实现思路是模仿tv端页面做个单独的输入法页，有这个需求欢迎来提交代码呀，我暂时没时间做太复杂的修改

**Comment by xfangfang** [comment]
@winq2008 glfw 还没有合并那个pr，所以我等不及了wiliwili现在直接基于那个IME的pr来编译，已经可以使用系统输入法了，不过linux版本比较多不确定是不是一定可以用在fedora上，有空可以测试看看。

来自群友的 Steam Deck截图
![IMG_4258](https://user-images.githubusercontent.com/16631584/211253685-36d22050-bef0-41eb-9e73-77a51fe041b9.JPG)

**Comment by xfangfang** [comment]
@winq2008 请问有任何更新吗？

**Comment by xfangfang** [comment]
@winq2008 因为没有任何回复，所以先关闭这个issue了
