### ISSUE TITLE
[Feature Request]Publish to the PortMaster Project

### ISSUE THREAD

**Issue by erispyu** [xfangfang/wiliwili#420]
Hi xfangfang, would you consider to publish your wonderful WiliWili project to the PortMaster paltform as well?
Link: https://portmaster.games/games.html
Background: I encountered to WiliWili via Anbernic's retro handleds, which run Linux. Their stockOS run WiliWili via portmaster.

**Comment by xfangfang** [comment]
@erispyu 
Thank you for your feedback. We welcome anyone to port wiliwili to different PC platforms or game consoles. I am completely unfamiliar with Anbernic and PortMaster, so you might want to reach out to someone who has ported wiliwili to Anbernic. If he is interested in sharing his work on PortMaster, I am supportive of that.

There are too many Linux platforms, and I don't have enough time to port wiliwili to various platforms. Currently, we only support Linux installation packages in flatpak format, but anyone is welcome to share GitHub action workflows with us.

**Comment by erispyu** [comment]
@xfangfang Thanks for you reply! Portmaster is an intresting project to support an universe port on different Linux devices, especially for game consoles. If I want to publish ported wiliwili on their website, which permission I should applied from you? Or which info I should mark in my publish.

**Comment by xfangfang** [comment]
Just follow the project license:
https://github.com/xfangfang/wiliwili?tab=GPL-3.0-1-ov-file#readme

In addition, there should not be any paid parts, the port needs to be free for everyone.
