### ISSUE TITLE
评论区up放了视频传送门链接，但点不了；另外能否整合B站空降助手？

### ISSUE THREAD

**Issue by Hao0920** [xfangfang/wiliwili#421]
https://github.com/hanydd/BilibiliSponsorBlock

**Comment by xfangfang** [comment]
1. 暂时还未支持。
2. 未来不会集成。

**Comment by Hao0920** [comment]
那能否添加一个开关自动打开AI字幕，每回需要静音观看时没有快捷键快速打开这个功能。然后 【高通X Elite深度分析：年度最自信CPU-哔哩哔哩】 https://b23.tv/KN5igbx 这个视频的AI字幕货不对板😂显示的字幕像解说电影的。

**Comment by xfangfang** [comment]
@Hao0920 感谢反馈，这个字幕确实看起来有点问题哈，我稍后有时间研究一下。

因为很多视频都有内嵌在视频画面中的字幕，默认打开AI字幕会造成大多数人的困扰，添加太多开关又会导致应用设置过于臃肿和不方便维护，之后应该会做一些快捷键的支持来方便大家开关各种功能。

目前预期的字幕显示逻辑是和官方客户端一致的，up主 主动在B站设置的字幕会自动显示，AI字幕需要主动开启后才显示。

**Comment by Hao0920** [comment]
按照平替官方客户端的话..掌机版的评论区图片打开之后希望可以通过肩键放大缩小，摇杆移动图片，有些人喜欢发长图..根本看不了，个别图也因为屏幕小看不清。另外加个一键删除搜索记录吧🫣

**Comment by xfangfang** [comment]
最新的版本是支持一键删除搜索记录的（入口在所有搜索记录的最下方）。

图片这个确实我也想改，但是时间有限，这个应用还要解决的内容有很多，一两个人的空闲时间是不足以满足大家的全部需求的，如果有能力欢迎贡献代码。

---
图片这个我预计的修改方式是，在图片比例过长时，点击确定自动放大图片到顶部，这时可以通过上下键来移动图片。

这样的设计可以保证只有方向键和确认键的情况下也可以使用。

另外一个修改是给图片预览添加触摸时的双指放大缩小。

如果有人对这两个修改感兴趣，欢迎在动工前下面回复～

**Comment by xfangfang** [comment]
@Hao0920 字幕问题已修复：https://github.com/xfangfang/wiliwili/issues/424#issuecomment-2456022538

其他问题建议分别发送issue 方便跟踪。

**Comment by Hao0920** [comment]
👌
