### ISSUE TITLE
关于wiliwil应用里字幕自动生成功能疑问

### ISSUE THREAD

**Issue by gufeisheng001** [xfangfang/wiliwili#424]
应用内字幕生成和浏览器生成不同，Wiliwili应用生成的完全不是视频内容字幕

wiliwili生成的
![Screenshot from 2024-11-05 03-19-43](https://github.com/user-attachments/assets/f5607e36-2e10-4f9c-8a41-76d8ef481c27)

浏览器生成的
![Screenshot from 2024-11-05 03-23-09](https://github.com/user-attachments/assets/c99592cb-9c7c-4a78-a36d-eaf37eea4511)

**Comment by xfangfang** [comment]
感觉可能是B站故意的，或者是B站开发更新时的疏忽，我倾向于后者。

比如这个视频：https://www.bilibili.com/video/BV1KNDsY5E5H
wiliwili 目前使用的获取字幕的接口为：https://api.bilibili.com/x/player/v2?bvid=BV1KNDsY5E5H&cid=26617319267

同样的参数，通过这个接口获取到的字幕链接，每次都是不同的，而且时不时还消失。

官方目前使用的接口是：https://api.bilibili.com/x/player/wbi/v2?aid=113425153789954&cid=26617319267&w_rid=0123456789abcdef0123456789abcdef&wts=1730768111

这里的 w_rid 和 wts 目前不提供也可以，但是不确定未来会不会添加相关认证

---

已通过 https://github.com/xfangfang/wiliwili/commit/1e49a60fc1e59605040accea50c8c527d9b79e69 修复
最新构建：https://github.com/xfangfang/wiliwili/actions/runs/11675643052
