### ISSUE TITLE
请问能否添加任天堂上世代主机的支持

### ISSUE THREAD

**Issue by 123xzxc** [xfangfang/wiliwili#427]
请问能否添加任天堂上世代主机的支持
比如New Nintendo 3DS/Nintendo WiiU的支持
3DS的话如果可以看一些左右3D的VR游戏视频的话用处会变得很大
而Wii U可以电视端播放视频,Pad作为为视频播放控件,当看番电视盒会很好用

现在这两个平台几乎没有什么视频播放软件，如果能支持的话那就再好不过了

**Comment by dragonflylee** [comment]
3DS 不是自带视频播放器么

https://github.com/Core-2-Extreme/Video_player_for_3DS 这里有个自制播放器

**Comment by 123xzxc** [comment]
> 3DS 不是自带视频播放器么
> 
> https://github.com/Core-2-Extreme/Video_player_for_3DS 这里有个自制播放器

这个不好用，只能播放本地视频还有格式限制，还很卡
我想要的是那种像是Youtube/Niconico的在线视频客户端
(这两个客户端流畅性特别高，但是目前都已经停止服务无法使用）

**Comment by xfangfang** [comment]
关于3ds的回复： https://github.com/xfangfang/wiliwili/issues/248#issuecomment-1832514291

关于wiiu的回复： 
![image](https://github.com/user-attachments/assets/353aa76d-2148-4810-9097-f0de4bcd2652)

**Comment by 123xzxc** [comment]
> 关于3ds的回复： [#248 （comment）](https://github.com/xfangfang/wiliwili/issues/248#issuecomment-1832514291)
> 
> 关于wiiu的回复： ![image](https://private-user-images.githubusercontent.com/16631584/386233043-353aa76d-2148-4810-9097-f0de4bcd2652.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1OTQ3MzMsIm5iZiI6MTczMTU5NDQzMywicGF0aCI6Ii8xNjYzMTU4NC8zODYyMzMwNDMtMzUzYWE3NmQtMjE0OC00ODEwLTkwOTctZjBkZTRiY2QyNjUyLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQxNDI3MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZjYxNmJjZmE1YjRjZDAwYjUzNzYxMDcwMTBkMTI3MWI2MTY4NjIyNmQ2YzRkMGJjNDI2NDZjNTNmOTdiM2EyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.91mBJJsYyOJPkOwWCQin8B1zL-6lBsvmRYtcYdz44MM)

好的，谢谢解答喵
