### ISSUE TITLE
是否有x86的Appimage版本供老旧电脑使用

### ISSUE THREAD

**Issue by 123xzxc** [xfangfang/wiliwili#428]
是否有x86的Appimage版本供老旧电脑使用
目前电脑使用的是eos系统,没有自带软件商店
下载的aarch64-Ubuntu版本无法启动
未来会有PC端的Appimage格式软件使用么

**Comment by dragonflylee** [comment]
不太清楚 eos系统是啥，是基于 Ubuntu 吗？最好能看一些 neofetch 的信息，
另外可以参考 https://github.com/xfangfang/wiliwili/discussions/89 自行编译

**Comment by xfangfang** [comment]
建议自行编译，每增加一个新的格式都会对之后的维护造成很大的困扰，尤其是我感觉appimage这种编译出来了可能也不一定能运行在老系统上，用的人少适配又麻烦。
linux下如果不支持flatpak，那么就需要自己编译或者找愿意维护包管理器或者其他任何分发方式的第三方开发者帮助。

**Comment by 123xzxc** [comment]
> 不太清楚 eos系统是啥，是基于 Ubuntu 吗？最好能看一些 neofetch 的信息， 另外可以参考 #89 自行编译

endeavouros
基于 Arch

**Comment by dragonflylee** [comment]
arch 的包已经有了呀 https://github.com/xfangfang/wiliwili/discussions/92#discussioncomment-4992101

https://aur.archlinux.org/packages/wiliwili-git

**Comment by 123xzxc** [comment]
> arch 的包已经有了呀 [#92 (comment)](https://github.com/xfangfang/wiliwili/discussions/92#discussioncomment-4992101)
> 
> https://aur.archlinux.org/packages/wiliwili-git

谢谢,刚刚才知道,一会我去试一下
