### ISSUE TITLE
[OpenGL 2.1] windows版运行：已停止工作

### ISSUE THREAD

**Issue by sonichy** [xfangfang/wiliwili#43]
wiliwili-Windows-x64-79662b5.zip
Actions自动打包都测试了吗？

还有打包是zip，解压是tar.gz，再解压是tar，没必要压缩这么多层。

**Comment by xfangfang** [comment]
测试版称之为测试版的原因就是他可能出现问题，作者不可能每次提交代码都针对多个平台下载测试一遍。

刚刚下载测试了一下，在我这里是没问题的，可以下载这个版本来看看log：https://github.com/xfangfang/DIY/actions/workflows/wiliwili_win_debug.yml

多压了一层zip是因为github actions上传时会自动加一层，如果发布release的话就没有这层zip，我想作为测试版解压时候多点一下应该影响不大的

**Comment by sonichy** [comment]
https://glmje.com/i/2022/12/11/n6sr5b.jpg

**Comment by xfangfang** [comment]
> ![n6sr5b](https://user-images.githubusercontent.com/16631584/206902772-902c89b7-f9cf-49e8-b0a1-3a703e7e6179.jpg)

@sonichy 
根据这个图里的信息看，应该是你的显卡驱动不支持 opengl 3.2，我参考 [别人的代码](https://github.com/memononen/nanovg/blob/7544c114e83db7cf67bd1c9e012349b70caacc2f/example/example_gl3.c#L77) 对Windows下做了一下微调，希望能在你的设备上运行起来。

如果不行的话，可以考虑更新显卡驱动，按道理opengl3.2 应该都是支持的，可能是你在用虚拟机测试这个软件？

**Comment by sonichy** [comment]
i3-530，够老的。

**Comment by xfangfang** [comment]
> i3-530，够老的。

或许改一改代码把opengl3.2改到2.0也是可以运行的，因为我手头没有可供测试的设备，而且毕竟是播视频的软件，对性能要求比较大，所以就不考虑适配这么老的设备了。

**Comment by sonichy** [comment]
播放1080P没问题，opengl 可能没装，而且不会装，是包含在显卡驱动里面吗？

**Comment by xfangfang** [comment]
> 播放1080P没问题，opengl 可能没装，而且不会装，是包含在显卡驱动里面吗？

我也不甚了解windows的情况 百度看看吧

**Comment by xfangfang** [comment]
@sonichy 最近因为想要运行在树莓派上，所以写了 OpenGL2.1 的支持。

目前在树莓派上可以正常运行，不知道在Windows上会是如何，如果还有需要的话可以从这个链接下载测试一下看看：https://github.com/xfangfang/DIY/actions/runs/4097493150

**Comment by sonichy** [comment]
查看显卡是否支持 OpenGL：
Windows：AIDA64 (EVEREST)
![alt](https://s1.ax1x.com/2023/02/07/pSgaebT.jpg)
Linux：glxinfo | grep OpenGL
```
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics (ILK)
OpenGL version string: 2.1 Mesa 20.3.5
OpenGL shading language version string: 1.20
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 2.0 Mesa 20.3.5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
OpenGL ES profile extensions:
```

**Comment by xfangfang** [comment]
> 查看显卡是否支持 OpenGL：
> 
> Windows：EVEREST（https://www.clinicmed.net/jc/197.html）
> 
> Linux：glxinfo | grep OpenGL
> 
> ```
> 
> OpenGL vendor string: Intel Open Source Technology Center
> 
> OpenGL renderer string: Mesa DRI Intel(R) HD Graphics (ILK)
> 
> OpenGL version string: 2.1 Mesa 20.3.5
> 
> OpenGL shading language version string: 1.20
> 
> OpenGL extensions:
> 
> OpenGL ES profile version string: OpenGL ES 2.0 Mesa 20.3.5
> 
> OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
> 
> OpenGL ES profile extensions:
> 
> ```
> 
> 
@sonichy 
我上面那条回复的意思是 wiliwili 这个软件现在已经支持OpenGL 2.1啦～

我只有树莓派一个设备是OpenGL 2.1的，所以还是有一点点小不确定这个软件是否可以正常运行。

所以上面发了最新 windows 测试版的下载链接，如果你或者其他搜索进来这里的朋友有需要可以下载测试看看

**Comment by sonichy** [comment]
我的意思是查看本机OpenGL版本以确定软件依赖是否满足。

**Comment by xfangfang** [comment]
@sonichy 所以现在可以用在你的电脑上了吗？这个是我比较想知道的内容

**Comment by sonichy** [comment]
我主要使用Linux，已经转存到阿里云盘，安排时间测试。

**Comment by xfangfang** [comment]
感谢，linux应该也是支持的，只要重新编译一下添加编译参数 -DUSE_GL2=ON 就可以了

**Comment by sonichy** [comment]
我期待的是Linux版，你搞一下。

**Comment by xfangfang** [comment]
可以先试试win行不行，能正常运行的话，我再花时间搞一下linux的

**Comment by sonichy** [comment]
出界面（无法截图，只能拍照）就黑屏，显示器驱动程序停止响应。
为什么你没有Windows系统？加QQ方便测试。
![alt](https://s1.ax1x.com/2023/02/07/pSgNj7F.jpg)
![alt](https://s1.ax1x.com/2023/02/07/pSgNX0U.jpg)

**Comment by xfangfang** [comment]
可以加群：678069834 来交流

我有windows电脑，但是没有只支持OpenGL2.1的老显卡来测试

这个系统驱动停止响应就不是我能远程解决的了，最好还是本地调试看看，有可能是用到的某些操作显卡不支持。

**Comment by sonichy** [comment]
明白了，开发者的电脑太新。
