### ISSUE TITLE
希望推出Meta Quest/PCVR的客户端

### ISSUE THREAD

**Issue by 123xzxc** [xfangfang/wiliwili#430]
希望推出Meta Quest(基于Android)/PCVR(基于Windows/Linux)的客户端
像Youtube VR一样 支持播放3D格式视频，并且可以在透视模式下播放视频
界面为VR优化版，具有视频/评论等浮窗分离，视频窗口大小可缩放，弧形屏幕，氛围背景等功能

**Comment by xfangfang** [comment]
不会做安卓的移植，因为担心会有人将其安装到安卓电视，影响官方收益，由此背离wiliwili的初衷：https://github.com/xfangfang/wiliwili/issues/182#issuecomment-1657572553

---

我已经在issue区内评论过很多次了，任何安卓版的支持都会导致wiliwili的其他任何全平台版一起被封禁，作者会被连累律师函，已经有相当多的实例案件。

wiliwili从来都是丰富官方客户端不支持的平台而不是在某些平台替代官方客户端，尤其是安卓端的替代，会导致官方损失大量利益，被封禁是必然。

在这里我再次声明，我从未以任何方式发布过wiliwili的安卓版，并且只要有任何wiliwili的安卓版出现在互联网，我都会立即关闭wiliwili的github仓库不再维护。

**Comment by 123xzxc** [comment]
> 不会做安卓的移植，因为担心会有人将其安装到安卓电视，影响官方收益，由此背离wiliwili的初衷：[#182 (comment)](https://github.com/xfangfang/wiliwili/issues/182#issuecomment-1657572553)

Meta Quest的话 强制XR服务运行的话应该不算纯安卓，安装到普通安卓设备应该也无法使用（就算能打开也是VR的界面无法控制）

**Comment by xfangfang** [comment]
你说的对，那我也不能只发布安装包不开源代码呀

**Comment by 123xzxc** [comment]
> 你说的对，那我也不能只发布安装包不开源代码呀

如果只移植PCVR的话是可行的么（？

**Comment by xfangfang** [comment]
我认为只是运行在各类现代设备上是没问题的，专门适配做一做微调应该也是可以的，但是过于复杂的页面样式可能需要有人来重做。我愿意接受这样的pr（在开发者愿意持续维护的情况下），但是应该不会自己去做。
现在wiliwili支持了很多的系统，因为每次更新都要花很多时间来测试各个系统下效果，我不想自己去花时间维护更多的系统了。

**Comment by 123xzxc** [comment]
> 我认为只是运行在各类现代设备上是没问题的，专门适配做一做微调应该也是可以的，但是过于复杂的页面样式可能需要有人来重做。我愿意接受这样的pr（在开发者愿意持续维护的情况下），但是应该不会自己去做。 现在wiliwili支持了很多的系统，因为每次更新都要花很多时间来测试各个系统下效果，我不想自己去花时间维护更多的系统了。

好的，了解了
