### ISSUE TITLE
1.50_windows_x86_64_old_gpu版本在win7下GUI焦点错位，显示错误

### ISSUE THREAD

**Issue by maskmark** [xfangfang/wiliwili#445]
1.50_windows_x86_64_old_gpu版本GUI焦点错位，显示错误，32位版本无此问题（win10下两个版本无问题）

**Comment by xfangfang** [comment]
1. 可以有具体的截图来展示一下效果
2. 列出设备的具体系统版本（比如：win7 sp1）和cpu gpu型号

**Comment by maskmark** [comment]
> 1. 可以有具体的截图来展示一下效果
> 2. 列出设备的具体系统版本（比如：win7 sp1）和cpu gpu型号

win7 sp1 
现象如下
![IMG_20241202_015432](https://github.com/user-attachments/assets/dc4e8f6f-46c6-4226-a56a-d390cd519bec)
![Uploading IMG_20241202_015946.jpg…]()

**Comment by maskmark** [comment]
![IMG_20241202_020049](https://github.com/user-attachments/assets/fff4d0b8-c533-45f8-923f-8772b8658f1d)对照组：正常的版本

**Comment by xfangfang** [comment]
<img width="1067" alt="image" src="https://github.com/user-attachments/assets/de089fc6-289c-4f4f-907a-282797b95d99">

从截图来看像是 OpenGL的问题，在虚拟机里测试是正常的（见上图），在没有更多其他用户的相似反馈前，我认为应该是你正在使用的系统的问题，或者是显卡驱动的问题。

如果您不能从源码自行编译进行排查测试的话，我确实是无能为力了。
