### ISSUE TITLE
StemDeck游戏模式打开软件后闪屏一次

### ISSUE THREAD

**Issue by Grails125** [xfangfang/wiliwili#447]
steamdeck商店下载的最新版本
在游戏模式下打开应用加载完毕后会重新刷新闪屏一次

**Comment by xfangfang** [comment]
@Grails125 可以来个录屏看一看具体的情况

**Comment by Grails125** [comment]
https://github.com/user-attachments/assets/d3ea30a0-b5a1-4c83-ab90-9fe497dab784

我刚录的，麻烦看看

**Comment by Grails125** [comment]
上个版本没遇到过，机器重启也还是这样

**Comment by xfangfang** [comment]
@Grails125 是不是你改屏幕刷新率了，游戏模式首页和wiliwili的刷新率不同，steamdeck就会闪一次来调整

这个应该不是wiliwili自身的问题。

**Comment by Grails125** [comment]
是的，我刚试了之前默认的90HZ，我给改成60HZ了，麻烦了。
