### ISSUE TITLE
好像没找到如何倍速？

### ISSUE THREAD

**Issue by Leadrive** [xfangfang/wiliwili#46]
平常习惯看1.5X，好像没找到？

**Comment by xfangfang** [comment]
【switch版B站客户端终于稳定啦，耗时半年解决了那一个关键的bug】 【精准空降到 10:47】 https://www.bilibili.com/video/BV1xM411C7kr/?share_source=copy_web&vd_source=e5f8f52ed6023559ceaa6a1f7fb2a454&t=647

**Comment by Leadrive** [comment]
@xfangfang 刚才没说清楚，我是在LINUX下运行的，确实没找到哪个快捷键。播放页面中也没有。麻烦指点一二，谢谢！

**Comment by xfangfang** [comment]
@Leadrive 上面的视频中有关于快捷键的详细说明，直接点链接进去就是了。

**Comment by Leadrive** [comment]
@xfangfang 看到视频说了，长按右摇杆是快进，对应到键盘上，是哪个键呢？

**Comment by xfangfang** [comment]
![1F4F67C4-5972-4B48-9DD1-8E277C711439](https://user-images.githubusercontent.com/16631584/207103522-43e63d6d-9116-430b-835e-0f2efe67c604.jpeg)

这个并不是为桌面用户制作的客户端，如果有其他需求欢迎为项目提交pr

**Comment by xfangfang** [comment]
@Leadrive 稍微更新了一下代码添加了几个按键映射，具体内容可以看：https://github.com/xfangfang/wiliwili/discussions/47

播放页面按 `P` 可以倍速，不过目前的倍速设定是2倍速，如果需要自定义倍速，可以fork项目，将下列代码中的 `set speed 2.0` 改成自己想要的值（当时临时实现的这个功能，所以需要改好几个地方），提交代码之后Github actions就会自动编译了。

https://github.com/xfangfang/wiliwili/blob/3bc236e75796df1bd0a57ea7bd574c51f171e2ac/wiliwili/source/view/video_view.cpp#L656-L709

**Comment by Leadrive** [comment]
@xfangfang 非常感谢，这个感觉是基本功能，希望后续能完善一下，最好能在播放界面选择。

**Comment by xfangfang** [comment]
感觉用官方的客户端会更好一些，功能也更多。
这个主要是满足switch用户的基本需求，提供其他平台客户端的自动构建更多的是保证每一次提交代码都能正常编译，同时也方便潜在的开发者上手提交pr，而不是作为官方客户端的替代品。
还是希望有需求自己来改，同时欢迎给项目提交pr，目前的结果已经是我日常可以使用的程度啦，可能一时半会不会添加新功能。
