### ISSUE TITLE
PS4版在PS5上用不了 会修复成PS5能用的吗

### ISSUE THREAD

**Issue by 917361877** [xfangfang/wiliwili#460]
关于那个权限什么的好像etahen 可以搞定了吧 第三方文件管理器那样使用。

**Comment by xfangfang** [comment]
@917361877 
https://www.psdevwiki.com/ps5/Homebrew_Development

1. 作者没有ps5，不过欢迎大家贡献适配代码
2. 据我所知目前还不支持开源的工具链，如上面链接所示，目前已有的ps5自制软件应该都是用官方的SDK做的（用官方SDK不合法，到时候索尼一封邮件，这个项目就因为DMCA被封了）。
