### ISSUE TITLE
【PC触摸】希望在windows平板也能正常使用

### ISSUE THREAD

**Issue by meowrain** [xfangfang/wiliwili#48]
在小米平板2上测试,发现触屏没办法拖动

**Comment by xfangfang** [comment]
@meowrain 希望可以收到可供开发测试的支持触摸的Windows设备

**Comment by xfangfang** [comment]
发布之后，在B站也不断收到网友的私信和评论，需要windows的触摸功能。

于是在爱发电搞了一个众筹，差不多可以买个win触摸设备之后，我就能搞一搞了：https://b23.tv/hKNf4Pv

**Comment by zeromake** [comment]
@xfangfang 
有个 surface pro7 在吃灰要的话，可以拿去用个一年半载的。

**Comment by xfangfang** [comment]
@zeromake  感谢，不用麻烦您啦，估计众筹一阵就差不多了，正好我最近时间也不富裕，等众筹好正好能有空

**Comment by xfangfang** [comment]
@meowrain 最新的测试版简单支持了windows下的触摸，可以下载测试看看。

[#Support windows touch](https://github.com/xfangfang/wiliwili/actions/runs/4538544859)

**Comment by meowrain** [comment]
好的，感谢大佬！

**Comment by xfangfang** [comment]
@meowrain 请问体验过有什么问题吗？没有的话可以先关闭这个issue了

**Comment by AndreaFrederica** [comment]
触摸需要双击 望修复

**Comment by AndreaFrederica** [comment]
能否在左上角加个返回键 现在的按键位置有点不方便纯触摸设备

**Comment by AndreaFrederica** [comment]
还有一个恶性问题就是没法呼出软键盘

**Comment by AndreaFrederica** [comment]
又发现一个严重问题 在surface上直接跑满3d（主界面） 导致过热卡死

**Comment by xfangfang** [comment]
@AndreaFrederica 这又是恶性问题又是严重问题的，说的我都以为咱俩用的不是一个软件了。

1. 我印象中现在几乎每个页面的右上角都有一个 X 用来方便纯触摸设备关闭页面，这个放右上角和左上角我认为没啥区别。
2. 不自动弹出软键盘的问题我确实知道，之前简单找了一下没找到windows的哪个api能控制软键盘。因为我几乎不在windows上用这个软件，所以可能要等一阵了，欢迎了解这一方面的朋友提交PR。
3. 这个软件确实GPU占用会高一些，但是应该不会过于离谱，我建议多观察看看。

**Comment by AndreaFrederica** [comment]
![image](https://user-images.githubusercontent.com/30312657/232307931-38bc8942-307e-4796-a94f-10cd0c5e8255.png)
打开前
![image](https://user-images.githubusercontent.com/30312657/232307964-610abbdb-3c98-446e-9d5f-bc97086ab769.png)
打开后
![image](https://user-images.githubusercontent.com/30312657/232308007-38f92b13-290a-4fc2-a336-3c3dc38118dd.png)
播放时
测下来在surface上确实是影响极大了 打开的时间一长就会很热 插着充电器就能严重降频了

**Comment by AndreaFrederica** [comment]
另外我发现gpu占用和窗口尺寸呈现正相关 
问题是出在窗体绘制上吗

**Comment by xfangfang** [comment]
@AndreaFrederica 

> 另外我发现gpu占用和窗口尺寸呈现正相关

这个应该是正常的，夸张点说渲染8K不可能和1080P占用同样的GPU

> 这个软件确实GPU占用会高一些，但是应该不会过于离谱，我建议多观察看看。

在不播放视频且用户无操作时，wiliwili 还是会保持显示器最大帧数渲染，在这种情况下GPU占用会大于官方客户端。

在播放视频时，二者应该差不多。 wiliwili 目前使用 OpenGL，可能在 Windows 上效率不如 direct3D （我没有测试过）

我对 Windows 这个任务管理器不是很了解，但是我感觉 GPU 占用百分比可能不能反映出实际状态来，还是得结合 GPU 的频率看，或者直接看 GPU 功率。

发热也可能是因为没有开硬解，cpu占用太高导致的。

可能造成问题的原因多种多样，我现在能想到的可以优化的地方，一个是用 ANGLE 把 gles 转成 direct3D（不确定有没有效果），一个是在静止状态下减少刷新帧数（可能会比较麻烦）。
或者其他地方还有优化的空间，比如文字绘制等等方面，这个暂时还不在我目前的工作重点中，欢迎在这些可以优化的方面提交PR。

---
因为这是个跨平台的应用，对不同操作系统的优化或者适配都让我自己来搞有点浪费时间，尤其是我平时几乎不咋用 windows 和 linux。现阶段的计划还是专注于应用功能上的完善，先解决有没有的问题。

**Comment by AndreaFrederica** [comment]
实际上导致的cpu降频似乎是挺严重的 静候更新了 
不过发热严重是在主菜单就出现了 我找个时间做个基准测试好了
主界面的GPU占用我用另一台机器也复现了 看频率的话也有这个问题
感觉主要问题还是出在NanoVG渲染的原因 没用过这个库做过开发
不过看介绍和我以前用的qt之类的完全不一样 更接近于直接调用OpenGL做渲染？
感觉还是这个库的优化有点问题 并且这个问题目前在高分辨率的显示器上及其严重（远比浏览器下正常渲染网页的开销大）
不清楚在mac下面是否没有这个问题
我手头没mac 没法测试

**Comment by xfangfang** [comment]
@AndreaFrederica mac上问题可能更大，macOS13 之后 openGL vsync存在问题，默认刷新帧数到了120。

nanovg 和 imgui 这种比较类似，我认为最大影响GPU的问题就是固定刷新率。与之对比，网页在没有画面变动时刷新率很低 GPU占用也相应更低。

另外一个可能影响到GPU的就是文字渲染，有些框架的文字渲染会用系统提供的功能去做，nanovg 是独立处理的这一部分，可能会产生影响。

也就是说，正常情况下，软件内全屏无弹幕播放视频应该和其他播放器对系统的消耗类似。如果在这种情况下和官方客户端对比结果不同，那么倒是可以检查看看有什么问题，否则的话我也无能为力了。

**Comment by zeromake** [comment]
@xfangfang 要不我 winrt 分支合并一下上游打个 glfw + direct3D 让他试试吧？

**Comment by xfangfang** [comment]
@zeromake 如果不麻烦的话，当然是很好的呀～

周末更新了一下依赖，wiliwili 还有点小修改没有传上去，大概等半个小时到一个小时就好啦。

**Comment by xfangfang** [comment]
@zeromake 稍微迟了一些，最新的代码已经同步到 yoga 分支了。

**Comment by zeromake** [comment]
@xfangfang 
``` diff
diff --cc wiliwili/source/view/text_box.cpp
index 56e3aed,92661bf..0000000
--- a/wiliwili/source/view/text_box.cpp
+++ b/wiliwili/source/view/text_box.cpp
@@@ -25,24 -195,39 +195,52 @@@ static YGSize textBoxMeasureFunc(YGNode
      nvgFontFaceId(vg, textBox->getFont());
      nvgTextLineHeight(vg, textBox->getLineHeight());
  
-     int maxRows = textBox->getMaxRows();
-     if (maxRows <= 0) {
-         float bounds[4];
-         nvgTextBoxBounds(vg, 0, 0, width, fullText.c_str(), nullptr, bounds);
-         size.height = bounds[3] - bounds[1];
-         return size;
+     size_t maxRows = textBox->getMaxRows();
+     if (textBox->isShowMoreText() && maxRows != SIZE_T_MAX) maxRows++;
+     float maxHeight = maxRows == SIZE_T_MAX
+                           ? 0
+                           : (float)maxRows * pxLineHeight - pxBottomSpace;
+ 
+     // 计算最大高度
+     float bounds[6];
+     float lx = 0, ly = 0;
+     for (const auto& i : richTextData) {
+         if (i->type == RichTextType::Text) {
+             auto* t = (RichTextSpan*)i.get();
+             if (t->text.empty()) continue;
+             richTextBoxBounds(vg, 0, ly, width, t->text.c_str(), nullptr,
+                               lineHeight, lx, bounds);
+             lx = bounds[4];
+             ly = bounds[5];
+         } else if (i->type == RichTextType::Image) {
+             auto* t = (RichTextImage*)i.get();
+             // 当前行长度不够，就换到下一行
+             if (lx + t->width - 2 > width) {
+                 lx = 0;
+                 ly += pxLineHeight;
+             }
+             lx += t->width;
+         }
+         size.height = ly + textBox->getFontSize();
+         if (maxRows != SIZE_T_MAX && size.height > maxHeight) {
+             size.height = maxHeight;
+             return size;
+         }
      }
  
++<<<<<<< HEAD
 +    std::unique_ptr<NVGtextRow, std::function<void(NVGtextRow*)>> rows(new NVGtextRow[maxRows + 1], [](NVGtextRow* p){delete []p;});
 +    int numberOfRows = nvgTextBreakLines(vg, fullText.c_str(), nullptr, width,
 +                                         rows.get(), maxRows + 1);
 +    if (numberOfRows > maxRows && !textBox->isShowMoreText()) {
 +        numberOfRows = maxRows;
 +    }
 +    // 以最后一行 baseline 为底
 +    size.height =
 +        (numberOfRows - 1) * textBox->getFontSize() * textBox->getLineHeight() +
 +        textBox->getFontSize();
++=======
++>>>>>>> origin/yoga
      return size;
  }
  
@@@ -68,35 -332,41 +345,56 @@@ void TextBox::draw(NVGcontext* vg, floa
      nvgTextLineHeight(vg, this->lineHeight);
      nvgFillColor(vg, a(this->textColor));
  
-     // 显示全部文字
-     if (maxRows <= 0) {
-         nvgTextBox(vg, x, y, width, fullText.c_str(), nullptr);
-         return;
+     // 当显示 "更多" 提示时，最大的绘制行数加1
+     size_t drawRow = this->getMaxRows();
+     if (drawRow != SIZE_T_MAX && this->showMoreText) {
+         drawRow++;
      }
  
++<<<<<<< HEAD
 +    std::unique_ptr<NVGtextRow, std::function<void(NVGtextRow*)>> rows(new NVGtextRow[maxRows + 2], [](NVGtextRow* p){delete []p;});
 +    const char* end  = nullptr;
 +    int numberOfRows = nvgTextBreakLines(vg, fullText.c_str(), nullptr, width,
 +                                         rows.get(), maxRows + 2);
++=======
+     for (size_t line = 0; line < drawRow && line < lineContent.size(); line++) {
+         // 当最后一行给 "更多" 留出空闲区域时，跳出循环
+         if (showMoreText && line == drawRow - 1 &&
+             lineContent.size() != drawRow)
+             break;
++>>>>>>> origin/yoga
  
-     // 显示全部文字
-     if (numberOfRows <= maxRows) {
-         nvgTextBox(vg, x, y, width, fullText.c_str(), nullptr);
-         return;
+         // 绘制第 line 行
+         for (auto& i : lineContent[line]) {
+             if (i->type == RichTextType::Text) {
+                 auto* t = (RichTextSpan*)i.get();
+                 if (t->text.empty()) continue;
+                 nvgFillColor(vg, a(t->color));
+                 nvgText(vg, x + t->x, y + t->y, t->text.c_str(), nullptr);
+             } else if (i->type == RichTextType::Image) {
+                 auto* t = (RichTextImage*)i.get();
+                 t->image->setAlpha(this->getAlpha());
+                 t->image->draw(vg, x + t->x, y + t->y, t->width, t->height,
+                                style, ctx);
+             }
+         }
      }
  
-     // 当显示 "更多" 提示 且只超出一行时，可以借用提示所在的行
-     if (numberOfRows == maxRows + 1 && showMoreText) {
-         nvgTextBox(vg, x, y, width, fullText.c_str(), nullptr);
+     // 已经显示了全部文字
+     if (lineContent.size() <= drawRow) {
          return;
      }
  
++<<<<<<< HEAD
 +    // 行数过多，只显示部分内容
 +    end = rows.get()[maxRows - 1].end;
 +    nvgTextBox(vg, x, y, width, fullText.c_str(), end);
 +    if (!showMoreText) return;
 +
++=======
++>>>>>>> origin/yoga
      // 显示 "更多" 提示
+     if (!showMoreText) return;
      static auto linkColor = ctx->theme.getColor("color/link");
      nvgFontSize(vg, 18);
      nvgFillColor(vg, a(linkColor));
```
wiliwili/source/view/text_box.cpp 这个文件更改我没啥印象，哪里来的呢？是软件渲染分支的？

**Comment by xfangfang** [comment]
@zeromake 是我最近改的: https://github.com/xfangfang/wiliwili/commit/696d87aec68e298a3aff56b795521e259e914159

用来在评论区加载表情包和图片的。

软件渲染分支后来就没在单独添加过内容了，现在所有的分支都应该是基于那个软件渲染分支的。

**Comment by zeromake** [comment]
@xfangfang 行，看了一下直接覆盖就行了。

**Comment by xfangfang** [comment]
@zeromake 嗯嗯，对滴～

**Comment by zeromake** [comment]
@xfangfang 
感觉效果一般吧，windows 下 gpu 占用也要 35%，显卡 rtx 3070 laptop，可能需要做 dx 直接纹理渲染才能把 gpu 降下来。
https://github.com/zeromake/wiliwili/releases/tag/v0.6.0

试了一下 opengl 的渲染好像没啥区别也在 30+%，开全屏 1080p 60hz 在 40+%，dx11 的全屏在 glfw 有bug 渲染画布模糊。

**Comment by xfangfang** [comment]
@zeromake 我这边测出来1080P视频差距不是特别明显，于是找了个8K视频。

`win11` `2070s` `2K屏幕最大化窗口` `硬解 h265`

测试视频（8K分辨率）：[BV1qM4y1w716](https://www.bilibili.com/video/BV1qM4y1w716) (这个视频无需会员也能看8K)

| 客户端 | 首页静止GPU占用（%）| 首页上下滑动GPU占用（%） | 8K视频GPU占用（%）  |
| --- | --- | --- | --- |
| wiliwili gl | 28 | 28 | 55 |
| wiliwili dx | 17| 17 | 31 （有轻微掉帧） |
| bilibili | 1 | 10 - 30 （变化比较快） | 大约25（同样变化比较快） |

dx下 确实渲染出来的界面模糊一点

---

上面这些数字都是目测出来的，可能不是特别精确。

**Comment by zeromake** [comment]
@xfangfang 
dx + glfw 有些模糊的修复了(主要是 scaleFactor 对不上，开了 hidpi 的情况下)，更新到 https://github.com/zeromake/wiliwili/releases/tag/v0.6.0 了，感觉吃的资源更多了一些，弹幕属实性能杀手，比较多一些的开了直接掉到 20+hz。

**Comment by zeromake** [comment]
@xfangfang 
重新打过 glfw + d3d11 的 release 版本，感觉性能有所提升，SurfacePro7  4k 窗口全屏 gpu-3d 消耗稳定在 40-50%（av1会有些掉帧应该是 SurfacePro7 核显不支持硬解 av1 格式，h264，h256都比较正常），8k 视频明显有掉帧，但是 3d 消耗和 4k 差不多，应该是 SurfacePro7  性能不够的问题了。笔记本 r7-5800h + rtx3060l 8k cpu 54+% gpu 24+%。

**Comment by zeromake** [comment]
随便一提，我体验了一下 windows 触屏除了输入框不会自动调起软键盘其它没有感觉到有什么问题。

**Comment by xfangfang** [comment]
@zeromake 我在steam deck上测试的windows触屏，感觉有点不太跟手。switch上的触屏效果和手机上差不多，但是在 steam deck(windows)上轻轻的点击经常被忽视掉，不知道这是windows的问题还是steam deck的问题。

可以在播放器全屏时按f1，能看到当前有没有使用硬解。

不知道软键盘那里要怎么处理，我之前没找到对应的api，如果能知道怎么做的话感觉可以提交给glfw那个ime的pr

**Comment by zeromake** [comment]
@xfangfang 
SurfacePro7 确实没有硬解 av1，能硬解的机器显示(rtx3060l) 
```
Pixel Format: nv12
Hardware Decode: dxva2-copy
```
SurfacePro7 显示 
```
Pixel Format: yuv420p
Hardware Decode: 
```

**Comment by xfangfang** [comment]
@meowrain 新版本发布，已经支持了windows下的触摸。

关于gpu占用过高的问题，开了一个新的issue：https://github.com/xfangfang/wiliwili/issues/120

**Comment by zeromake** [comment]
> @zeromake 我在steam deck上测试的windows触屏，感觉有点不太跟手。switch上的触屏效果和手机上差不多，但是在 steam deck(windows)上轻轻的点击经常被忽视掉，不知道这是windows的问题还是steam deck的问题。
> 
> 可以在播放器全屏时按f1，能看到当前有没有使用硬解。
> 
> 不知道软键盘那里要怎么处理，我之前没找到对应的api，如果能知道怎么做的话感觉可以提交给glfw那个ime的pr

SDL [2.28.0](https://github.com/libsdl-org/SDL/releases/tag/release-2.28.0) 加了一个 SDL_HINT_ENABLE_SCREEN_KEYBOARD 看了一下有一些平台但是没有 win32，uwp 那边我加一下 SDL_HINT_ENABLE_SCREEN_KEYBOARD 应该就能调起了，但是安装了 uwp 的也不是必须要软键盘，应该加一个选项吧。

**Comment by xfangfang** [comment]
@zeromake 感觉可以诶，我之前想是不是可以在输入框那里给支持软键盘的平台加一个软键盘的按钮。这样的话就
需要：
1. Platform 这个类多加一个接口来判断对应的平台是否支持软键盘
2. 给输入组件增加一个切换的按钮

我去研究一下SDL那边，比较好奇有没有优雅滴支持Steam Deck的软键盘

**Comment by xfangfang** [comment]
@zeromake 经过刚刚的issue提醒，我找到了Win下的唤起虚拟键盘的方式：https://github.com/TransposonY/GestureSign/blob/master/GestureSign.CorePlugins/TouchKeyboard/TouchKeyboard.cs
