### ISSUE TITLE
PC 希望可以增加内存释放功能

### ISSUE THREAD

**Issue by 147-jelly** [xfangfang/wiliwili#49]
PC端，运行一段时间后，占用内存很大，只能通过关闭重新进入释放内存。

![image](https://user-images.githubusercontent.com/74666842/207546826-86f2e026-3904-4253-88b2-d2424f52de02.png)

**Comment by xfangfang** [comment]
这个其实是图片缓存实现的一个bug，我在本地修复了但是还想完善完善，等有空就更新新版本

**Comment by xfangfang** [comment]
@147-jelly 提交了一个小的修复，可能还有少部分svg图片的缓存没有处理干净，不过占大头的网络图片已经正常了，可以测试看看

**Comment by xfangfang** [comment]
@147-jelly 请问还有后续反馈吗？如果没有的话我就关闭这个issue了
