### ISSUE TITLE
视频播放结束后，应该有重新播放选项。

### ISSUE THREAD

**Issue by tiansongyu** [xfangfang/wiliwili#5]
@xfangfang Issues可以添加一个 Labels 来区分功能更新、BUG、建议。

**Comment by xfangfang** [comment]
@tiansongyu 添加了这个功能，可以等ci运行结束后下载体验：https://github.com/xfangfang/wiliwili/actions/runs/7213302131

<img width="702" alt="截屏2023-12-15 02 35 58" src="https://github.com/xfangfang/wiliwili/assets/16631584/ce2ed380-6c76-4443-92ca-9205bba0df30">
