### ISSUE TITLE
flatpak error

### ISSUE THREAD

**Issue by sonichy** [xfangfang/wiliwili#50]
23:04:00.228[INFO] Using platform GLFW
23:04:00.275[ERROR] glfw: error 65543: GLX: Failed to create context: GLXBadFBConfig
23:04:00.275[ERROR] glfw: failed to create window
23:04:00.281[ERROR] glfw: error 65537: The GLFW library is not initialized
23:04:00.281[ERROR] glfw: error 65537: The GLFW library is not initialized
23:04:00.281[ERROR] glfw: error 65537: The GLFW library is not initialized
23:04:00.281[ERROR] glfw: error 65537: The GLFW library is not initialized
23:04:00.281[ERROR] glfw: error 65537: The GLFW library is not initialized
23:04:00.281[ERROR] glfw: error 65537: The GLFW library is not initialized
23:04:00.281[ERROR] glfw: error 65537: The GLFW library is not initialized
23:04:00.281[ERROR] glfw: error 65537: The GLFW library is not initialized
23:04:00.281[ERROR] glfw: error 65537: The GLFW library is not initialized
23:04:00.281[WARNING] Cannot find custom font, (Searched at: ~/.var/app/cn.xfangfang.wiliwili/config/wiliwili/font.ttf)
23:04:00.281[INFO] Using internal font: /app/share/wiliwili/resources/font/switch_font.ttf

**Comment by xfangfang** [comment]
@sonichy 这个问题咱们应该讨论过了吧，使用的设备应该支持opengl3.2

**Comment by sonichy** [comment]
Linux flatpak 也有这问题吗？

**Comment by xfangfang** [comment]
@sonichy 程序在渲染画面的时候用到了OpenGL3.2的接口，无论哪个平台都需要支持 OpenGL3.2（目前是这样），先关闭这个issue了。
