### ISSUE TITLE
Two issues for windows's wiliwili

### ISSUE THREAD

**Issue by DDinghoya** [xfangfang/wiliwili#53]
At once, I always feel grateful for good programs. :)

1. Isn't libmpv-2.dll distributed together?
I did a search and renamed it and put it in a folder.

3. The provided switch_font.ttf(Source Han Sans CN Regular) has problems recognizing Korean. It'll have similar experiences in other languages. Common Korean ttf fonts do not recognize Chinese, so using "Source Han Sans KR Regular" solved the problem.

There is a issue of having to put the font directly into the folder.

Thank you!

**Comment by xfangfang** [comment]
For the first problem, It was yesterday that mpv changed the name of the library under Windows. I have received feedback from other users. I will push an update as soon as possible to fix this problem.

Considering the repo size, if I update this file, it seems that it will cause too much traffic to download font files when git clone. It is not a big problem, but in China, github is very slow, so it is good to reduce the size of the repo.

What I'm going to do is find the default font of the system as fallback, I think this should be a better solution. At the same time, you can also set custom fonts: https://github.com/xfangfang/wiliwili/discussions/40

I am writing the options related to danmaku. After solving this, I will deal with the font issues. And I will also add an option to quickly open the configuration directory to facilitate the setting of custom fonts.

Thanks for feedbacks

**Comment by xfangfang** [comment]
@DDinghoya 
Using `malgun` under Windows and `Arial Unicode` under MacOS as fallback font, so that wiliwili can be used out of the box in all supported languages.

**Comment by DDinghoya** [comment]
> @DDinghoya Using `malgun` under Windows and `Arial Unicode` under MacOS as fallback font, so that wiliwili can be used out of the box in all supported languages.

Great! Good job! :)
