### ISSUE TITLE
是否可以在追番的部分追加視頻CC字幕開關部分?

### ISSUE THREAD

**Issue by Shan-Mk** [xfangfang/wiliwili#56]
wiliwili很好用 但是要在追番菜單時 幾乎沒字幕顯示
原因是bilibili新番都是CC字幕 
能否作者做個CC字幕開關呢   
謝謝作者!!

**Comment by xfangfang** [comment]
@Shan-Mk 感谢提出建议，cc字幕确实是在开发的计划当中，如果有时间我会添加上的。

注意到您是在使用繁体中文，wiliwili内也支持繁体中文的显示与自动转换，但是我一直不确定转换的效果，所以如果有哪些内容转换的不正确，也欢迎反馈呀。

除了自动转换的部分，还有一些是我手动设置的，同样欢迎来审核一下：https://github.com/xfangfang/wiliwili/tree/yoga/resources/i18n/zh-Hant

**Comment by Shan-Mk** [comment]
> @Shan-Mk 感谢提出建议，cc字幕确实是在开发的计划当中，如果有时间我会添加上的。
> 
> 注意到您是在使用繁体中文，wiliwili内也支持繁体中文的显示与自动转换，但是我一直不确定转换的效果，所以如果有哪些内容转换的不正确，也欢迎反馈呀。
> 
> 除了自动转换的部分，还有一些是我手动设置的，同样欢迎来审核一下：https://github.com/xfangfang/wiliwili/tree/yoga/resources/i18n/zh-Hant

希望大佬能來QQ79114278  一起討論喔

**Comment by xfangfang** [comment]
> > @Shan-Mk 感谢提出建议，cc字幕确实是在开发的计划当中，如果有时间我会添加上的。
> 
> > 
> 
> > 注意到您是在使用繁体中文，wiliwili内也支持繁体中文的显示与自动转换，但是我一直不确定转换的效果，所以如果有哪些内容转换的不正确，也欢迎反馈呀。
> 
> > 
> 
> > 除了自动转换的部分，还有一些是我手动设置的，同样欢迎来审核一下：https://github.com/xfangfang/wiliwili/tree/yoga/resources/i18n/zh-Hant
> 
> 
> 
> 希望大佬能來QQ79114278  一起討論喔

感谢邀请，因为我时间太过有限，还是先不加其他的群了
如果有反馈的话可以发送在github issue或者发送在wiliwili的用户交流群：678069834

**Comment by xfangfang** [comment]
@Shan-Mk 打扰一下，请问不知道可不可以提供几个带字幕的新番，我找了一会，找到的番剧都是内嵌字幕的。

**Comment by qlmmm** [comment]
> 

港澳台的番剧都是外挂字幕的

**Comment by qlmmm** [comment]
@xfangfang 港澳台的番剧都是外挂字幕的

**Comment by xfangfang** [comment]
@qlmmm @Shan-Mk 最新的测试版添加了字幕支持，可以测试一下看看，尤其是前面说的港澳台视频，我因为没有环境所以不确定能否正常使用

**Comment by cirfi** [comment]
[![Screenshot-2023-03-17-at-19-30-07.png](https://i.postimg.cc/FzhKCzhs/Screenshot-2023-03-17-at-19-30-07.png)](https://postimg.cc/9RNVrW4v)
dev 分支编译了一下，亲测可用。
