### ISSUE TITLE
cpr编译中止：将警告视为错误

### ISSUE THREAD

**Issue by sekaiacg** [xfangfang/wiliwili#58]
**系统信息：**
OS: Arch Linux x86_64 
Kernel: 6.1.6-arch1-3 
DE: GNOME 43.2 

**出问题的库：wiliwili/library/cpr**
可能是本地curl库版本问题导致cpr编译出错
curl 7.87.0-3
lib32-curl 7.87.0-1

**问题信息：**
![截图 2023-01-21 11-30-04](https://user-images.githubusercontent.com/33929605/213841920-5f906995-5921-4973-9ffa-01cae7f43e61.png)

![截图 2023-01-21 11-36-11](https://user-images.githubusercontent.com/33929605/213841922-b18328c6-e6c5-44bf-992e-15cc5d65cc59.png)

**临时解决方法：**
将 wiliwili/library/cpr/CMakeLists.txt：107行的` -Werrors` 删除

**Comment by sekaiacg** [comment]
ps：b站看到的，前来支持一下

**Comment by xfangfang** [comment]
另一个解决办法是把这一行的ON改成OFF

https://github.com/xfangfang/wiliwili/blob/334e7977b41ce92ab1e42bbca1d96f4ee3e1c4e4/library/CMakeLists.txt#L4


Linux上默认使用系统curl库，如果系统curl太新就会出现这个问题。

貌似是因为curl新版本在windows上的某些bug，所以cpr还是在使用旧版本的curl，估计过一阵就会解决吧。

因为编译 wiliwili 的 flatpak 包的时候不能联网，所以不能使用cpr自动下载的curl库，于是这个问题就维持了现状。

感谢反馈，可以保留着这个issue避免其他人踩坑，等cpr解决了问题，或者我有空多加个编译选项的时候再关～

**Comment by sekaiacg** [comment]
> 另一个解决办法是把这一行的ON改成OFF
> 
> https://github.com/xfangfang/wiliwili/blob/334e7977b41ce92ab1e42bbca1d96f4ee3e1c4e4/library/CMakeLists.txt#L4
> 
> Linux上默认使用系统curl库，如果系统curl太新就会出现这个问题。
> 
> 貌似是因为curl新版本在windows上的某些bug，所以cpr还是在使用旧版本的curl，估计过一阵就会解决吧。
> 
> 因为编译 wiliwili 的 flatpak 包的时候不能联网，所以不能使用cpr自动下载的curl库，于是这个问题就维持了现状。
> 
> 感谢反馈，可以保留着这个issue避免其他人踩坑，等cpr解决了问题，或者我有空多加个编译选项的时候再关～

感谢解答，改为OFF才是正常的方法....
https://github.com/xfangfang/wiliwili/blob/334e7977b41ce92ab1e42bbca1d96f4ee3e1c4e4/library/CMakeLists.txt#L4

**Comment by xfangfang** [comment]
添加了cmake选项， linux默认构建已经转为了使用cpr提供的curl
