### ISSUE TITLE
希望增加长按L/R倍速快退/快进功能

### ISSUE THREAD

**Issue by leafleave** [xfangfang/wiliwili#59]
感谢作者的无私奉献！经过几天的使用已经感觉软件十分稳定。
在网页端或者手机端，长按屏幕或者按住→键可以实现临时的3倍速播放，在wiliwili上是不是也可以实现按住R键倍速播放呢？
感谢作者的付出！

**Comment by xfangfang** [comment]
@leafleave 感谢支持，可以在应用设置中找到更多的快捷键说明。

倍速的快捷键是按下右摇杆

**Comment by leafleave** [comment]
原来如此，感谢感谢！
