### ISSUE TITLE
Support Android TV ..?

### ISSUE THREAD

**Issue by mio-19** [xfangfang/wiliwili#60]
Don't know if nanovg support Android

**Comment by xfangfang** [comment]
I have been able to run the borealis demo on Android. There seems to be a little problem with scissor, but all the other functions are good.
That is to say, wiliwili can also run on Android.

However, I don’t think it is a good idea to port wiliwili to Android under the requirements of relevant regulations.

You can try this instead: https://github.com/xiaye13579/BBLL

**Comment by shenhaiyu** [comment]
> I have been able to run the borealis demo on Android. There seems to be a little problem with scissor, but all the other functions are good. That is to say, wiliwili can also run on Android.
> 
> However, I don’t think it is a good idea to port wiliwili to Android under the requirements of relevant regulations.
> 
> You can try this instead: https://github.com/xiaye13579/BBLL

可是现在bbll已经不能用了
