### ISSUE TITLE
需要switch tv模式下的音量调节功能

### ISSUE THREAD

**Issue by LeUKi** [xfangfang/wiliwili#62]
tv模式默认不开放音量调节，不同视频音量忽大忽小，希望有调节音量功能。

**Comment by xfangfang** [comment]
可以下载最新测试版体验此功能：https://nightly.link/xfangfang/wiliwili/workflows/build.yaml/dev

**Comment by xfangfang** [comment]
先关闭这个issue啦

**Comment by lingr7** [comment]
![image](https://github.com/xfangfang/wiliwili/assets/37898999/6ed17184-9495-4ec0-a845-73dd6dde0f5d)
这个dev版本电量显示图标有Bug。电池过长
