### ISSUE TITLE
无法播放没有声音的视频

### ISSUE THREAD

**Issue by XPRAMT** [xfangfang/wiliwili#66]
[BV1Ka41187We](https://www.bilibili.com/video/BV1Ka41187We/)
[BV11v4y1r7JG](https://www.bilibili.com/video/BV11v4y1r7JG/)
<img src="https://www.z4a.net/images/2023/01/24/5f8ccf5a5c8880f3dcb4064c5343b57c.jpg" alt="5f8ccf5a5c8880f3dcb4064c5343b57c.jpg" border="0" />

**Comment by xfangfang** [comment]
感谢反馈，我写的时候就想过这个事，但是没有找到这样的视频

**Comment by xfangfang** [comment]
最新代码已经修复，可以在github action下载测试版

**Comment by xfangfang** [comment]
@XPRAMT 请问有相关后续吗

**Comment by XPRAMT** [comment]
> @XPRAMT 请问有相关后续吗

可以正常使用了

**Comment by xfangfang** [comment]
感谢回复，先关闭这个issue了
