### ISSUE TITLE
关于linux的sdl2

### ISSUE THREAD

**Issue by yigekuyou** [xfangfang/wiliwili#67]
OS: openSUSE Tumbleweed x86_64
显示：kde-wayland Plasma 5.26.5
版本：dev，obs构建https://build.opensuse.org/package/show/home:lighthomo/wiliwili
在wayland下，是开个窗口，不知道x11的怎么样
![image](https://user-images.githubusercontent.com/47034094/214205704-96675451-d7a8-4c16-9575-dfdfedd6fdf2.png)
1主界面不能实时调整大小否则
![image](https://user-images.githubusercontent.com/47034094/214205769-32aa4821-e0fa-4e86-8046-5c488d191d3f.png)
2但是播放界面可以实时改变，退回到主界面也变换
![image](https://user-images.githubusercontent.com/47034094/214205936-47a2285e-e47d-4df3-b9a6-04b725814f4c.png)
但是和1相同的效果
![image](https://user-images.githubusercontent.com/47034094/214205828-3a2bce79-fcbf-41f0-b5fa-7aef07917710.png)
搜索是终端的
❯ /usr/bin/wiliwili 
11:10:30.339[INFO] wiliwili 
11:10:30.339[INFO] client: 54945413.1674480383
11:10:30.339[INFO] cookie: DedeUserID:0
11:10:30.339[INFO] setting: null
11:10:30.339[INFO] Load config from: /home/light/.config/wiliwili/wiliwili_config.json
11:10:30.339[INFO] Load window state: 0x0,0x0
11:10:30.339[INFO] Set app locale: zh-Hans
11:10:30.341[INFO] Using platform SDL
11:10:30.492[INFO] sdl: GL Vendor: NVIDIA Corporation
11:10:30.492[INFO] sdl: GL Renderer: NVIDIA GeForce GTX 1060/PCIe/SSE2
11:10:30.492[INFO] sdl: GL Version: 4.6.0 NVIDIA 525.85.05
11:10:30.573[INFO] windows size changed: 1280 height: 720
11:10:30.573[INFO] framebuffer size changed: fwidth: 1280 fheight: 720
11:10:30.573[INFO] scale factor: 1.0
11:10:30.573[INFO] Window size changed to 1280x720, content size: 1280.0x720.0 factor: 1.0
11:10:30.573[INFO] Window position changed to 320x180
11:10:32.967[INFO] joystick num: 0
11:10:32.967[WARNING] Cannot find custom font, (Searched at: /home/light/.config/wiliwili/font.ttf)
11:10:32.968[INFO] Using internal font: /usr/share/wiliwili/resources/font/switch_font.ttf
11:10:32.974[INFO] Load keymap icon: /usr/share/wiliwili/resources/font/keymap_xbox.ttf
11:10:32.975[INFO] createWindow done
11:10:33.006[INFO] Window position changed to 324x218
11:10:33.013[INFO] WindowSizeChangedEvent trigger
11:10:33.472[INFO] max_thread_num: 4
11:10:35.290[INFO] Window position changed to 343x206
11:10:36.850[INFO] App is up to date
11:10:47.432[INFO] Window position changed to 467x186
11:11:10.539[INFO] Window position changed to 0x34
11:11:10.539[INFO] windows size changed: 1920 height: 1046
11:11:10.539[INFO] framebuffer size changed: fwidth: 1920 fheight: 1046
11:11:10.539[INFO] scale factor: 1.0
11:11:10.539[INFO] Window size changed to 1920x1046, content size: 1280.0x697.0 factor: 1.5
11:11:10.643[INFO] WindowSizeChangedEvent trigger
11:11:12.727[INFO] Window position changed to 589x113
11:11:12.727[INFO] windows size changed: 1280 height: 720
11:11:12.727[INFO] framebuffer size changed: fwidth: 1280 fheight: 720
11:11:12.727[INFO] scale factor: 1.0
11:11:12.727[INFO] Window size changed to 1280x720, content size: 1280.0x720.0 factor: 1.0
11:11:12.830[INFO] WindowSizeChangedEvent trigger
11:11:14.462[INFO] Window position changed to 624x38
11:11:14.463[INFO] Window position changed to 0x34
11:11:14.463[INFO] windows size changed: 1920 height: 1046
11:11:14.463[INFO] framebuffer size changed: fwidth: 1920 fheight: 1046
11:11:14.463[INFO] scale factor: 1.0
11:11:14.463[INFO] Window size changed to 1920x1046, content size: 1280.0x697.0 factor: 1.5
11:11:14.576[INFO] WindowSizeChangedEvent trigger
11:11:17.224[INFO] Window position changed to 467x186
11:11:17.224[INFO] windows size changed: 1280 height: 720
11:11:17.224[INFO] framebuffer size changed: fwidth: 1280 fheight: 720
11:11:17.224[INFO] scale factor: 1.0
11:11:17.224[INFO] Window size changed to 1280x720, content size: 1280.0x720.0 factor: 1.0
11:11:17.327[INFO] WindowSizeChangedEvent trigger
11:11:32.074[INFO] Window position changed to 573x165
11:12:13.839[INFO] Window position changed to 0x34
11:12:13.839[INFO] windows size changed: 1920 height: 1046
11:12:13.839[INFO] framebuffer size changed: fwidth: 1920 fheight: 1046
11:12:13.839[INFO] scale factor: 1.0
11:12:13.839[INFO] Window size changed to 1920x1046, content size: 1280.0x697.0 factor: 1.5
11:12:13.942[INFO] WindowSizeChangedEvent trigger
11:12:15.682[INFO] set memory cache: 20MB
11:12:15.682[INFO] MPV hardware decode: true
11:12:15.783[INFO] MPV Version: mpv 0.35.0.93.05bc366d
11:12:15.783[INFO] FFMPEG Version: 5.1.2
11:12:15.804[INFO] ========> core-idle: 1
11:12:15.804[INFO] ========> LOADING
11:12:16.615[ERROR] error msg: 账号未登录; error code: -101
11:12:16.657[INFO] ========> MPV_EVENT_START_FILE
 (+) Video --vid=1 (*) (h264 852x480 12.000fps)
 (+) Audio --aid=1 (*) '973273203_nb3-1-30280.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1674537136&gen=playurlv2&os=cosbv&oi=0&trid=55be3b43ed7c4d7fa76d14cfd12387f6u&mid=0&platform=pc&upsig=9c05ec3ca1d73b5abbf0bd33aa006cad&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&bvc=vod&nettype=0&orderid=0,3&buvid=&build=0&agrr=1&bw=22414&logo=80000000' (aac 2ch 48000Hz) (external)
File tags:
 Description: Packed by Bilibili XCoder v2.0.2
11:12:17.391[INFO] ========> MPV_EVENT_FILE_LOADED
AO: [pipewire] 48000Hz stereo 2ch floatp
Using hardware decoding (nvdec).
VO: [libmpv] 852x480 cuda[nv12]
11:12:17.597[INFO] ========> MPV_EVENT_PLAYBACK_RESTART
11:12:17.598[INFO] ========> core-idle: 0
11:12:17.598[INFO] ========> RESUME
11:12:22.841[INFO] Window position changed to 573x16510MB
11:12:22.842[INFO] windows size changed: 1280 height: 720
11:12:22.842[INFO] framebuffer size changed: fwidth: 1280 fheight: 720
11:12:22.842[INFO] scale factor: 1.0
11:12:22.842[INFO] Window size changed to 1280x720, content size: 1280.0x720.0 factor: 1.0
11:12:22.948[INFO] WindowSizeChangedEvent trigger34s/10MB
AV: 00:00:27 / 00:04:00 (11%) A-V:  0.000 Cache: 212s/9MB

11:12:45.033[INFO] ========> MPV_STOP
11:12:45.219[INFO] ========> core-idle: 1
11:12:45.219[INFO] ========> LOADING
11:12:47.337[INFO] Window position changed to 0x34
11:12:47.338[INFO] windows size changed: 1920 height: 1046
11:12:47.338[INFO] framebuffer size changed: fwidth: 1920 fheight: 1046
11:12:47.338[INFO] scale factor: 1.0
11:12:47.338[INFO] Window size changed to 1920x1046, content size: 1280.0x697.0 factor: 1.5
11:12:47.451[INFO] WindowSizeChangedEvent trigger
11:12:51.248[ERROR] DynamicTab::onError 用户未登录11:12:51.248[ERROR] DynamicTab::onError 用户未登录11:12:52.175[ERROR] MineHistory::onError: 用户未登录11:12:52.599[ERROR] getUserInfo: error msg: 账号未登录; error code: -101
11:12:53.004[ERROR] getUserDynamicStat: error msg: ; error code: -6
11:12:53.386[ERROR] getUserRelationStat: error msg: 请求错误; error code: -400
11:14:21.397[ERROR] error msg: 账号未登录; error code: -101
11:14:21.441[INFO] ========> MPV_EVENT_START_FILE
 (+) Video --vid=1 (*) (h264 480x852 30.000fps)
 (+) Audio --aid=1 (*) '975405822_nb3-1-30280.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1674537261&gen=playurlv2&os=hwbv&oi=0&trid=34f6255577714ce0b53e5df75416ce3du&mid=0&platform=pc&upsig=988c5b8b800e1ac4361c8917730b3578&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&bvc=vod&nettype=0&orderid=0,3&buvid=&build=0&agrr=1&bw=9538&logo=80000000' (aac 2ch 44100Hz) (external)
File tags:
 Description: Packed by Bilibili XCoder v2.0.2
11:14:21.975[INFO] ========> MPV_EVENT_FILE_LOADED
AO: [pipewire] 44100Hz stereo 2ch floatp
Using hardware decoding (nvdec).
VO: [libmpv] 480x852 cuda[nv12]
11:14:22.023[INFO] ========> MPV_EVENT_PLAYBACK_RESTART
11:14:22.023[INFO] ========> core-idle: 0
11:14:22.023[INFO] ========> RESUME
AV: 00:00:00 / 00:01:51 (1%) A-V:  0.000 Cache: 41s/2MB

11:14:22.672[INFO] ========> MPV_STOP
11:14:22.856[INFO] ========> core-idle: 1
11:14:22.856[INFO] ========> LOADING
11:14:32.664[INFO] Window position changed to 573x165
11:14:32.664[INFO] windows size changed: 1280 height: 720
11:14:32.664[INFO] framebuffer size changed: fwidth: 1280 fheight: 720
11:14:32.664[INFO] scale factor: 1.0
11:14:32.664[INFO] Window size changed to 1280x720, content size: 1280.0x720.0 factor: 1.0
11:14:32.769[INFO] WindowSizeChangedEvent trigger
11:14:34.054[INFO] Window position changed to 536x165
11:15:33.764[ERROR] error msg: 账号未登录; error code: -101
11:15:34.139[INFO] ========> MPV_EVENT_START_FILE
 (+) Video --vid=1 (*) (h264 480x852 30.000fps)
 (+) Audio --aid=1 (*) '975405822_nb3-1-30280.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1674537334&gen=playurlv2&os=hwbv&oi=0&trid=740812055f2d4ec6bb1d442ea5ec6100u&mid=0&platform=pc&upsig=9e4032291d97122d028666ea7734cc81&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&bvc=vod&nettype=0&orderid=0,3&buvid=&build=0&agrr=1&bw=9538&logo=80000000' (aac 2ch 44100Hz) (external)
File tags:
 Description: Packed by Bilibili XCoder v2.0.2
11:15:34.587[INFO] ========> MPV_EVENT_FILE_LOADED
AO: [pipewire] 44100Hz stereo 2ch floatp
Using hardware decoding (nvdec).
VO: [libmpv] 480x852 cuda[nv12]
11:15:34.635[INFO] ========> MPV_EVENT_PLAYBACK_RESTART
11:15:34.635[INFO] ========> core-idle: 0
11:15:34.635[INFO] ========> RESUME
AV: 00:00:01 / 00:01:51 (1%) A-V:  0.000 Cache: 109s/6MB

11:15:35.770[INFO] ========> MPV_STOP
11:15:35.969[INFO] ========> core-idle: 1
11:15:35.969[INFO] ========> LOADING
11:15:36.702[INFO] Window position changed to 0x34
11:15:36.702[INFO] windows size changed: 1920 height: 1046
11:15:36.702[INFO] framebuffer size changed: fwidth: 1920 fheight: 1046
11:15:36.702[INFO] scale factor: 1.0
11:15:36.702[INFO] Window size changed to 1920x1046, content size: 1280.0x697.0 factor: 1.5
11:15:36.818[INFO] WindowSizeChangedEvent trigger
11:15:40.530[ERROR] error msg: 账号未登录; error code: -101
11:15:40.568[INFO] ========> MPV_EVENT_START_FILE
11:15:41.115[INFO] Window position changed to 536x165
11:15:41.115[INFO] windows size changed: 1280 height: 720
11:15:41.115[INFO] framebuffer size changed: fwidth: 1280 fheight: 720
11:15:41.115[INFO] scale factor: 1.0
11:15:41.115[INFO] Window size changed to 1280x720, content size: 1280.0x720.0 factor: 1.0
11:15:41.219[INFO] WindowSizeChangedEvent trigger
 (+) Video --vid=1 (*) (h264 852x480 25.000fps)
 (+) Audio --aid=1 (*) '977112262_nb3-1-30280.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1674537340&gen=playurlv2&os=cosbv&oi=0&trid=05336fbd86914ee8a4321d613ee9d316u&mid=0&platform=pc&upsig=956d9134f6770b38e995466205c0fb89&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&bvc=vod&nettype=0&orderid=0,3&buvid=&build=0&agrr=1&bw=27359&logo=80000000' (aac 2ch 48000Hz) (external)
File tags:
 Description: Packed by Bilibili XCoder v2.0.2
11:15:41.254[INFO] ========> MPV_EVENT_FILE_LOADED
Using hardware decoding (nvdec).
AO: [pipewire] 48000Hz stereo 2ch floatp
VO: [libmpv] 852x480 => 853x480 cuda[nv12]
11:15:41.317[INFO] ========> MPV_EVENT_PLAYBACK_RESTART
11:15:41.317[INFO] ========> core-idle: 0
11:15:41.317[INFO] ========> RESUME
11:15:42.088[INFO] Window position changed to 0x34s/1MB
11:15:42.088[INFO] windows size changed: 1920 height: 1046
11:15:42.088[INFO] framebuffer size changed: fwidth: 1920 fheight: 1046
11:15:42.088[INFO] scale factor: 1.0
11:15:42.088[INFO] Window size changed to 1920x1046, content size: 1280.0x697.0 factor: 1.5
11:15:42.200[INFO] WindowSizeChangedEvent trigger5s/1MB
AV: 00:00:01 / 00:04:30 (1%) A-V:  0.000 Cache: 104s/9MB

11:15:43.299[INFO] ========> MPV_STOP
11:15:43.486[INFO] ========> core-idle: 1
11:15:43.486[INFO] ========> LOADING
11:15:47.012[INFO] Window position changed to 536x165
11:15:47.012[INFO] windows size changed: 1280 height: 720
11:15:47.012[INFO] framebuffer size changed: fwidth: 1280 fheight: 720
11:15:47.012[INFO] scale factor: 1.0
11:15:47.012[INFO] Window size changed to 1280x720, content size: 1280.0x720.0 factor: 1.0
11:15:47.114[INFO] WindowSizeChangedEvent trigger
[INPUT] 搜索你感兴趣的视频: cuowude
11:16:30.349[INFO] windows size changed: 1920 height: 1046
11:16:30.349[INFO] framebuffer size changed: fwidth: 1920 fheight: 1046
11:16:30.349[INFO] scale factor: 1.0
11:16:30.349[INFO] Window size changed to 1920x1046, content size: 1280.0x697.0 factor: 1.5
11:16:30.349[INFO] Window position changed to 0x34
11:16:30.353[INFO] Window position changed to 536x165
11:16:30.353[INFO] windows size changed: 1280 height: 720
11:16:30.353[INFO] framebuffer size changed: fwidth: 1280 fheight: 720
11:16:30.353[INFO] scale factor: 1.0
11:16:30.353[INFO] Window size changed to 1280x720, content size: 1280.0x720.0 factor: 1.0
11:16:30.353[INFO] windows size changed: 1280 height: 720
11:16:30.353[INFO] framebuffer size changed: fwidth: 1280 fheight: 720
11:16:30.353[INFO] scale factor: 1.0
11:16:30.353[INFO] Window size changed to 1280x720, content size: 1280.0x720.0 factor: 1.0
11:16:30.473[INFO] WindowSizeChangedEvent trigger
11:16:44.146[ERROR] error msg: 账号未登录; error code: -101
11:16:44.188[INFO] ========> MPV_EVENT_START_FILE
 (+) Video --vid=1 (*) (h264 854x478 20.167fps)
 (+) Audio --aid=1 (*) '962368841-1-30280.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1674537404&gen=playurlv2&os=hwbv&oi=0&trid=3f43b2a2d0ae4d6dba2a1f1eafec4157u&mid=0&platform=pc&upsig=3d60554fb85d5bcc519decff1c69ac17&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&bvc=vod&nettype=0&orderid=0,3&buvid=&build=0&agrr=1&bw=8257&logo=80000000' (aac 2ch 44100Hz) (external)
File tags:
 Description: Packed by Bilibili XCoder v2.0.2
11:16:44.803[INFO] ========> MPV_EVENT_FILE_LOADED
AO: [pipewire] 44100Hz stereo 2ch floatp
Using hardware decoding (nvdec).
VO: [libmpv] 854x478 cuda[nv12]
11:16:44.867[INFO] ========> MPV_EVENT_PLAYBACK_RESTART
11:16:44.867[INFO] ========> core-idle: 0
11:16:44.867[INFO] ========> RESUME
AV: 00:00:00 / 00:00:05 (4%) A-V:  0.016 Cache: 4.9s/481KB

11:16:45.184[INFO] ========> MPV_STOP
11:16:45.366[INFO] ========> core-idle: 1
11:16:45.366[INFO] ========> LOADING
11:17:06.892[INFO] Window position changed to 0x0
11:17:06.892[INFO] windows size changed: 1920 height: 1080
11:17:06.892[INFO] framebuffer size changed: fwidth: 1920 fheight: 1080
11:17:06.892[INFO] scale factor: 1.0
11:17:06.892[INFO] Window size changed to 1920x1080, content size: 1280.0x720.0 factor: 1.5
11:17:07.009[INFO] WindowSizeChangedEvent trigger
11:17:14.402[ERROR] error msg: 账号未登录; error code: -101
11:17:14.424[INFO] ========> MPV_EVENT_START_FILE
 (+) Video --vid=1 (*) (h264 852x480 30.000fps)
 (+) Audio --aid=1 (*) '974336848-1-30280.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1674537434&gen=playurlv2&os=hwbv&oi=0&trid=9b113ebc992243efbb28355915a12476u&mid=0&platform=pc&upsig=0dbb4220ac4b43d494a6cdd504b6cb5d&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&bvc=vod&nettype=0&orderid=0,3&buvid=&build=0&agrr=1&bw=13980&logo=80000000' (aac 2ch 44100Hz) (external)
File tags:
 Description: Packed by Bilibili XCoder v2.0.2
AO: [pipewire] 44100Hz stereo 2ch floatp
11:17:15.107[INFO] ========> MPV_EVENT_FILE_LOADED
Using hardware decoding (nvdec).
VO: [libmpv] 852x480 => 853x480 cuda[nv12]
11:17:15.142[INFO] ========> MPV_EVENT_PLAYBACK_RESTART
11:17:15.142[INFO] ========> core-idle: 0
11:17:15.142[INFO] ========> RESUME
AV: 00:00:00 / 00:04:59 (0%) A-V:  0.000 Cache: 10s/639KB

11:17:15.523[INFO] ========> MPV_STOP
11:17:15.709[INFO] ========> core-idle: 1
11:17:15.709[INFO] ========> LOADING
[INPUT] 搜索你感兴趣的视频: wsa
11:17:33.398[ERROR] error msg: 账号未登录; error code: -101
11:17:33.919[INFO] ========> MPV_EVENT_START_FILE
 (+) Video --vid=1 (*) (h264 852x480 30.000fps)
 (+) Audio --aid=1 (*) '889433131_nb3-1-30280.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1674537453&gen=playurlv2&os=cosbv&oi=0&trid=a38d59d3d4cf4fc2985cfc6ccd84aebbu&mid=0&platform=pc&upsig=807b054be634691c2d4396f7c5dccaac&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&bvc=vod&nettype=0&orderid=0,3&buvid=&build=0&agrr=1&bw=37069&logo=80000000' (aac 2ch 44100Hz) (external)
File tags:
 Description: Packed by Bilibili XCoder v2.0.2
11:17:34.636[INFO] ========> MPV_EVENT_FILE_LOADED
AO: [pipewire] 44100Hz stereo 2ch floatp
Using hardware decoding (nvdec).
VO: [libmpv] 852x480 cuda[nv12]
11:17:34.684[INFO] ========> MPV_EVENT_PLAYBACK_RESTART
11:17:34.685[INFO] ========> core-idle: 0
11:17:34.685[INFO] ========> RESUME
11:17:43.682[INFO] ========> core-idle: 1:  0.000 Cache: 652s/20MB
11:17:43.682[INFO] ========> PAUSE

11:17:53.248[INFO] ========> MPV_STOP
11:18:36.940[INFO] Window position changed to 536x165
11:18:36.940[INFO] windows size changed: 1280 height: 720
11:18:36.940[INFO] framebuffer size changed: fwidth: 1280 fheight: 720
11:18:36.940[INFO] scale factor: 1.0
11:18:36.940[INFO] Window size changed to 1280x720, content size: 1280.0x720.0 factor: 1.0
11:18:37.050[INFO] WindowSizeChangedEvent trigger
11:18:39.137[INFO] Window position changed to 392x234
11:18:45.018[INFO] ========> MPV_EVENT_START_FILE

11:18:45.098[INFO] ========> MPV_STOP
11:20:12.488[INFO] Window position changed to 0x34
11:20:12.488[INFO] windows size changed: 1920 height: 1046
11:20:12.488[INFO] framebuffer size changed: fwidth: 1920 fheight: 1046
11:20:12.488[INFO] scale factor: 1.0
11:20:12.488[INFO] Window size changed to 1920x1046, content size: 1280.0x697.0 factor: 1.5
11:20:12.590[INFO] WindowSizeChangedEvent trigger
11:20:16.060[INFO] Window position changed to 392x234
11:20:16.060[INFO] windows size changed: 1280 height: 720
11:20:16.060[INFO] framebuffer size changed: fwidth: 1280 fheight: 720
11:20:16.060[INFO] scale factor: 1.0
11:20:16.060[INFO] Window size changed to 1280x720, content size: 1280.0x720.0 factor: 1.0
11:20:16.172[INFO] WindowSizeChangedEvent trigger
11:20:40.907[ERROR] error msg: 账号未登录; error code: -101
11:20:40.965[INFO] ========> MPV_EVENT_START_FILE
11:20:41.251[INFO] Window position changed to 0x34
11:20:41.251[INFO] windows size changed: 1920 height: 1046
11:20:41.251[INFO] framebuffer size changed: fwidth: 1920 fheight: 1046
11:20:41.251[INFO] scale factor: 1.0
11:20:41.251[INFO] Window size changed to 1920x1046, content size: 1280.0x697.0 factor: 1.5
11:20:41.363[INFO] WindowSizeChangedEvent trigger
 (+) Video --vid=1 (*) (h264 480x480 30.000fps)
 (+) Audio --aid=1 (*) '975105868-1-30280.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1674537640&gen=playurlv2&os=hwbv&oi=0&trid=2a75b92b5491488b9e29074d75b3054bu&mid=0&platform=pc&upsig=89222e11b142fff2f7e86d7526f45194&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&bvc=vod&nettype=0&orderid=0,3&buvid=&build=0&agrr=1&bw=24341&logo=80000000' (aac 2ch 48000Hz) (external)
File tags:
 Description: Packed by Bilibili XCoder v2.0.2
AO: [pipewire] 48000Hz stereo 2ch floatp
11:20:41.580[INFO] ========> MPV_EVENT_FILE_LOADED
Using hardware decoding (nvdec).
VO: [libmpv] 480x480 cuda[nv12]
11:20:41.616[INFO] ========> MPV_EVENT_PLAYBACK_RESTART
11:20:41.616[INFO] ========> core-idle: 0
11:20:41.616[INFO] ========> RESUME
11:20:44.703[INFO] ========> core-idle: 1V:  0.000 Cache: 11s/1MB
11:20:44.703[INFO] ========> PAUSE
11:20:46.404[INFO] Window position changed to 392x234
11:20:46.404[INFO] windows size changed: 1280 height: 720
11:20:46.404[INFO] framebuffer size changed: fwidth: 1280 fheight: 720
11:20:46.404[INFO] scale factor: 1.0
11:20:46.404[INFO] Window size changed to 1280x720, content size: 1280.0x720.0 factor: 1.0
11:20:46.514[INFO] WindowSizeChangedEvent trigger
11:20:47.649[INFO] Window position changed to 0x34
11:20:47.649[INFO] windows size changed: 1920 height: 1046
11:20:47.649[INFO] framebuffer size changed: fwidth: 1920 fheight: 1046
11:20:47.649[INFO] scale factor: 1.0
11:20:47.649[INFO] Window size changed to 1920x1046, content size: 1280.0x697.0 factor: 1.5
11:20:47.763[INFO] WindowSizeChangedEvent trigger

11:20:48.895[INFO] ========> MPV_STOP
11:20:53.182[INFO] Window position changed to 392x234
11:20:53.182[INFO] windows size changed: 1280 height: 720
11:20:53.182[INFO] framebuffer size changed: fwidth: 1280 fheight: 720
11:20:53.182[INFO] scale factor: 1.0
11:20:53.182[INFO] Window size changed to 1280x720, content size: 1280.0x720.0 factor: 1.0
11:20:53.297[INFO] WindowSizeChangedEvent trigger
11:22:01.344[ERROR] error msg: 账号未登录; error code: -101
11:22:01.426[INFO] ========> MPV_EVENT_START_FILE
 (+) Video --vid=1 (*) (h264 480x480 30.000fps)
 (+) Audio --aid=1 (*) '975105868-1-30280.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1674537721&gen=playurlv2&os=hwbv&oi=0&trid=472d7239be154cf9918b2eee7876e9cfu&mid=0&platform=pc&upsig=e128561cd5444a375a92c292a17a5bc1&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&bvc=vod&nettype=0&orderid=0,3&buvid=&build=0&agrr=1&bw=24341&logo=80000000' (aac 2ch 48000Hz) (external)
File tags:
 Description: Packed by Bilibili XCoder v2.0.2
11:22:01.980[INFO] ========> MPV_EVENT_FILE_LOADED
Using hardware decoding (nvdec).
AO: [pipewire] 48000Hz stereo 2ch floatp
VO: [libmpv] 480x480 cuda[nv12]
11:22:02.018[INFO] Window position changed to 0x34
11:22:02.018[INFO] windows size changed: 1920 height: 1046
11:22:02.018[INFO] framebuffer size changed: fwidth: 1920 fheight: 1046
11:22:02.018[INFO] scale factor: 1.0
11:22:02.018[INFO] Window size changed to 1920x1046, content size: 1280.0x697.0 factor: 1.5
11:22:02.026[INFO] ========> MPV_EVENT_PLAYBACK_RESTART
11:22:02.026[INFO] ========> core-idle: 0
11:22:02.026[INFO] ========> RESUME
11:22:02.126[INFO] WindowSizeChangedEvent trigger.3s/501KB
AV: 00:00:00 / 00:00:14 (7%) A-V:  0.000 Cache: 13s/1MB

11:22:03.108[INFO] ========> MPV_STOP
11:22:03.291[INFO] ========> core-idle: 1
11:22:03.291[INFO] ========> LOADING
11:22:07.921[INFO] Window position changed to 392x234
11:22:07.921[INFO] windows size changed: 1280 height: 720
11:22:07.921[INFO] framebuffer size changed: fwidth: 1280 fheight: 720
11:22:07.921[INFO] scale factor: 1.0
11:22:07.921[INFO] Window size changed to 1280x720, content size: 1280.0x720.0 factor: 1.0
11:22:08.024[INFO] WindowSizeChangedEvent trigger

**Comment by yigekuyou** [comment]
我技术太低，只会打包了捏

**Comment by xfangfang** [comment]
好的，感谢反馈我有时间会看一看的

如果没有其他理由还是推荐使用默认的glfw，sdl支持主要目的是向某些游戏主机，安卓或iOS等不支持glfw平台移植

（虽然现阶段并没有此类移植计划）

**Comment by sekaiacg** [comment]
x11下问题和你的一样，初次启动窗口还会随机卡几秒...

**Comment by xfangfang** [comment]
更新了一下sdl的代码，或许解决了拉动窗口后视角不正确的问题。
sdl的输入法支持短时间不在我的考虑之内了，写这个太耗费时间，而且sdl的支持只是用来在开发其他平台时用来简单参考的，所以也没必要搞这个。

先关闭这个issue了
