### ISSUE TITLE
Windows下只能在主显示器上显示，无法窗口化。激活其他显示器的窗口，界面会隐藏

### ISSUE THREAD

**Issue by hugohehuan** [xfangfang/wiliwili#68]
系统：Win10 22H2
现象：如题
硬件：PC

看了B站视频推荐就滚来了
用XBOX手柄都能玩，很爽

**Comment by xfangfang** [comment]
1. 应用是可以窗口化的，应用内设置有切换选项
2. 刚刚更新了一下，已经支持了多个显示器的默认设置，可以下载测试版试一下。

新的更新内容：
软件从哪个显示器关闭重启后就会出现在哪个显示器，位置保留上一次关闭的状态。

如何下载测试版见 readme

**Comment by xfangfang** [comment]
@hugohehuan 请问有相关后续吗

**Comment by hugohehuan** [comment]
> @hugohehuan 请问有相关后续吗

不好意思，这几天网络不太好，回复晚了……
感谢这么快就进行了修复

下载了测试板，还有2个小问题……
(1)
我的显示器是这样配列的
![微信截图_20230131234341](https://user-images.githubusercontent.com/10740498/215807319-489e7d92-fdee-4977-9adf-81c3ae6cd785.png)
把窗口化的界面拖到了显示器1，
窗口最大化，然后设置为全屏
再关掉全屏显示，然后窗口就跑到显示器3上面去了……
(2)
全屏的时候激活其他显示器的窗口，Wiliwili界面就没了(后置了)，这个问题依然存在

====
还有个小建议，在首页界面，“返回”是否能改成“退出”呢？
全屏的时候有时候脑子短路去找小叉叉……
![微信截图_20230131233910](https://user-images.githubusercontent.com/10740498/215806376-a6f5b48f-7657-430f-b281-f8e739ebfc49.png)
![Uploading 微信截图_20230131234341.png…]()

**Comment by hugohehuan** [comment]
还发现个小问题……
正常情况下，首页除了热门以外的板块，下面有(X)(Y)(B)(A) 4个按钮的说明
从设置页面返回之后，就剩两个了^
如上一楼的截图图

**Comment by xfangfang** [comment]
这个软件是为手柄用户设计的，焦点在哪个位置就会显示那个位置的所有快捷键操作，所以最后一个问题以及显示退出的问题可能短时间会保持现状。

如果使用鼠标，那么我还是推荐把下面的提示栏隐藏起来，因为确实用处不大。

第一个问题触发的几率估计不大，感觉影响也不大，就也先保持现状吧，而且我在我的两个屏幕上没有复现出来这个问题。

第二个问题确实是存在的，有时间会看一下，之前我忽视了这个问题

非常感谢详细反馈

**Comment by hugohehuan** [comment]
> 这个软件是为手柄用户设计的，焦点在哪个位置就会显示那个位置的所有快捷键操作，所以最后一个问题以及显示退出的问题可能短时间会保持现状。
> 
> 如果使用鼠标，那么我还是推荐把下面的提示栏隐藏起来，因为确实用处不大。
> 
> 第一个问题触发的几率估计不大，感觉影响也不大，就也先保持现状吧，而且我在我的两个屏幕上没有复现出来这个问题。
> 
> 第二个问题确实是存在的，有时间会看一下，之前我忽视了这个问题
> 
> 非常感谢详细反馈

我还有个触摸屏的Windows设备，也试一试
C++的应该能省不少电

键位提示暂时还是不关吧，因为对于没有键盘的Windows设备，全屏的时候没有按钮可以退出了……

**Comment by xfangfang** [comment]
鼠标右键是返回，中间是x快捷键。

暂时不支持windows触屏，相关进度：https://github.com/xfangfang/wiliwili/issues/48

**Comment by xfangfang** [comment]
> 全屏的时候激活其他显示器的窗口，Wiliwili界面就没了(后置了)，这个问题依然存在

@hugohehuan 
刚刚提交了修复，可以测试看看：https://github.com/xfangfang/wiliwili/actions/runs/4283776918

**Comment by xfangfang** [comment]
@hugohehuan 如果没有反馈我就把这个issue关了
