### ISSUE TITLE
steam deck打开代理也无法观看港澳台

### ISSUE THREAD

**Issue by qlmmm** [xfangfang/wiliwili#70]
请问是我自身的问题还是目前没有这个功能

**Comment by xfangfang** [comment]
软件是照着官方pc端写的，所以如果出现软件某些行为和官方pc端不一致，那么就是我写出来的问题；如果官方pc端也做不到那就是官方的限制。

可以试试官方客户端可不可以用，如果说官方客户端在翻墙的情况下可以用的话，那我可能需要研究研究研究这个问题了，因为我平时看番剧不多，可能要等我空闲一点的

**Comment by xfangfang** [comment]
当然，也有一个可能是，我没写代理的支持，这个可能性大一点

**Comment by xfangfang** [comment]
经过国内外多个地区多位用户测试测试，可以正常播放。
