### ISSUE TITLE
在PC端1080p 144hz的屏幕上会出现输入不支持

### ISSUE THREAD

**Issue by BenAlan11** [xfangfang/wiliwili#75]
其余软件显示正常，打开wiliwili就会黑屏输入不支持，是否PC端可以修改为默认窗口模式或可以通过哪个文件在文件夹修改显示模式或分辩率

**Comment by xfangfang** [comment]
@BenAlan11 感谢反馈

您可以更详细地描述一下 “输入不支持” 是从哪里来的吗？

有四件事是您现在可以做的（按照先后顺序去做）：

1. 测试修复
  我提交了一个小的修复，可以在这里下载：https://github.com/xfangfang/wiliwili/actions/runs/4039157452  
  因为我没有高刷显示器来测试，所以并不清楚有没有效果。

2. 下载debug版查看log
  https://github.com/xfangfang/DIY/actions/runs/4031534174  
  你可以打开一个cmd，把wiliwili.exe拖进去，看到log之后复制出来贴在这里。

4. 切换为窗口模式
  修改配置文件为如下内容，可以在开启应用时不全屏：
    ```
    {
      "setting": {
        "fullscreen": false
      }
    }
    ```
    https://github.com/xfangfang/wiliwili/discussions/39

5. 本地编译调试

**Comment by BenAlan11** [comment]
您新提交的版本修复了，非常感谢。
当软件的设定分辩率大于显示器支持的分辩率时就会黑屏并且浮窗提示输入不支持，以前玩LOL时也出现过这种情况。猜想之前的版本默认的分辩率比1080p要高。

**Comment by BenAlan11** [comment]
Microsoft Windows [版本 10.0.22000.1455](c) Microsoft Corporation。保留所有权利。C:\Users\Ben.Alan>"C:\Users\Ben.Alan\Documents\Tencent Files\1198777151\FileRecv\MobileFile\wiliwili-Windows-x64-07548e2\wiliwili-Windows-x64-07548e2\wiliwili\wiliwili.exe"10:18:59.907[0;34m[INFO][0m wiliwili v0.6.0-10-g07548e210:18:59.914[0;34m[INFO][0m client: 88431163.167504478810:18:59.914[0;34m[INFO][0m cookie: DedeUserID:010:18:59.914[0;34m[INFO][0m setting: null10:18:59.914[0;34m[INFO][0m Load config from: \Users\Ben.Alan\AppData\Local\xfangfang\wiliwili/wiliwili_config.json10:18:59.914[0;34m[INFO][0m Set app locale: zh-Hans10:18:59.923[0;34m[INFO][0m Using platform GLFW10:18:59.923[0;31m[ERROR][0m Cannot load locale en-US: directory ./resources/i18n/en-US doesn't exist10:18:59.924[0;31m[ERROR][0m Cannot load locale zh-Hans: directory ./resources/i18n/zh-Hans doesn't exist10:19:00.218[0;31m[ERROR][0m GLFW 65540: Invalid image dimensions for window icon10:19:00.256[0;34m[INFO][0m glfw: GL Vendor: NVIDIA Corporation10:19:00.256[0;34m[INFO][0m glfw: GL Renderer: NVIDIA GeForce GTX 960/PCIe/SSE210:19:00.256[0;34m[INFO][0m glfw: GL Version: 4.6.0 NVIDIA 511.2310:19:00.256[0;34m[INFO][0m glfw: GLFW Version: 3.4.010:19:00.258[0;33m[WARNING][0m Cannot find custom gamepad db, (Searched at: \Users\Ben.Alan\AppData\Local\xfangfang\wiliwili/gamecontrollerdb.txt)10:19:00.305[0;33m[WARNING][0m Cannot find custom font, (Searched at: \Users\Ben.Alan\AppData\Local\xfangfang\wiliwili/font.ttf)10:19:00.312[0;34m[INFO][0m Using internal font: ./resources/font/switch_font.ttf10:19:00.312[0;33m[WARNING][0m "regular" font couldn't be located (searched at "./resources/font/switch_font.ttf")10:19:00.312[0;34m[INFO][0m Load system font: C:\WINDOWS\Fonts\malgun.ttf10:19:00.319[0;33m[WARNING][0m Cannot find keymap icon, (Searched at: ./resources/font/keymap_xbox.ttf)10:19:00.324[0;33m[WARNING][0m Icons may not be displayed, for more information please refer to: https://github.com/xfangfang/wiliwili/discussions/3810:19:00.324[0;33m[WARNING][0m "material" font couldn't be located (searched at "./resources/material/MaterialIcons-Regular.ttf")10:19:00.337[0;31m[ERROR][0m switch: could not load Material icons font from resources10:19:00.339[0;34m[INFO][0m createWindow done10:19:00.340[0;31m[ERROR][0m Fatal error: Unable to load XML file "./resources/xml/activity/main.xml": error 3terminate called after throwing an instance of 'std::logic_error'  what():  Unable to load XML file "./resources/xml/activity/main.xml": error 3

**Comment by xfangfang** [comment]
@BenAlan11 感谢，这个问题应该不是分辨率导致的，而是默认的帧数设定不匹配造成的，修复是按照显示器的帧数重新设置了一下。

如果修复版解决了问题的话，就不用操作后面那几步了。

还有几处可能出现问题的位置：

1. 可以在设置中开启fps，检查一下帧数是否正常，我不确定会不会限制60帧，预期的结果应该在144附近。
2. 在设置中切换 全屏/窗口，我不确定那个设置会不会有问题
3. 窗口化应用后，退出，重新开启应用，检查重启后的窗口的位置和大小是不是和退出时一致。

如果上面三项均没问题，那么就可以关闭这个issue了

**Comment by BenAlan11** [comment]
FPS显示数字为1100左右
全屏窗口切换没有问题
位置一致

**Comment by xfangfang** [comment]
@BenAlan11 看起来fps还是有点问题，可以看看在应用内切换 全屏/窗口，或者怎么操作会不会影响到这个帧率。

**Comment by BenAlan11** [comment]
全屏在1100左右，切换为窗口后会变成1400左右

**Comment by xfangfang** [comment]
@BenAlan11 好的，只能等我有空找到高刷屏测试看看了

**Comment by xfangfang** [comment]
拿朋友的电脑测试了一下：

1. 他正常使用release版本是没有问题的
2. 他的刷新率是和屏幕刷新率相同的，不会出现跑到1000多的情况

所以这个问题可能与您的系统，显卡驱动或者显示器相关。在没有更多信息前，我感觉大概率是显卡驱动的问题。

**Comment by xfangfang** [comment]
@BenAlan11 如果没有更多的反馈了我可能要关闭这个issue了，因为我感觉这更多像是显卡驱动的问题，而不是wiliiwili的bug，而且我没有办法复现出来同样的问题。

**Comment by BenAlan11** [comment]
最近使用发现在笔记本上小窗模式会出现反复最小化又打开的问题，表现为软件显示区域一直闪动，在144hz那个台式机上没有这个问题

**Comment by BenAlan11** [comment]
就像这样，
https://user-images.githubusercontent.com/121960534/220850374-bdfb147c-883e-4c32-beb4-30bc11cca9ab.mp4

**Comment by BenAlan11** [comment]
使用兼容性运行好像解决了，我不清楚是否与win11版本有关
