### ISSUE TITLE
键盘键位与播放界面触摸手势

### ISSUE THREAD

**Issue by Blue-Beaker** [xfangfang/wiliwili#76]
键盘的键位有部分是照搬手柄的键位名称，然而其在键盘上的位置并不方便使用，比如L/R快退快进
我建议键盘键位可以借鉴官方网页端而非照搬手柄
全屏且导航栏隐藏时用左右方向键快退快进，上下方向键调节应用内音量，空格暂停，回车显示导航栏
导航栏显示时为了可以完全键盘操作，仍保留原来的机制，方向键变为选择按钮，回车按下该按钮。

另外如果可以的话，希望能加上播放界面的双击暂停与左右拖动快进快退手势，平板触摸会方便不少。

**Comment by xfangfang** [comment]
@Blue-Beaker 

wiliwili 其实是专注于手柄操作的，对于PC端的支持更多的是为了开发与掌机考虑的。您说的这些建议很好，但是我现阶段并没有时间和精力去改进。

我认为对于一个面向大众的软件，优秀的设计应该是尽可能减少快捷键的，操作越复杂对于用户来说就越痛苦，所以可以发现软件内大多数操作都可以通过鼠标来操作，对我个人来说其实并不需要经常按键盘。

也有一些实现上的问题，wiliwili最开始并不是为了pc设计的，现在能支持键盘快捷键已经是很不容易的事了，更复杂的快捷键可能也许需要对底层的修改。需要这个功能的人可能很少，但是消耗我的时间却很多。

**Comment by Blue-Beaker** [comment]
请问可否指出键位在源码中的位置，方便我自行修改编译？

**Comment by xfangfang** [comment]
library/lib/platforms/glfw/glfw_input.cpp

53行附近

**Comment by xfangfang** [comment]
刚刚出炉了快捷键自定义方案：
https://github.com/xfangfang/wiliwili/wiki#自定义pc端快捷键

https://github.com/xfangfang/wiliwili/actions/runs/16600976476

还在测试阶段，有按键不匹配或者其他自定义快捷键需求的朋友欢迎反馈。
