### ISSUE TITLE
SWITCH上有的视频不显示分集，无法连续播放

### ISSUE THREAD

**Issue by CARYCJ** [xfangfang/wiliwili#81]
视频在手机、网页和电脑端都有合集或分集，switch上没有显示，只能自动连播推荐的视频

**Comment by xfangfang** [comment]
@CARYCJ 
我确实没做合集的功能，但是分集貌似是做了的，如果哪个视频不能正常显示分集，可以把具体的视频发出来。

合集的支持可以在readme中的todolist里找到

**Comment by xfangfang** [comment]
@CARYCJ 刚刚推送了合集的支持，可以于测试版下载试用，欢迎反馈。

https://github.com/xfangfang/wiliwili/actions/runs/4554327155

**Comment by xfangfang** [comment]
@CARYCJ 因为没有回复，先关闭这个issue了

（多补充一句：如果没有后续回复，就不要在github上提issue）

**Comment by CARYCJ** [comment]
@xfangfang 不好意思，是我疏忽了，合集功能在测试版得到解决，正式版本上也有合集，但只用少部分视频合集功能正常可用，大部分没有合集选项

**Comment by xfangfang** [comment]
@CARYCJ 正式版支持的是分集，测试版新增了合集。

这两个不是一回事。

**Comment by CARYCJ** [comment]
@xfangfan 原来如此，经常在手机上使用B站忽略了这是两个功能，感谢分享
