### ISSUE TITLE
[macOS] 按照README编译后如何运行呢？

### ISSUE THREAD

**Issue by MostlyHarmlessxyz** [xfangfang/wiliwili#83]
抱歉

平台是Macos （M1）

用Cmake编译后只有一个Unix可执行文件

**Comment by xfangfang** [comment]
readme的参考是给潜在的开发者用来开发的，你可以cd到构建目录，直接执行即可。

如果想要构建成一个mac上的app，可以参考：

https://github.com/xfangfang/wiliwili/blob/7a79cd6286083d1ef8ab08cfc690384ec599e34f/.github/workflows/build.yaml#L234-L235

**Comment by MostlyHarmlessxyz** [comment]
编译时貌似还要安装一个 Jq

最后编译完毕显示了一个

"dylibbundle" is not installed. The application you built can only be used locally

但是程序已经能打开了

谢谢您🙏

**Comment by xfangfang** [comment]
# 最后写了一个提示的原因

现在构建的应用只能在你自己的电脑上运行，是没办法分享给别人的，如果需要分享给别人，可以先执行下面的内容：

```shell
brew tap xfangfang/wiliwili
brew install xfangfang/wiliwili/mpv-wiliwili
brew install dylibbundler
```

上述内容会在你的电脑上安装一个专门用于wiliwili的依赖较少的mpv，和依赖打包工具，换一个目录重新执行构建指令会构建出可以分发的app。

# 可能出现的问题
可能在系统中存在多个mpv时会出现应用没有找到正确的mpv的情况（可以检查cmake的输出来判断当前使用了哪个mpv），这种时候可以使用如下方法处理：

执行：`brew info mpv-wiliwili` 

可能会出现如下内容：
```
mpv-wiliwili is keg-only, which means it was not symlinked into /usr/local,
because it is intended to only be used for building wiliwili.

For compilers to find mpv-wiliwili you may need to set:
  export LDFLAGS="-L/usr/local/opt/mpv-wiliwili/lib"
  export CPPFLAGS="-I/usr/local/opt/mpv-wiliwili/include"

For pkg-config to find mpv-wiliwili you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/mpv-wiliwili/lib/pkgconfig"
```

复制你系统中 wiliwili 专属的 mpv 安装的路径：`/usr/local/opt/mpv-wiliwili`

替换这个路径：
https://github.com/xfangfang/wiliwili/blob/7a79cd6286083d1ef8ab08cfc690384ec599e34f/cmake/FindMPV.cmake#L29


---
如果有空闲时间的话欢迎把构建的结果贴上来，这样其他人有需要的话就可以直接下载测试啦
