### ISSUE TITLE
[求助]怎么自制wiliwili前端

### ISSUE THREAD

**Issue by tangyuxian** [xfangfang/wiliwili#84]
我通过工具制作的前端,结果打开后提示软件错误,而那个nro自己生成的wiliwili图标太别扭了,请问有bilibili图标或者能够自制前端?

**Comment by xfangfang** [comment]
https://github.com/xfangfang/wiliwili/tree/yoga/scripts/switch-forwarder

**Comment by tangyuxian** [comment]
我用的一个NSP前端工具成功生成图标了,我其它软件生成图标都可以链接到nro,但是偏偏wiliwili不行呢

**Comment by tangyuxian** [comment]
有B站那个图标nsp前端分享个嘛

**Comment by xfangfang** [comment]
不存在偏偏wiliwili不行的情况，在0.6.0之前的版本，我都是使用第三方工具快速生成的nsp

所以，大概率是哪里操作错了

**Comment by tangyuxian** [comment]
可以分享下你的那个第三方工具嘛,我用的是汉化版的...Menu 0.12 beta....

**Comment by xfangfang** [comment]
这是一个非常容易验证的问题，你可以保持其他参数不变，将指向的nro换成你认为可以正常使用的nro

**Comment by xfangfang** [comment]
https://gbatemp.net/threads/nsp-forwarder-tool-for-12.587936/

**Comment by xfangfang** [comment]
我推荐不要使用这些工具来制作，因为他们内置的hbloader版本不是最新的，随着大气层的更新不一定哪里就存在问题

**Comment by tangyuxian** [comment]
prod.keys 哪里来啊,我之前的工具只有个key.dat

**Comment by xfangfang** [comment]
如果问题解决了的话，可以分享下解决的办法，这样可以方便后面的朋友参考

**Comment by tangyuxian** [comment]
我把单词打错了,那个啥,太难为情了(ŎдŎ；)
