### ISSUE TITLE
在windows平板上关闭按钮（X）使用手指双击不灵敏 && 视频进度条无法拖拽

### ISSUE THREAD

**Issue by meowrain** [xfangfang/wiliwili#90]
1.在windows平板上关闭按钮（X）使用手指双击不灵敏
2.视频进度条无法拖拽
目前发现以上两个问题，希望作者大大能修正❤️

**Comment by meowrain** [comment]
刚才发现拖拽可以双击小电视拖动，不过还是希望能有点哪儿到哪儿得操作逻辑

**Comment by xfangfang** [comment]
windows的触摸支持需要我有设备来调试，已经有这样的issue了：https://github.com/xfangfang/wiliwili/issues/48

视频进度点击直接跳转我可能短时间不会做，目前的设计在其他设备上尤其是switch这样的小屏设备可能会导致误触，这个要好好考虑考虑

**Comment by meowrain** [comment]
好的

**Comment by xfangfang** [comment]
@meowrain windows触摸支持因为已经有存在的issue了，先关闭这个issue
