### ISSUE TITLE
Windows平台的release程序和debug程序的配置目录与Discussions/39中的对不上

### ISSUE THREAD

**Issue by LoneWindG** [xfangfang/wiliwili#93]
版本: 
Release 0.6.0 
测试版 v0.6.0 -22-g29880ac
Debug v0.6.0-19-g8c1b2bf

Release程序配置目录在程序运行目录所在盘(如D:)\Users\USER_NAME\AppData\Local\xfangfang\wiliwili
Debug与测试版配置目录都在C:\Users\USER_NAME\AppData\Local\xfangfang\wiliwili

**Comment by xfangfang** [comment]
> Release程序配置目录在程序运行目录所在盘(如D:)\Users\USER_NAME\AppData\Local\xfangfang\wiliwili

这个问题是因为我之前电脑只有C盘，所以一直没有发现，0.6.0发布之后有用户反馈，所以修复了。（我也不知道为啥 Windows提供的 HOMEPATH 在应用中获取就会变成所在盘路径）

> Debug与测试版配置目录都在C:\Users\USER_NAME\AppData\Local\xfangfang\wiliwili

这两个是预期结果，提供的Debug版只是增加了 log 显示，其余部分和测试版相同。

最新测试版用的路径为：`$LOCALAPPDATA\xfangfang\wiliwili` 就是 ：`C:\Users\USER_NAME\AppData\Local\xfangfang\wiliwili`

**Comment by LoneWindG** [comment]
> > Release程序配置目录在程序运行目录所在盘(如D:)\Users\USER_NAME\AppData\Local\xfangfang\wiliwili
> 
> 这个问题是因为我之前电脑只有C盘，所以一直没有发现，0.6.0发布之后有用户反馈，所以修复了。（我也不知道为啥 Windows提供的 HOMEPATH 在应用中获取就会变成所在盘路径）
> 
> > Debug与测试版配置目录都在C:\Users\USER_NAME\AppData\Local\xfangfang\wiliwili
> 
> 这两个是预期结果，提供的Debug版只是增加了 log 显示，其余部分和测试版相同。
> 
> 最新测试版用的路径为：`$LOCALAPPDATA\xfangfang\wiliwili` 就是 ：`C:\Users\USER_NAME\AppData\Local\xfangfang\wiliwili`

OK, 我先用测试版;
cmd里看了下HOMEPATH环境变量, 输出结果是"\User\USER_NAME", 不带盘符的所以就变成当前盘的路径了;
win里面的用户文件夹应该是USERPROFILE这个环境变量

不过Debug版不是在当前运行目录的么, Debug构建时候不是按构建时最新代码构建的?
看了下提交记录[[56efc57](https://github.com/xfangfang/wiliwili/commit/56efc57461c544d7695d9b5a1091da4a28d68061)]1月14号debug的配置路径就已经改成getcwd获取路径了(没怎么写过cpp, 可能理解有错)

**Comment by xfangfang** [comment]
> 提供的Debug版只是增加了 log 显示，其余部分和测试版相同。

提供的debug版（只是面向大众这么叫，并不是真正的debug构建）目的是大家遇到什么问题的时候可以下载他查看log，其他方面全部保持一致避免引入变量，比如 如果加载配置的路径都变了，那很可能问题也不存在了。


代码的宏定义是可以在编译的时候来指定的，要看编译的指令才能知道有没有开启debug构建。

文档中也有提及，开发者在本地编译调试才会加载本地目录的。

**Comment by LoneWindG** [comment]
> > 提供的Debug版只是增加了 log 显示，其余部分和测试版相同。
> 
> 提供的debug版（只是面向大众这么叫，并不是真正的debug构建）目的是大家遇到什么问题的时候可以下载他查看log，其他方面全部保持一致避免引入变量，比如 如果加载配置的路径都变了，那很可能问题也不存在了。
> 
> 代码的宏定义是可以在编译的时候来指定的，要看编译的指令才能知道有没有开启debug构建。
> 
> 文档中也有提及，开发者在本地编译调试才会加载本地目录的。

😂这样啊, 我以为debug版就是debug构建的呢
