### ISSUE TITLE
请问如何配置或者修改可以关闭直播tab？

### ISSUE THREAD

**Issue by aloasut** [xfangfang/wiliwili#94]
给比较低龄儿童看，不想打开直播。谢谢。

**Comment by xfangfang** [comment]
@aloasut windows下操作比较方便，其他平台略微复杂一些。

# 原理
大概原理是： wiliwili 使用类似安卓开发的xml来创建布局，只需要修改对应的布局文件就能自定义显示的内容，甚至可以做到自由组合要显示的页面。比如之前有用户需要打开软件只显示单个收藏夹用来给家里老人看，类似的操作都是支持的。

# 详细操作

具体到直播的问题，找到这个文件：https://github.com/xfangfang/wiliwili/blob/yoga/resources/xml/fragment/home_tab.xml

https://github.com/xfangfang/wiliwili/blob/9ae65e2eadc9a8166cb4f7e54040a7e6523bcdd0/resources/xml/fragment/home_tab.xml#L1-L20

把里面：`HomeLive` 所在的Tab 删掉，然后把上一级的 `defaultTab="1"` 改为 `defaultTab="0"`

# 不同平台

- windows 下比较简单，直接从下载的文件夹中找到 `resources/xml/fragment/home_tab.xml` 来修改就行

- macOS 也可以直接修改下载的 app内部的资源文件，原理相同。

- linux 视安装方式和安装目录不定，资源文件位置不固定，需要自己来找了。

- 其他平台通用的方式是修改源码来重新构建，除了拉项目自己编译外也可以使用在线编译：

  1. fork 我的项目
  2. 在项目设置中开启 github action
  3. 找到对应的文件修改
  4. 在自己项目的github action 分栏等待自动构建，等待十分钟到二十分钟后项目就构建好了，直接安装即可

**Comment by xfangfang** [comment]
@aloasut 请问问题有没有得到解决，如果解决了的话可以及时关闭掉这个issue

**Comment by aloasut** [comment]
完全明白，谢谢！
