### ISSUE TITLE
大气层1.5.0无法从桌面图标启动wiliwili

### ISSUE THREAD

**Issue by Gokou-Ruri** [xfangfang/wiliwili#95]
目前只能通过R+A打开桌面游戏的模式启动wiliwili，直接从桌面图标启动会直接报错。
大气层说1.5.0预发布版更新了很多东西，是不是跟这个有关系？
类似的软件我也试了tinfoil，桌面图标同样无法启动，必须R+A键启动游戏才能打开tinfoil。
普通游戏能正常启动，只有类似wiliwili这种在游戏内存里启动小程序的自制软件启动不了。

**Comment by xfangfang** [comment]
@Gokou-Ruri 我现在知道的唯一可以造成闪退的情况就是手动在内存卡创建目录（注意是目录，不是文件）：switch/wiliwili.nro/

除此之外的闪退有可能是其他原因导致的，我有见过其他人遇到类似的事，可以通过重做虚拟系统来解决

**Comment by Gokou-Ruri** [comment]
> @Gokou-Ruri 我现在知道的唯一可以造成闪退的情况就是手动在内存卡创建目录（注意是目录，不是文件）：switch/wiliwili.nro/
> 
> 除此之外的闪退有可能是其他原因导致的，我有见过其他人遇到类似的事，可以通过重做虚拟系统来解决

你试试把大气层更新到[1.5.0](https://github.com/Atmosphere-NX/Atmosphere/releases/tag/1.5.0-prerelease)，这个是今天刚发布的，我大概是第一个来反馈的，所以应该没人知道这个问题，更新后就这样了，上面我也说了，不只是wiliwili，所有通过桌面图标启动的自制程序都这样了，应该是大气层1.5.0有什么变动需要自制程序去适配，而且我觉得这个不是wiliwili闪退，应该是桌面图标的问题，图标无法启动wiliwili了，打个比方，快捷方式指向的目标路径找不到对应的程序了，所以系统就报错误，R+A能启动是因为没经过桌面图标而是直接执行的nro本体。

  > The following was changed since the last release:
 > 
 > Support was added for 16.0.0
 > `mesosphère` was updated to reflect the latest official kernel behavior.
 > `ncm` was updated to reflect the latest official behavior.
 > Many FS apis were updated under the hood to reflect the latest official behavior.
 > **Please Note:** 16.0.0 made breaking changes to a number of system APIs, including in FS/NCM/Shared Font commands that some homebrew programs may use.
 > These programs may encounter strange errors, and may need to be recompiled with a libnx updated to support 16.0.0's changes to function properly.
 > If you are an impacted developer, please contact `SciresM#0524` on discord for assistance.
 > A number of minor issues were fixed and improvements were made, including:
 > An issue was fixed that could cause GPIO outputs to be misconfigured under certain circumstances.
 > General system stability improvements to enhance the user's experience.

**Comment by xfangfang** [comment]
@Gokou-Ruri 感谢，我把你说的大气层1.5.0和固件15.0搞混了，今晚之前我会更新大气层来测试一下的，万分感谢反馈

**Comment by xfangfang** [comment]
@Gokou-Ruri 

### 确保有 signature patches
在开始之前要确保你使用的大气层包含了对应系统的 `signature patches`，可以参考 tinfoil 的说明

> If you install it and Tinfoil will not launch, then you are missing the correct signature patches required to run homebrew titles. If you are unable to obtain the correct homebrew patches, then download the Applet version of Tinfoil.

### 相关链接
这里是两个包含了前面说的补丁的整合包，我注意到第二个链接内容并没有包含固件 16.0 的patch，所以如果是新系统推荐用第一个链接自行组合 hekate 使用：  
https://sigmapatches.coomer.party
https://shipengliang.com/games/大气层-atmosphere-最新版-历史版-下载.html

### 测试结果

我这边测试了两个虚拟系统，系统固件为 14.1.2，大气层 1.5.0 beta

其中一个 exFat 卡内的系统有类似的问题（甚至更严重，大量游戏也打不开），另外一个 Fat32 的卡可以正常使用。

本来就不推荐使用 exFat 格式的卡，在更新之后还出现了一些文件错误，现象是我的一些游戏和自制软件无法打开，这在之前也是偶尔会发生的，所以有很大可能是卡本身的问题。在这种情况下 格式化为 Fat32 重做系统是最好的选择。

### 更新计划

我认为只要软件能正常在 hbmenu 中打开，就说明这次的更新对其是没有影响的。其他的问题，比如在某些版本固件 + 大气层1.5.0 beta 确实存在 nsp forwarder 无法打开自制软件的问题（我感觉这种可能性不高），可以等待正式版发布，相信这样的问题肯定是大家急于解决的，到时候肯定会有优雅的解决方案。

---

补充：我认为你的问题很可能是 系统固件 16.0，使用的整合包或者自行更新的大气层没有包含对应 signature patches 导致的。
也有可能是因为 exFat 内存卡在升级大气层时，拷贝文件导致一些奇奇怪怪的文件错误，然后出现的神奇问题。

**Comment by Gokou-Ruri** [comment]
@xfangfang 
感谢！确实是signature补丁的问题，之前复制的时候直接覆盖了，没删除旧文件，刚才发现多了两个旧的ips文件，目前正常了。

**Comment by xfangfang** [comment]
好的，先关闭这个issue了
