### ISSUE TITLE
希望改善倍速功能对应的按键

### ISSUE THREAD

**Issue by y2485871697** [xfangfang/wiliwili#97]
如果能将左侧十字按键和摇杆的功能分离开，将倍速功能绑定到十字按键上会是非常方便的设定

**Comment by jingsu2000** [comment]
非常需要B站的倍速功能，目前ZL,ZR按钮闲置的，完全可以用。十字键维持现状比较好，因为十字键切换光标比摇杆更加准确

**Comment by jingsu2000** [comment]
LR是后退前进，ZLZR是减速加速，也是很对称

**Comment by xfangfang** [comment]
@jingsu2000 可以进 设置 实用工具 里看一下现在的倍速键设定。

我认为zl zr会导致很严重的误触。

在我看最佳的键位设置应该是只有：

方向键 确定(a) 返回(b) 菜单（x)

过多的快捷键只会增加软件的上手难度，而且也不利于多平台的迁移，所以并不在我的考虑范围内。

当然，如果可以完美的实现自然是让很多内置的功能支持用户自定义快捷键，但是因为我没有这样的需求，所以只能接受pr而不会去实际开发。

**Comment by jingsu2000** [comment]
> @jingsu2000 可以进 设置 实用工具 里看一下现在的倍速键设定。
> 
> 我认为zl zr会导致很严重的误触。
> 
> 在我看最佳的键位设置应该是只有：
> 
> 方向键 确定(a) 返回(b) 菜单（x)
> 
> 过多的快捷键只会增加软件的上手难度，而且也不利于多平台的迁移，所以并不在我的考虑范围内。
> 
> 当然，如果可以完美的实现自然是让很多内置的功能支持用户自定义快捷键，但是因为我没有这样的需求，所以只能接受pr而不会去实际开发。

目前我好想没看到有加速减速的设置方法，界面上也没有，因为B站有很大一个群体就是看评测和访谈这类语言类的节目，加速功能挺重要的

另外就是你说的误触，我觉得不是问题啊，因为加速减速不是一个破坏性的功能（不像快进快退），就算误触了，也不会影响到节目完整性，再按一下就好了

**Comment by jingsu2000** [comment]
如果你担心误触，我觉得加一个快捷键设置开关呢？就是一个更加完整的游戏机用的app了，我非常期待能加上倍速快捷功能

**Comment by xfangfang** [comment]
@jingsu2000 可以进 “设置 实用工具” 里看一下现在的倍速键设定。

注意是：“设置 **实用工具**”，因为里面还涉及其他未说明的快捷键，所以推荐去看一看。

欢迎大家有新功能的建议，但是对于所有新功能（除了我自己需要的部分外）都只能借助开源的力量来实现，因为我时间确实有限。

- - -

有听到过很多次“加了什么什么就完美了”这种话，但是相信我，总会有人提出新的需求的，新老需求间也会有冲突。我真的没办法响应所有人的需求，也没有办法给每个冲突的功能都加上开关。

欢迎大家写好代码来找我合并，对于任何贡献我都乐于帮助。

**Comment by Eitetsu0** [comment]
@xfangfang 是不是可以考虑把pc端mpv默认的快捷键功能加上？
这样起码pc端的播放功能可以满足绝大多数场景了。
现在pc上好像只能用鼠标控制播放，交互体验比较差。

**Comment by xfangfang** [comment]
@Eitetsu0 软件内的所有操作都可以使用键盘来完成。

这里是pc端快捷键的说明：
https://github.com/xfangfang/wiliwili/wiki#2-使用指南

在应用内设置中同样有说明与pc端按键图标配置。


mpv的默认快捷键比较多，而且需要重新来实现，因为libmpv并不包含对应的api

**Comment by Eitetsu0** [comment]
> @Eitetsu0 软件内的所有操作都可以使用键盘来完成。
> 
> 这里是pc端快捷键的说明： [https://github.com/xfangfang/wiliwili/wiki#2-使用指南](https://github.com/xfangfang/wiliwili/wiki#2-%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97)
> 
> 在应用内设置中同样有说明与pc端按键图标配置。
> 
> mpv的默认快捷键比较多，而且需要重新来实现，因为libmpv并不包含对应的api

感谢说明。之前因为字体原因没看懂键盘快捷键，现在懂了。😂

或许可以增加一个直接调用mpv播放的选项？
这样的话 #27 的小窗播放功能也可以实现了。

**Comment by xfangfang** [comment]
> 或许可以增加一个直接调用mpv播放的选项？

@Eitetsu0 感谢提出来这个建议，但是我不想把这个软件做的这么极客风。

---

如果你想自己修改的话，大概有两种方式：

mpv的部分基本都在 mpv_core.hpp/cpp 这两个文件中。

1. libmpv可以自己创建新窗口，这个窗口貌似可以使用mpv的快捷键来控制。
2. 也可以通过json ipc的方式直接调用外部mpv，不过这就需要完善很多代码，来让wiliwili与外部的mpv状态同步。

---

那个小窗的反馈，我认为他指的应该是应用内小窗，就像pad端b站做的那样。

**Comment by jingsu2000** [comment]
发现ns目前的加速播放，速度太快了（2倍速？）

**Comment by xfangfang** [comment]
@jingsu2000 @y2485871697 
倍速功能整体重写了：

1. 现在可以直接在屏幕上控制倍速。
2. 按压右摇杆会使用上次的倍速值，而不是固定2.0倍
3. 按压右摇杆会显示倍速提示，双击右摇杆或直接在屏幕上控制倍速不会显示提示

如果测试没有什么问题的话，这个issue就可以关闭啦～

代码变更：https://github.com/xfangfang/wiliwili/commit/0e4b9a27d575dea18ae9bef4672819a13a719c93
测试版（正在构建中）：https://github.com/xfangfang/wiliwili/actions/runs/4576891584

**Comment by xfangfang** [comment]
因为没有后续回复，先关闭这个issue了
